#!/usr/bin/env node
// Drift detector: regenerates types into a temp file and compares against
// the checked-in src/openapi-types.ts. Exits non-zero on any difference.
//
// Run in CI to ensure that whoever updated openapi.json also regenerated
// the TS types (or vice versa).

import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import openapiTSDefault, * as openapiTSMod from 'openapi-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const inputPath = join(pkgRoot, 'openapi.json');
const committedPath = join(pkgRoot, 'src', 'openapi-types.ts');

if (!existsSync(inputPath)) {
  console.error(`[api-client] openapi.json not found at ${inputPath}`);
  process.exit(2);
}
if (!existsSync(committedPath)) {
  console.error(`[api-client] committed types not found at ${committedPath}`);
  process.exit(2);
}

const openapiTS = openapiTSDefault ?? openapiTSMod.default ?? openapiTSMod;
const astToString = openapiTSMod.astToString;

const ast = await openapiTS(new URL(`file://${inputPath}`));
const ts = typeof ast === 'string' ? ast : astToString(ast);

const banner = [
  '// AUTO-GENERATED by openapi-typescript. DO NOT EDIT BY HAND.',
  '// Source: packages/api-client/openapi.json',
  '// Regenerate: npm --prefix packages/api-client run generate',
  '',
].join('\n');

const fresh = banner + ts;
const committed = await readFile(committedPath, 'utf8');

if (fresh === committed) {
  console.log('[api-client] no drift between openapi.json and src/openapi-types.ts');
  process.exit(0);
}

// Write out a diff target for debugging.
const dir = await mkdtemp(join(tmpdir(), 'api-client-drift-'));
const diffPath = join(dir, 'openapi-types.fresh.ts');
await writeFile(diffPath, fresh, 'utf8');

console.error('[api-client] DRIFT DETECTED between openapi.json and src/openapi-types.ts');
console.error('[api-client] Fresh types written to ' + diffPath);
console.error('[api-client] To fix:');
console.error('    npm --prefix packages/api-client run generate');
console.error('    git add packages/api-client/src/openapi-types.ts');
// Best-effort cleanup hint.
console.error(`(temp file at ${diffPath}; rm -rf ${dir} when done)`);
process.exit(1);
