#!/usr/bin/env node
// Regenerate src/openapi-types.ts from the checked-in openapi.json.
//
// Usage: node scripts/generate-types.mjs [path-to-openapi.json] [--out=path]
//
// Defaults to ../openapi.json (repo-root path: packages/api-client/openapi.json)
// → src/openapi-types.ts.

import { writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import openapiTSDefault, * as openapiTSMod from 'openapi-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');

const args = process.argv.slice(2);
let inputPath = join(pkgRoot, 'openapi.json');
let outPath = join(pkgRoot, 'src', 'openapi-types.ts');
for (const arg of args) {
  if (arg.startsWith('--out=')) {
    outPath = resolve(arg.slice('--out='.length));
  } else if (!arg.startsWith('--')) {
    inputPath = resolve(arg);
  }
}

if (!existsSync(inputPath)) {
  console.error(`[api-client] openapi.json not found at ${inputPath}`);
  console.error(
    '[api-client] Fetch one first, e.g.\n' +
      '    curl -sf https://deepsynaps-studio.fly.dev/openapi.json \\\n' +
      `      > ${inputPath}`,
  );
  process.exit(2);
}

const openapiTS = openapiTSDefault ?? openapiTSMod.default ?? openapiTSMod;
const astToString = openapiTSMod.astToString;

const ast = await openapiTS(new URL(`file://${inputPath}`));
const ts = typeof ast === 'string' ? ast : astToString(ast);

const banner = [
  '// AUTO-GENERATED by openapi-typescript. DO NOT EDIT BY HAND.',
  '// Source: packages/api-client/openapi.json',
  '// Regenerate: npm --prefix packages/api-client run generate',
  '',
].join('\n');

await writeFile(outPath, banner + ts, 'utf8');
console.log(`[api-client] wrote ${outPath}`);
