#!/usr/bin/env python3
"""Build the new pgBrainMapPlanner function source and write to _bmp_func.txt"""

BT = chr(96)  # backtick

# NOTE: All HTML is built with string concatenation (no template literals).
# SVG event handling uses data-site attributes + a single delegated listener,
# which avoids all inline onclick quoting issues.

FUNC = (
"export async function pgBrainMapPlanner(setTopbar) {\n"
"  setTopbar('Brain Map Planner', " + BT + "\n"
"    <button class=\"btn btn-sm\" onclick=\"window._nav('protocol-wizard')\" style=\"border-color:var(--teal);color:var(--teal)\">Protocol Search</button>\n"
"    <button class=\"btn btn-sm\" onclick=\"window._nav('prescriptions')\">Prescriptions</button>\n"
"  " + BT + ");\n"
"  const el = document.getElementById('content');\n"
"  if (!el) return;\n"
"\n"
"  const FALLBACK_CONDITIONS = [\n"
"    'Major Depressive Disorder','Treatment-Resistant Depression','Bipolar Depression',\n"
"    'OCD','PTSD','Generalized Anxiety','Social Anxiety','Panic Disorder',\n"
"    'ADHD','Schizophrenia','Auditory Hallucinations','Chronic Pain','Fibromyalgia',\n"
"    'Parkinson Disease','Stroke Rehabilitation','Aphasia','Tinnitus',\n"
"    'Insomnia','Traumatic Brain Injury','Eating Disorders','Addiction','Autism Spectrum'\n"
"  ];\n"
"\n"
"  const BMP_SITES = {\n"
"    'Fpz':[150,14],'Fp1':[107,20],'Fp2':[193,20],\n"
"    'AF7':[72,38],'AFz':[150,40],'AF8':[228,38],\n"
"    'F7':[38,82],'F3':[97,72],'Fz':[150,68],'F4':[203,72],'F8':[262,82],\n"
"    'FT7':[28,118],'FC3':[90,108],'FCz':[150,104],'FC4':[210,108],'FT8':[272,118],\n"
"    'T7':[22,155],'C3':[78,155],'Cz':[150,155],'C4':[222,155],'T8':[278,155],\n"
"    'TP7':[28,192],'CP3':[90,202],'CPz':[150,206],'CP4':[210,202],'TP8':[272,192],\n"
"    'T5':[38,228],'P3':[97,238],'Pz':[150,242],'P4':[203,238],'T6':[262,228],\n"
"    'PO7':[60,268],'PO3':[107,260],'POz':[150,264],'PO4':[193,260],'PO8':[240,268],\n"
"    'O1':[108,288],'Oz':[150,294],'O2':[192,288],\n"
"    'AF3':[118,46],'AF4':[182,46],\n"
"    'F1':[123,72],'F2':[177,72],'F5':[62,80],'F6':[238,80],\n"
"    'FC1':[119,108],'FC2':[181,108],'FC5':[54,114],'FC6':[246,114],\n"
"    'C1':[114,155],'C2':[186,155],'C5':[50,155],'C6':[250,155],\n"
"    'CP1':[119,202],'CP2':[181,202],'CP5':[54,196],'CP6':[246,196],\n"
"    'P1':[122,240],'P2':[178,240],'P5':[72,236],'P6':[228,236],\n"
"    'PO1':[125,262],'PO2':[175,262],\n"
"  };\n"
"\n"
"  const BMP_REGION_SITES = {\n"
"    'DLPFC-L':    { primary:['F3'],        ref:['Fp2'],        alt:['AF3','F1','FC1'] },\n"
"    'DLPFC-R':    { primary:['F4'],        ref:['Fp1'],        alt:['AF4','F2','FC2'] },\n"
"    'DLPFC-B':    { primary:['F3','F4'],   ref:[],             alt:['Fz'] },\n"
"    'M1-L':       { primary:['C3'],        ref:['C4'],         alt:['FC3','CP3'] },\n"
"    'M1-R':       { primary:['C4'],        ref:['C3'],         alt:['FC4','CP4'] },\n"
"    'M1-B':       { primary:['C3','C4'],   ref:['Cz'],         alt:['FC3','FC4'] },\n"
"    'SMA':        { primary:['FCz','Cz'],  ref:[],             alt:['FC1','FC2','Fz'] },\n"
"    'mPFC':       { primary:['Fz'],        ref:['Pz'],         alt:['AFz','FCz'] },\n"
"    'DMPFC':      { primary:['Fz'],        ref:['Oz'],         alt:['FCz','AF4'] },\n"
"    'VMPFC':      { primary:['Fpz'],       ref:['Pz'],         alt:['Fp1','Fp2'] },\n"
"    'OFC':        { primary:['Fp1','Fp2'], ref:['Pz'],         alt:['AF3','AF4'] },\n"
"    'ACC':        { primary:['FCz'],       ref:['Pz'],         alt:['Cz','Fz'] },\n"
"    'IFG-L':      { primary:['F7'],        ref:['F8'],         alt:['FT7','FC3'] },\n"
"    'IFG-R':      { primary:['F8'],        ref:['F7'],         alt:['FT8','FC4'] },\n"
"    'PPC-L':      { primary:['P3'],        ref:['F4'],         alt:['CP3','P5'] },\n"
"    'PPC-R':      { primary:['P4'],        ref:['F3'],         alt:['CP4','P6'] },\n"
"    'TEMPORAL-L': { primary:['T7'],        ref:['T8'],         alt:['TP7','FT7'] },\n"
"    'TEMPORAL-R': { primary:['T8'],        ref:['T7'],         alt:['TP8','FT8'] },\n"
"    'S1':         { primary:['C3'],        ref:['C4'],         alt:['CP3','FC3'] },\n"
"    'V1':         { primary:['Oz'],        ref:['Cz'],         alt:['O1','O2'] },\n"
"    'CEREBELLUM': { primary:['Oz'],        ref:['Cz'],         alt:['O1','O2','POz'] },\n"
"    'Cz':         { primary:['Cz'],        ref:['Fz'],         alt:['FC1','FC2','CP1','CP2'] },\n"
"    'Pz':         { primary:['Pz'],        ref:['Fz'],         alt:['CPz','POz'] },\n"
"    'Fz':         { primary:['Fz'],        ref:['Pz'],         alt:['FCz','AFz'] },\n"
"  };\n"
"\n"
"  const BMP_PROTO_MAP = {\n"
"    'tms-mdd-hf-standard':    { region:'DLPFC-L', modality:'TMS/rTMS',     lat:'left',     freq:'10',      intensity:'120',  pulses:'3000', sessions:'36' },\n"
"    'tms-mdd-itbs':           { region:'DLPFC-L', modality:'iTBS',         lat:'left',     freq:'50',      intensity:'80',   pulses:'600',  sessions:'30' },\n"
"    'tms-mdd-bilateral':      { region:'DLPFC-B', modality:'TMS/rTMS',     lat:'bilateral',freq:'10',      intensity:'120',  pulses:'3000', sessions:'36' },\n"
"    'tms-mdd-saint':          { region:'DLPFC-L', modality:'iTBS',         lat:'left',     freq:'50',      intensity:'90',   pulses:'1800', sessions:'50' },\n"
"    'tms-ocd-h7coil':         { region:'DMPFC',   modality:'Deep TMS',     lat:'bilateral',freq:'20',      intensity:'100',  pulses:'2000', sessions:'29' },\n"
"    'tms-ocd-standard':       { region:'DMPFC',   modality:'TMS/rTMS',     lat:'bilateral',freq:'20',      intensity:'100',  pulses:'1500', sessions:'30' },\n"
"    'tms-anxiety-r-dlpfc':    { region:'DLPFC-R', modality:'TMS/rTMS',     lat:'right',    freq:'1',       intensity:'110',  pulses:'360',  sessions:'20' },\n"
"    'tms-ptsd-dlpfc':         { region:'DLPFC-L', modality:'TMS/rTMS',     lat:'left',     freq:'10',      intensity:'110',  pulses:'2000', sessions:'20' },\n"
"    'tms-schiz-avh':          { region:'TEMPORAL-L', modality:'TMS/rTMS',  lat:'left',     freq:'1',       intensity:'90',   pulses:'360',  sessions:'15' },\n"
"    'tms-parkinsons-motor':   { region:'M1-L',    modality:'TMS/rTMS',     lat:'bilateral',freq:'5',       intensity:'90',   pulses:'500',  sessions:'20' },\n"
"    'tdcs-mdd-anodal-f3':     { region:'DLPFC-L', modality:'tDCS',         lat:'left',     freq:'DC',      intensity:'2 mA', pulses:'\\u2014', sessions:'20' },\n"
"    'tdcs-adhd':              { region:'DLPFC-L', modality:'tDCS',         lat:'bilateral',freq:'DC',      intensity:'1 mA', pulses:'\\u2014', sessions:'15' },\n"
"    'tdcs-pain-m1':           { region:'M1-L',    modality:'tDCS',         lat:'left',     freq:'DC',      intensity:'2 mA', pulses:'\\u2014', sessions:'10' },\n"
"    'tdcs-stroke-motor':      { region:'M1-L',    modality:'tDCS',         lat:'left',     freq:'DC',      intensity:'2 mA', pulses:'\\u2014', sessions:'15' },\n"
"    'tdcs-aphasia':           { region:'IFG-L',   modality:'tDCS',         lat:'left',     freq:'DC',      intensity:'1 mA', pulses:'\\u2014', sessions:'15' },\n"
"    'nfb-alpha-theta-anxiety':{ region:'Pz',      modality:'Neurofeedback',lat:'bilateral',freq:'6-12Hz',  intensity:'\\u2014', pulses:'\\u2014', sessions:'30' },\n"
"    'nfb-smr-adhd':           { region:'Cz',      modality:'Neurofeedback',lat:'bilateral',freq:'12-15Hz', intensity:'\\u2014', pulses:'\\u2014', sessions:'40' },\n"
"    'nfb-gamma-cognition':    { region:'Fz',      modality:'Neurofeedback',lat:'bilateral',freq:'38-42Hz', intensity:'\\u2014', pulses:'\\u2014', sessions:'30' },\n"
"    'nfb-theta-alpha-depress':{ region:'Fz',      modality:'Neurofeedback',lat:'bilateral',freq:'4-12Hz',  intensity:'\\u2014', pulses:'\\u2014', sessions:'30' },\n"
"  };\n"
"\n"
"  const BMP_MNI = {\n"
"    'F3':'-46, 36, 20','F4':'46, 36, 20','C3':'-52, -2, 50','C4':'52, -2, 50',\n"
"    'Cz':'0, -2, 62','Fz':'0, 24, 58','Pz':'0, -62, 56','T7':'-72, -24, 4',\n"
"    'T8':'72, -24, 4','T5':'-62, -52, 0','T6':'62, -52, 0','Fp1':'-28, 70, 8',\n"
"    'Fp2':'28, 70, 8','Oz':'0, -100, 12','FCz':'0, 16, 62','F7':'-52, 22, 8',\n"
"    'F8':'52, 22, 8','O1':'-28, -102, 12','O2':'28, -102, 12',\n"
"    'P3':'-46, -58, 46','P4':'46, -58, 46',\n"
"  };\n"
"\n"
"  const BMP_BA = {\n"
"    'F3':'BA9/46','F4':'BA9/46','C3':'BA4','C4':'BA4','Cz':'BA4',\n"
"    'Fz':'BA8/32','Pz':'BA7','T7':'BA21/22','T8':'BA21/22',\n"
"    'Fp1':'BA10','Fp2':'BA10','Oz':'BA17','FCz':'BA6',\n"
"    'F7':'BA45/47','F8':'BA45/47','O1':'BA17/18','O2':'BA17/18',\n"
"    'P3':'BA40','P4':'BA40',\n"
"  };\n"
"\n"
"  const BMP_ANATOMY = {\n"
"    'Fpz':'Prefrontal Midline','Fp1':'Left Frontopolar Cortex','Fp2':'Right Frontopolar Cortex',\n"
"    'AF7':'Left Anterior Frontal','AFz':'Anterior Frontal Midline','AF8':'Right Anterior Frontal',\n"
"    'AF3':'Left Anterior Frontal (lat)','AF4':'Right Anterior Frontal (lat)',\n"
"    'F7':'Left Inferior Frontal Gyrus','F3':'Left Dorsolateral Prefrontal Cortex (DLPFC)',\n"
"    'Fz':'Supplementary Motor / Medial PFC','F4':'Right Dorsolateral Prefrontal Cortex (DLPFC)',\n"
"    'F8':'Right Inferior Frontal Gyrus',\n"
"    'F1':'Left Frontal (medial)','F2':'Right Frontal (medial)',\n"
"    'F5':'Left Frontal (lateral)','F6':'Right Frontal (lateral)',\n"
"    'FT7':'Left Frontotemporal','FC3':'Left Premotor / Frontal Eye Field',\n"
"    'FCz':'Supplementary Motor Area (SMA)','FC4':'Right Premotor','FT8':'Right Frontotemporal',\n"
"    'FC1':'Left SMA (medial)','FC2':'Right SMA (medial)',\n"
"    'FC5':'Left Premotor (lateral)','FC6':'Right Premotor (lateral)',\n"
"    'T7':'Left Superior Temporal Gyrus','C3':'Left Primary Motor Cortex (M1)',\n"
"    'Cz':'Primary Motor / Sensory Midline','C4':'Right Primary Motor Cortex (M1)',\n"
"    'T8':'Right Superior Temporal Gyrus',\n"
"    'C1':'Left Motor (medial)','C2':'Right Motor (medial)',\n"
"    'C5':'Left Motor (lateral)','C6':'Right Motor (lateral)',\n"
"    'TP7':'Left Temporoparietal Junction','CP3':'Left Somatosensory / Parietal',\n"
"    'CPz':'Parietal Midline','CP4':'Right Somatosensory / Parietal',\n"
"    'TP8':'Right Temporoparietal Junction',\n"
"    'CP1':'Left Parietal (medial)','CP2':'Right Parietal (medial)',\n"
"    'CP5':'Left Parietal (lateral)','CP6':'Right Parietal (lateral)',\n"
"    'T5':'Left Posterior Temporal','P3':'Left Inferior Parietal Lobule',\n"
"    'Pz':'Posterior Parietal Midline','P4':'Right Inferior Parietal Lobule',\n"
"    'T6':'Right Posterior Temporal',\n"
"    'P1':'Left Parietal (medial)','P2':'Right Parietal (medial)',\n"
"    'P5':'Left Parietal (lateral)','P6':'Right Parietal (lateral)',\n"
"    'PO7':'Left Parieto-Occipital','PO3':'Left Parieto-Occipital (medial)',\n"
"    'POz':'Parieto-Occipital Midline','PO4':'Right Parieto-Occipital (medial)',\n"
"    'PO8':'Right Parieto-Occipital',\n"
"    'PO1':'Left Parieto-Occipital (para)','PO2':'Right Parieto-Occipital (para)',\n"
"    'O1':'Left Primary Visual Cortex','Oz':'Occipital Midline / V1','O2':'Right Primary Visual Cortex',\n"
"  };\n"
"\n"
"  const BMP_CONDITIONS = {\n"
"    'F3':['MDD','TRD','PTSD','ADHD','Anxiety','Bipolar Depression'],\n"
"    'F4':['Anxiety','Depression (inhibitory)','OCD','Addiction'],\n"
"    'Fz':['ADHD','Depression (midline)','Neurofeedback','SMA disorders'],\n"
"    'FCz':['SMA','OCD (deep midline)','Motor recovery'],\n"
"    'C3':['Motor rehabilitation','Chronic pain','Parkinson','Stroke'],\n"
"    'C4':['Motor rehabilitation','Stroke (left hemisphere)','Chronic pain'],\n"
"    'Cz':['Neurofeedback (SMR)','Motor midline','ADHD'],\n"
"    'Pz':['Neurofeedback (alpha-theta)','Anxiety','Memory'],\n"
"    'T7':['Auditory hallucinations','Schizophrenia','Language disorders'],\n"
"    'T8':['Tinnitus','Right temporal disorders'],\n"
"    'F7':['Aphasia','IFG stimulation'],\n"
"    'Oz':['Visual cortex stimulation','Migraine','V1 research'],\n"
"  };\n"
"\n"
"  const BMP_PLACEMENT = {\n"
"    'F3': 'Position the coil 5 cm anterior and 2 cm lateral to M1 (C3). Target: -46,36,20 MNI. Beam F3: from Cz, 2cm left then 3cm forward.',\n"
"    'F4': '5 cm anterior and 2 cm lateral to C4. Mirror of F3. MNI: +46,36,20. From Cz: 2cm right then 3cm forward.',\n"
"    'C3': 'Motor cortex left. Locate Cz (50% nasion-inion), measure 7cm lateral left. Confirm with MEP for motor threshold.',\n"
"    'C4': 'Motor cortex right. Mirror of C3. 7cm lateral right from Cz.',\n"
"    'Cz': 'Midpoint: 50% of nasion-to-inion and 50% of tragus-to-tragus. Their intersection = Cz.',\n"
"    'Fz': 'Midline frontal. 30% from nasion along nasion-to-inion midline = Fz.',\n"
"    'FCz': 'Midpoint between Fz and Cz on the midline.',\n"
"    'T7': 'Left temporal. Step = 10% of nasion-inion arc. T7 is 3 steps lateral-left from Cz on temporal line.',\n"
"    'Oz': 'Occipital midline. 10% above the inion; measure upward from inion along midline.',\n"
"    'Fp1': 'Left frontopolar. ~5% from Fpz toward F7 on nasion arc.',\n"
"    'Fp2': 'Right frontopolar. Mirror of Fp1.',\n"
"    'F7': 'Left inferior frontal. Between F3 and T7; ~3 steps lateral from Fz on frontal arc.',\n"
"    'F8': 'Right inferior frontal. Mirror of F7.',\n"
"    'P3': 'Left inferior parietal. 7cm left from Pz, or 60% nasion-inion then 7cm lateral.',\n"
"    'P4': 'Right inferior parietal. Mirror of P3.',\n"
"    'T8': 'Right temporal. Mirror of T7.',\n"
"    'Pz': 'Parietal midline. 80% of nasion-to-inion distance from nasion.',\n"
"  };\n"
"\n"
"  const BMP_PROTO_LABELS = {\n"
"    'tms-mdd-hf-standard':    'HF-rTMS DLPFC-L (MDD)',\n"
"    'tms-mdd-itbs':           'iTBS DLPFC-L (MDD)',\n"
"    'tms-mdd-bilateral':      'Bilateral rTMS (MDD)',\n"
"    'tms-mdd-saint':          'SAINT / Accelerated iTBS',\n"
"    'tms-ocd-h7coil':         'Deep TMS H7-Coil (OCD)',\n"
"    'tms-ocd-standard':       'rTMS DMPFC (OCD)',\n"
"    'tms-anxiety-r-dlpfc':    'LF-rTMS R-DLPFC (Anxiety)',\n"
"    'tms-ptsd-dlpfc':         'rTMS DLPFC-L (PTSD)',\n"
"    'tms-schiz-avh':          'LF-rTMS Temporal-L (AVH)',\n"
"    'tms-parkinsons-motor':   'rTMS M1 (Parkinson)',\n"
"    'tdcs-mdd-anodal-f3':     'tDCS Anodal F3 (MDD)',\n"
"    'tdcs-adhd':              'tDCS DLPFC Bilateral (ADHD)',\n"
"    'tdcs-pain-m1':           'tDCS M1 (Chronic Pain)',\n"
"    'tdcs-stroke-motor':      'tDCS M1 (Stroke Motor)',\n"
"    'tdcs-aphasia':           'tDCS IFG-L (Aphasia)',\n"
"    'nfb-alpha-theta-anxiety':'NFB Alpha-Theta Pz (Anxiety)',\n"
"    'nfb-smr-adhd':           'NFB SMR Cz (ADHD)',\n"
"    'nfb-gamma-cognition':    'NFB Gamma Fz (Cognition)',\n"
"    'nfb-theta-alpha-depress':'NFB Theta-Alpha Fz (Depression)',\n"
"  };\n"
"\n"
"  const MODALITY_COLORS = {\n"
"    'TMS/rTMS':'#00d4bc','iTBS':'#00d4bc','cTBS':'#5ee7df','Deep TMS':'#06b6d4',\n"
"    'tDCS':'#4a9eff','tACS':'#818cf8','Neurofeedback':'#f59e0b',\n"
"    'taVNS':'#a78bfa','CES':'#34d399','PBM':'#fb923c','TPS':'#f472b6',\n"
"  };\n"
"\n"
"  let bmpState = {\n"
"    region:'', modality:'TMS/rTMS', lat:'left',\n"
"    freq:'', intensity:'', pulses:'', duration:'', sessions:'', notes:'',\n"
"    selectedSite:'', view:'clinical', protoId:'',\n"
"  };\n"
"\n"
"  let conds = [], protos = [];\n"
"  try {\n"
"    const apiObj = window._api || window.api;\n"
"    const [cd, pd] = await Promise.all([\n"
"      apiObj ? apiObj.conditions().catch(function() { return null; }) : Promise.resolve(null),\n"
"      apiObj ? apiObj.protocols().catch(function()  { return null; }) : Promise.resolve(null),\n"
"    ]);\n"
"    conds  = (cd && cd.items)  ? cd.items  : [];\n"
"    protos = (pd && pd.items)  ? pd.items  : [];\n"
"  } catch (_) {}\n"
"  if (!conds.length) conds = FALLBACK_CONDITIONS.map(function(n) { return { name: n }; });\n"
"\n"
"  function _esc(s) {\n"
"    return String(s || '').replace(/[&<>\"']/g, function(c) {\n"
"      return { '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', \"'\":'&#39;' }[c];\n"
"    });\n"
"  }\n"
"\n"
"  function _mc() { return MODALITY_COLORS[bmpState.modality] || '#00d4bc'; }\n"
"\n"
"  function _siteRole(site) {\n"
"    if (!bmpState.region || !BMP_REGION_SITES[bmpState.region]) return 'inactive';\n"
"    const rs = BMP_REGION_SITES[bmpState.region];\n"
"    if (rs.primary.indexOf(site) !== -1) return 'primary';\n"
"    if (rs.ref.indexOf(site)     !== -1) return 'ref';\n"
"    if (rs.alt.indexOf(site)     !== -1) return 'alt';\n"
"    return 'inactive';\n"
"  }\n"
"\n"
"  // SVG uses data-site attr + delegated events (avoids inline handler quoting issues)\n"
"  function _siteG(name, sx, sy, innerHtml) {\n"
"    return '<g class=\"bmp-site-g\" data-site=\"' + _esc(name) + '\" style=\"cursor:pointer\">'\n"
"      + innerHtml\n"
"      + '</g>';\n"
"  }\n"
"\n"
"  function _buildSVG(patientView) {\n"
"    const mc = _mc();\n"
"    const region = (bmpState.region && BMP_REGION_SITES[bmpState.region])\n"
"      ? BMP_REGION_SITES[bmpState.region] : { primary:[], ref:[], alt:[] };\n"
"    const pp = region.primary, rp = region.ref, ap = region.alt;\n"
"    const sp = [];\n"
"    const s = function(x) { sp.push(x); };\n"
"    s('<svg id=\"bmp-svg\" viewBox=\"0 0 300 310\" width=\"280\" height=\"290\"'\n"
"      + ' xmlns=\"http://www.w3.org/2000/svg\" style=\"display:block;overflow:visible\">');\n"
"    s('<defs><filter id=\"bmp-glow\" x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\">'\n"
"      + '<feGaussianBlur stdDeviation=\"3\" result=\"blur\"/>'\n"
"      + '<feMerge><feMergeNode in=\"blur\"/><feMergeNode in=\"SourceGraphic\"/></feMerge>'\n"
"      + '</filter></defs>');\n"
"    s('<ellipse cx=\"150\" cy=\"155\" rx=\"128\" ry=\"148\" fill=\"#0f1623\"'\n"
"      + ' stroke=\"rgba(148,163,184,0.25)\" stroke-width=\"1.5\"/>');\n"
"    s('<path d=\"M143,8 Q150,2 157,8\" fill=\"none\" stroke=\"rgba(148,163,184,0.25)\"'\n"
"      + ' stroke-width=\"1.5\" stroke-linecap=\"round\"/>');\n"
"    s('<path d=\"M22,148 Q15,155 22,162\" fill=\"none\" stroke=\"rgba(148,163,184,0.25)\"'\n"
"      + ' stroke-width=\"1.5\" stroke-linecap=\"round\"/>');\n"
"    s('<path d=\"M278,148 Q285,155 278,162\" fill=\"none\" stroke=\"rgba(148,163,184,0.25)\"'\n"
"      + ' stroke-width=\"1.5\" stroke-linecap=\"round\"/>');\n"
"    s('<line x1=\"150\" y1=\"10\" x2=\"150\" y2=\"300\" stroke=\"rgba(148,163,184,0.08)\"'\n"
"      + ' stroke-width=\"0.5\" stroke-dasharray=\"4 4\"/>');\n"
"    s('<line x1=\"22\" y1=\"155\" x2=\"278\" y2=\"155\" stroke=\"rgba(148,163,184,0.08)\"'\n"
"      + ' stroke-width=\"0.5\" stroke-dasharray=\"4 4\"/>');\n"
"    if (patientView) {\n"
"      pp.forEach(function(site) {\n"
"        const pos = BMP_SITES[site]; if (!pos) return;\n"
"        const sx = pos[0], sy = pos[1];\n"
"        const anat = BMP_ANATOMY[site] || site;\n"
"        const lbl  = anat.length > 22 ? anat.slice(0, 22) + '...' : anat;\n"
"        s(_siteG(site, sx, sy,\n"
"          '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"32\" fill=\"' + mc + '\" opacity=\"0.18\"/>'\n"
"          + '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"22\" fill=\"' + mc + '\" opacity=\"0.28\"/>'\n"
"          + '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"13\" fill=\"' + mc + '\" opacity=\"0.55\"/>'\n"
"          + '<text x=\"' + sx + '\" y=\"' + (sy + 42) + '\" text-anchor=\"middle\" font-size=\"7.5\"'\n"
"          + ' fill=\"rgba(255,255,255,0.7)\" font-family=\"system-ui\">' + _esc(lbl) + '</text>'\n"
"        ));\n"
"      });\n"
"    } else {\n"
"      Object.keys(BMP_SITES).forEach(function(name) {\n"
"        if (_siteRole(name) !== 'inactive') return;\n"
"        const pos = BMP_SITES[name];\n"
"        const sx = pos[0], sy = pos[1];\n"
"        s(_siteG(name, sx, sy,\n"
"          '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"5\" fill=\"rgba(148,163,184,0.10)\"'\n"
"          + ' stroke=\"rgba(148,163,184,0.22)\" stroke-width=\"0.8\"/>'\n"
"          + '<text x=\"' + (sx + 7) + '\" y=\"' + (sy + 3) + '\" font-size=\"6\"'\n"
"          + ' fill=\"rgba(148,163,184,0.35)\" font-family=\"system-ui\">' + _esc(name) + '</text>'\n"
"        ));\n"
"      });\n"
"      ap.forEach(function(name) {\n"
"        const pos = BMP_SITES[name]; if (!pos) return;\n"
"        const sx = pos[0], sy = pos[1];\n"
"        s(_siteG(name, sx, sy,\n"
"          '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"7\" fill=\"rgba(74,158,255,0.15)\"'\n"
"          + ' stroke=\"#4a9eff\" stroke-width=\"0.8\" stroke-dasharray=\"3 2\"/>'\n"
"          + '<text x=\"' + (sx + 9) + '\" y=\"' + (sy + 3) + '\" font-size=\"7\"'\n"
"          + ' fill=\"rgba(74,158,255,0.7)\" font-family=\"system-ui\">' + _esc(name) + '</text>'\n"
"        ));\n"
"      });\n"
"      rp.forEach(function(name) {\n"
"        const pos = BMP_SITES[name]; if (!pos) return;\n"
"        const sx = pos[0], sy = pos[1];\n"
"        s(_siteG(name, sx, sy,\n"
"          '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"13\" fill=\"#ffb547\" opacity=\"0.12\"/>'\n"
"          + '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"8\" fill=\"#ffb547\" opacity=\"0.55\"'\n"
"          + ' filter=\"url(#bmp-glow)\"/>'\n"
"          + '<text x=\"' + (sx + 10) + '\" y=\"' + (sy + 3) + '\" font-size=\"7.5\" fill=\"#ffb547\"'\n"
"          + ' font-weight=\"600\" font-family=\"system-ui\">' + _esc(name)\n"
"          + (bmpState.modality === 'tDCS' ? ' \\u2212' : '') + '</text>'\n"
"        ));\n"
"      });\n"
"      pp.forEach(function(name) {\n"
"        const pos = BMP_SITES[name]; if (!pos) return;\n"
"        const sx = pos[0], sy = pos[1];\n"
"        const isTDCS = (bmpState.modality === 'tDCS');\n"
"        const isNFB  = (bmpState.modality === 'Neurofeedback');\n"
"        const isTMS  = (['TMS/rTMS','iTBS','cTBS','Deep TMS'].indexOf(bmpState.modality) !== -1);\n"
"        s('<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"18\" fill=\"' + mc + '\" opacity=\"0.09\"/>');\n"
"        s('<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"14\" fill=\"' + mc + '\" opacity=\"0.13\"/>');\n"
"        if (isTMS) {\n"
"          s('<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"18\" fill=\"none\" stroke=\"' + mc + '\"'\n"
"            + ' stroke-width=\"3\" stroke-dasharray=\"2 3\" opacity=\"0.35\"/>');\n"
"          s('<line x1=\"' + sx + '\" y1=\"' + (sy - 18) + '\" x2=\"' + sx + '\" y2=\"' + (sy - 25) + '\"'\n"
"            + ' stroke=\"' + mc + '\" stroke-width=\"2\" opacity=\"0.5\"/>');\n"
"        }\n"
"        if (isNFB) {\n"
"          s('<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"16\" fill=\"none\" stroke=\"' + mc + '\"'\n"
"            + ' stroke-width=\"1.5\" stroke-dasharray=\"4 3\" opacity=\"0.4\"/>');\n"
"          s('<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"22\" fill=\"none\" stroke=\"' + mc + '\"'\n"
"            + ' stroke-width=\"1\" stroke-dasharray=\"6 4\" opacity=\"0.25\"/>');\n"
"        }\n"
"        s(_siteG(name, sx, sy,\n"
"          '<circle cx=\"' + sx + '\" cy=\"' + sy + '\" r=\"9\" fill=\"' + mc + '\" opacity=\"0.85\"'\n"
"          + ' filter=\"url(#bmp-glow)\"/>'\n"
"          + '<text x=\"' + (sx + 11) + '\" y=\"' + (sy + 3) + '\" font-size=\"8\" fill=\"' + mc + '\"'\n"
"          + ' font-weight=\"700\" font-family=\"system-ui\">' + _esc(name)\n"
"          + (isTDCS ? ' +' : '') + '</text>'\n"
"        ));\n"
"      });\n"
"    }\n"
"    s('</svg>');\n"
"    return sp.join('');\n"
"  }\n"
"\n"
"  // Attach delegated events to the SVG container after it is rendered\n"
"  function _attachSVGEvents(container) {\n"
"    if (!container) return;\n"
"    container.addEventListener('click', function(e) {\n"
"      const g = e.target.closest('[data-site]');\n"
"      if (g) window._bmpSiteClick(g.dataset.site);\n"
"    });\n"
"    container.addEventListener('mouseover', function(e) {\n"
"      const g = e.target.closest('[data-site]');\n"
"      if (g) window._bmpSiteHover(g.dataset.site, true, e);\n"
"    });\n"
"    container.addEventListener('mouseout', function(e) {\n"
"      const g = e.target.closest('[data-site]');\n"
"      if (g) window._bmpSiteHover(g.dataset.site, false, e);\n"
"    });\n"
"  }\n"
"\n"
"  function _buildDetailPanel(site) {\n"
"    if (!site) {\n"
"      return '<div class=\"bmp-detail-placeholder\">'\n"
"        + '<div style=\"font-size:13px;color:var(--text-tertiary);text-align:center;padding:40px 0\">'\n"
"        + 'Click any electrode on the map<br>or load a protocol to see details'\n"
"        + '</div></div>';\n"
"    }\n"
"    const anat = BMP_ANATOMY[site] || site;\n"
"    const mni  = BMP_MNI[site]  || '\\u2014';\n"
"    const ba   = BMP_BA[site]   || '\\u2014';\n"
"    const condArr = BMP_CONDITIONS[site] || [];\n"
"    const condsHtml = condArr.map(function(c) {\n"
"      return '<span class=\"bmp-cond-chip\">' + _esc(c) + '</span>';\n"
"    }).join('');\n"
"    const placement = BMP_PLACEMENT[site] || 'See 10-20 standard for placement.';\n"
"    let siteRegion = '';\n"
"    const rkeys = Object.keys(BMP_REGION_SITES);\n"
"    for (let ri = 0; ri < rkeys.length; ri++) {\n"
"      const rv = BMP_REGION_SITES[rkeys[ri]];\n"
"      if (rv.primary.indexOf(site) !== -1 || rv.ref.indexOf(site) !== -1 || rv.alt.indexOf(site) !== -1) {\n"
"        siteRegion = rkeys[ri]; break;\n"
"      }\n"
"    }\n"
"    const altSites = (siteRegion && BMP_REGION_SITES[siteRegion]) ? BMP_REGION_SITES[siteRegion].alt : [];\n"
"    const linkedProtos = [];\n"
"    Object.keys(BMP_PROTO_MAP).forEach(function(pid) {\n"
"      const rs = BMP_REGION_SITES[BMP_PROTO_MAP[pid].region];\n"
"      if (rs && (rs.primary.indexOf(site) !== -1 || rs.ref.indexOf(site) !== -1) && linkedProtos.length < 6)\n"
"        linkedProtos.push(pid);\n"
"    });\n"
"    let h = '<div class=\"bmp-detail-card\">';\n"
"    h += '<div class=\"bmp-detail-site-name\">' + _esc(site) + '</div>';\n"
"    h += '<div class=\"bmp-detail-region\">' + _esc(anat) + '</div>';\n"
"    h += '<div style=\"display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px\">';\n"
"    if (mni !== '\\u2014') h += '<span style=\"font-size:11px;padding:2px 8px;border-radius:6px;background:rgba(255,255,255,0.04);border:1px solid var(--border);color:var(--text-secondary)\">MNI: ' + _esc(mni) + '</span>';\n"
"    if (ba  !== '\\u2014') h += '<span style=\"font-size:11px;padding:2px 8px;border-radius:6px;background:rgba(255,255,255,0.04);border:1px solid var(--border);color:var(--text-secondary)\">' + _esc(ba) + '</span>';\n"
"    h += '</div>';\n"
"    if (condsHtml) {\n"
"      h += '<div class=\"bmp-detail-section-label\">Associated Conditions</div>';\n"
"      h += '<div style=\"display:flex;flex-wrap:wrap;gap:5px;margin-bottom:4px\">' + condsHtml + '</div>';\n"
"    }\n"
"    h += '<div class=\"bmp-detail-section-label\">Placement Guidance</div>';\n"
"    h += '<div class=\"bmp-placement-text\">' + _esc(placement) + '</div>';\n"
"    if (altSites.length) {\n"
"      h += '<div class=\"bmp-detail-section-label\">Alternate Targets</div>';\n"
"      h += '<div style=\"display:flex;flex-wrap:wrap;gap:5px\">';\n"
"      altSites.forEach(function(s2) {\n"
"        h += '<button class=\"bmp-alt-btn\" data-altsite=\"' + _esc(s2) + '\">'\n"
"          + _esc(s2) + '</button>';\n"
"      });\n"
"      h += '</div>';\n"
"    }\n"
"    if (linkedProtos.length) {\n"
"      h += '<div class=\"bmp-detail-section-label\">Linked Protocols</div>';\n"
"      h += '<div style=\"display:flex;flex-direction:column;gap:5px\">';\n"
"      linkedProtos.forEach(function(pid) {\n"
"        h += '<button class=\"bmp-proto-link\" data-proto=\"' + _esc(pid) + '\">'\n"
"          + _esc(BMP_PROTO_LABELS[pid] || pid) + '</button>';\n"
"      });\n"
"      h += '</div>';\n"
"    }\n"
"    h += '</div>';\n"
"    return h;\n"
"  }\n"
"\n"
"  function _updateMap() {\n"
"    const ctr = document.getElementById('bmp-svg-container');\n"
"    if (!ctr) return;\n"
"    ctr.innerHTML = _buildSVG(bmpState.view === 'patient');\n"
"    _attachSVGEvents(ctr);\n"
"  }\n"
"\n"
"  function _updateDetail() {\n"
"    const dp = document.getElementById('bmp-detail-panel');\n"
"    if (dp) dp.innerHTML = _buildDetailPanel(bmpState.selectedSite);\n"
"  }\n"
"\n"
"  function _updateParams() {\n"
"    const pp = document.getElementById('bmp-params-section');\n"
"    if (pp) pp.style.display = (bmpState.modality || bmpState.protoId) ? '' : 'none';\n"
"  }\n"
"\n"
"  function _loadProtocol(pid) {\n"
"    const pm = BMP_PROTO_MAP[pid]; if (!pm) return;\n"
"    bmpState.protoId   = pid;\n"
"    bmpState.region    = pm.region;\n"
"    bmpState.modality  = pm.modality;\n"
"    bmpState.lat       = pm.lat;\n"
"    bmpState.freq      = pm.freq;\n"
"    bmpState.intensity = pm.intensity;\n"
"    bmpState.pulses    = pm.pulses;\n"
"    bmpState.sessions  = pm.sessions;\n"
"    const modSel = document.getElementById('bmp-mod-sel');\n"
"    if (modSel) modSel.value = pm.modality;\n"
"    document.querySelectorAll('.bmp-lat-btn').forEach(function(b) {\n"
"      b.classList.toggle('bmp-lat-active', b.dataset.lat === pm.lat);\n"
"    });\n"
"    ['freq','intensity','pulses','sessions'].forEach(function(k) {\n"
"      const inp = document.getElementById('bmp-param-' + k);\n"
"      if (inp) inp.value = pm[k] || '';\n"
"    });\n"
"    const ps = document.getElementById('bmp-proto-sel');\n"
"    if (ps) ps.value = pid;\n"
"    const rs = BMP_REGION_SITES[pm.region];\n"
"    if (rs && rs.primary.length) bmpState.selectedSite = rs.primary[0];\n"
"    _updateMap(); _updateDetail(); _updateParams();\n"
"  }\n"
"\n"
"  const protoOptions = Object.keys(BMP_PROTO_LABELS).map(function(id) {\n"
"    return '<option value=\"' + _esc(id) + '\">' + _esc(BMP_PROTO_LABELS[id]) + '</option>';\n"
"  }).join('');\n"
"\n"
"  const condOptions = conds.map(function(c) {\n"
"    const n = c.name || c;\n"
"    return '<option value=\"' + _esc(n) + '\">' + _esc(n) + '</option>';\n"
"  }).join('');\n"
"\n"
"  const modalityOptions = ['TMS/rTMS','iTBS','cTBS','Deep TMS','tDCS','tACS',\n"
"    'Neurofeedback','taVNS','CES','PBM','TPS'].map(function(m) {\n"
"    return '<option value=\"' + _esc(m) + '\"'\n"
"      + (m === bmpState.modality ? ' selected' : '') + '>' + _esc(m) + '</option>';\n"
"  }).join('');\n"
"\n"
"  const latVal = bmpState.lat;\n"
"  function _latBtn(v, lbl) {\n"
"    return '<button class=\"bmp-lat-btn' + (latVal === v ? ' bmp-lat-active' : '') + '\"'\n"
"      + ' data-lat=\"' + v + '\">'\n"
"      + lbl + '</button>';\n"
"  }\n"
"\n"
"  el.innerHTML =\n"
"    '<div class=\"bmp-layout\">'\n"
"    + '<div class=\"bmp-panel bmp-panel--left\">'\n"
"      + '<div class=\"bmp-section-card\">'\n"
"        + '<div class=\"bmp-section-title\">Load Protocol</div>'\n"
"        + '<select id=\"bmp-proto-sel\" class=\"form-select\" style=\"width:100%;font-size:12px\"'\n"
"          + ' onchange=\"window._bmpLoadProto(this.value)\">'\n"
"          + '<option value=\"\">\\u2014 select protocol \\u2014</option>'\n"
"          + protoOptions\n"
"        + '</select>'\n"
"      + '</div>'\n"
"      + '<div style=\"display:flex;align-items:center;gap:8px;margin:2px 0 4px\">'\n"
"        + '<div style=\"flex:1;height:1px;background:var(--border)\"></div>'\n"
"        + '<span style=\"font-size:11px;color:var(--text-tertiary);white-space:nowrap\">or configure manually</span>'\n"
"        + '<div style=\"flex:1;height:1px;background:var(--border)\"></div>'\n"
"      + '</div>'\n"
"      + '<div class=\"bmp-section-card\">'\n"
"        + '<div class=\"bmp-section-title\">Condition</div>'\n"
"        + '<select id=\"bmp-cond-sel\" class=\"form-select\" style=\"width:100%;font-size:12px\">'\n"
"          + '<option value=\"\">\\u2014 select \\u2014</option>' + condOptions\n"
"        + '</select>'\n"
"      + '</div>'\n"
"      + '<div class=\"bmp-section-card\">'\n"
"        + '<div class=\"bmp-section-title\">Modality</div>'\n"
"        + '<select id=\"bmp-mod-sel\" class=\"form-select\" style=\"width:100%;font-size:12px\"'\n"
"          + ' onchange=\"window._bmpSetModality(this.value)\">'\n"
"          + modalityOptions\n"
"        + '</select>'\n"
"      + '</div>'\n"
"      + '<div class=\"bmp-section-card\">'\n"
"        + '<div class=\"bmp-section-title\">Laterality</div>'\n"
"        + '<div class=\"bmp-lat-toggle\">'\n"
"          + _latBtn('left','Left') + _latBtn('bilateral','Bilateral') + _latBtn('right','Right')\n"
"        + '</div>'\n"
"      + '</div>'\n"
"      + '<div id=\"bmp-params-section\" class=\"bmp-section-card\" style=\"display:none\">'\n"
"        + '<div class=\"bmp-section-title\">Parameters</div>'\n"
"        + '<div style=\"display:flex;flex-direction:column;gap:8px\">'\n"
"          + '<label style=\"font-size:11px;color:var(--text-secondary)\">Frequency (Hz)'\n"
"            + '<input id=\"bmp-param-freq\" class=\"form-input\" type=\"text\"'\n"
"            + ' style=\"margin-top:3px;width:100%;font-size:12px;box-sizing:border-box\"></label>'\n"
"          + '<label style=\"font-size:11px;color:var(--text-secondary)\">Intensity (% MT)'\n"
"            + '<input id=\"bmp-param-intensity\" class=\"form-input\" type=\"text\"'\n"
"            + ' style=\"margin-top:3px;width:100%;font-size:12px;box-sizing:border-box\"></label>'\n"
"          + '<label style=\"font-size:11px;color:var(--text-secondary)\">Pulses/session'\n"
"            + '<input id=\"bmp-param-pulses\" class=\"form-input\" type=\"text\"'\n"
"            + ' style=\"margin-top:3px;width:100%;font-size:12px;box-sizing:border-box\"></label>'\n"
"          + '<label style=\"font-size:11px;color:var(--text-secondary)\">Duration (min)'\n"
"            + '<input id=\"bmp-param-duration\" class=\"form-input\" type=\"text\"'\n"
"            + ' style=\"margin-top:3px;width:100%;font-size:12px;box-sizing:border-box\"></label>'\n"
"          + '<label style=\"font-size:11px;color:var(--text-secondary)\">Sessions'\n"
"            + '<input id=\"bmp-param-sessions\" class=\"form-input\" type=\"text\"'\n"
"            + ' style=\"margin-top:3px;width:100%;font-size:12px;box-sizing:border-box\"></label>'\n"
"          + '<label style=\"font-size:11px;color:var(--text-secondary)\">Notes'\n"
"            + '<textarea id=\"bmp-param-notes\" class=\"form-input\" rows=\"2\"'\n"
"            + ' style=\"margin-top:3px;width:100%;font-size:12px;box-sizing:border-box;resize:vertical\"></textarea></label>'\n"
"        + '</div>'\n"
"      + '</div>'\n"
"      + '<div style=\"display:flex;flex-direction:column;gap:6px;margin-top:4px\">'\n"
"        + '<button class=\"btn btn-sm\" style=\"border-color:var(--teal);color:var(--teal);font-size:12px\"'\n"
"          + ' onclick=\"window._bmpPrescribe()\">Add to Prescription</button>'\n"
"        + '<button class=\"btn btn-sm\" style=\"font-size:12px\"'\n"
"          + ' onclick=\"window._bmpUseInWizard()\">Use in Protocol Wizard</button>'\n"
"      + '</div>'\n"
"    + '</div>'\n"
"    + '<div class=\"bmp-panel bmp-panel--map\">'\n"
"      + '<div class=\"bmp-map-wrap\">'\n"
"        + '<div class=\"bmp-map-header\">'\n"
"          + '<span style=\"font-size:13px;font-weight:700;color:var(--text-primary)\">Electrode Map</span>'\n"
"          + '<div class=\"bmp-view-toggle\">'\n"
"            + '<button class=\"bmp-view-btn bmp-view-active\" data-view=\"clinical\">Clinical</button>'\n"
"            + '<button class=\"bmp-view-btn\" data-view=\"patient\">Patient</button>'\n"
"          + '</div>'\n"
"        + '</div>'\n"
"        + '<div class=\"bmp-svg-wrap\"><div id=\"bmp-svg-container\">' + _buildSVG(false) + '</div></div>'\n"
"        + '<div class=\"bmp-legend-row\">'\n"
"          + '<div class=\"bmp-legend-item\"><span class=\"bmp-legend-swatch\" style=\"background:var(--teal)\"></span>Primary</div>'\n"
"          + '<div class=\"bmp-legend-item\"><span class=\"bmp-legend-swatch\" style=\"background:#ffb547\"></span>Reference</div>'\n"
"          + '<div class=\"bmp-legend-item\"><span class=\"bmp-legend-swatch\" style=\"background:#4a9eff;opacity:0.6\"></span>Alternate</div>'\n"
"          + '<div class=\"bmp-legend-item\"><span class=\"bmp-legend-swatch\" style=\"background:rgba(148,163,184,0.3)\"></span>Inactive</div>'\n"
"        + '</div>'\n"
"      + '</div>'\n"
"    + '</div>'\n"
"    + '<div class=\"bmp-panel bmp-panel--right\">'\n"
"      + '<div id=\"bmp-detail-panel\">' + _buildDetailPanel('') + '</div>'\n"
"      + '<div style=\"margin-top:8px;display:flex;flex-direction:column;gap:6px\">'\n"
"        + '<button class=\"btn btn-sm\" style=\"font-size:12px\" onclick=\"window._bmpViewDetail()\">View Protocol Detail</button>'\n"
"        + '<button class=\"btn btn-sm\" style=\"font-size:12px\" onclick=\"window._bmpPrescribeProto(window._bmpState && window._bmpState.protoId)\">Prescribe This Protocol</button>'\n"
"      + '</div>'\n"
"    + '</div>'\n"
"    + '</div>'\n"
"    + '<div id=\"bmp-tooltip\" class=\"bmp-tooltip\" style=\"display:none\"></div>';\n"
"\n"
"  // Attach SVG events after initial render\n"
"  _attachSVGEvents(document.getElementById('bmp-svg-container'));\n"
"\n"
"  // Delegated events for lat buttons\n"
"  const latToggle = el.querySelector('.bmp-lat-toggle');\n"
"  if (latToggle) {\n"
"    latToggle.addEventListener('click', function(e) {\n"
"      const b = e.target.closest('[data-lat]');\n"
"      if (!b) return;\n"
"      bmpState.lat = b.dataset.lat;\n"
"      el.querySelectorAll('.bmp-lat-btn').forEach(function(btn) {\n"
"        btn.classList.toggle('bmp-lat-active', btn.dataset.lat === bmpState.lat);\n"
"      });\n"
"    });\n"
"  }\n"
"\n"
"  // View toggle\n"
"  const viewToggle = el.querySelector('.bmp-view-toggle');\n"
"  if (viewToggle) {\n"
"    viewToggle.addEventListener('click', function(e) {\n"
"      const b = e.target.closest('[data-view]');\n"
"      if (!b) return;\n"
"      bmpState.view = b.dataset.view;\n"
"      el.querySelectorAll('.bmp-view-btn').forEach(function(btn) {\n"
"        btn.classList.toggle('bmp-view-active', btn.dataset.view === bmpState.view);\n"
"      });\n"
"      _updateMap();\n"
"    });\n"
"  }\n"
"\n"
"  // Detail panel delegated events (alt targets + linked protocols)\n"
"  const detailPanel = document.getElementById('bmp-detail-panel');\n"
"  if (detailPanel) {\n"
"    detailPanel.addEventListener('click', function(e) {\n"
"      const ab = e.target.closest('[data-altsite]');\n"
"      if (ab) { window._bmpSiteClick(ab.dataset.altsite); return; }\n"
"      const pb = e.target.closest('[data-proto]');\n"
"      if (pb) { window._bmpLoadProto(pb.dataset.proto); return; }\n"
"    });\n"
"  }\n"
"\n"
"  // ── global handlers ───────────────────────────────────────────────────────\n"
"  window._bmpLoadProto = function(pid) { if (pid) _loadProtocol(pid); };\n"
"\n"
"  window._bmpSetModality = function(m) {\n"
"    bmpState.modality = m; _updateMap(); _updateParams();\n"
"  };\n"
"\n"
"  window._bmpSetLat = function(lat) {\n"
"    bmpState.lat = lat;\n"
"    el.querySelectorAll('.bmp-lat-btn').forEach(function(b) {\n"
"      b.classList.toggle('bmp-lat-active', b.dataset.lat === lat);\n"
"    });\n"
"  };\n"
"\n"
"  window._bmpSetView = function(v) {\n"
"    bmpState.view = v;\n"
"    const btns = el.querySelectorAll('.bmp-view-btn');\n"
"    btns.forEach(function(b) { b.classList.toggle('bmp-view-active', b.dataset.view === v); });\n"
"    _updateMap();\n"
"  };\n"
"\n"
"  window._bmpSiteHover = function(name, on, evt) {\n"
"    const tt = document.getElementById('bmp-tooltip');\n"
"    if (!tt) return;\n"
"    if (!on) {\n"
"      tt.style.display = 'none';\n"
"      return;\n"
"    }\n"
"    const anat = BMP_ANATOMY[name] || name;\n"
"    const cl   = (BMP_CONDITIONS[name] || []).join(', ') || 'General electrode site';\n"
"    tt.innerHTML = '<strong style=\"font-size:13px\">' + name + '</strong>'\n"
"      + '<br><span style=\"font-size:11px;color:rgba(255,255,255,0.7)\">' + anat + '</span>'\n"
"      + '<br><span style=\"font-size:10px;color:rgba(255,255,255,0.5);margin-top:4px;display:block\">' + cl + '</span>';\n"
"    tt.style.display = 'block';\n"
"    if (evt) { tt.style.left = (evt.clientX + 14) + 'px'; tt.style.top = (evt.clientY - 10) + 'px'; }\n"
"  };\n"
"\n"
"  document.addEventListener('mousemove', function(e) {\n"
"    const tt = document.getElementById('bmp-tooltip');\n"
"    if (tt && tt.style.display !== 'none') {\n"
"      tt.style.left = (e.clientX + 14) + 'px';\n"
"      tt.style.top  = (e.clientY - 10) + 'px';\n"
"    }\n"
"  });\n"
"\n"
"  window._bmpSiteClick = function(name) {\n"
"    bmpState.selectedSite = name;\n"
"    _updateDetail(); _updateMap(); _updateParams();\n"
"  };\n"
"\n"
"  window._bmpPrescribe   = function() { window._nav('prescriptions'); };\n"
"  window._bmpUseInWizard = function() { window._nav('protocol-wizard'); };\n"
"\n"
"  window._bmpViewDetail = function() {\n"
"    if (bmpState.protoId && protos && protos.find) {\n"
"      const p = protos.find(function(pr) { return (pr.id || '') === bmpState.protoId; });\n"
"      if (p) window._pilDetailProto = p;\n"
"    }\n"
"    window._nav('protocol-detail');\n"
"  };\n"
"\n"
"  window._bmpPrescribeProto = function(pid) {\n"
"    if (pid && protos && protos.find) {\n"
"      const p = protos.find(function(pr) { return (pr.id || '').replace(/['\"<>&]/g, '') === pid; });\n"
"      if (p) window._rxPrefilledProto = p;\n"
"    }\n"
"    window._nav('prescriptions');\n"
"  };\n"
"\n"
"  window._bmpState = bmpState;\n"
"}\n"
)

out_path = r'C:\Users\yildi\DeepSynaps-Protocol-Studio\_bmp_func.txt'
with open(out_path, 'w', encoding='utf-8', newline='') as f:
    f.write(FUNC)

print(f'Written {len(FUNC)} chars to {out_path}')
print(f'Backtick count: {FUNC.count(chr(96))}')
print('First 200:', repr(FUNC[:200]))
print('Last 80:', repr(FUNC[-80:]))
