"""MultimodalTimelineEngine — unifies patient events across all modalities into a sorted timeline."""

from datetime import datetime, timedelta, timezone
from typing import List, Optional, Tuple

from contracts import MultimodalEvent
from knowledge_layer import KnowledgeLayer


class MultimodalTimelineEngine:
    """Builds unified, sorted patient timelines from all multimodal data sources."""

    ALL_MODALITIES = [
        "assessment", "qeeg", "mri", "biomarker", "lab",
        "medication", "intervention", "session", "voice", "text",
        "video", "movement", "wearable", "digital_phenotyping",
        "risk_signal", "report", "document", "patient_checkin",
    ]

    def __init__(self, knowledge_layer: KnowledgeLayer):
        self.kl = knowledge_layer

    def build_timeline(
        self,
        patient_id: str,
        modality_filter: Optional[List[str]] = None,
        date_range: Optional[Tuple[datetime, datetime]] = None,
    ) -> List[MultimodalEvent]:
        """Build a unified patient timeline sorted by timestamp ascending."""
        if modality_filter:
            invalid = [m for m in modality_filter if m not in self.ALL_MODALITIES]
            if invalid:
                raise ValueError(f"Unknown modalities in filter: {invalid}")

        events = self.kl.get_events_for_patient(
            patient_id=patient_id,
            modality_filter=modality_filter,
            date_range=date_range,
        )
        events.sort(key=lambda e: (e.timestamp, e.event_id))
        return events

    def seed_sample_events(self, patient_id: str) -> List[str]:
        """Insert realistic sample events across 7+ modalities with varied timestamps."""
        now = datetime.now()
        base = now - timedelta(days=60)

        seed_events = [
            {
                "patient_id": patient_id,
                "event_type": "cognitive_assessment",
                "modality": "assessment",
                "source_system": "redcap",
                "source_record_id": f"mmse_{patient_id}_001",
                "timestamp": base + timedelta(days=0, hours=9),
                "value_summary": "MMSE score 28/30 (mild attention deficit)",
                "numeric_features": {"mmse_total": 28.0, "attention_subscore": 4.0},
                "textual_summary": "Patient showed mild difficulty with serial sevens. Orientation intact.",
                "confidence": 0.92,
                "data_quality": "high",
                "provenance": {"entered_by": "clinician_001", "site": "clinic_a"},
                "evidence_links": ["ev_assessment_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "mood_assessment",
                "modality": "assessment",
                "source_system": "redcap",
                "source_record_id": f"phq9_{patient_id}_002",
                "timestamp": base + timedelta(days=0, hours=9, minutes=30),
                "value_summary": "PHQ-9 score 12 (moderate depression)",
                "numeric_features": {"phq9_total": 12.0, "sleep_item": 2.0},
                "textual_summary": "Patient reports low mood, sleep disturbance, and reduced interest.",
                "confidence": 0.88,
                "data_quality": "high",
                "provenance": {"entered_by": "clinician_001", "site": "clinic_a"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "qeeg_recording",
                "modality": "qeeg",
                "source_system": "neuroguide",
                "source_record_id": f"qeeg_{patient_id}_001",
                "timestamp": base + timedelta(days=2, hours=10),
                "value_summary": "Elevated frontal theta/beta ratio (2.8, norm <2.5)",
                "numeric_features": {"theta_beta_ratio_frontal": 2.8, "alpha_peak_hz": 9.2},
                "textual_summary": "Increased slow-wave activity in frontal regions.",
                "confidence": 0.78,
                "data_quality": "high",
                "provenance": {"acquired_by": "tech_002", "reviewed_by": "neuro_001"},
                "evidence_links": ["ev_qeeg_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "mri_scan",
                "modality": "mri",
                "source_system": "pacs",
                "source_record_id": f"mri_{patient_id}_001",
                "timestamp": base + timedelta(days=3, hours=14),
                "value_summary": "Mild hippocampal volume reduction (z-score -1.4)",
                "numeric_features": {"hippocampal_volume_z": -1.4, "cortical_thickness_mm": 2.3},
                "textual_summary": "Structural MRI shows mild medial temporal atrophy for age.",
                "confidence": 0.85,
                "data_quality": "high",
                "provenance": {"acquired_by": "radiology_001", "reviewed_by": "radiologist_003"},
                "evidence_links": ["ev_mri_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "blood_draw",
                "modality": "biomarker",
                "source_system": "labcorp",
                "source_record_id": f"nfl_{patient_id}_001",
                "timestamp": base + timedelta(days=5, hours=8),
                "value_summary": "Plasma NfL elevated at 18.2 pg/mL (ref <14)",
                "numeric_features": {"nfl_pg_ml": 18.2, "gfap_pg_ml": 120.5},
                "textual_summary": "Neurofilament light chain elevated.",
                "confidence": 0.82,
                "data_quality": "high",
                "provenance": {"lab": "labcorp_central"},
                "evidence_links": ["ev_biomarker_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "blood_panel",
                "modality": "labs",
                "source_system": "labcorp",
                "source_record_id": f"cbc_{patient_id}_001",
                "timestamp": base + timedelta(days=5, hours=8, minutes=15),
                "value_summary": "CBC normal; mild vitamin D insufficiency 22 ng/mL",
                "numeric_features": {"vitamin_d_ng_ml": 22.0, "crp_mg_l": 1.2, "wbc_k_ul": 6.5},
                "textual_summary": "No signs of acute infection. Vitamin D slightly low.",
                "confidence": 0.90,
                "data_quality": "high",
                "provenance": {"lab": "labcorp_central", "fasting": False},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "medication_start",
                "modality": "medication",
                "source_system": "ehr",
                "source_record_id": f"rx_{patient_id}_001",
                "timestamp": base + timedelta(days=7, hours=10),
                "value_summary": "Started sertraline 25mg daily",
                "numeric_features": {"dose_mg": 25.0, "pill_count_dispensed": 30.0},
                "textual_summary": "Initiated SSRI for moderate depressive symptoms.",
                "confidence": 0.95,
                "data_quality": "high",
                "provenance": {"prescriber": "dr_smith", "ehr_system": "epic"},
                "evidence_links": ["ev_medication_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "medication_change",
                "modality": "medication",
                "source_system": "ehr",
                "source_record_id": f"rx_{patient_id}_002",
                "timestamp": base + timedelta(days=21, hours=10),
                "value_summary": "Sertraline increased to 50mg daily",
                "numeric_features": {"dose_mg": 50.0, "pill_count_dispensed": 30.0},
                "textual_summary": "Titrated up per protocol.",
                "confidence": 0.95,
                "data_quality": "high",
                "provenance": {"prescriber": "dr_smith", "ehr_system": "epic"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "tms_session",
                "modality": "intervention",
                "source_system": "magventure",
                "source_record_id": f"tms_{patient_id}_001",
                "timestamp": base + timedelta(days=10, hours=11),
                "value_summary": "rTMS session 1/20: L-DLPFC 10Hz, 3000 pulses",
                "numeric_features": {"frequency_hz": 10.0, "pulse_count": 3000.0, "mt_percentage": 80.0},
                "textual_summary": "First session tolerated well. Motor threshold 52%.",
                "confidence": 0.88,
                "data_quality": "high",
                "provenance": {"operator": "tech_003", "device": "magventure_x100"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "tms_session",
                "modality": "sessions",
                "source_system": "magventure",
                "source_record_id": f"tms_{patient_id}_010",
                "timestamp": base + timedelta(days=30, hours=11),
                "value_summary": "rTMS session 10/20: L-DLPFC 10Hz, 3000 pulses",
                "numeric_features": {"frequency_hz": 10.0, "pulse_count": 3000.0, "mt_percentage": 80.0},
                "textual_summary": "Patient reports subjective improvement in concentration.",
                "confidence": 0.88,
                "data_quality": "medium",
                "provenance": {"operator": "tech_003", "device": "magventure_x100"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "voice_sample",
                "modality": "voice",
                "source_system": "winterlight",
                "source_record_id": f"vox_{patient_id}_001",
                "timestamp": base + timedelta(days=14, hours=15),
                "value_summary": "Voice analysis: prosodic flattening, reduced pitch variability (CV=0.12)",
                "numeric_features": {"pitch_cv": 0.12, "speech_rate_wpm": 105.0, "pause_ratio": 0.35},
                "textual_summary": "Acoustic features suggest reduced emotional prosody.",
                "confidence": 0.65,
                "data_quality": "medium",
                "provenance": {"acquired_by": "app_voice", "background_noise": "low"},
                "evidence_links": ["ev_voice_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "journal_entry",
                "modality": "text",
                "source_system": "patient_portal",
                "source_record_id": f"journal_{patient_id}_001",
                "timestamp": base + timedelta(days=15, hours=20),
                "value_summary": "Text sentiment: negative valence (-0.6), high fatigue mentions",
                "numeric_features": {"sentiment_valence": -0.6, "fatigue_mentions": 4.0, "anxiety_score": 0.4},
                "textual_summary": "Patient writes about feeling tired and unmotivated.",
                "confidence": 0.72,
                "data_quality": "medium",
                "provenance": {"entered_by": "patient", "source": "digital_journal"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "gait_analysis",
                "modality": "movement",
                "source_system": "motion_capture",
                "source_record_id": f"gait_{patient_id}_001",
                "timestamp": base + timedelta(days=20, hours=10),
                "value_summary": "Gait speed reduced (0.82 m/s), increased stride time variability (CV=4.2%)",
                "numeric_features": {"gait_speed_ms": 0.82, "stride_time_cv": 4.2, "step_length_m": 0.58},
                "textual_summary": "Gait analysis shows slower walking speed.",
                "confidence": 0.75,
                "data_quality": "medium",
                "provenance": {"acquired_by": "cam_sys_001", "location": "hallway_A"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "video_review",
                "modality": "video",
                "source_system": "observation_suite",
                "source_record_id": f"vid_{patient_id}_001",
                "timestamp": base + timedelta(days=25, hours=14),
                "value_summary": "Facial expression: reduced expressivity, decreased smile frequency",
                "numeric_features": {"au12_intensity_mean": 0.3, "expression_entropy": 0.45},
                "textual_summary": "Video analysis shows limited facial expression range.",
                "confidence": 0.68,
                "data_quality": "medium",
                "provenance": {"acquired_by": "cam_sys_002", "reviewer": "ai_model_v2.1"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "sleep_summary",
                "modality": "wearable",
                "source_system": "oura",
                "source_record_id": f"oura_{patient_id}_001",
                "timestamp": base + timedelta(days=17, hours=6),
                "value_summary": "Sleep efficiency 71%, total sleep 5h 42m, WASO 87 min",
                "numeric_features": {"sleep_efficiency": 0.71, "total_sleep_min": 342.0, "waso_min": 87.0, "deep_sleep_min": 42.0},
                "textual_summary": "Suboptimal sleep architecture with prolonged wake after sleep onset.",
                "confidence": 0.80,
                "data_quality": "medium",
                "provenance": {"device": "oura_ring_gen3", "firmware": "2.1.0"},
                "evidence_links": ["ev_sleep_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "activity_summary",
                "modality": "wearable",
                "source_system": "oura",
                "source_record_id": f"oura_{patient_id}_002",
                "timestamp": base + timedelta(days=35, hours=6),
                "value_summary": "Sleep efficiency 78%, total sleep 6h 30m, WASO 45 min",
                "numeric_features": {"sleep_efficiency": 0.78, "total_sleep_min": 390.0, "waso_min": 45.0, "deep_sleep_min": 65.0},
                "textual_summary": "Improved sleep metrics compared to baseline.",
                "confidence": 0.80,
                "data_quality": "medium",
                "provenance": {"device": "oura_ring_gen3", "firmware": "2.1.0"},
                "evidence_links": ["ev_sleep_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "screen_time",
                "modality": "digital_phenotyping",
                "source_system": "mindstrong",
                "source_record_id": f"dp_{patient_id}_001",
                "timestamp": base + timedelta(days=18, hours=0),
                "value_summary": "Late-night phone use increased, social app interaction decreased",
                "numeric_features": {"screen_on_after_10pm_min": 85.0, "social_app_sessions": 3.0, "typing_speed_wpm": 28.0},
                "textual_summary": "Digital phenotype shows increased nocturnal screen time.",
                "confidence": 0.70,
                "data_quality": "medium",
                "provenance": {"platform": "mindstrong", "data_collection": "passive"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "risk_flag",
                "modality": "risk_signals",
                "source_system": "predictive_model",
                "source_record_id": f"risk_{patient_id}_001",
                "timestamp": base + timedelta(days=22, hours=8),
                "value_summary": "Cognitive decline risk score 0.62 (moderate elevation)",
                "numeric_features": {"risk_score": 0.62, "confidence_interval_lower": 0.48, "confidence_interval_upper": 0.74},
                "textual_summary": "Ensemble model flags moderate risk of cognitive decline over 12 months.",
                "confidence": 0.62,
                "data_quality": "medium",
                "provenance": {"model_version": "risk_v2.4", "validated": False},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "clinical_note",
                "modality": "reports",
                "source_system": "ehr",
                "source_record_id": f"note_{patient_id}_001",
                "timestamp": base + timedelta(days=40, hours=16),
                "value_summary": "Progress note: patient reports 30% improvement in mood and sleep",
                "numeric_features": {"patient_reported_improvement_pct": 30.0, "cgi_s": 3.0},
                "textual_summary": "Clinician notes patient appears brighter, more engaged.",
                "confidence": 0.85,
                "data_quality": "high",
                "provenance": {"author": "dr_smith", "ehr_system": "epic"},
                "evidence_links": ["ev_adherence_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "referral",
                "modality": "documents",
                "source_system": "ehr",
                "source_record_id": f"ref_{patient_id}_001",
                "timestamp": base + timedelta(days=45, hours=9),
                "value_summary": "Referral to neuropsychology for comprehensive battery",
                "numeric_features": {},
                "textual_summary": "Referral placed for formal neuropsychological testing.",
                "confidence": 0.90,
                "data_quality": "high",
                "provenance": {"author": "dr_smith", "ehr_system": "epic"},
                "evidence_links": [],
            },
            {
                "patient_id": patient_id,
                "event_type": "weekly_checkin",
                "modality": "patient_checkins",
                "source_system": "patient_app",
                "source_record_id": f"checkin_{patient_id}_001",
                "timestamp": base + timedelta(days=28, hours=19),
                "value_summary": "Check-in: mood 6/10, sleep 7/10, energy 5/10, side effects none",
                "numeric_features": {"mood_self": 6.0, "sleep_self": 7.0, "energy_self": 5.0, "side_effect_count": 0.0},
                "textual_summary": "Patient reports gradual improvement.",
                "confidence": 0.75,
                "data_quality": "medium",
                "provenance": {"source": "patient_app", "response_time_min": 12.0},
                "evidence_links": ["ev_adherence_001"],
            },
            {
                "patient_id": patient_id,
                "event_type": "weekly_checkin",
                "modality": "patient_checkins",
                "source_system": "patient_app",
                "source_record_id": f"checkin_{patient_id}_002",
                "timestamp": base + timedelta(days=50, hours=19),
                "value_summary": "Check-in: mood 7/10, sleep 8/10, energy 7/10, side effects mild headache",
                "numeric_features": {"mood_self": 7.0, "sleep_self": 8.0, "energy_self": 7.0, "side_effect_count": 1.0},
                "textual_summary": "Continued improvement in all domains.",
                "confidence": 0.75,
                "data_quality": "medium",
                "provenance": {"source": "patient_app", "response_time_min": 8.0},
                "evidence_links": [],
            },
        ]

        event_ids = []
        for evt_data in seed_events:
            event = MultimodalEvent(**evt_data)
            self.kl.insert_event(event)
            event_ids.append(event.event_id)
        return event_ids
