"""Repo-native qEEG courseware distilled for analyzer and raw-review workflows."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CoursewareTopic:
    """Structured teaching topic derived from local qEEG courseware."""

    topic_id: str
    title: str
    summary: str
    analyzer_use: str
    raw_use: str
    confound_domains: tuple[str, ...]


_COURSEWARE_TOPICS: tuple[CoursewareTopic, ...] = (
    CoursewareTopic(
        topic_id="manual_editing_guardrails",
        title="Manual editing and anti-automation guardrails",
        summary=(
            "Advanced courseware emphasizes that automated editing and autogenerated "
            "interpretations are support tools, not substitutes for morphology-aware review."
        ),
        analyzer_use=(
            "Do not escalate an abnormality purely from computed output when raw morphology, "
            "artifact burden, or montage context has not been verified."
        ),
        raw_use=(
            "Review suspicious segments manually before rejecting them; distinguish artifact "
            "from genuine cerebral signal using morphology, channel spread, and state context."
        ),
        confound_domains=("artifact", "automation_bias"),
    ),
    CoursewareTopic(
        topic_id="delta_theta_frequency_reasoning",
        title="Delta and theta frequency reasoning",
        summary=(
            "The local qEEG courseware focuses on identifying delta/theta morphology, "
            "counting oscillations over one-second intervals, and linking slowing patterns "
            "to clinically meaningful interpretations."
        ),
        analyzer_use=(
            "Use delta/theta findings as pattern-supporting context, then integrate age, "
            "state, and localization before calling the pattern pathological."
        ),
        raw_use=(
            "Count oscillations directly in the trace when frequency identity is unclear, "
            "and verify whether the waveform is rhythmic enough to support the label."
        ),
        confound_domains=("state", "development", "artifact"),
    ),
    CoursewareTopic(
        topic_id="frontocentral_theta_context",
        title="Frontocentral and frontal midline theta context",
        summary=(
            "Course material links frontal and frontocentral theta to attention, working "
            "memory, ACC-related generators, and some symptom phenotypes, but warns against "
            "oversimplified disease labeling."
        ),
        analyzer_use=(
            "Frame elevated Fz/frontocentral theta as a context-dependent pattern that may "
            "relate to attention or control systems, not a stand-alone diagnosis."
        ),
        raw_use=(
            "Inspect whether frontocentral theta is persistent, state-linked, familial, or "
            "artifact-like before treating it as an abnormal target."
        ),
        confound_domains=("genetics", "state", "symptom_context"),
    ),
    CoursewareTopic(
        topic_id="psychopharmacology_confound_awareness",
        title="Psychopharmacology confound awareness",
        summary=(
            "Attendance records confirm dedicated psychopharmacology training within the "
            "qEEG curriculum, reinforcing medication-aware interpretation."
        ),
        analyzer_use=(
            "Check medication, caffeine, alcohol, and sedative exposure before classifying "
            "diffuse slowing or beta excess as intrinsic dysfunction."
        ),
        raw_use=(
            "When a tracing shows generalized beta, attenuation, or slowing, verify whether "
            "the pattern is medication-related before annotating pathology."
        ),
        confound_domains=("medication", "stimulant", "sedative", "substance"),
    ),
)


class CoursewareAtlas:
    """Read-only access to local qEEG courseware concepts."""

    @staticmethod
    def all_topics() -> tuple[CoursewareTopic, ...]:
        return _COURSEWARE_TOPICS

    @staticmethod
    def lookup(topic_id: str) -> CoursewareTopic | None:
        key = topic_id.lower().strip()
        for topic in _COURSEWARE_TOPICS:
            if topic.topic_id == key:
                return topic
        return None


def courseware_context_for_workflow(workflow: str) -> list[str]:
    """Return short workflow-specific guidance from the local qEEG courseware."""
    mode = workflow.lower().strip()
    if mode in {"raw", "raw_review", "raw-workbench", "raw_workbench"}:
        return [topic.raw_use for topic in _COURSEWARE_TOPICS]
    if mode in {"copilot", "agent", "narrative", "report", "reporting"}:
        return [
            f"{topic.title}: {topic.analyzer_use} Raw-review guardrail: {topic.raw_use}"
            for topic in _COURSEWARE_TOPICS
        ]
    return [topic.analyzer_use for topic in _COURSEWARE_TOPICS]


def courseware_brief(workflow: str, limit: int = 4) -> list[str]:
    """Return a compact subset of courseware guidance for prompts and summaries."""
    items = courseware_context_for_workflow(workflow)
    if limit <= 0:
        return []
    return items[:limit]


def courseware_prompt_block(workflow: str, limit: int = 4) -> str:
    """Render courseware guidance as a prompt-safe bullet block."""
    items = courseware_brief(workflow, limit=limit)
    if not items:
        return "(none)"
    return "\n".join(f"- {item}" for item in items)
