// ── DeepSynaps Clinical Registries ───────────────────────────────────────────
// Authoritative frontend data for all 10 core registries.
// Pages load from live API first; fall back to these constants on failure.
// ─────────────────────────────────────────────────────────────────────────────

// ── 1. CONDITION REGISTRY — 53 conditions ─────────────────────────────────────
export const CONDITION_REGISTRY = [
  // ── MOOD ─────────────────────────────────────────────────────────────────
  { id:'mdd',        name:'Major Depressive Disorder',           icd10:'F32',    cat:'Mood',         ev:'A', modalities:['TMS/rTMS','tDCS','iTBS','ECT'],       onLabel:['TMS/rTMS','ECT'], assessments:['phq9','madrs','hamd','qids','cgi','eq5d'],         targets:['F3','F4','Fp1'],          flags:['seizure-check'],  notes:'L-DLPFC HF-TMS is FDA-cleared first-line for adults.' },
  { id:'trd',        name:'Treatment-Resistant Depression',       icd10:'F32.2',  cat:'Mood',         ev:'A', modalities:['TMS/rTMS','iTBS','ECT','tDCS'],       onLabel:['TMS/rTMS','ECT'], assessments:['madrs','hamd','qids','cgi'],                       targets:['F3','F4'],                flags:['seizure-check'],  notes:'Defined as ≥2 failed adequate antidepressant trials.' },
  { id:'bpd',        name:'Bipolar Depression',                   icd10:'F31.3',  cat:'Mood',         ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','madrs','cgi','ses'],                        targets:['F3','F4'],                flags:['seizure-check'],  notes:'Bipolar I/II depressive phase. Caution — mood switching risk.' },
  { id:'ppd',        name:'Postpartum Depression',                icd10:'F53.0',  cat:'Mood',         ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','madrs','cgi'],                              targets:['F3'],                     flags:['pregnancy-check']},
  { id:'sad',        name:'Seasonal Affective Disorder',          icd10:'F33.9',  cat:'Mood',         ev:'B', modalities:['TMS/rTMS','tDCS','PBM'],              onLabel:[],                assessments:['phq9','madrs'],                                    targets:['F3'],                     flags:[]},
  { id:'pdd',        name:'Persistent Depressive Disorder',       icd10:'F34.1',  cat:'Mood',         ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','madrs','hamd'],                             targets:['F3','F4'],                flags:[]},

  // ── ANXIETY ──────────────────────────────────────────────────────────────
  { id:'gad',        name:'Generalised Anxiety Disorder',         icd10:'F41.1',  cat:'Anxiety',      ev:'B', modalities:['TMS/rTMS','tDCS','taVNS'],            onLabel:[],                assessments:['gad7','dass21','cgi','eq5d'],                      targets:['F4','Fp2','F8'],          flags:[]},
  { id:'panic',      name:'Panic Disorder',                       icd10:'F41.0',  cat:'Anxiety',      ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['gad7','cgi'],                                     targets:['F4','Fp2'],               flags:[]},
  { id:'social-anx', name:'Social Anxiety Disorder',              icd10:'F40.10', cat:'Anxiety',      ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['gad7','cgi'],                                     targets:['F4','DLPFC-R'],           flags:[]},
  { id:'specific-ph',name:'Specific Phobia',                      icd10:'F40.2',  cat:'Anxiety',      ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['gad7','cgi'],                                     targets:['F4'],                     flags:[]},
  { id:'agoraphobia',name:'Agoraphobia',                          icd10:'F40.00', cat:'Anxiety',      ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['gad7','cgi'],                                     targets:['F4'],                     flags:[]},

  // ── OCD SPECTRUM ─────────────────────────────────────────────────────────
  { id:'ocd',        name:'OCD',                                  icd10:'F42',    cat:'OCD Spectrum',  ev:'A', modalities:['TMS/rTMS','tDCS','DBS'],              onLabel:['TMS/rTMS'],      assessments:['ybocs','cgi','ses'],                               targets:['SMA','Fp1','F4'],        flags:['seizure-check'],  notes:'SMA-TMS FDA-cleared for OCD (BrainsWay H7-Coil).' },
  { id:'bdd',        name:'Body Dysmorphic Disorder',             icd10:'F45.22', cat:'OCD Spectrum',  ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['ybocs','cgi'],                                     targets:['SMA','DLPFC-R'],         flags:[]},
  { id:'hoarding',   name:'Hoarding Disorder',                    icd10:'F42.3',  cat:'OCD Spectrum',  ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['cgi'],                                            targets:['DLPFC-L'],               flags:[]},
  { id:'trich',      name:'Trichotillomania',                     icd10:'F63.3',  cat:'OCD Spectrum',  ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['cgi'],                                            targets:['SMA'],                   flags:[]},

  // ── TRAUMA ───────────────────────────────────────────────────────────────
  { id:'ptsd',       name:'PTSD',                                 icd10:'F43.10', cat:'Trauma',        ev:'A', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['pcl5','caps5','phq9','cgi','ses'],                 targets:['F3','F4','Fp1'],         flags:['seizure-check'],  notes:'DLPFC bilateral protocol. CAPS-5 required for diagnosis.' },
  { id:'cptsd',      name:'Complex PTSD (cPTSD)',                 icd10:'6B41',   cat:'Trauma',        ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['pcl5','caps5','phq9'],                             targets:['F3','F4'],               flags:[]},
  { id:'asd-trauma', name:'Acute Stress Disorder',               icd10:'F43.0',  cat:'Trauma',        ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['pcl5','cgi'],                                     targets:['F3'],                    flags:[]},

  // ── PSYCHOSIS ─────────────────────────────────────────────────────────────
  { id:'schizo',     name:'Schizophrenia',                        icd10:'F20',    cat:'Psychosis',     ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['panss','bprs','cgi','ses'],                        targets:['F3','T7','T8'],          flags:['seizure-check'],  notes:'Low-frequency rTMS to bilateral temporoparietal for auditory hallucinations.' },
  { id:'schizo-aff', name:'Schizoaffective Disorder',             icd10:'F25',    cat:'Psychosis',     ev:'B', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['panss','bprs','cgi'],                              targets:['F3','T7'],               flags:['seizure-check']},
  { id:'fep',        name:'First Episode Psychosis',              icd10:'F20.01', cat:'Psychosis',     ev:'C', modalities:['tDCS','TMS/rTMS'],                    onLabel:[],                assessments:['panss','cgi'],                                     targets:['F3','F4'],               flags:['seizure-check']},

  // ── ADHD ─────────────────────────────────────────────────────────────────
  { id:'adhd-i',     name:'ADHD — Inattentive',                   icd10:'F90.0',  cat:'ADHD',          ev:'B', modalities:['tDCS','TMS/rTMS','Neurofeedback'],    onLabel:[],                assessments:['cgi','qids'],                                     targets:['F3','F4','Cz'],          flags:[]},
  { id:'adhd-hi',    name:'ADHD — Hyperactive / Impulsive',       icd10:'F90.1',  cat:'ADHD',          ev:'B', modalities:['tDCS','TMS/rTMS','Neurofeedback'],    onLabel:[],                assessments:['cgi'],                                            targets:['F3','F4','Cz'],          flags:[]},
  { id:'adhd-c',     name:'ADHD — Combined',                      icd10:'F90.2',  cat:'ADHD',          ev:'B', modalities:['tDCS','TMS/rTMS','Neurofeedback'],    onLabel:[],                assessments:['cgi','qids'],                                     targets:['F3','F4','Cz'],          flags:[]},

  // ── AUTISM ───────────────────────────────────────────────────────────────
  { id:'asd',        name:'Autism Spectrum Disorder',             icd10:'F84.0',  cat:'Autism',        ev:'C', modalities:['tDCS','TMS/rTMS'],                    onLabel:[],                assessments:['cgi'],                                            targets:['F3','F4','P3','P4'],     flags:['seizure-check']},

  // ── EATING ───────────────────────────────────────────────────────────────
  { id:'anorexia',   name:'Anorexia Nervosa',                     icd10:'F50.0',  cat:'Eating',        ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','gad7','cgi'],                               targets:['F4','DLPFC-L'],          flags:[]},
  { id:'bulimia',    name:'Bulimia Nervosa',                       icd10:'F50.2',  cat:'Eating',        ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','gad7','cgi'],                               targets:['F4','DLPFC-R'],          flags:[]},
  { id:'bed',        name:'Binge Eating Disorder',                 icd10:'F50.81', cat:'Eating',        ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','cgi'],                                     targets:['F4'],                    flags:[]},

  // ── SUBSTANCE ────────────────────────────────────────────────────────────
  { id:'aud',        name:'Alcohol Use Disorder',                  icd10:'F10.2',  cat:'Substance',     ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['audit','cgi'],                                    targets:['F3','F4','DLPFC-L'],     flags:[]},
  { id:'nic-dep',    name:'Nicotine Dependence',                   icd10:'F17.2',  cat:'Substance',     ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['cgi'],                                            targets:['F3','Insula'],           flags:[]},
  { id:'oud',        name:'Opioid Use Disorder',                   icd10:'F11.2',  cat:'Substance',     ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['audit','cgi'],                                    targets:['F3','F4'],               flags:[]},
  { id:'cud',        name:'Cannabis Use Disorder',                 icd10:'F12.2',  cat:'Substance',     ev:'C', modalities:['TMS/rTMS'],                           onLabel:[],                assessments:['audit','cgi'],                                    targets:['F3'],                    flags:[]},

  // ── SLEEP ────────────────────────────────────────────────────────────────
  { id:'insomnia',   name:'Insomnia Disorder',                     icd10:'G47.0',  cat:'Sleep',         ev:'B', modalities:['tDCS','TMS/rTMS','CES'],              onLabel:[],                assessments:['isi','cgi','ses'],                                 targets:['F3','Cz'],               flags:[]},
  { id:'hypersomn',  name:'Hypersomnia',                           icd10:'G47.1',  cat:'Sleep',         ev:'C', modalities:['tDCS'],                               onLabel:[],                assessments:['isi','cgi'],                                      targets:['F3'],                    flags:[]},

  // ── PAIN ─────────────────────────────────────────────────────────────────
  { id:'pain-neuro', name:'Neuropathic Pain',                      icd10:'G62.9',  cat:'Pain',          ev:'B', modalities:['TMS/rTMS','tDCS','CES'],              onLabel:[],                assessments:['eq5d','cgi','ses'],                                targets:['C3','C4','F3','F4'],     flags:[]},
  { id:'pain-msk',   name:'Musculoskeletal Chronic Pain',          icd10:'M79.3',  cat:'Pain',          ev:'B', modalities:['TMS/rTMS','tDCS','PBM'],              onLabel:[],                assessments:['eq5d','cgi','ses'],                                targets:['C3','C4'],               flags:[]},
  { id:'fibro',      name:'Fibromyalgia',                          icd10:'M79.7',  cat:'Pain',          ev:'B', modalities:['TMS/rTMS','tDCS','CES'],              onLabel:[],                assessments:['eq5d','cgi','ses'],                                targets:['F3','C3','M1'],          flags:[]},
  { id:'migraine',   name:'Migraine / Chronic Headache',           icd10:'G43.9',  cat:'Pain',          ev:'B', modalities:['TMS/rTMS','tDCS','taVNS','nVNS'],     onLabel:['TMS/rTMS'],      assessments:['eq5d','cgi'],                                     targets:['Oz','O1','O2','F3'],     flags:[],                 notes:'Single-pulse TMS FDA-cleared for migraine with aura.' },
  { id:'tinnitus',   name:'Tinnitus',                              icd10:'H93.1',  cat:'Pain',          ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['cgi','ses'],                                      targets:['T7','T8','F3'],          flags:['implant-check'], notes:'Check for cochlear implants before any neuromodulation.' },

  // ── NEUROLOGICAL ─────────────────────────────────────────────────────────
  { id:'stroke-mtr', name:'Stroke Rehabilitation — Motor',         icd10:'Z87.39', cat:'Neurological',  ev:'A', modalities:['TMS/rTMS','tDCS','PBM'],              onLabel:[],                assessments:['moca','cgi','eq5d'],                               targets:['C3','C4','M1'],          flags:['seizure-check'],  notes:'HF-TMS ipsilesional / LF-TMS contralesional M1.' },
  { id:'stroke-aph', name:'Stroke Rehabilitation — Aphasia',       icd10:'I69.320',cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['moca','cgi'],                                     targets:['F8','T7','Broca'],       flags:['seizure-check']},
  { id:'tbi',        name:'Traumatic Brain Injury',                 icd10:'S09.90', cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','tDCS','PBM'],              onLabel:[],                assessments:['moca','cgi','eq5d'],                               targets:['F3','F4','Cz'],          flags:['seizure-check'],  notes:'Must confirm no metal fragments. Low-intensity preferred early post-TBI.' },
  { id:'alzheimer',  name:"Alzheimer's Disease",                    icd10:'G30',    cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['moca','cgi'],                                     targets:['F3','F4','P3','P4'],     flags:['seizure-check']},
  { id:'vasc-dem',   name:'Vascular Dementia',                     icd10:'F01',    cat:'Neurological',  ev:'C', modalities:['tDCS','TMS/rTMS'],                    onLabel:[],                assessments:['moca','cgi'],                                     targets:['F3','F4'],               flags:['seizure-check','cardiac-check']},
  { id:'parkinsons', name:"Parkinson's Disease",                    icd10:'G20',    cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','tDCS','DBS'],              onLabel:['DBS'],           assessments:['moca','cgi','eq5d','ses'],                         targets:['M1','SMA','Cz'],         flags:['implant-check'],  notes:'DBS FDA-cleared. rTMS adjunct for motor symptoms and depression.' },
  { id:'ms',         name:'Multiple Sclerosis',                     icd10:'G35',    cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['eq5d','cgi','ses'],                                targets:['M1','C3','C4'],          flags:['seizure-check']},
  { id:'epilepsy',   name:'Epilepsy — Drug-Resistant',             icd10:'G40.9',  cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','taVNS','DBS'],             onLabel:['taVNS','DBS'],   assessments:['cgi'],                                            targets:['Focus-area','Cz'],       flags:['seizure-check'],  notes:'taVNS FDA-cleared for drug-resistant epilepsy.' },
  { id:'essential-t',name:'Essential Tremor',                      icd10:'G25.0',  cat:'Neurological',  ev:'B', modalities:['TMS/rTMS','tDCS','FUS','DBS'],        onLabel:['DBS','FUS'],     assessments:['cgi'],                                            targets:['M1','Cz','Vim'],         flags:['implant-check']},
  { id:'dystonia',   name:'Dystonia',                              icd10:'G24.9',  cat:'Other',         ev:'C', modalities:['TMS/rTMS','DBS'],                     onLabel:['DBS'],           assessments:['cgi'],                                            targets:['M1','SMA'],              flags:['implant-check']},

  // ── OTHER ─────────────────────────────────────────────────────────────────
  { id:'tourette',   name:'Tourette Syndrome',                     icd10:'F95.2',  cat:'Other',         ev:'C', modalities:['TMS/rTMS','DBS'],                     onLabel:[],                assessments:['cgi'],                                            targets:['SMA','DLPFC-L'],         flags:['seizure-check']},
  { id:'long-covid', name:'Long COVID — Cognitive Symptoms',       icd10:'U09.9',  cat:'Other',         ev:'C', modalities:['tDCS','TMS/rTMS','PBM'],              onLabel:[],                assessments:['moca','phq9','cgi'],                               targets:['F3','F4'],               flags:[],                 notes:'Emerging indication. Cognitive fatigue and brain fog.' },
  { id:'fnd',        name:'Functional Neurological Disorder',      icd10:'F44.9',  cat:'Other',         ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','gad7','cgi'],                               targets:['M1','SMA'],              flags:[]},
  { id:'bpd-psy',    name:'Borderline Personality Disorder',       icd10:'F60.3',  cat:'Other',         ev:'C', modalities:['TMS/rTMS','tDCS'],                    onLabel:[],                assessments:['phq9','gad7','cgi'],                               targets:['F3','F4','DLPFC-L'],     flags:[]},
];

// ── 2. ASSESSMENT REGISTRY ────────────────────────────────────────────────────
export const ASSESSMENT_REGISTRY = [
  // Mood
  { id:'phq9',    name:'PHQ-9',        domain:'Mood',      type:'Self-report',   items:9,  mins:3,  ev:'A', scoring:'0–27. ≥10=moderate. ≥20=severe.',   conditions:['mdd','trd','bpd','ppd','pdd'],       freq:['pre','weekly','post'],  link:'https://www.phqscreeners.com' },
  { id:'madrs',   name:'MADRS',        domain:'Mood',      type:'Clinician',     items:10, mins:15, ev:'A', scoring:'0–60. ≥20=moderate. ≥35=severe.',   conditions:['mdd','trd','bpd'],                   freq:['pre','milestone','post'],link:'' },
  { id:'hamd',    name:'HAM-D 17',     domain:'Mood',      type:'Clinician',     items:17, mins:20, ev:'A', scoring:'0–52. ≥14=moderate. ≥23=severe.',   conditions:['mdd','trd'],                         freq:['pre','weekly','post'],  link:'' },
  { id:'qids',    name:'QIDS-SR16',    domain:'Mood',      type:'Self-report',   items:16, mins:5,  ev:'A', scoring:'0–27. ≥11=moderate. ≥16=severe.',   conditions:['mdd','trd','bpd'],                   freq:['pre','weekly','post'],  link:'' },
  { id:'dass21',  name:'DASS-21',      domain:'Mood',      type:'Self-report',   items:21, mins:5,  ev:'A', scoring:'3 subscales D/A/S ×2.',              conditions:['mdd','gad'],                         freq:['pre','weekly','post'],  link:'' },
  // Anxiety
  { id:'gad7',    name:'GAD-7',        domain:'Anxiety',   type:'Self-report',   items:7,  mins:2,  ev:'A', scoring:'0–21. ≥10=moderate. ≥15=severe.',   conditions:['gad','panic','social-anx'],          freq:['pre','weekly','post'],  link:'' },
  // PTSD
  { id:'pcl5',    name:'PCL-5',        domain:'PTSD',      type:'Self-report',   items:20, mins:5,  ev:'A', scoring:'0–80. ≥33=probable PTSD.',          conditions:['ptsd','cptsd'],                      freq:['pre','weekly','post'],  link:'' },
  { id:'caps5',   name:'CAPS-5',       domain:'PTSD',      type:'Clinician',     items:30, mins:45, ev:'A', scoring:'0–80. Gold standard DSM-5.',        conditions:['ptsd'],                              freq:['pre','post'],           link:'' },
  // OCD
  { id:'ybocs',   name:'Y-BOCS',       domain:'OCD',       type:'Clinician',     items:10, mins:20, ev:'A', scoring:'0–40. ≥16=moderate. ≥24=severe.',   conditions:['ocd','bdd'],                         freq:['pre','weekly'],         link:'' },
  // Psychosis
  { id:'panss',   name:'PANSS',        domain:'Psychosis', type:'Clinician',     items:30, mins:30, ev:'A', scoring:'30–210. Positive/Negative subscales.',conditions:['schizo','schizo-aff','fep'],        freq:['pre','weekly'],         link:'' },
  { id:'bprs',    name:'BPRS',         domain:'Psychosis', type:'Clinician',     items:18, mins:20, ev:'A', scoring:'18–126.',                           conditions:['schizo','schizo-aff'],               freq:['pre','weekly'],         link:'' },
  // Cognition
  { id:'moca',    name:'MoCA',         domain:'Cognition', type:'Clinician',     items:30, mins:10, ev:'A', scoring:'0–30. <26=possible impairment.',    conditions:['alzheimer','vasc-dem','tbi','parkinsons'],freq:['pre','milestone'],link:'' },
  // Sleep
  { id:'isi',     name:'ISI',          domain:'Sleep',     type:'Self-report',   items:7,  mins:2,  ev:'A', scoring:'0–28. ≥15=moderate insomnia.',      conditions:['insomnia'],                          freq:['pre','weekly','post'],  link:'' },
  { id:'psqi',    name:'PSQI',         domain:'Sleep',     type:'Self-report',   items:19, mins:5,  ev:'A', scoring:'0–21. >5=poor sleep quality.',      conditions:['insomnia'],                          freq:['pre','post'],           link:'' },
  // Substance
  { id:'audit',   name:'AUDIT',        domain:'Substance', type:'Self-report',   items:10, mins:5,  ev:'A', scoring:'0–40. ≥8=hazardous use.',           conditions:['aud'],                               freq:['pre','milestone'],      link:'' },
  // Quality of life
  { id:'cgi',     name:'CGI-S / CGI-I',domain:'QoL',       type:'Clinician',     items:2,  mins:2,  ev:'A', scoring:'1–7 severity; 1–7 improvement.',    conditions:['all'],                               freq:['pre','weekly','post'],  link:'' },
  { id:'eq5d',    name:'EQ-5D',        domain:'QoL',       type:'Self-report',   items:5,  mins:2,  ev:'A', scoring:'0–1 utility score.',                conditions:['all'],                               freq:['pre','post'],           link:'' },
  // Side effects
  { id:'ses',     name:'Side Effects Checklist',domain:'Safety',type:'Self-report',items:12,mins:3, ev:'B', scoring:'Symptom frequency & severity.',     conditions:['all'],                               freq:['weekly'],               link:'' },
  // Neuromodulation-specific structured forms
  { id:'nmb',     name:'Neuromodulation Baseline Screen', domain:'Intake',   type:'Structured', items:8, mins:5,  ev:'B', scoring:'Clinician qualitative.', conditions:['all'], freq:['pre'],      link:'' },
  { id:'stc',     name:'Session Tolerance Check',         domain:'Safety',   type:'Structured', items:6, mins:3,  ev:'B', scoring:'Clinician qualitative.', conditions:['all'], freq:['post-sess'],link:'' },
  { id:'wpc',     name:'Weekly Progress Check-In',        domain:'Progress', type:'Structured', items:9, mins:4,  ev:'B', scoring:'Clinician qualitative.', conditions:['all'], freq:['weekly'],   link:'' },
  { id:'drs',     name:'Discharge Readiness Screen',      domain:'Discharge',type:'Structured', items:7, mins:5,  ev:'B', scoring:'Clinician qualitative.', conditions:['all'], freq:['post'],     link:'' },
];

// ── 3. PROTOCOL REGISTRY — key neuromodulation protocol templates ─────────────
// (supplement to CSV backend; used as fallback)
export const PROTOCOL_REGISTRY = [
  { id:'tms-mdd-dlpfc-hf',  name:'L-DLPFC HF-TMS — MDD',         condition:'mdd',    modality:'TMS/rTMS', target:'F3',   laterality:'Left',     freq:'10 Hz',  intensity:'120% MT', sessions:30, sessPerWeek:5, duration:'6 wks', ev:'A', onLabel:true,  notes:'Standard 3000-pulse, 10 Hz left DLPFC. FDA-cleared.' },
  { id:'tms-mdd-itbs',      name:'iTBS — MDD (accelerated)',      condition:'mdd',    modality:'iTBS',     target:'F3',   laterality:'Left',     freq:'50 Hz burst', intensity:'80% AMT',sessions:20,sessPerWeek:5, duration:'4 wks', ev:'A', onLabel:true,  notes:'SAINT/Stanford protocol variant. 3-min per session.' },
  { id:'tms-trd-bilateral', name:'Bilateral TMS — TRD',           condition:'trd',    modality:'TMS/rTMS', target:'F3/F4',laterality:'Bilateral', freq:'10 Hz / 1 Hz', intensity:'120% MT',sessions:30,sessPerWeek:5,duration:'6 wks',ev:'A', onLabel:false, notes:'HF left + LF right DLPFC sequential protocol.' },
  { id:'tms-ocd-sma',       name:'SMA H7-Coil TMS — OCD',        condition:'ocd',    modality:'TMS/rTMS', target:'SMA',  laterality:'Bilateral', freq:'20 Hz deep', intensity:'120% MT',sessions:29,sessPerWeek:5,duration:'6 wks', ev:'A', onLabel:true,  notes:'BrainsWay H7 deep TMS. FDA-cleared for OCD.' },
  { id:'tms-ptsd-dlpfc',    name:'DLPFC TMS — PTSD',             condition:'ptsd',   modality:'TMS/rTMS', target:'F3',   laterality:'Left',     freq:'10 Hz',  intensity:'120% MT', sessions:20, sessPerWeek:5, duration:'4 wks', ev:'B', onLabel:false, notes:'Bilateral protocol also used in trauma networks.' },
  { id:'tms-stroke-m1-hf',  name:'M1 HF-TMS — Stroke Motor',    condition:'stroke-mtr',modality:'TMS/rTMS',target:'C3/C4',laterality:'Ipsilesional',freq:'10 Hz',intensity:'90% MT',sessions:10,sessPerWeek:5,duration:'2 wks', ev:'A', onLabel:false, notes:'Paired with physiotherapy. Contralesional LF also used.' },
  { id:'tdcs-mdd-dlpfc',    name:'tDCS — MDD',                   condition:'mdd',    modality:'tDCS',     target:'F3',   laterality:'Left',     freq:'2 mA DC', intensity:'2 mA',   sessions:20, sessPerWeek:5, duration:'4 wks', ev:'B', onLabel:false, notes:'Anode F3, cathode Fp2 or right supraorbital.' },
  { id:'tdcs-pain-m1',      name:'M1 tDCS — Chronic Pain',       condition:'pain-neuro',modality:'tDCS',  target:'C3',   laterality:'Contralateral',freq:'2 mA DC',intensity:'2 mA',sessions:10,sessPerWeek:5,duration:'2 wks', ev:'B', onLabel:false, notes:'Anode M1 contralateral to pain, cathode supraorbital.' },
  { id:'tavns-epilepsy',    name:'taVNS — Drug-Resistant Epilepsy',condition:'epilepsy',modality:'taVNS', target:'Auricular',laterality:'Left', freq:'25 Hz',  intensity:'Sensory threshold',sessions:90,sessPerWeek:7,duration:'12 wks',ev:'A',onLabel:true, notes:'NEMOS/Cerbomed device. FDA 510(k) cleared.' },
  { id:'nfb-adhd-theta-beta',name:'Theta/Beta NFB — ADHD',       condition:'adhd-c', modality:'Neurofeedback',target:'Cz',laterality:'Midline',freq:'4–30 Hz feedback',intensity:'Threshold-based',sessions:40,sessPerWeek:3,duration:'13 wks',ev:'B',onLabel:false,notes:'Reduce theta, increase beta at Cz.' },
  { id:'tms-migraine-occ',  name:'TMS — Migraine with Aura',     condition:'migraine',modality:'TMS/rTMS',target:'Oz',  laterality:'Bilateral', freq:'Single-pulse',intensity:'MT calibrated',sessions:3,sessPerWeek:1,duration:'Acute',ev:'A',onLabel:true, notes:'SpringTMS / eNeura single-pulse. FDA-cleared.' },
  { id:'dbs-parkinsons-stn',name:'STN DBS — Parkinson\'s',       condition:'parkinsons',modality:'DBS',  target:'STN',  laterality:'Bilateral', freq:'130 Hz',  intensity:'Individualized', sessions:1,sessPerWeek:1,duration:'Lifelong',ev:'A',onLabel:true, notes:'Medtronic/Abbott/Boston Scientific DBS. Neurosurgical referral required.' },
];

// ── 4. DEVICE REGISTRY ────────────────────────────────────────────────────────
export const DEVICE_REGISTRY = [
  // TMS
  { id:'magstim-horizon', name:'Magstim Horizon Performance TMS', mfr:'Magstim',      modality:'TMS/rTMS', type:'Figure-8 Coil',   region:'Clinical', clearance:'FDA 510(k)', indication:'MDD, OCD',     channels:1,  homeClinic:'Clinic', notes:'Industry-standard TMS system. 70mm figure-8 and double-cone coils.' },
  { id:'magventure-x100', name:'MagVenture MagPro X100',          mfr:'MagVenture',   modality:'TMS/rTMS', type:'Figure-8 / Cool-B65', region:'Clinical',clearance:'CE/FDA',indication:'MDD',         channels:1,  homeClinic:'Clinic', notes:'Active liquid cooling. Enables high-frequency protocols.' },
  { id:'brainsway-h1',    name:'BrainsWay Deep TMS H1',           mfr:'BrainsWay',    modality:'TMS/rTMS', type:'H1 Deep Coil',    region:'Clinical', clearance:'FDA 510(k)', indication:'MDD',          channels:1,  homeClinic:'Clinic', notes:'Deep TMS coil reaching DLPFC and limbic structures.' },
  { id:'brainsway-h7',    name:'BrainsWay Deep TMS H7',           mfr:'BrainsWay',    modality:'TMS/rTMS', type:'H7 Deep Coil',    region:'Clinical', clearance:'FDA 510(k)', indication:'OCD',          channels:1,  homeClinic:'Clinic', notes:'SMA/ACC deep TMS. FDA-cleared for OCD.' },
  { id:'nexstim-nbs',     name:'Nexstim NBS eXimia',              mfr:'Nexstim',      modality:'TMS/rTMS', type:'Figure-8 + fMRI',  region:'Clinical', clearance:'CE/FDA',     indication:'Motor mapping',channels:1,  homeClinic:'Clinic', notes:'Neuronavigated TMS with integrated cortical mapping.' },
  { id:'spring-tms',      name:'SpringTMS (eNeura)',              mfr:'eNeura',       modality:'TMS/rTMS', type:'Single-pulse',     region:'Home',     clearance:'FDA 510(k)', indication:'Migraine',     channels:1,  homeClinic:'Home',   notes:'Patient-operated. Single-pulse occipital TMS for migraine.' },
  // tDCS
  { id:'soterix-2x2',     name:'Soterix Medical 2×2 tDCS',       mfr:'Soterix',      modality:'tDCS',     type:'Dual-channel',     region:'Clinical', clearance:'FDA Exempt',  indication:'Research/TBI', channels:2,  homeClinic:'Clinic', notes:'Clinical-grade tDCS. Used in stroke and TBI research.' },
  { id:'flow-neuro',      name:'Flow Neuroscience tDCS',          mfr:'Flow Neuroscience',modality:'tDCS', type:'Headset',         region:'Home',     clearance:'CE/FDA 510(k)',indication:'MDD adjunct', channels:1,  homeClinic:'Home',   notes:'CE-cleared home tDCS + app-based therapy.' },
  { id:'starstim-8',      name:'Neuroelectrics Starstim 8',       mfr:'Neuroelectrics',modality:'tDCS',    type:'8-ch multielectrode',region:'Clinical',clearance:'CE',        indication:'Research',     channels:8,  homeClinic:'Clinic', notes:'Multielectrode tCS including tDCS/tACS/tRNS.' },
  { id:'somaStim',        name:'Soterix somaStim',                mfr:'Soterix',      modality:'tDCS',     type:'1-ch clinical',    region:'Clinical', clearance:'FDA Exempt',  indication:'Pain/Clinical',channels:1,  homeClinic:'Clinic'},
  // taVNS
  { id:'nemos',           name:'NEMOS (Cerbomed)',                mfr:'tVNS Technologies',modality:'taVNS', type:'Ear electrode',  region:'Home/Clinic',clearance:'CE/FDA',   indication:'Epilepsy/Depression',channels:1,homeClinic:'Both',notes:'Tragus/cymba conchae stimulation. FDA-cleared for epilepsy.' },
  { id:'gammacore',       name:'gammaCore (nVNS)',                mfr:'electroCore',  modality:'nVNS',     type:'Neck device',      region:'Home',     clearance:'FDA 510(k)', indication:'Cluster headache',channels:1,homeClinic:'Home',  notes:'Non-invasive cervical VNS. Handheld.' },
  // Neurofeedback
  { id:'brainmaster',     name:'BrainMaster Discovery 24E',      mfr:'BrainMaster',  modality:'Neurofeedback',type:'EEG headset',  region:'Clinical', clearance:'FDA 510(k)', indication:'ADHD, anxiety',channels:24, homeClinic:'Clinic', notes:'24-channel clinical-grade EEG neurofeedback system.' },
  { id:'muse-2',          name:'Muse 2 Headband',                mfr:'InteraXon',    modality:'Neurofeedback',type:'Consumer EEG', region:'Home',     clearance:'Not FDA',     indication:'Wellness/NFB',  channels:4,  homeClinic:'Home',   notes:'4-ch consumer EEG. For home neurofeedback programs only.' },
  // CES
  { id:'alpha-stim',      name:'Alpha-Stim AID',                 mfr:'Electromedical Products',modality:'CES',type:'Ear clip',  region:'Home/Clinic',clearance:'FDA 510(k)', indication:'Anxiety, insomnia',channels:1,homeClinic:'Both', notes:'100–500 µA. FDA-cleared for anxiety, depression, insomnia.' },
  // PBM
  { id:'vielight-neuro',  name:'Vielight Neuro Gamma',           mfr:'Vielight',     modality:'PBM',      type:'Transcranial LED', region:'Home',     clearance:'Not FDA',     indication:'Cognition/AD', channels:5,  homeClinic:'Home',   notes:'810 nm NIR + 40 Hz intranasal PBM. Research phase.' },
  // DBS
  { id:'medtronic-activa',name:'Medtronic Activa RC',            mfr:'Medtronic',    modality:'DBS',      type:'Implantable IPG',  region:'Clinical', clearance:'FDA PMA',     indication:"Parkinson's, ET",channels:4, homeClinic:'Clinic', notes:'Deep brain stimulator. Requires neurosurgical implant.' },
  // FUS
  { id:'insightec-exablate',name:'InSightec Exablate Neuro',     mfr:'InSightec',    modality:'FUS',      type:'MRI-guided FUS',   region:'Clinical', clearance:'FDA PMA',     indication:'ET, Parkinson\'s',channels:1,homeClinic:'Clinic', notes:'Non-invasive focused ultrasound. FDA-cleared for essential tremor.' },
  // TPS
  { id:'neurolith',       name:'NEUROLITH TPS',                  mfr:'Storz Medical',modality:'TPS',      type:'Transcranial pulse',region:'Clinical',clearance:'CE / FDA IDE',indication:"Alzheimer's",  channels:1,  homeClinic:'Clinic', notes:'Transcranial pulse stimulation. CE-marked in Europe.' },
];

// ── 5. BRAIN TARGET REGISTRY — 10–20 / 10–10 sites + clinical mapping ─────────
export const BRAIN_TARGET_REGISTRY = [
  // Prefrontal
  { id:'DLPFC-L', label:'L-DLPFC',   site10_20:'F3',   site10_10:'FC1/F3',  lobe:'Frontal',    region:'Dorsolateral Prefrontal Cortex — Left',  ba:'BA9/46', function:'Executive function, working memory, mood regulation',          clinical:'MDD, TRD, ADHD, PTSD, Schizophrenia (negative symptoms)' },
  { id:'DLPFC-R', label:'R-DLPFC',   site10_20:'F4',   site10_10:'FC2/F4',  lobe:'Frontal',    region:'Dorsolateral Prefrontal Cortex — Right',  ba:'BA9/46', function:'Emotional regulation, cognitive control',                       clinical:'Anxiety, GAD, Bipolar depression, OCD (adjunct)' },
  { id:'VMPFC',   label:'vmPFC',      site10_20:'Fpz',  site10_10:'AFz',     lobe:'Frontal',    region:'Ventromedial Prefrontal Cortex',          ba:'BA10/11',function:'Default mode, self-referential processing, fear extinction',    clinical:'PTSD, anxiety, depression, emotional regulation' },
  { id:'OFC',     label:'OFC',        site10_20:'Fp1/2',site10_10:'AF3/AF4', lobe:'Frontal',    region:'Orbitofrontal Cortex',                    ba:'BA11/47',function:'Reward processing, inhibitory control, compulsive behavior',    clinical:'OCD, BDD, substance use, eating disorders' },
  { id:'SMA',     label:'SMA',        site10_20:'Cz',   site10_10:'FCz',     lobe:'Frontal',    region:'Supplementary Motor Area',                ba:'BA6',    function:'Motor planning, habit formation, impulse control',              clinical:'OCD (H7 TMS), tics, Tourette, Parkinson\'s' },
  { id:'premotor',label:'Premotor Cx',site10_20:'FC1/FC2',site10_10:'FC3/FC4',lobe:'Frontal',  region:'Premotor Cortex',                         ba:'BA6',    function:'Motor preparation, action selection',                           clinical:'Stroke rehabilitation, FND' },
  // Motor
  { id:'M1-L',    label:'M1 Left',    site10_20:'C3',   site10_10:'C3',      lobe:'Parietal',   region:'Primary Motor Cortex — Left (controls right body)', ba:'BA4', function:'Voluntary motor commands, right-side body',                  clinical:'Stroke rehab (left hemisphere), chronic pain (contralateral)' },
  { id:'M1-R',    label:'M1 Right',   site10_20:'C4',   site10_10:'C4',      lobe:'Parietal',   region:'Primary Motor Cortex — Right (controls left body)',  ba:'BA4', function:'Voluntary motor commands, left-side body',                   clinical:'Stroke rehab (right hemisphere), chronic pain' },
  { id:'M1-vertex',label:'M1 Vertex', site10_20:'Cz',   site10_10:'Cz',      lobe:'Parietal',   region:'Primary Motor Cortex — Vertex (leg area)',           ba:'BA4', function:'Lower limb and trunk motor control',                         clinical:'Gait disorders, chronic pelvic pain' },
  // Parietal
  { id:'IPL-L',   label:'L-IPL',      site10_20:'P3',   site10_10:'CP3',     lobe:'Parietal',   region:'Inferior Parietal Lobule — Left',         ba:'BA39/40',function:'Spatial attention, language, praxis',                           clinical:'Stroke rehabilitation, working memory' },
  { id:'IPL-R',   label:'R-IPL',      site10_20:'P4',   site10_10:'CP4',     lobe:'Parietal',   region:'Inferior Parietal Lobule — Right',         ba:'BA39/40',function:'Spatial attention, visuospatial processing',                  clinical:'Neglect (post-stroke), attention deficits' },
  { id:'S1-L',    label:'L-S1',       site10_20:'C3/CP3',site10_10:'CP5',    lobe:'Parietal',   region:'Primary Somatosensory Cortex — Left',     ba:'BA1/2/3',function:'Somatosensory processing',                                    clinical:'Chronic pain, post-amputation phantom pain' },
  // Temporal
  { id:'TPJ-L',   label:'L-TPJ',      site10_20:'T7/P7',site10_10:'TP7',     lobe:'Temporal',   region:'Temporoparietal Junction — Left',          ba:'BA39/22',function:'Language, social cognition, auditory processing',              clinical:'Stroke aphasia, auditory hallucinations' },
  { id:'TPJ-R',   label:'R-TPJ',      site10_20:'T8/P8',site10_10:'TP8',     lobe:'Temporal',   region:'Temporoparietal Junction — Right',         ba:'BA39/40',function:'Spatial attention, theory of mind',                            clinical:'Auditory hallucinations (schizophrenia), attention' },
  { id:'STG-L',   label:'L-STG',      site10_20:'T7',   site10_10:'FT7',     lobe:'Temporal',   region:'Superior Temporal Gyrus — Left (Wernicke)',ba:'BA22',   function:'Language comprehension, auditory processing',                  clinical:'Aphasia, auditory verbal hallucinations' },
  { id:'STG-R',   label:'R-STG',      site10_20:'T8',   site10_10:'FT8',     lobe:'Temporal',   region:'Superior Temporal Gyrus — Right',          ba:'BA22',   function:'Music perception, prosody, social cognition',                  clinical:'Tinnitus, auditory hallucinations' },
  // Occipital
  { id:'V1',      label:'V1 / Occipital',site10_20:'Oz', site10_10:'Oz',    lobe:'Occipital',  region:'Primary Visual Cortex',                   ba:'BA17',   function:'Primary visual processing',                                    clinical:'Migraine with aura, visual phosphenes (calibration)' },
  { id:'VLOC',    label:'Visual Association',site10_20:'O1/O2',site10_10:'PO7/PO8',lobe:'Occipital',region:'Visual Association Areas', ba:'BA18/19',function:'Visual recognition and integration',                           clinical:'Migraine, visual rehabilitation after stroke' },
  // Subcortical / special
  { id:'STN',     label:'Subthalamic Nucleus',site10_20:'N/A',site10_10:'N/A',lobe:'Subcortical',region:'Subthalamic Nucleus',              ba:'N/A',    function:'Motor control, reward, impulse inhibition',                    clinical:"Parkinson's (DBS), OCD (DBS), TRD (DBS)" },
  { id:'Vim',     label:'Ventralis Intermedius',site10_20:'N/A',site10_10:'N/A',lobe:'Subcortical',region:'Ventral Intermediate Nucleus (Thalamus)',ba:'N/A',function:'Tremor relay, cerebellar feedback',                          clinical:'Essential tremor (DBS/FUS), Parkinson\'s tremor' },
  { id:'Insula',  label:'Insula',      site10_20:'T7/FT7',site10_10:'FT7/FC5',lobe:'Temporal',  region:'Insular Cortex',                          ba:'BA13',   function:'Interoception, craving, pain integration',                     clinical:'Substance use disorders, chronic pain, anxiety' },
  { id:'Cerebellum',label:'Cerebellum',site10_20:'N/A',site10_10:'Iz',      lobe:'Cerebellar', region:'Cerebellum',                              ba:'N/A',    function:'Motor coordination, cognitive modulation',                     clinical:'Ataxia, essential tremor, autism (research)' },
  { id:'Auricular',label:'Auricular (taVNS)',site10_20:'N/A',site10_10:'N/A',lobe:'Peripheral', region:'Auricular branch — Vagus Nerve',          ba:'N/A',    function:'Parasympathetic activation via vagal afferents',               clinical:'Epilepsy, depression, pain, migraine' },
];

// ── 6. CONSENT / DOCUMENT REGISTRY ────────────────────────────────────────────
export const CONSENT_REGISTRY = [
  // Intake
  { id:'intake-general',       cat:'Intake',    name:'General Patient Intake Form',       required:true,  version:'1.2', desc:'Demographics, emergency contact, GP, insurance, referral source.', fields:['name','dob','address','emergency_contact','gp','insurance','referral'] },
  { id:'intake-clinical',      cat:'Intake',    name:'Clinical Intake Form',              required:true,  version:'1.2', desc:'Presenting problem, symptom duration, prior treatments, current medications, mood/function overview.', fields:['chief_complaint','symptom_onset','prior_tx','medications','goals'] },
  { id:'intake-safety',        cat:'Intake',    name:'Safety Screening Questionnaire',    required:true,  version:'1.1', desc:'Seizure history, implants, cardiac devices, pregnancy, metal in body, previous adverse reactions.', fields:['seizure_hx','implants','cardiac_device','pregnancy','metal','prior_ae'] },
  // Neuromodulation consent
  { id:'consent-tms-general',  cat:'Consent',   name:'TMS Treatment Consent',             required:true,  version:'2.0', desc:'Risks, benefits, alternatives, voluntary participation for TMS/rTMS/iTBS.', fields:['risks','benefits','alternatives','voluntary','signature','date'] },
  { id:'consent-tdcs',         cat:'Consent',   name:'tDCS Treatment Consent',            required:true,  version:'1.3', desc:'Consent form for transcranial direct current stimulation.', fields:['risks','benefits','signature','date'] },
  { id:'consent-ect',          cat:'Consent',   name:'ECT Consent',                       required:true,  version:'2.1', desc:'Electroconvulsive therapy consent including anaesthetic risks and memory effects.', fields:['risks','anaesthetic_risks','memory_effects','voluntary','signature','date'] },
  { id:'consent-dbs',          cat:'Consent',   name:'DBS Surgical Consent',              required:true,  version:'1.4', desc:'Deep brain stimulation device + surgical consent.', fields:['surgical_risks','device_risks','voluntary','signature','date'] },
  { id:'consent-tavns',        cat:'Consent',   name:'taVNS Device Consent',              required:true,  version:'1.0', desc:'Transcutaneous auricular VNS consent.', fields:['risks','benefits','signature','date'] },
  { id:'consent-nfb',          cat:'Consent',   name:'Neurofeedback Consent',             required:false, version:'1.0', desc:'EEG neurofeedback treatment consent.', fields:['risks','benefits','signature','date'] },
  { id:'consent-home-device',  cat:'Consent',   name:'Home Device Use Consent',           required:true,  version:'1.1', desc:'Consent for patient to use prescribed neuromodulation device at home.', fields:['device_name','usage_instructions','risks','signature','date'] },
  // Research / data
  { id:'consent-research',     cat:'Privacy',   name:'Research Data Use Consent',         required:false, version:'1.0', desc:'Consent for de-identified data use in research and quality improvement.', fields:['data_scope','withdrawal_rights','signature','date'] },
  { id:'consent-privacy',      cat:'Privacy',   name:'Privacy & Data Sharing Policy',     required:true,  version:'1.3', desc:'Clinic privacy policy, data retention, third-party sharing acknowledgement.', fields:['policy_text','signature','date'] },
  { id:'consent-telehealth',   cat:'Privacy',   name:'Telehealth / Virtual Care Consent', required:true,  version:'1.1', desc:'Consent for telehealth service delivery including limitations and security.', fields:['platform','limitations','signature','date'] },
  // Caregiver
  { id:'consent-caregiver-auth',cat:'Caregiver',name:'Caregiver / Representative Auth',  required:false, version:'1.0', desc:'Authorises caregiver to receive information and act on patient behalf.', fields:['caregiver_name','relationship','scope','signature','date'] },
  { id:'consent-caregiver-tx', cat:'Caregiver', name:'Caregiver Treatment Consent',       required:false, version:'1.0', desc:'Caregiver consent when patient lacks capacity for treatment decisions.', fields:['capacity_assessment','caregiver_name','signature','date'] },
  // Clinical documents
  { id:'doc-referral-ack',     cat:'Clinical',  name:'Referral Acknowledgement',          required:false, version:'1.0', desc:'Confirms receipt and review of referral letter, treatment pathway agreed.', fields:['referrer','pathway','agreed_plan','date'] },
  { id:'doc-discharge',        cat:'Clinical',  name:'Discharge Summary Template',        required:true,  version:'1.2', desc:'Structured discharge: diagnosis, treatment given, response, follow-up plan, medications.', fields:['diagnosis','treatment_summary','response','follow_up','medications','clinician'] },
  { id:'doc-info-release',     cat:'Clinical',  name:'Information Release Authorisation', required:false, version:'1.0', desc:'Patient authorises release of clinical records to named third party.', fields:['recipient','scope','expiry','signature','date'] },
  { id:'doc-ae-report',        cat:'Clinical',  name:'Adverse Event Report',              required:true,  version:'1.1', desc:'Structured adverse event documentation: type, severity, management, outcome.', fields:['event_type','severity','session_id','management','outcome','clinician'] },
];

// ── 7. REPORT TEMPLATE REGISTRY ───────────────────────────────────────────────
export const REPORT_TEMPLATE_REGISTRY = [
  { id:'rpt-progress',   cat:'Progress',     name:'Treatment Progress Report',       freq:'Every 2 weeks', auto:true,  desc:'PHQ-9/MADRS trend, sessions completed, tolerance summary, clinician comment.', sections:['patient_id','period','assessments','sessions','tolerance','clinician_notes','plan'] },
  { id:'rpt-eeg-base',   cat:'EEG / qEEG',   name:'Baseline qEEG Report',            freq:'Once (pre)',    auto:false, desc:'Full qEEG spectral analysis, coherence, asymmetry, clinical interpretation.', sections:['patient','date','acquisition','spectral_power','coherence','asymmetry','interpretation','recommendations'] },
  { id:'rpt-eeg-post',   cat:'EEG / qEEG',   name:'Post-Treatment qEEG Comparison',  freq:'Once (post)',   auto:false, desc:'Pre/post qEEG comparison with change scores and treatment response indicators.', sections:['patient','pre_eeg_ref','post_date','change_spectral','change_coherence','clinical_correlation'] },
  { id:'rpt-course-end', cat:'Outcome',      name:'End-of-Course Outcome Report',    freq:'Once (post)',   auto:true,  desc:'Full treatment course summary: sessions, scale scores, response rate, discharge plan.', sections:['patient','course_id','diagnosis','modality','sessions_completed','assessment_trends','response_class','ae_summary','discharge_plan'] },
  { id:'rpt-ae',         cat:'Safety',       name:'Adverse Events Report',           freq:'As needed',     auto:false, desc:'All adverse events for a patient or course with severity and resolution status.', sections:['patient','period','ae_list','severity_breakdown','resolution','clinician'] },
  { id:'rpt-lab',        cat:'Blood / Lab',  name:'Pre-Treatment Labs Report',       freq:'Once (pre)',    auto:false, desc:'Blood panel: TSH, CBC, CMP, relevant biomarkers. Flagged abnormalities.', sections:['patient','date','lab_source','results','flags','clinical_notes'] },
  { id:'rpt-mri',        cat:'MRI / Imaging',name:'Brain MRI Report',                freq:'As needed',     auto:false, desc:'Structural MRI findings, contraindication clearance, relevant lesions.', sections:['patient','date','facility','sequences','findings','contraindication_cleared','radiologist'] },
  { id:'rpt-specialist', cat:'Specialist',   name:'Specialist Referral Letter',      freq:'As needed',     auto:false, desc:'Letter to/from specialist: diagnosis, treatment context, request/response.', sections:['patient','date','referring_clinician','specialist','purpose','clinical_summary','request','reply'] },
  { id:'rpt-clinician-sum',cat:'Summary',    name:'Clinician Clinical Summary',      freq:'As needed',     auto:false, desc:'Structured clinical summary for handover, records, or insurance.', sections:['patient','date','diagnosis','current_tx','response','plan','clinician'] },
  { id:'rpt-ai-summary', cat:'AI',           name:'AI-Assisted Report Summary',      freq:'On demand',     auto:true,  desc:'LLM-generated summary of selected reports with key findings and flags.', sections:['source_reports','summary_text','key_findings','flags','generated_date'] },
  { id:'rpt-population', cat:'Population',   name:'Population Analytics Report',     freq:'Monthly',       auto:true,  desc:'Aggregate outcomes: response rates, AE rates, protocol usage, by condition/modality.', sections:['period','n_patients','conditions','modalities','response_rates','ae_rates','top_protocols'] },
  { id:'rpt-irb',        cat:'Research',     name:'IRB / Ethics Report',             freq:'As required',   auto:false, desc:'Structured IRB/ethics reporting: patient numbers, adverse events, protocol deviations.', sections:['study_id','period','n_enrolled','protocol_deviations','ae_serious','status'] },
];

// ── 8. HANDBOOK TEMPLATE REGISTRY ─────────────────────────────────────────────
export const HANDBOOK_REGISTRY = [
  { id:'hb-tms-patient',   cat:'Patient',     name:'TMS Treatment — Patient Guide',     condition:'all',    pages:6,  format:'PDF', desc:'What is TMS, what to expect, preparation, common sensations, contraindications.' },
  { id:'hb-tdcs-patient',  cat:'Patient',     name:'tDCS Treatment — Patient Guide',    condition:'all',    pages:4,  format:'PDF', desc:'tDCS overview, electrode placement, sensations, home use instructions.' },
  { id:'hb-nfb-patient',   cat:'Patient',     name:'Neurofeedback — Patient Guide',     condition:'adhd-c', pages:4,  format:'PDF', desc:'What is neurofeedback, how EEG works, session expectations, home practice.' },
  { id:'hb-mdd-pt',        cat:'Patient',     name:'Depression & TMS — Patient Booklet',condition:'mdd',    pages:10, format:'PDF', desc:'Comprehensive patient education: MDD overview, TMS evidence, course expectations, FAQs.' },
  { id:'hb-ocd-pt',        cat:'Patient',     name:'OCD & TMS — Patient Booklet',       condition:'ocd',    pages:8,  format:'PDF', desc:'OCD psychoeducation, deep TMS (H7 coil), exposure therapy integration, FAQs.' },
  { id:'hb-ptsd-pt',       cat:'Patient',     name:'PTSD & Brain Stimulation — Guide',  condition:'ptsd',   pages:8,  format:'PDF', desc:'PTSD overview, TMS as adjunct, trauma-informed session approach, self-regulation tips.' },
  { id:'hb-stroke-pt',     cat:'Patient',     name:'Stroke Rehab & TMS — Guide',        condition:'stroke-mtr',pages:6,format:'PDF',desc:'Stroke rehabilitation overview, TMS role, physiotherapy coordination, expectations.' },
  { id:'hb-migraine-pt',   cat:'Patient',     name:'Migraine & TMS — Guide',            condition:'migraine',pages:5,format:'PDF', desc:'Migraine types, single-pulse TMS for aura, when/how to use device, diary.' },
  { id:'hb-tms-clinical',  cat:'Clinician',   name:'TMS Operator Clinical Manual',      condition:'all',    pages:22, format:'PDF', desc:'Motor threshold determination, coil positioning, protocol parameters, safety protocols, adverse event management.' },
  { id:'hb-tdcs-clinical', cat:'Clinician',   name:'tDCS Clinical Protocol Manual',     condition:'all',    pages:14, format:'PDF', desc:'Electrode preparation, montage setup, current ramp-up, monitoring, electrode care.' },
  { id:'hb-safety',        cat:'Safety',      name:'Neuromodulation Safety Manual',     condition:'all',    pages:16, format:'PDF', desc:'Universal contraindications, seizure risk management, emergency protocols, incident reporting.' },
  { id:'hb-consent',       cat:'Governance',  name:'Consent & Documentation Handbook',  condition:'all',    pages:12, format:'PDF', desc:'Consent process, documentation standards, storage requirements, patient rights.' },
  { id:'hb-caregiver',     cat:'Caregiver',   name:'Family & Caregiver Guide',          condition:'all',    pages:8,  format:'PDF', desc:'Supporting your family member through neuromodulation: what to expect, how to help, warning signs.' },
];

// ── 9. HOME PROGRAM TEMPLATE REGISTRY ─────────────────────────────────────────
export const HOME_PROGRAM_REGISTRY = [
  { id:'hp-tdcs-mdd',     cat:'Device',       name:'Home tDCS — MDD Maintenance',       device:'Flow Neuroscience',condition:'mdd',     freq:'5x/wk', duration:'30 min', ev:'B', desc:'F3 anode, Fp2 cathode. 2 mA, 30 min. Paired with cognitive tasks (app-guided).', tasks:['device-session','mood-diary','sleep-log'] },
  { id:'hp-ces-anxiety',  cat:'Device',       name:'Home CES — Anxiety / Insomnia',     device:'Alpha-Stim',    condition:'gad',     freq:'Daily', duration:'20 min', ev:'B', desc:'Ear-clip CES at 100 µA. 20 min morning or evening. Anxiety and sleep protocol.', tasks:['device-session','symptom-log'] },
  { id:'hp-nfb-adhd',     cat:'Device',       name:'Home Neurofeedback — ADHD',         device:'Muse 2',        condition:'adhd-c',  freq:'4x/wk', duration:'20 min', ev:'C', desc:'Theta suppression / beta enhancement. App-guided 20-min sessions at home.', tasks:['nfb-session','symptom-log'] },
  { id:'hp-spring-migr',  cat:'Device',       name:'Home TMS — Migraine Prevention',    device:'SpringTMS',     condition:'migraine',freq:'Daily', duration:'5 min',  ev:'A', desc:'Single-pulse TMS to occiput. 4 pulses at onset of aura, or daily prevention protocol.', tasks:['device-session','headache-diary'] },
  { id:'hp-breathing',    cat:'Behavioural',  name:'Diaphragmatic Breathing Program',   device:'None',          condition:'gad',     freq:'2x/day',duration:'10 min', ev:'A', desc:'Box breathing (4-4-4-4). Guided via app. Reduces HRV baseline anxiety.', tasks:['breathing-exercise','symptom-log'] },
  { id:'hp-sleep-hygiene',cat:'Behavioural',  name:'Sleep Hygiene Protocol',            device:'None',          condition:'insomnia',freq:'Daily', duration:'15 min', ev:'A', desc:'Fixed wake time, stimulus control, wind-down routine. Structured 4-week programme.', tasks:['sleep-diary','routine-checklist'] },
  { id:'hp-act-mdd',      cat:'Behavioural',  name:'Behavioural Activation — MDD',      device:'None',          condition:'mdd',     freq:'Daily', duration:'30 min', ev:'A', desc:'Scheduled pleasant activities, values-based actions. Weekly activity log.', tasks:['activity-log','mood-diary'] },
  { id:'hp-erp-ocd',      cat:'Behavioural',  name:'ERP Practice — OCD',               device:'None',          condition:'ocd',     freq:'Daily', duration:'30 min', ev:'A', desc:'Exposure and response prevention homework. Hierarchy-based. Clinician-supervised.', tasks:['erp-diary','compulsion-log'] },
  { id:'hp-grounding-ptsd',cat:'Behavioural', name:'Grounding & Stabilisation — PTSD',  device:'None',          condition:'ptsd',    freq:'2x/day',duration:'10 min', ev:'B', desc:'5-4-3-2-1 sensory grounding, safe place visualisation, breath anchor.', tasks:['grounding-log','safety-check'] },
  { id:'hp-motor-stroke',  cat:'Rehab',       name:'Motor Rehab Exercises — Stroke',    device:'None',          condition:'stroke-mtr',freq:'2x/day',duration:'45 min',ev:'A', desc:'Task-specific upper limb exercises, mirror therapy, constraint-induced movement prep.', tasks:['exercise-log','motor-diary'] },
  { id:'hp-cognitive-tbi', cat:'Rehab',       name:'Cognitive Rehab Tasks — TBI',       device:'None',          condition:'tbi',     freq:'Daily', duration:'20 min', ev:'B', desc:'Attention training (APT-III style), memory strategies, compensatory tools.', tasks:['task-log','cognitive-diary'] },
  { id:'hp-mindfulness',   cat:'Behavioural', name:'Mindfulness-Based Practice',        device:'None',          condition:'all',     freq:'Daily', duration:'20 min', ev:'A', desc:'MBSR-style daily mindfulness: body scan, breath awareness, mindful movement.', tasks:['mindfulness-log','symptom-log'] },
];

// ── 10. VIRTUAL CARE TEMPLATE REGISTRY ────────────────────────────────────────
export const VIRTUAL_CARE_REGISTRY = [
  { id:'vc-intake',      cat:'Intake',        name:'Virtual Intake Consultation',      duration:60, modality:'Video', staffing:'Clinician',  desc:'Initial assessment, history, consent, goals, suitability screening.', tasks:['history-review','consent-send','assessment-schedule','care-plan-draft'] },
  { id:'vc-pre-tx',      cat:'Pre-Treatment', name:'Pre-Treatment Check-In',           duration:30, modality:'Video', staffing:'Clinician',  desc:'Review medical history, confirm safety screening, address questions before first session.', tasks:['safety-screen-review','q-and-a','consent-confirm'] },
  { id:'vc-progress',    cat:'Progress',      name:'Mid-Course Progress Review',       duration:20, modality:'Video', staffing:'Clinician',  desc:'Review assessment scores, tolerance, side effects, protocol adjustment if needed.', tasks:['assessment-review','ae-check','protocol-note'] },
  { id:'vc-post-tx',     cat:'Discharge',     name:'Post-Treatment Discharge Review',  duration:45, modality:'Video', staffing:'Clinician',  desc:'Full outcome review, discharge summary, relapse prevention plan, referrals.', tasks:['outcome-review','discharge-summary','referral-letters','follow-up-plan'] },
  { id:'vc-ae-urgent',   cat:'Safety',        name:'Adverse Event Urgent Review',      duration:30, modality:'Video', staffing:'Clinician',  desc:'Urgent virtual assessment of adverse event. Determines if in-person required.', tasks:['ae-report','clinical-decision','protocol-hold'] },
  { id:'vc-family',      cat:'Support',       name:'Family / Caregiver Consultation',  duration:30, modality:'Video', staffing:'Clinician',  desc:'Caregiver education, questions, progress update, support plan.', tasks:['caregiver-education','q-and-a','support-plan'] },
  { id:'vc-nfb-remote',  cat:'Therapy',       name:'Remote Neurofeedback Session',     duration:45, modality:'Video+EEG', staffing:'Technician+Clinician', desc:'Supervised home EEG/NFB session via telehealth with device monitoring.', tasks:['eeg-connect','nfb-session','session-note'] },
  { id:'vc-supervision', cat:'Clinical',      name:'Resident / Technician Supervision',duration:30, modality:'Video', staffing:'Supervisor', desc:'Supervision session: case review, protocol questions, competency check.', tasks:['case-review','competency-note','learning-goals'] },
  { id:'vc-psycho-ed',   cat:'Education',     name:'Psychoeducation Group Session',    duration:60, modality:'Video', staffing:'Clinician',  desc:'Group session: condition education, treatment rationale, Q&A.', tasks:['group-invite','slides','q-and-a','attendance-record'] },
  { id:'vc-check-in',    cat:'Monitoring',    name:'Brief Symptom Check-In',           duration:10, modality:'Phone/Video', staffing:'Admin',desc:'10-minute scheduled check-in: side effects, adherence, flags for clinician.', tasks:['symptom-check','flag-review','note-to-clinician'] },
];
