"""Persistence ORM models — split by bounded context.

Originally a single 4,172-line ``models.py``. The 2026-05-02 architect review flagged the file as a top-3 ROI split (bus factor 1, concurrent edits guaranteed to collide). This package preserves the public surface exactly: every class is re-exported from this module, so callers can keep writing ``from app.persistence.models import Patient, AuditEventRecord``.

All classes share the single declarative ``Base`` from ``app.database``, imported through ``_base.py`` — verify with::

    from app.persistence.models import Patient, AuditEventRecord
    assert Patient.metadata is AuditEventRecord.metadata

Buckets:
  - ``audit.py`` — 7 classes
  - ``auth.py`` — 8 classes
  - ``billing.py`` — 13 classes
  - ``caregiver.py`` — 3 classes
  - ``clinical.py`` — 33 classes
  - ``devices.py`` — 16 classes
  - ``media.py`` — 9 classes
  - ``mri.py`` — 6 classes
  - ``ops.py`` — 13 classes
  - ``patient.py`` — 9 classes
  - ``qeeg.py`` — 16 classes
  - ``research.py`` — 20 classes
  - ``wellness.py`` — 2 classes
"""
from __future__ import annotations

from ._base import (  # noqa: F401 — public surface compatibility
    Base,
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Mapped,
    Optional,
    String,
    Text,
    UniqueConstraint,
    datetime,
    event,
    mapped_column,
    sa_text,
    timezone,
    uuid,
    _HAS_PGVECTOR,
    _PgVector,
    _embedding_column,
    _embedding_column_1536,
)

from .billing import (  # noqa: F401 — public surface compatibility
    _DEFAULT_PACKAGE_BUDGETS,
    _seed_default_package_budgets,
)

from .audit import (
    AgentRunAudit,
    AiSummaryAudit,
    AuditEventRecord,
    ClinicalDatasetSnapshotRecord,
    ClinicalSeedRecord,
    QualityFinding,
    QualityFindingRevision,
)
from .auth import (
    ClinicDefaults,
    PasswordResetToken,
    TeamMember,
    User,
    User2FASecret,
    UserContactMapping,
    UserPreferences,
    UserSession,
)
from .billing import (
    AgentPromptOverride,
    AgentSubscription,
    ClinicMonthlyCostCap,
    DataExport,
    InsuranceClaim,
    Invoice,
    MarketplaceItem,
    MarketplaceOrder,
    PackageTokenBudget,
    PatientPayment,
    StripeWebhookEvent,
    StripeWebhookLog,
    Subscription,
)
from .caregiver import (
    CaregiverConsentGrant,
    CaregiverConsentRevision,
    CaregiverDigestPreference,
)
from .clinical import (
    AdverseEvent,
    AgentSkill,
    Annotation,
    AssessmentRecord,
    ClinicalSession,
    ClinicalSessionEvent,
    ClinicianHomeProgramTask,
    DeepTwinAnalysisRun,
    DeepTwinClinicianNote,
    DeepTwinSimulationRun,
    DeliveredSessionParameters,
    DigitalPhenotypingAudit,
    DigitalPhenotypingObservation,
    DigitalPhenotypingPatientState,
    DocumentTemplate,
    FormDefinition,
    FormSubmission,
    FusionCase,
    FusionCaseAudit,
    FusionCaseFinding,
    HomeTaskTemplate,
    MedicationAnalyzerAudit,
    MedicationAnalyzerReviewNote,
    MedicationAnalyzerTimelineEvent,
    MedicationInteractionLog,
    MovementAnalyzerAudit,
    MovementAnalyzerSnapshot,
    NutritionAnalyzerAudit,
    OnboardingEvent,
    OnboardingState,
    PatientAgentActivation,
    PatientHomeProgramTaskCompletion,
    PatientMedication,
    PatientNutritionDietLog,
    PatientRiskFormulation,
    PatientSupplement,
    PrescribedProtocol,
    ProtocolVersion,
    ReminderCampaign,
    ReminderOutboxMessage,
    RiskAnalyzerAudit,
    RiskStratificationAudit,
    RiskStratificationResult,
    SessionRecording,
    TreatmentCourse,
    TreatmentCourseReview,
)
from .devices import (
    BiometricsSnapshot,
    DeviceConnection,
    DeviceSessionLog,
    DeviceSourceRegistry,
    DeviceSyncEvent,
    HomeDeviceAssignment,
    HomeDeviceReviewFlag,
    PatientAdherenceEvent,
    PatientHomeDeviceCalibration,
    PatientHomeDeviceRegistration,
    VideoAnalysis,
    VideoAssessmentSession,
    VirtualCareSession,
    VoiceAnalysis,
    WearableAlertFlag,
    WearableDailySummary,
    WearableObservation,
)
from .media import (
    AudioAnalysis,
    ClinicianMediaNote,
    ClinicianMediaTranscript,
    ClinicianNoteDraft,
    MediaConsent,
    MediaRedFlag,
    PatientMediaAnalysis,
    PatientMediaReviewAction,
    PatientMediaTranscript,
    PatientMediaUpload,
)
from .labs import PatientLabResult
from .mri import (
    MriAnalysis,
    MriReportAudit,
    MriReportFinding,
    MriTargetPlan,
    MriTimelineEvent,
    MriUpload,
)
from .ops import (
    Clinic,
    ClinicLead,
    ClinicTeamInvite,
    DeviceResource,
    EscalationChain,
    EscalationPolicy,
    OncallPage,
    ReceptionCall,
    ReceptionTask,
    ResolverCoachingDigestPreference,
    ReviewerSLACalibrationThreshold,
    RoomResource,
    RotationPolicyAdvisorThreshold,
    SLAConfig,
    SalesInquiry,
    ShiftRoster,
)
from .patient import (
    ConsentRecord,
    IntakePacket,
    Message,
    OutcomeEvent,
    OutcomeSeries,
    Patient,
    PatientInvite,
    PhenotypeAssignment,
    ReviewQueueItem,
)
from .qeeg import (
    AnalysisAnnotation,
    AutoCleanRun,
    CleaningDecision,
    KgEntity,
    KgHyperedge,
    QEEGAIReport,
    QEEGAnalysis,
    QEEGComparison,
    QEEGProtocolFit,
    QEEGRecord,
    QEEGReportAnnotation,
    QEEGReportAudit,
    QEEGReportFinding,
    QEEGTimelineEvent,
    QeegCleaningAnnotation,
    QeegCleaningAuditEvent,
    QeegCleaningVersion,
)
from .research import (
    ClinicalTrial,
    ClinicalTrialEnrollment,
    ClinicalTrialRevision,
    DsClaimCitation,
    DsGroundingAudit,
    DsHgEdgeCitation,
    DsPaper,
    EvidenceSavedCitation,
    IRBAdverseEvent,
    IRBAmendment,
    IRBProtocol,
    IRBProtocolAmendment,
    IRBProtocolRevision,
    IRBStudy,
    LiteratureCuration,
    LiteraturePaper,
    LiteratureProtocolTag,
    LiteratureReadingList,
    TelegramPendingLink,
    TelegramUserChat,
)
from .wellness import (
    SymptomJournalEntry,
    WellnessCheckin,
)

__all__ = [
    "Base",
    "AdverseEvent",
    "AgentPromptOverride",
    "AgentRunAudit",
    "AgentSkill",
    "AgentSubscription",
    "AiSummaryAudit",
    "AnalysisAnnotation",
    "Annotation",
    "AssessmentRecord",
    "AudioAnalysis",
    "AuditEventRecord",
    "AutoCleanRun",
    "BiometricsSnapshot",
    "CaregiverConsentGrant",
    "CaregiverConsentRevision",
    "CaregiverDigestPreference",
    "CleaningDecision",
    "Clinic",
    "ClinicDefaults",
    "ClinicLead",
    "ClinicMonthlyCostCap",
    "ClinicTeamInvite",
    "ClinicalDatasetSnapshotRecord",
    "ClinicalSeedRecord",
    "ClinicalSession",
    "ClinicalSessionEvent",
    "ClinicalTrial",
    "ClinicalTrialEnrollment",
    "ClinicalTrialRevision",
    "ClinicianHomeProgramTask",
    "ClinicianMediaNote",
    "ClinicianMediaTranscript",
    "ClinicianNoteDraft",
    "ConsentRecord",
    "DataExport",
    "DeepTwinAnalysisRun",
    "DeepTwinClinicianNote",
    "DeepTwinSimulationRun",
    "DeliveredSessionParameters",
    "DigitalPhenotypingAudit",
    "DigitalPhenotypingObservation",
    "DigitalPhenotypingPatientState",
    "DeviceConnection",
    "DeviceResource",
    "DeviceSessionLog",
    "DeviceSourceRegistry",
    "DeviceSyncEvent",
    "DocumentTemplate",
    "DsClaimCitation",
    "DsGroundingAudit",
    "DsHgEdgeCitation",
    "DsPaper",
    "EscalationChain",
    "EscalationPolicy",
    "EvidenceSavedCitation",
    "FormDefinition",
    "FormSubmission",
    "FusionCase",
    "FusionCaseAudit",
    "FusionCaseFinding",
    "HomeDeviceAssignment",
    "HomeDeviceReviewFlag",
    "HomeTaskTemplate",
    "IRBAdverseEvent",
    "IRBAmendment",
    "IRBProtocol",
    "IRBProtocolAmendment",
    "IRBProtocolRevision",
    "IRBStudy",
    "InsuranceClaim",
    "IntakePacket",
    "Invoice",
    "KgEntity",
    "KgHyperedge",
    "LiteratureCuration",
    "LiteraturePaper",
    "LiteratureProtocolTag",
    "LiteratureReadingList",
    "MarketplaceItem",
    "MarketplaceOrder",
    "MediaConsent",
    "MediaRedFlag",
    "MedicationAnalyzerAudit",
    "MedicationAnalyzerReviewNote",
    "MedicationAnalyzerTimelineEvent",
    "MedicationInteractionLog",
    "MovementAnalyzerAudit",
    "MovementAnalyzerSnapshot",
    "NutritionAnalyzerAudit",
    "Message",
    "MriAnalysis",
    "MriReportAudit",
    "MriReportFinding",
    "MriTargetPlan",
    "MriTimelineEvent",
    "MriUpload",
    "OnboardingEvent",
    "OnboardingState",
    "OncallPage",
    "OutcomeEvent",
    "OutcomeSeries",
    "PackageTokenBudget",
    "PasswordResetToken",
    "Patient",
    "PatientAdherenceEvent",
    "PatientAgentActivation",
    "PatientHomeDeviceCalibration",
    "PatientHomeDeviceRegistration",
    "PatientHomeProgramTaskCompletion",
    "PatientInvite",
    "PatientMediaAnalysis",
    "PatientMediaReviewAction",
    "PatientMediaTranscript",
    "PatientMediaUpload",
    "PatientLabResult",
    "PatientMedication",
    "PatientNutritionDietLog",
    "PatientRiskFormulation",
    "PatientSupplement",
    "PatientPayment",
    "PhenotypeAssignment",
    "PrescribedProtocol",
    "ProtocolVersion",
    "QEEGAIReport",
    "QEEGAnalysis",
    "QEEGComparison",
    "QEEGProtocolFit",
    "QEEGRecord",
    "QEEGReportAnnotation",
    "QEEGReportAudit",
    "QEEGReportFinding",
    "QEEGTimelineEvent",
    "QeegCleaningAnnotation",
    "QeegCleaningAuditEvent",
    "QeegCleaningVersion",
    "QualityFinding",
    "QualityFindingRevision",
    "ReceptionCall",
    "ReceptionTask",
    "ResolverCoachingDigestPreference",
    "ReviewerSLACalibrationThreshold",
    "RotationPolicyAdvisorThreshold",
    "ReminderCampaign",
    "ReminderOutboxMessage",
    "ReviewQueueItem",
    "RiskAnalyzerAudit",
    "RiskStratificationAudit",
    "RiskStratificationResult",
    "RoomResource",
    "SLAConfig",
    "SalesInquiry",
    "SessionRecording",
    "ShiftRoster",
    "StripeWebhookEvent",
    "StripeWebhookLog",
    "Subscription",
    "SymptomJournalEntry",
    "TeamMember",
    "TelegramPendingLink",
    "TelegramUserChat",
    "TreatmentCourse",
    "TreatmentCourseReview",
    "User",
    "User2FASecret",
    "UserContactMapping",
    "UserPreferences",
    "UserSession",
    "VideoAnalysis",
    "VideoAssessmentSession",
    "VirtualCareSession",
    "VoiceAnalysis",
    "WearableAlertFlag",
    "WearableDailySummary",
    "WearableObservation",
    "WellnessCheckin",
]
