"""Patient Home Program Tasks (Homework) launch-audit (2026-05-01).

Seventh patient-facing launch-audit surface in the chain after Symptom
Journal (#344), Wellness Hub (#345), Patient Reports (#346), Patient
Messages (#347), Home Devices (#348) and Adherence Events (#350).

Closes the home-therapy regulator loop end-to-end: clinician assigns
tasks via the clinician-side ``home_program_tasks_router`` → patient
SEES tasks here → patient LOGS completion via the Adherence Events
router (#350) → side-effect with severity >= 7 escalates to the AE Hub
(#342) → safety review in QA Hub (#321).

This page is read-side + start + help-request. **Task completion is
NOT logged here** — the "Log now" CTA deep-links the patient into
``/?page=pt-adherence-events&task_id=<id>`` so completion flows
through the single-source-of-truth ``patient_adherence_events`` queue.

Endpoints
---------
GET    /api/v1/home-program-tasks/patient/today          Today's tasks (due today, not yet completed)
GET    /api/v1/home-program-tasks/patient/upcoming       Next 7d (excludes today)
GET    /api/v1/home-program-tasks/patient/completed      Completed history (limit 200)
GET    /api/v1/home-program-tasks/patient/summary        Counts: assigned-today, due-today, overdue, completion_rate_7d, missed_streak
GET    /api/v1/home-program-tasks/patient/{task_id}      Detail (404 cross-patient)
POST   /api/v1/home-program-tasks/patient/{task_id}/start          Mark started — emits clinician-visible audit
POST   /api/v1/home-program-tasks/patient/{task_id}/help-request   Creates Patient Messages thread linked to task_id
GET    /api/v1/home-program-tasks/patient/export.csv      DEMO-prefixed when demo
GET    /api/v1/home-program-tasks/patient/export.ndjson   DEMO-prefixed when demo
POST   /api/v1/home-program-tasks/patient/audit-events    Page-level audit ingestion (target_type=home_program_tasks)

Role gate
---------
Patient role only on these endpoints. Clinicians use the existing
clinician-side ``home_program_tasks_router`` queue. Cross-role hits
return 404 (never 403/401) so the patient-scope URL existence is
invisible to clinicians and admins. Cross-patient task lookups also
return 404.

Consent gate
------------
Once a patient has revoked consent
(``Patient.consent_signed = False`` OR a ``ConsentRecord`` row with
``status='withdrawn'``) the page is read-only post-revocation:
existing tasks remain visible, but no new ``start`` or
``help-request`` events can be written (HTTP 403). Mirrors the
adherence_events / patient_messages / wellness_hub / home_devices
pattern.

Demo honesty
------------
``is_demo`` is sourced from :func:`_patient_is_demo_hpt`. Exports
prefix ``DEMO-`` to the filename whenever the patient row is demo
and a ``X-HomeProgramTasks-Demo: 1`` response header is set.
"""

from __future__ import annotations

import csv
import io
import json
import logging
import re
import uuid
from datetime import date, datetime, timedelta, timezone
from typing import Any, Optional

from fastapi import APIRouter, Depends, Path, Query, Response
from pydantic import BaseModel, Field, field_validator
from sqlalchemy.orm import Session

from app.auth import AuthenticatedActor, get_authenticated_actor
from app.database import get_db_session
from app.errors import ApiServiceError
from app.persistence.models import (
    ClinicianHomeProgramTask,
    ConsentRecord,
    Message,
    Patient,
    PatientHomeProgramTaskCompletion,
    User,
)
from app.services.home_program_tasks import load_task_dict


router = APIRouter(
    prefix="/api/v1/home-program-tasks/patient",
    tags=["Patient Home Program Tasks"],
)
_log = logging.getLogger(__name__)


# Honest disclaimers always rendered on the page so reviewers know the
# regulatory weight of the homework surface.
HOMEWORK_DISCLAIMERS = [
    "Tasks shown here are assigned by your clinician. The 'Why am I "
    "doing this?' note is written by your care team, not generated by "
    "AI.",
    "Marking a task started or asking for help creates an audit row "
    "your care team can review.",
    "To log that you finished a task, use the 'Log now' button — it "
    "takes you to the Adherence Events page where the entry becomes "
    "part of your clinical record.",
    "If you withdraw consent, your existing tasks remain readable but "
    "no new starts / help requests can be logged until consent is "
    "reinstated.",
]


# ── Helpers ─────────────────────────────────────────────────────────────────


_DEMO_PATIENT_ACTOR_ID = "actor-patient-demo"
_DEMO_PATIENT_EMAILS = {"patient@deepsynaps.com", "patient@demo.com"}

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_EXTERNAL_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,96}$")


def _aware(dt: Optional[datetime]) -> Optional[datetime]:
    """Coerce a naive datetime to tz-aware UTC.

    SQLite strips tzinfo on roundtrip — see memory note
    ``deepsynaps-sqlite-tz-naive.md``. All comparisons against
    ``datetime.now(timezone.utc)`` must coerce first.
    """
    if dt is None:
        return None
    return dt if dt.tzinfo is not None else dt.replace(tzinfo=timezone.utc)


def _iso(dt: Optional[datetime]) -> Optional[str]:
    aw = _aware(dt)
    return aw.isoformat() if aw is not None else None


def _patient_is_demo_hpt(db: Session, patient: Patient | None) -> bool:
    """Mirrors :func:`patients_router._patient_is_demo` for this surface."""
    if patient is None:
        return False
    notes = patient.notes or ""
    if notes.startswith("[DEMO]"):
        return True
    try:
        u = db.query(User).filter_by(id=patient.clinician_id).first()
        if u is None or not u.clinic_id:
            return False
        return u.clinic_id in {"clinic-demo-default", "clinic-cd-demo"}
    except Exception:
        return False


def _resolve_patient_for_actor_hpt(
    db: Session, actor: AuthenticatedActor
) -> Patient:
    """Return the Patient row the actor is allowed to act on.

    Patient role only. Cross-role hits return 404 (never 403/401) so the
    patient-scope URL existence is invisible to clinicians and admins.
    """
    if actor.role != "patient":
        raise ApiServiceError(
            code="not_found",
            message="Patient record not found.",
            status_code=404,
        )

    if actor.actor_id == _DEMO_PATIENT_ACTOR_ID:
        patient = (
            db.query(Patient)
            .filter(Patient.email.in_(list(_DEMO_PATIENT_EMAILS)))
            .first()
        )
    else:
        user = db.query(User).filter_by(id=actor.actor_id).first()
        if user is None or not user.email:
            raise ApiServiceError(
                code="not_found",
                message="Patient record not found.",
                status_code=404,
            )
        patient = db.query(Patient).filter(Patient.email == user.email).first()
    if patient is None:
        raise ApiServiceError(
            code="not_found",
            message="Patient record not found.",
            status_code=404,
        )
    return patient


def _consent_active_hpt(db: Session, patient: Patient) -> bool:
    """Same consent gate as adherence_events / patient_messages / wellness_hub."""
    has_withdrawn = (
        db.query(ConsentRecord)
        .filter(
            ConsentRecord.patient_id == patient.id,
            ConsentRecord.status == "withdrawn",
        )
        .first()
        is not None
    )
    if has_withdrawn:
        return False
    if patient.consent_signed:
        return True
    has_active = (
        db.query(ConsentRecord)
        .filter(
            ConsentRecord.patient_id == patient.id,
            ConsentRecord.status == "active",
        )
        .first()
        is not None
    )
    return has_active


def _assert_patient_consent_active(db: Session, patient: Patient) -> None:
    if not _consent_active_hpt(db, patient):
        raise ApiServiceError(
            code="consent_inactive",
            message=(
                "Starting a task or sending a help request requires "
                "active consent. Existing tasks remain readable until "
                "consent is reinstated."
            ),
            status_code=403,
        )


def _homework_audit(
    db: Session,
    actor: AuthenticatedActor,
    *,
    event: str,
    target_id: str,
    note: str = "",
    using_demo_data: bool = False,
    target_type: str = "home_program_tasks",
    role_override: Optional[str] = None,
    actor_override: Optional[str] = None,
) -> str:
    """Best-effort audit hook for the ``home_program_tasks`` surface.

    Never raises — audit must not block the UI even when the umbrella
    audit table is unreachable. Mirrors helpers in
    adherence_events_router / home_devices_patient_router /
    patient_messages_router / wellness_hub_router.
    """
    from app.repositories.audit import create_audit_event  # noqa: PLC0415

    now = datetime.now(timezone.utc)
    role = role_override or actor.role
    actor_id = actor_override or actor.actor_id
    event_id = (
        f"home_program_tasks-{event}-{actor_id}-{int(now.timestamp())}"
        f"-{uuid.uuid4().hex[:6]}"
    )
    note_parts: list[str] = []
    if using_demo_data:
        note_parts.append("DEMO")
    if note:
        note_parts.append(note[:500])
    final_note = "; ".join(note_parts) or event
    try:
        create_audit_event(
            db,
            event_id=event_id,
            target_id=str(target_id) or actor_id,
            target_type=target_type,
            action=f"home_program_tasks.{event}",
            role=role,
            actor_id=actor_id,
            note=final_note[:1024],
            created_at=now.isoformat(),
        )
    except Exception:  # pragma: no cover — audit must never block UI
        _log.exception("home_program_tasks self-audit skipped")
    return event_id


def _validate_external_task_id(task_id: str) -> None:
    if not _EXTERNAL_ID_RE.match(task_id or ""):
        raise ApiServiceError(
            code="not_found",
            message="Task not found.",
            status_code=404,
        )


def _resolve_task_or_404(
    db: Session, patient: Patient, task_id: str
) -> ClinicianHomeProgramTask:
    """Return the home program task owned by this patient, or 404.

    Cross-patient lookups return 404 even if the row exists — the
    existence of that row must not be observable.
    """
    _validate_external_task_id(task_id)
    row = session_get_task(db, task_id)
    if row is None or row.patient_id != patient.id:
        raise ApiServiceError(
            code="not_found",
            message="Task not found.",
            status_code=404,
        )
    return row


def session_get_task(db: Session, task_id: str) -> Optional[ClinicianHomeProgramTask]:
    return (
        db.query(ClinicianHomeProgramTask)
        .filter(ClinicianHomeProgramTask.id == task_id)
        .first()
    )


def _completion_for(
    db: Session, patient_id: str, server_task_id: str
) -> Optional[PatientHomeProgramTaskCompletion]:
    return (
        db.query(PatientHomeProgramTaskCompletion)
        .filter(
            PatientHomeProgramTaskCompletion.patient_id == patient_id,
            PatientHomeProgramTaskCompletion.server_task_id == server_task_id,
        )
        .order_by(PatientHomeProgramTaskCompletion.completed_at.desc())
        .first()
    )


def _safe_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    return {}


def _patient_safe_task_view(
    row: ClinicianHomeProgramTask,
    *,
    completion: Optional[PatientHomeProgramTaskCompletion] = None,
) -> dict[str, Any]:
    """Build a patient-safe projection for the task drawer / list.

    Strips clinician-only confidence tiers / scores. Surfaces only
    fields the patient should see: title, instructions, illustration,
    equipment, due_on, time_bucket, repeat, clinician-authored
    rationale ("why am I doing this?") and clinician-authored
    instructions / notes. NEVER returns AI-generated rationale —
    only fields the clinician explicitly authored or the catalog
    template provided.
    """
    task = load_task_dict(row.task_json)
    safe = {
        "id": row.id,
        "server_task_id": row.server_task_id,
        "patient_id": row.patient_id,
        "title": task.get("title") or task.get("name") or "Home program task",
        "category": task.get("category"),
        "task_type": task.get("task_type") or task.get("type"),
        "duration_min": task.get("duration_min") or task.get("durationMin"),
        "repeat": task.get("repeat") or task.get("repeat_pattern"),
        "due_on": task.get("due_on") or task.get("dueOn"),
        "due_by": task.get("due_by") or task.get("dueBy"),
        "time_bucket": task.get("time_bucket") or task.get("timeBucket"),
        "instructions": task.get("instructions") or task.get("description") or "",
        "illustration_url": task.get("illustration_url") or task.get("illustrationUrl"),
        "equipment": task.get("equipment") or [],
        "rationale": task.get("rationale") or task.get("why"),
        "rationale_author": task.get("rationale_author") or task.get("clinician_assigned_by"),
        "clinician_note": _safe_dict(task.get("clinician_note") or task.get("clinicianNote")),
        "assigned_at": _iso(row.created_at),
        "updated_at": _iso(row.updated_at),
        "started_at": None,
        "completed": False,
        "completed_at": None,
        "skipped": False,
        "rating": None,
        "difficulty": None,
        "feedback_text": None,
    }
    if completion is not None:
        safe["completed"] = bool(completion.completed)
        safe["completed_at"] = _iso(completion.completed_at)
        safe["rating"] = completion.rating
        safe["difficulty"] = completion.difficulty
        safe["feedback_text"] = completion.feedback_text
    # The "started_at" stamp lives on the task_json — if the patient
    # earlier hit /start, we mirrored a structured field there.
    started_at = task.get("patient_started_at")
    if isinstance(started_at, str):
        safe["started_at"] = started_at
    return safe


def _list_tasks_for_patient(
    db: Session, patient: Patient
) -> list[ClinicianHomeProgramTask]:
    return (
        db.query(ClinicianHomeProgramTask)
        .filter(ClinicianHomeProgramTask.patient_id == patient.id)
        .order_by(ClinicianHomeProgramTask.created_at.desc())
        .limit(500)
        .all()
    )


# ── Schemas ─────────────────────────────────────────────────────────────────


class PatientHomeworkTaskOut(BaseModel):
    id: str
    server_task_id: str
    patient_id: str
    title: str
    category: Optional[str] = None
    task_type: Optional[str] = None
    duration_min: Optional[int] = None
    repeat: Optional[str] = None
    due_on: Optional[str] = None
    due_by: Optional[str] = None
    time_bucket: Optional[str] = None
    instructions: Optional[str] = ""
    illustration_url: Optional[str] = None
    equipment: list = Field(default_factory=list)
    rationale: Optional[str] = None
    rationale_author: Optional[str] = None
    clinician_note: dict = Field(default_factory=dict)
    assigned_at: Optional[str] = None
    updated_at: Optional[str] = None
    started_at: Optional[str] = None
    completed: bool = False
    completed_at: Optional[str] = None
    skipped: bool = False
    rating: Optional[int] = None
    difficulty: Optional[int] = None
    feedback_text: Optional[str] = None


class HomeworkListResponse(BaseModel):
    items: list[PatientHomeworkTaskOut] = Field(default_factory=list)
    total: int = 0
    consent_active: bool = True
    is_demo: bool = False
    disclaimers: list[str] = Field(default_factory=lambda: list(HOMEWORK_DISCLAIMERS))


class HomeworkSummaryResponse(BaseModel):
    total_assigned: int = 0
    assigned_today: int = 0
    due_today: int = 0
    overdue: int = 0
    completed_today: int = 0
    completed_7d: int = 0
    completion_rate_7d: int = 0  # 0-100
    missed_streak_days: int = 0
    last_completed_at: Optional[str] = None
    consent_active: bool = True
    is_demo: bool = False
    disclaimers: list[str] = Field(default_factory=lambda: list(HOMEWORK_DISCLAIMERS))


class HomeworkStartIn(BaseModel):
    note: Optional[str] = Field(default=None, max_length=500)


class HomeworkStartOut(BaseModel):
    accepted: bool
    task_id: str
    started_at: str


class HomeworkHelpRequestIn(BaseModel):
    reason: str = Field(..., min_length=1, max_length=500)
    is_urgent: bool = False
    body: Optional[str] = Field(default=None, max_length=2000)

    @field_validator("reason")
    @classmethod
    def _strip_reason(cls, v: str) -> str:
        v = (v or "").strip()
        if not v:
            raise ValueError("help-request reason cannot be blank")
        return v


class HomeworkHelpRequestOut(BaseModel):
    accepted: bool
    task_id: str
    thread_id: str
    message_id: str
    is_urgent: bool


class HomeworkAuditEventIn(BaseModel):
    event: str = Field(..., min_length=1, max_length=64)
    task_id: Optional[str] = Field(default=None, max_length=96)
    note: Optional[str] = Field(default=None, max_length=512)
    using_demo_data: Optional[bool] = False


class HomeworkAuditEventOut(BaseModel):
    accepted: bool
    event_id: str


# ── Endpoints ───────────────────────────────────────────────────────────────


@router.get("/today", response_model=HomeworkListResponse)
def list_today(
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkListResponse:
    """List the patient's tasks due today (not yet completed)."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)
    today_str = datetime.now(timezone.utc).date().isoformat()

    rows = _list_tasks_for_patient(db, patient)
    items: list[PatientHomeworkTaskOut] = []
    for row in rows:
        task = load_task_dict(row.task_json)
        due = (task.get("due_on") or task.get("dueOn") or "")[:10]
        if due != today_str:
            continue
        completion = _completion_for(db, patient.id, row.server_task_id)
        if completion is not None and bool(completion.completed):
            continue
        items.append(
            PatientHomeworkTaskOut(**_patient_safe_task_view(row, completion=completion))
        )

    _homework_audit(
        db,
        actor,
        event="today_viewed",
        target_id=patient.id,
        note=f"items={len(items)}",
        using_demo_data=is_demo,
    )

    return HomeworkListResponse(
        items=items,
        total=len(items),
        consent_active=_consent_active_hpt(db, patient),
        is_demo=is_demo,
    )


@router.get("/upcoming", response_model=HomeworkListResponse)
def list_upcoming(
    days: int = Query(default=7, ge=1, le=30),
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkListResponse:
    """List the patient's tasks due in the next N days (excludes today)."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)
    today = datetime.now(timezone.utc).date()
    horizon = today + timedelta(days=days)

    rows = _list_tasks_for_patient(db, patient)
    items: list[PatientHomeworkTaskOut] = []
    for row in rows:
        task = load_task_dict(row.task_json)
        due_str = (task.get("due_on") or task.get("dueOn") or "")[:10]
        if not _DATE_RE.match(due_str):
            continue
        try:
            due_date = date.fromisoformat(due_str)
        except ValueError:
            continue
        if due_date <= today or due_date > horizon:
            continue
        completion = _completion_for(db, patient.id, row.server_task_id)
        items.append(
            PatientHomeworkTaskOut(**_patient_safe_task_view(row, completion=completion))
        )

    _homework_audit(
        db,
        actor,
        event="upcoming_viewed",
        target_id=patient.id,
        note=f"items={len(items)} days={days}",
        using_demo_data=is_demo,
    )

    return HomeworkListResponse(
        items=items,
        total=len(items),
        consent_active=_consent_active_hpt(db, patient),
        is_demo=is_demo,
    )


@router.get("/completed", response_model=HomeworkListResponse)
def list_completed(
    since: Optional[str] = Query(default=None, max_length=10),
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkListResponse:
    """List the patient's completed tasks (newest first; max 200)."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)

    completions_q = (
        db.query(PatientHomeProgramTaskCompletion)
        .filter(
            PatientHomeProgramTaskCompletion.patient_id == patient.id,
            PatientHomeProgramTaskCompletion.completed.is_(True),
        )
        .order_by(PatientHomeProgramTaskCompletion.completed_at.desc())
        .limit(200)
    )
    if since and _DATE_RE.match(since):
        try:
            since_dt = datetime.fromisoformat(f"{since}T00:00:00+00:00")
            completions_q = completions_q.filter(
                PatientHomeProgramTaskCompletion.completed_at >= since_dt
            )
        except ValueError:
            pass

    completions = completions_q.all()
    items: list[PatientHomeworkTaskOut] = []
    for c in completions:
        row = (
            db.query(ClinicianHomeProgramTask)
            .filter(ClinicianHomeProgramTask.server_task_id == c.server_task_id)
            .first()
        )
        if row is None or row.patient_id != patient.id:
            continue
        items.append(
            PatientHomeworkTaskOut(**_patient_safe_task_view(row, completion=c))
        )

    _homework_audit(
        db,
        actor,
        event="completed_viewed",
        target_id=patient.id,
        note=f"items={len(items)} since={since or '-'}",
        using_demo_data=is_demo,
    )

    return HomeworkListResponse(
        items=items,
        total=len(items),
        consent_active=_consent_active_hpt(db, patient),
        is_demo=is_demo,
    )


@router.get("/summary", response_model=HomeworkSummaryResponse)
def get_summary(
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkSummaryResponse:
    """Top counts: assigned-today, due-today, overdue, completion_rate_7d, missed_streak."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)

    rows = _list_tasks_for_patient(db, patient)
    now = datetime.now(timezone.utc)
    today = now.date()
    today_str = today.isoformat()
    week_cutoff = now - timedelta(days=7)

    # Build a quick set of completed server_task_ids to avoid N queries.
    completion_rows = (
        db.query(PatientHomeProgramTaskCompletion)
        .filter(
            PatientHomeProgramTaskCompletion.patient_id == patient.id,
            PatientHomeProgramTaskCompletion.completed.is_(True),
        )
        .all()
    )
    completed_by_server_id: dict[str, PatientHomeProgramTaskCompletion] = {}
    for c in completion_rows:
        existing = completed_by_server_id.get(c.server_task_id)
        if existing is None or _aware(c.completed_at) > _aware(existing.completed_at):  # type: ignore[operator]
            completed_by_server_id[c.server_task_id] = c

    assigned_today = 0
    due_today = 0
    overdue = 0
    completed_today = 0
    completed_7d = 0

    for row in rows:
        created = _aware(row.created_at)
        if created is not None and created.date() == today:
            assigned_today += 1
        task = load_task_dict(row.task_json)
        due_str = (task.get("due_on") or task.get("dueOn") or "")[:10]
        completion = completed_by_server_id.get(row.server_task_id)
        if completion is None and _DATE_RE.match(due_str):
            try:
                due_date = date.fromisoformat(due_str)
            except ValueError:
                due_date = None
            if due_date == today:
                due_today += 1
            elif due_date is not None and due_date < today:
                overdue += 1
        if completion is not None:
            completed_at_aw = _aware(completion.completed_at)
            if completed_at_aw is not None:
                if completed_at_aw.date() == today:
                    completed_today += 1
                if completed_at_aw >= week_cutoff:
                    completed_7d += 1

    # Completion rate over last 7d:
    #   numerator   = completed in last 7d
    #   denominator = tasks with due_on in last 7d (cap completed_7d when no due dates)
    seven_days_ago = today - timedelta(days=7)
    due_in_7d = 0
    for row in rows:
        task = load_task_dict(row.task_json)
        due_str = (task.get("due_on") or task.get("dueOn") or "")[:10]
        if not _DATE_RE.match(due_str):
            continue
        try:
            due_date = date.fromisoformat(due_str)
        except ValueError:
            continue
        if seven_days_ago <= due_date <= today:
            due_in_7d += 1
    if due_in_7d == 0:
        completion_rate_7d = 100 if completed_7d > 0 else 0
    else:
        completion_rate_7d = min(100, int(round(completed_7d * 100 / due_in_7d)))

    # Missed streak: count days back from yesterday with at least one
    # task due that wasn't completed.
    days_with_complete: set[str] = set()
    for c in completion_rows:
        completed_at_aw = _aware(c.completed_at)
        if completed_at_aw is not None:
            days_with_complete.add(completed_at_aw.date().isoformat())
    days_with_due: dict[str, int] = {}
    for row in rows:
        task = load_task_dict(row.task_json)
        due_str = (task.get("due_on") or task.get("dueOn") or "")[:10]
        if _DATE_RE.match(due_str):
            days_with_due[due_str] = days_with_due.get(due_str, 0) + 1

    missed_streak = 0
    cursor = today
    safety = 0
    while safety < 365:
        cursor_iso = cursor.isoformat()
        if cursor_iso in days_with_complete:
            break
        if days_with_due.get(cursor_iso, 0) > 0:
            missed_streak += 1
        else:
            # No tasks were due that day; not a "missed" day. Stop the
            # streak rather than over-counting.
            if missed_streak > 0:
                break
        cursor = cursor - timedelta(days=1)
        safety += 1

    last_completed_at = None
    if completion_rows:
        latest = max(completion_rows, key=lambda c: _aware(c.completed_at) or datetime.min.replace(tzinfo=timezone.utc))
        last_completed_at = _iso(latest.completed_at)

    _homework_audit(
        db,
        actor,
        event="summary_viewed",
        target_id=patient.id,
        note=(
            f"assigned_today={assigned_today} due_today={due_today} "
            f"overdue={overdue} completed_today={completed_today} "
            f"completed_7d={completed_7d} rate_7d={completion_rate_7d} "
            f"missed_streak={missed_streak}"
        ),
        using_demo_data=is_demo,
    )

    return HomeworkSummaryResponse(
        total_assigned=len(rows),
        assigned_today=assigned_today,
        due_today=due_today,
        overdue=overdue,
        completed_today=completed_today,
        completed_7d=completed_7d,
        completion_rate_7d=completion_rate_7d,
        missed_streak_days=missed_streak,
        last_completed_at=last_completed_at,
        consent_active=_consent_active_hpt(db, patient),
        is_demo=is_demo,
    )


@router.get("/export.csv")
def export_csv(
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> Response:
    """CSV export of every homework task for this patient."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)
    rows = _list_tasks_for_patient(db, patient)

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "task_id", "server_task_id", "title", "category", "task_type",
        "due_on", "repeat", "completed", "completed_at", "assigned_at",
    ])
    for row in rows:
        completion = _completion_for(db, patient.id, row.server_task_id)
        view = _patient_safe_task_view(row, completion=completion)
        writer.writerow([
            view["id"], view["server_task_id"], view["title"],
            view.get("category") or "", view.get("task_type") or "",
            view.get("due_on") or "", view.get("repeat") or "",
            "1" if view.get("completed") else "0",
            view.get("completed_at") or "",
            view.get("assigned_at") or "",
        ])

    prefix = "DEMO-" if is_demo else ""
    filename = f"{prefix}home-program-tasks-{patient.id}.csv"

    _homework_audit(
        db,
        actor,
        event="export",
        target_id=patient.id,
        note=f"format=csv; rows={len(rows)}; demo={1 if is_demo else 0}",
        using_demo_data=is_demo,
    )

    return Response(
        content=buf.getvalue(),
        media_type="text/csv",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-HomeProgramTasks-Demo": "1" if is_demo else "0",
        },
    )


@router.get("/export.ndjson")
def export_ndjson(
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> Response:
    """NDJSON export — one task per line."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)
    rows = _list_tasks_for_patient(db, patient)

    lines: list[str] = []
    for row in rows:
        completion = _completion_for(db, patient.id, row.server_task_id)
        view = _patient_safe_task_view(row, completion=completion)
        view["is_demo"] = bool(is_demo)
        lines.append(json.dumps(view))

    prefix = "DEMO-" if is_demo else ""
    filename = f"{prefix}home-program-tasks-{patient.id}.ndjson"

    _homework_audit(
        db,
        actor,
        event="export",
        target_id=patient.id,
        note=f"format=ndjson; rows={len(rows)}; demo={1 if is_demo else 0}",
        using_demo_data=is_demo,
    )

    return Response(
        content="\n".join(lines) + ("\n" if lines else ""),
        media_type="application/x-ndjson",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-HomeProgramTasks-Demo": "1" if is_demo else "0",
        },
    )


@router.post("/audit-events", response_model=HomeworkAuditEventOut)
def post_homework_audit_event(
    body: HomeworkAuditEventIn,
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkAuditEventOut:
    """Page-level audit ingestion for the patient Homework UI.

    Surface: ``home_program_tasks``. Common events: ``view`` (mount),
    ``filter_changed``, ``task_viewed``, ``task_started``,
    ``task_completed_via_adherence``, ``task_skipped_via_adherence``,
    ``task_help_requested``, ``export``, ``deep_link_followed``,
    ``demo_banner_shown``, ``consent_banner_shown``.

    Patient role only — clinicians cannot emit ``home_program_tasks``
    audit rows directly. Cross-patient ingestion is blocked because
    ``task_id`` (when supplied) is verified to belong to the actor's
    patient.
    """
    if actor.role != "patient":
        raise ApiServiceError(
            code="patient_role_required",
            message=(
                "Home Program Tasks audit ingestion is restricted to "
                "the patient role."
            ),
            status_code=403,
        )
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)

    target_id: str = patient.id
    if body.task_id:
        any_row = (
            db.query(ClinicianHomeProgramTask)
            .filter(ClinicianHomeProgramTask.id == body.task_id)
            .first()
        )
        if any_row is not None and any_row.patient_id != patient.id:
            raise ApiServiceError(
                code="not_found",
                message="Task not found.",
                status_code=404,
            )
        target_id = body.task_id

    note_parts: list[str] = []
    if body.task_id:
        note_parts.append(f"task={body.task_id}")
    if body.note:
        note_parts.append(body.note[:480])
    note = "; ".join(note_parts) or body.event

    event_id = _homework_audit(
        db,
        actor,
        event=body.event,
        target_id=target_id,
        note=note,
        using_demo_data=bool(body.using_demo_data) or is_demo,
    )
    return HomeworkAuditEventOut(accepted=True, event_id=event_id)


@router.get("/{task_id}", response_model=PatientHomeworkTaskOut)
def get_task(
    task_id: str = Path(..., min_length=1, max_length=96),
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> PatientHomeworkTaskOut:
    """Return one task the patient owns. 404 cross-patient."""
    patient = _resolve_patient_for_actor_hpt(db, actor)
    is_demo = _patient_is_demo_hpt(db, patient)
    row = _resolve_task_or_404(db, patient, task_id)
    completion = _completion_for(db, patient.id, row.server_task_id)

    _homework_audit(
        db,
        actor,
        event="task_viewed",
        target_id=row.id,
        note=f"server_task_id={row.server_task_id}",
        using_demo_data=is_demo,
    )
    return PatientHomeworkTaskOut(
        **_patient_safe_task_view(row, completion=completion)
    )


@router.post("/{task_id}/start", response_model=HomeworkStartOut)
def start_task(
    body: HomeworkStartIn = HomeworkStartIn(),
    task_id: str = Path(..., min_length=1, max_length=96),
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkStartOut:
    """Mark a task as started by the patient. Audit-only — no completion
    log here. The patient still has to log the actual completion via
    ``POST /api/v1/adherence/events`` (Adherence Events #350).

    Mutates ``task_json.patient_started_at`` so the clinician detail
    view can show "patient started this task at ...". Emits both a
    patient-side and clinician-visible mirror audit row.
    """
    patient = _resolve_patient_for_actor_hpt(db, actor)
    _assert_patient_consent_active(db, patient)
    is_demo = _patient_is_demo_hpt(db, patient)
    row = _resolve_task_or_404(db, patient, task_id)

    now = datetime.now(timezone.utc)
    task = load_task_dict(row.task_json)
    task["patient_started_at"] = now.isoformat()
    row.task_json = json.dumps(task, separators=(",", ":"), ensure_ascii=False)
    row.updated_at = now
    db.commit()

    _homework_audit(
        db,
        actor,
        event="task_started",
        target_id=row.id,
        note=(body.note or "")[:200],
        using_demo_data=is_demo,
    )
    # Clinician-visible mirror so the care-team feed shows the start
    # without the patient having to formally escalate.
    clinician_actor = patient.clinician_id or "actor-clinician-demo"
    _homework_audit(
        db,
        actor,
        event="task_started_to_clinician",
        target_id=clinician_actor,
        note=f"task={row.id}; server_task_id={row.server_task_id}",
        using_demo_data=is_demo,
        role_override="clinician",
        actor_override=clinician_actor,
    )

    return HomeworkStartOut(
        accepted=True, task_id=row.id, started_at=now.isoformat()
    )


@router.post(
    "/{task_id}/help-request",
    response_model=HomeworkHelpRequestOut,
    status_code=201,
)
def help_request(
    body: HomeworkHelpRequestIn,
    task_id: str = Path(..., min_length=1, max_length=96),
    actor: AuthenticatedActor = Depends(get_authenticated_actor),
    db: Session = Depends(get_db_session),
) -> HomeworkHelpRequestOut:
    """Open a Patient Messages thread linked to this task.

    The thread is created with ``thread_id = "task-{task_id}"`` so the
    patient inbox can deep-link straight to the help-request thread
    (mirror of the report-question pattern from #346/#347). Creates a
    ``Message`` row whose ``patient_id`` is the patient and whose
    ``recipient_id`` is the clinician. If ``is_urgent`` is set, the
    ``priority`` column is ``urgent`` and a HIGH-priority
    clinician-visible audit row is emitted.
    """
    patient = _resolve_patient_for_actor_hpt(db, actor)
    _assert_patient_consent_active(db, patient)
    is_demo = _patient_is_demo_hpt(db, patient)
    row = _resolve_task_or_404(db, patient, task_id)

    recipient = patient.clinician_id or "actor-clinician-demo"
    thread_id = f"task-{row.id}"
    msg_id = str(uuid.uuid4())
    task = load_task_dict(row.task_json)
    title_text = (
        task.get("title") or task.get("name") or "home program task"
    )
    subject = f"Help with: {str(title_text)[:120]}"
    full_body_parts = [body.reason.strip()]
    if body.body:
        full_body_parts.append(body.body.strip())
    full_body = "\n\n".join(full_body_parts)[:4000]

    msg = Message(
        id=msg_id,
        sender_id=actor.actor_id,
        recipient_id=recipient,
        patient_id=patient.id,
        body=full_body,
        subject=subject[:255],
        category="task-help",
        thread_id=thread_id,
        priority=("urgent" if body.is_urgent else "normal"),
        created_at=datetime.now(timezone.utc),
    )
    db.add(msg)
    db.commit()

    _homework_audit(
        db,
        actor,
        event="task_help_requested",
        target_id=row.id,
        note=(
            f"thread={thread_id}; recipient={recipient}; "
            f"chars={len(body.reason)}; urgent={1 if body.is_urgent else 0}"
        ),
        using_demo_data=is_demo,
    )
    if body.is_urgent:
        _homework_audit(
            db,
            actor,
            event="task_help_urgent_to_clinician",
            target_id=recipient,
            note=(
                f"priority=high; thread={thread_id}; task={row.id}"
            ),
            using_demo_data=is_demo,
            role_override="clinician",
            actor_override=recipient,
        )

    return HomeworkHelpRequestOut(
        accepted=True,
        task_id=row.id,
        thread_id=thread_id,
        message_id=msg_id,
        is_urgent=bool(body.is_urgent),
    )
