"""Preferences router — /api/v1/preferences.

Two concerns living behind a single prefix:

1. Per-user UI + notification preferences (``user_preferences`` table):
   language, date/time format, units, notification matrix (channel x event),
   quiet hours, digest cadence, reminder timing, auto-logout, telemetry opt-ins.

2. Per-clinic clinical defaults (``clinic_defaults`` table): default protocol,
   session duration, follow-up cadence, course length, consent template,
   disclaimer, default assessment battery, AE handling protocol.

Endpoints:
  GET   /api/v1/preferences                     -> UserPreferencesResponse
  PATCH /api/v1/preferences                     -> UserPreferencesResponse
  GET   /api/v1/preferences/clinical-defaults   -> ClinicDefaultsResponse
  PATCH /api/v1/preferences/clinical-defaults   -> ClinicDefaultsResponse  (admin)

PATCH semantics: partial update. For JSON-typed columns
(``notification_prefs``, ``quiet_hours``, ``reminder_timing``,
``default_assessments``) the whole blob is replaced when the body provides a
value (no deep-merge in v0 — too error-prone for nested matrices).

See apps/api/SETTINGS_API_DESIGN.md - Preferences router for the full spec.
"""
import json
import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from ..database import get_db_session
from ..errors import ApiServiceError
from ..limiter import limiter
from ..persistence.models import ClinicDefaults, User, UserPreferences
from ..services import auth_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/preferences", tags=["preferences"])


# ── Constants / defaults ──────────────────────────────────────────────────────

# Full channel x event matrix for notifications. Mirrors the web Settings UI
# (apps/web/src/pages-practice.js). Channels: email / inapp / telegram.
DEFAULT_NOTIFICATION_PREFS: dict = {
    "sessionReminders":  {"email": True,  "inapp": True,  "telegram": False},
    "protocolAlerts":    {"email": False, "inapp": True,  "telegram": False},
    "aeAlerts":          {"email": True,  "inapp": True,  "telegram": True},
    "reviewQueueDigest": {"email": False, "inapp": True,  "telegram": False},
    "weeklySummary":     {"email": True,  "inapp": False, "telegram": False},
    "patientMessages":   {"email": False, "inapp": True,  "telegram": False},
    "systemUpdates":     {"email": False, "inapp": True,  "telegram": False},
}
DEFAULT_QUIET_HOURS: dict = {"enabled": False, "from": "22:00", "to": "07:00"}
DEFAULT_REMINDER_TIMING: list[str] = ["24h", "2h"]

DEFAULT_ASSESSMENTS: list[str] = ["PHQ-9", "GAD-7"]
DEFAULT_DISCLAIMER: str = (
    "This report is generated by DeepSynaps Protocol Studio based on current "
    "evidence and clinical guidelines. It is intended as clinical decision "
    "support only; final treatment decisions remain the clinician's "
    "responsibility."
)

# Enum-ish validation sets. Kept here (rather than imported from the frontend)
# so the backend can evolve independently; frontend LOCALES must mirror this.
_ALLOWED_LANGUAGES = {"en", "tr", "es", "fr", "de", "pt"}
_ALLOWED_DIGEST_FREQS = {"daily", "weekly", "off"}
_ALLOWED_TIME_FORMATS = {"12h", "24h"}
_ALLOWED_FIRST_DAYS = {"monday", "sunday"}
_ALLOWED_UNITS = {"metric", "imperial"}
_ALLOWED_DATE_FORMATS = {"ISO", "US", "EU"}
_ALLOWED_NUMBER_FORMATS = {"US", "EU", "FR"}
_ALLOWED_AUTO_LOGOUT_MIN = {0, 15, 30, 60, 240}
_ALLOWED_AE_PROTOCOLS = {"auto-notify", "log-only", "auto-pause"}

_SESSION_DURATION_MIN = 5
_SESSION_DURATION_MAX = 240
_COURSE_LENGTH_MIN = 1
_COURSE_LENGTH_MAX = 100
_FOLLOWUP_WEEKS_MIN = 0
_FOLLOWUP_WEEKS_MAX = 52


# ── Pydantic models ───────────────────────────────────────────────────────────


class UserPreferencesResponse(BaseModel):
    user_id: str
    notification_prefs: dict
    quiet_hours: dict
    digest_freq: str
    reminder_timing: list[str]
    language: str
    date_format: str
    time_format: str
    first_day: str
    units: str
    number_format: str
    session_default_duration_min: int
    auto_logout_min: int
    analytics_opt_in: bool
    error_reports_opt_in: bool
    updated_at: str


class UserPreferencesPatchRequest(BaseModel):
    notification_prefs: Optional[dict] = None
    quiet_hours: Optional[dict] = None
    digest_freq: Optional[str] = None
    reminder_timing: Optional[list[str]] = None
    language: Optional[str] = None
    date_format: Optional[str] = None
    time_format: Optional[str] = None
    first_day: Optional[str] = None
    units: Optional[str] = None
    number_format: Optional[str] = None
    session_default_duration_min: Optional[int] = None
    auto_logout_min: Optional[int] = None
    analytics_opt_in: Optional[bool] = None
    error_reports_opt_in: Optional[bool] = None


class ClinicDefaultsResponse(BaseModel):
    clinic_id: Optional[str] = None
    default_protocol_id: Optional[str] = None
    default_session_duration_min: int = 45
    default_followup_weeks: int = 4
    default_course_length: int = 20
    default_consent_template_id: Optional[str] = None
    custom_consent_text: Optional[str] = None
    default_disclaimer: Optional[str] = None
    default_assessments: list[str] = Field(default_factory=lambda: list(DEFAULT_ASSESSMENTS))
    ae_protocol: str = "auto-notify"
    updated_at: Optional[str] = None


class ClinicDefaultsPatchRequest(BaseModel):
    default_protocol_id: Optional[str] = None
    default_session_duration_min: Optional[int] = None
    default_followup_weeks: Optional[int] = None
    default_course_length: Optional[int] = None
    default_consent_template_id: Optional[str] = None
    custom_consent_text: Optional[str] = None
    default_disclaimer: Optional[str] = None
    default_assessments: Optional[list[str]] = None
    ae_protocol: Optional[str] = None


# ── Helpers ───────────────────────────────────────────────────────────────────


def _iso(dt: datetime | None) -> str:
    if dt is None:
        return ""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.isoformat().replace("+00:00", "Z")


def _load_json(raw: str | None, fallback):
    """Safe JSON load with a sensible fallback. Columns are ``Text`` — they
    may hold ``None``, an empty string, or malformed JSON in legacy rows.
    """
    if not raw:
        return fallback
    try:
        value = json.loads(raw)
    except (TypeError, ValueError):
        logger.warning("Malformed JSON pref column, using fallback", exc_info=True)
        return fallback
    return value


def _dump_json(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def _get_or_create_user_prefs(db: Session, user_id: str) -> UserPreferences:
    """Load the single ``UserPreferences`` row for this user, creating it with
    documented defaults on first access. First GET is always idempotent.
    """
    row = db.get(UserPreferences, user_id)
    if row is not None:
        return row
    row = UserPreferences(
        user_id=user_id,
        notification_prefs=_dump_json(DEFAULT_NOTIFICATION_PREFS),
        quiet_hours=_dump_json(DEFAULT_QUIET_HOURS),
        reminder_timing=_dump_json(DEFAULT_REMINDER_TIMING),
        # Scalar columns rely on SQLAlchemy column defaults:
        # digest_freq='daily', language='en', date_format='ISO',
        # time_format='24h', first_day='monday', units='metric',
        # number_format='US', session_default_duration_min=45,
        # auto_logout_min=30, analytics_opt_in=True, error_reports_opt_in=True.
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def _get_or_create_clinic_defaults(db: Session, clinic_id: str) -> ClinicDefaults:
    """Load the ClinicDefaults row for this clinic, creating it with
    documented defaults on first access.
    """
    row = db.get(ClinicDefaults, clinic_id)
    if row is not None:
        return row
    row = ClinicDefaults(
        clinic_id=clinic_id,
        default_session_duration_min=45,
        default_followup_weeks=4,
        default_course_length=20,
        default_assessments=_dump_json(DEFAULT_ASSESSMENTS),
        ae_protocol="auto-notify",
        default_disclaimer=DEFAULT_DISCLAIMER,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def _prefs_to_response(row: UserPreferences) -> UserPreferencesResponse:
    return UserPreferencesResponse(
        user_id=row.user_id,
        notification_prefs=_load_json(row.notification_prefs, DEFAULT_NOTIFICATION_PREFS),
        quiet_hours=_load_json(row.quiet_hours, DEFAULT_QUIET_HOURS),
        digest_freq=row.digest_freq or "daily",
        reminder_timing=_load_json(row.reminder_timing, DEFAULT_REMINDER_TIMING),
        language=row.language or "en",
        date_format=row.date_format or "ISO",
        time_format=row.time_format or "24h",
        first_day=row.first_day or "monday",
        units=row.units or "metric",
        number_format=row.number_format or "US",
        session_default_duration_min=row.session_default_duration_min or 45,
        auto_logout_min=row.auto_logout_min if row.auto_logout_min is not None else 30,
        analytics_opt_in=bool(row.analytics_opt_in),
        error_reports_opt_in=bool(row.error_reports_opt_in),
        updated_at=_iso(row.updated_at),
    )


def _defaults_to_response(row: ClinicDefaults) -> ClinicDefaultsResponse:
    return ClinicDefaultsResponse(
        clinic_id=row.clinic_id,
        default_protocol_id=row.default_protocol_id,
        default_session_duration_min=row.default_session_duration_min or 45,
        default_followup_weeks=row.default_followup_weeks if row.default_followup_weeks is not None else 4,
        default_course_length=row.default_course_length or 20,
        default_consent_template_id=row.default_consent_template_id,
        custom_consent_text=row.custom_consent_text,
        default_disclaimer=row.default_disclaimer,
        default_assessments=_load_json(row.default_assessments, list(DEFAULT_ASSESSMENTS)),
        ae_protocol=row.ae_protocol or "auto-notify",
        updated_at=_iso(row.updated_at),
    )


def _synthetic_clinic_defaults() -> ClinicDefaultsResponse:
    """Return a sensible default payload for users without a clinic, so the
    frontend can still render the Clinical Defaults card. ``clinic_id`` is
    None so the UI knows PATCH is unavailable."""
    return ClinicDefaultsResponse(
        clinic_id=None,
        default_protocol_id=None,
        default_session_duration_min=45,
        default_followup_weeks=4,
        default_course_length=20,
        default_consent_template_id=None,
        custom_consent_text=None,
        default_disclaimer=DEFAULT_DISCLAIMER,
        default_assessments=list(DEFAULT_ASSESSMENTS),
        ae_protocol="auto-notify",
        updated_at=None,
    )


# ── Validation ────────────────────────────────────────────────────────────────


def _invalid(code: str, message: str) -> ApiServiceError:
    return ApiServiceError(code=code, message=message, status_code=400)


def _validate_user_prefs_patch(body: UserPreferencesPatchRequest) -> None:
    if body.digest_freq is not None and body.digest_freq not in _ALLOWED_DIGEST_FREQS:
        raise _invalid(
            "invalid_digest_freq",
            "digest_freq must be one of: daily, weekly, off.",
        )
    if body.time_format is not None and body.time_format not in _ALLOWED_TIME_FORMATS:
        raise _invalid("invalid_time_format", "time_format must be one of: 12h, 24h.")
    if body.first_day is not None and body.first_day not in _ALLOWED_FIRST_DAYS:
        raise _invalid("invalid_first_day", "first_day must be one of: monday, sunday.")
    if body.units is not None and body.units not in _ALLOWED_UNITS:
        raise _invalid("invalid_units", "units must be one of: metric, imperial.")
    if body.date_format is not None and body.date_format not in _ALLOWED_DATE_FORMATS:
        raise _invalid("invalid_date_format", "date_format must be one of: ISO, US, EU.")
    if body.number_format is not None and body.number_format not in _ALLOWED_NUMBER_FORMATS:
        raise _invalid(
            "invalid_number_format",
            "number_format must be one of: US, EU, FR.",
        )
    if body.language is not None and body.language not in _ALLOWED_LANGUAGES:
        raise _invalid(
            "invalid_language",
            "language must be one of: en, tr, es, fr, de, pt.",
        )
    if body.auto_logout_min is not None and body.auto_logout_min not in _ALLOWED_AUTO_LOGOUT_MIN:
        raise _invalid(
            "invalid_auto_logout_min",
            "auto_logout_min must be one of: 0, 15, 30, 60, 240.",
        )
    if body.session_default_duration_min is not None and not (
        _SESSION_DURATION_MIN <= body.session_default_duration_min <= _SESSION_DURATION_MAX
    ):
        raise _invalid(
            "invalid_session_default_duration_min",
            f"session_default_duration_min must be between {_SESSION_DURATION_MIN} and {_SESSION_DURATION_MAX}.",
        )
    if body.reminder_timing is not None and not isinstance(body.reminder_timing, list):
        raise _invalid("invalid_reminder_timing", "reminder_timing must be a list of strings.")
    if body.reminder_timing is not None:
        for entry in body.reminder_timing:
            if not isinstance(entry, str):
                raise _invalid(
                    "invalid_reminder_timing",
                    "reminder_timing must contain strings only (e.g. '24h', '2h').",
                )
    if body.notification_prefs is not None and not isinstance(body.notification_prefs, dict):
        raise _invalid(
            "invalid_notification_prefs",
            "notification_prefs must be an object mapping event -> channel matrix.",
        )
    if body.quiet_hours is not None and not isinstance(body.quiet_hours, dict):
        raise _invalid(
            "invalid_quiet_hours",
            "quiet_hours must be an object {enabled, from, to}.",
        )


def _validate_clinic_defaults_patch(body: ClinicDefaultsPatchRequest) -> None:
    if body.ae_protocol is not None and body.ae_protocol not in _ALLOWED_AE_PROTOCOLS:
        raise _invalid(
            "invalid_ae_protocol",
            "ae_protocol must be one of: auto-notify, log-only, auto-pause.",
        )
    if body.default_session_duration_min is not None and not (
        _SESSION_DURATION_MIN <= body.default_session_duration_min <= _SESSION_DURATION_MAX
    ):
        raise _invalid(
            "invalid_default_session_duration_min",
            f"default_session_duration_min must be between {_SESSION_DURATION_MIN} and {_SESSION_DURATION_MAX}.",
        )
    if body.default_course_length is not None and not (
        _COURSE_LENGTH_MIN <= body.default_course_length <= _COURSE_LENGTH_MAX
    ):
        raise _invalid(
            "invalid_default_course_length",
            f"default_course_length must be between {_COURSE_LENGTH_MIN} and {_COURSE_LENGTH_MAX}.",
        )
    if body.default_followup_weeks is not None and not (
        _FOLLOWUP_WEEKS_MIN <= body.default_followup_weeks <= _FOLLOWUP_WEEKS_MAX
    ):
        raise _invalid(
            "invalid_default_followup_weeks",
            f"default_followup_weeks must be between {_FOLLOWUP_WEEKS_MIN} and {_FOLLOWUP_WEEKS_MAX}.",
        )
    if body.default_assessments is not None:
        if not isinstance(body.default_assessments, list):
            raise _invalid(
                "invalid_default_assessments",
                "default_assessments must be a list of assessment IDs.",
            )
        for entry in body.default_assessments:
            if not isinstance(entry, str):
                raise _invalid(
                    "invalid_default_assessments",
                    "default_assessments must contain strings only.",
                )


# ── User preferences endpoints ────────────────────────────────────────────────


@router.get("", response_model=UserPreferencesResponse)
@router.get("/", response_model=UserPreferencesResponse, include_in_schema=False)
def get_preferences(
    user: User = Depends(auth_service.current_user),
    db: Session = Depends(get_db_session),
) -> UserPreferencesResponse:
    """Return the caller's UserPreferences row, creating defaults on first read."""
    row = _get_or_create_user_prefs(db, user.id)
    return _prefs_to_response(row)


@router.patch("", response_model=UserPreferencesResponse)
@router.patch("/", response_model=UserPreferencesResponse, include_in_schema=False)
@limiter.limit("30/minute")
def update_preferences(
    request: Request,
    body: UserPreferencesPatchRequest,
    user: User = Depends(auth_service.current_user),
    db: Session = Depends(get_db_session),
) -> UserPreferencesResponse:
    """Partial update. JSON columns are replaced whole; scalars update in place.

    Validation errors raise 400 before any DB write; the row is not mutated
    until every provided field passes validation.
    """
    _validate_user_prefs_patch(body)
    row = _get_or_create_user_prefs(db, user.id)

    if body.notification_prefs is not None:
        row.notification_prefs = _dump_json(body.notification_prefs)
    if body.quiet_hours is not None:
        row.quiet_hours = _dump_json(body.quiet_hours)
    if body.reminder_timing is not None:
        row.reminder_timing = _dump_json(body.reminder_timing)
    if body.digest_freq is not None:
        row.digest_freq = body.digest_freq
    if body.language is not None:
        row.language = body.language
    if body.date_format is not None:
        row.date_format = body.date_format
    if body.time_format is not None:
        row.time_format = body.time_format
    if body.first_day is not None:
        row.first_day = body.first_day
    if body.units is not None:
        row.units = body.units
    if body.number_format is not None:
        row.number_format = body.number_format
    if body.session_default_duration_min is not None:
        row.session_default_duration_min = body.session_default_duration_min
    if body.auto_logout_min is not None:
        row.auto_logout_min = body.auto_logout_min
    if body.analytics_opt_in is not None:
        row.analytics_opt_in = bool(body.analytics_opt_in)
    if body.error_reports_opt_in is not None:
        row.error_reports_opt_in = bool(body.error_reports_opt_in)

    db.commit()
    db.refresh(row)
    return _prefs_to_response(row)


# ── Clinical defaults endpoints ───────────────────────────────────────────────


@router.get("/clinical-defaults", response_model=ClinicDefaultsResponse)
def get_clinical_defaults(
    user: User = Depends(auth_service.current_user),
    db: Session = Depends(get_db_session),
) -> ClinicDefaultsResponse:
    """Return the caller's clinic defaults.

    * If the caller has a ``clinic_id`` the matching row is returned, creating
      it with documented defaults on first access.
    * If the caller has no clinic, return a synthesized default payload with
      ``clinic_id: null`` — 404 would be unfriendly; the frontend renders a
      read-only state and the PATCH endpoint simply gates via admin dep.
    """
    if not user.clinic_id:
        return _synthetic_clinic_defaults()
    row = _get_or_create_clinic_defaults(db, user.clinic_id)
    return _defaults_to_response(row)


@router.patch("/clinical-defaults", response_model=ClinicDefaultsResponse)
@limiter.limit("30/minute")
def update_clinical_defaults(
    request: Request,
    body: ClinicDefaultsPatchRequest,
    user: User = Depends(auth_service.current_clinic_admin),
    db: Session = Depends(get_db_session),
) -> ClinicDefaultsResponse:
    """Partial update of the caller's clinic defaults. Admin-only (dep raises
    403/404 if the caller is not an admin of a clinic).

    JSON columns (``default_assessments``) are replaced whole; scalars update
    in place. Validation runs before any DB write.
    """
    _validate_clinic_defaults_patch(body)
    # Dep guarantees user.clinic_id is truthy.
    row = _get_or_create_clinic_defaults(db, user.clinic_id)

    if body.default_protocol_id is not None:
        row.default_protocol_id = body.default_protocol_id or None
    if body.default_session_duration_min is not None:
        row.default_session_duration_min = body.default_session_duration_min
    if body.default_followup_weeks is not None:
        row.default_followup_weeks = body.default_followup_weeks
    if body.default_course_length is not None:
        row.default_course_length = body.default_course_length
    if body.default_consent_template_id is not None:
        row.default_consent_template_id = body.default_consent_template_id or None
    if body.custom_consent_text is not None:
        row.custom_consent_text = body.custom_consent_text or None
    if body.default_disclaimer is not None:
        row.default_disclaimer = body.default_disclaimer or None
    if body.default_assessments is not None:
        row.default_assessments = _dump_json(body.default_assessments)
    if body.ae_protocol is not None:
        row.ae_protocol = body.ae_protocol

    db.commit()
    db.refresh(row)
    return _defaults_to_response(row)
