from __future__ import annotations
"""Verify FDA product codes in indications_seed.MODALITY_PRODUCT_CODES
against openFDA's /device/classification.json.

Outputs a Markdown report at docs/fda-product-codes.md.

Run:
    python3 services/evidence-pipeline/scripts/verify_product_codes.py
"""
import json
import os
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve()
ROOT = HERE.parents[3]
PIPELINE = HERE.parents[1]
sys.path.insert(0, str(PIPELINE))
from indications_seed import MODALITY_PRODUCT_CODES  # noqa: E402

KEY = os.environ.get("OPENFDA_API_KEY", "")
REPORT = ROOT / "docs" / "fda-product-codes.md"


def lookup(code: str) -> dict | None:
    url = (
        "https://api.fda.gov/device/classification.json?"
        f"search=product_code:%22{code}%22&limit=1"
        + (f"&api_key={KEY}" if KEY else "")
    )
    try:
        with urllib.request.urlopen(url, timeout=15) as r:
            data = json.loads(r.read().decode())
        results = data.get("results") or []
        return results[0] if results else None
    except Exception as e:
        return {"_error": str(e)}


def modality_keywords(modality: str) -> list[str]:
    return {
        "DBS":   ["deep brain", "neurological stimulator", "cortical"],
        "RNS":   ["responsive", "cortical"],
        "VNS":   ["vagus", "vagal", "cranial"],
        "SCS":   ["spinal cord", "pain"],
        "DRG":   ["dorsal root", "ganglion"],
        "SNM":   ["sacral", "urinary", "fecal"],
        "HNS":   ["hypoglossal", "upper airway", "apnea"],
        "PNS":   ["phrenic", "peripheral nerve", "diaphragm"],
        "rTMS":  ["magnetic", "transcranial", "tms"],
        "dTMS":  ["magnetic", "transcranial", "tms"],
        "tDCS":  ["direct current", "transcranial"],
        "MRgFUS": ["ultrasound", "thalamic", "focused"],
        "BAT":   ["baroreflex", "carotid"],
        "REN":   ["electrical", "migraine", "neuromodulation"],
    }.get(modality, [])


def main() -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# FDA product-code verification",
        "",
        "Generated by `services/evidence-pipeline/scripts/verify_product_codes.py`.",
        "Each code in `indications_seed.MODALITY_PRODUCT_CODES` is looked up against",
        "openFDA's /device/classification.json endpoint. The `Match?` column is a",
        "shallow keyword check against the modality's expected vocabulary — a `?`",
        "means review manually.",
        "",
        "| Modality | Code | Device name (FDA) | Medical specialty | Class | Match? |",
        "|---|---|---|---|---|---|",
    ]
    for modality, codes in MODALITY_PRODUCT_CODES.items():
        kw = [k.lower() for k in modality_keywords(modality)]
        for code in codes:
            rec = lookup(code) or {}
            if "_error" in rec:
                lines.append(f"| {modality} | {code} | _lookup error: {rec['_error']}_ | — | — | ⚠ |")
                continue
            name = (rec.get("device_name") or "").strip()
            spec = (rec.get("medical_specialty_description") or "").strip()
            klass = rec.get("device_class")
            haystack = (name + " " + spec).lower()
            is_match = any(k in haystack for k in kw) if kw and haystack else None
            mark = "✓" if is_match else ("—" if is_match is False else "?")
            lines.append(f"| {modality} | {code} | {name or '(not found)'} | {spec} | {klass or ''} | {mark} |")
            time.sleep(0.2 if KEY else 0.5)  # be polite
    REPORT.write_text("\n".join(lines) + "\n")
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
