// assessments.js — Clinical assessment tools registry for neuromodulation practice
// DeepSynaps Protocol Studio

export const ASSESSMENTS = [

  // ── DEPRESSION ────────────────────────────────────────────────────────────

  {
    id: 'phq9',
    name: 'Patient Health Questionnaire-9',
    abbr: 'PHQ-9',
    conditions: ['MDD', 'TRD', 'Bipolar Depression', 'Postpartum Depression'],
    domains: ['Depression severity', 'Suicidality screening'],
    rater: 'self',
    items: 9,
    min_score: 0,
    max_score: 27,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 4],   label: 'Minimal',            color: 'var(--green)' },
      { range: [5, 9],   label: 'Mild',               color: 'var(--teal)' },
      { range: [10, 14], label: 'Moderate',           color: 'var(--amber)' },
      { range: [15, 19], label: 'Moderately Severe',  color: 'var(--orange, #f97316)' },
      { range: [20, 27], label: 'Severe',             color: 'var(--red)' },
    ],
    response_cutoff: 5,
    remission_cutoff: 5,
    frequency: 'weekly',
    open_access: true,
    references: ['Kroenke et al., 2001, JGIM'],
    notes: 'Primary outcome measure for MDD TMS trials. PHQ-9 ≥10 = moderate depression threshold commonly used for treatment eligibility.',
  },

  {
    id: 'phq2',
    name: 'Patient Health Questionnaire-2',
    abbr: 'PHQ-2',
    conditions: ['MDD', 'TRD', 'Screening'],
    domains: ['Depression screening'],
    rater: 'self',
    items: 2,
    min_score: 0,
    max_score: 6,
    admin_time_min: 1,
    scoring_bands: [
      { range: [0, 2], label: 'Screen Negative', color: 'var(--green)' },
      { range: [3, 6], label: 'Screen Positive — proceed to PHQ-9', color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: 2,
    frequency: 'as-needed',
    open_access: true,
    references: ['Kroenke et al., 2003, Med Care'],
    notes: 'Ultra-brief screener; score ≥3 warrants full PHQ-9. Not used as primary outcome.',
  },

  {
    id: 'hamd17',
    name: 'Hamilton Depression Rating Scale (17-item)',
    abbr: 'HAM-D17',
    conditions: ['MDD', 'TRD', 'Bipolar Depression'],
    domains: ['Depression severity', 'Sleep', 'Anxiety', 'Somatic symptoms'],
    rater: 'clinician',
    items: 17,
    min_score: 0,
    max_score: 52,
    admin_time_min: 20,
    scoring_bands: [
      { range: [0, 7],   label: 'Normal / Remission',  color: 'var(--green)' },
      { range: [8, 13],  label: 'Mild',                color: 'var(--teal)' },
      { range: [14, 18], label: 'Moderate',            color: 'var(--amber)' },
      { range: [19, 22], label: 'Severe',              color: 'var(--orange, #f97316)' },
      { range: [23, 52], label: 'Very Severe',         color: 'var(--red)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 7,
    frequency: 'weekly',
    open_access: true,
    references: ['Hamilton, 1960, J Neurol Neurosurg Psychiatry'],
    notes: 'Gold-standard clinician-rated depression measure for clinical trials. Remission defined as ≤7.',
  },

  {
    id: 'hamd21',
    name: 'Hamilton Depression Rating Scale (21-item)',
    abbr: 'HAM-D21',
    conditions: ['MDD', 'TRD', 'Bipolar Depression'],
    domains: ['Depression severity', 'Sleep', 'Anxiety', 'Somatic symptoms', 'Paranoia', 'OCD symptoms'],
    rater: 'clinician',
    items: 21,
    min_score: 0,
    max_score: 64,
    admin_time_min: 25,
    scoring_bands: [
      { range: [0, 7],   label: 'Normal / Remission',  color: 'var(--green)' },
      { range: [8, 13],  label: 'Mild',                color: 'var(--teal)' },
      { range: [14, 18], label: 'Moderate',            color: 'var(--amber)' },
      { range: [19, 22], label: 'Severe',              color: 'var(--orange, #f97316)' },
      { range: [23, 64], label: 'Very Severe',         color: 'var(--red)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 7,
    frequency: 'weekly',
    open_access: true,
    references: ['Hamilton, 1960, J Neurol Neurosurg Psychiatry'],
    notes: 'Extended version of HAM-D17; items 18–21 add paranoia, depersonalisation, OCD, and helplessness ratings.',
  },

  {
    id: 'madrs',
    name: 'Montgomery–Åsberg Depression Rating Scale',
    abbr: 'MADRS',
    conditions: ['MDD', 'TRD', 'Bipolar Depression', 'Postpartum Depression'],
    domains: ['Depression severity', 'Suicidality', 'Cognitive symptoms'],
    rater: 'clinician',
    items: 10,
    min_score: 0,
    max_score: 60,
    admin_time_min: 15,
    scoring_bands: [
      { range: [0, 6],   label: 'No / Recovered',      color: 'var(--green)' },
      { range: [7, 19],  label: 'Mild',                color: 'var(--teal)' },
      { range: [20, 34], label: 'Moderate',            color: 'var(--amber)' },
      { range: [35, 60], label: 'Severe',              color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: 10,
    frequency: 'weekly',
    open_access: true,
    references: ['Montgomery & Åsberg, 1979, Br J Psychiatry'],
    notes: 'Highly sensitive to change; preferred for antidepressant and TMS trials. Remission ≤10; response = 50% reduction.',
  },

  {
    id: 'qids-sr16',
    name: 'Quick Inventory of Depressive Symptomatology — Self-Report',
    abbr: 'QIDS-SR16',
    conditions: ['MDD', 'TRD', 'Bipolar Depression'],
    domains: ['Depression severity', 'Sleep', 'Appetite', 'Psychomotor', 'Suicidality'],
    rater: 'self',
    items: 16,
    min_score: 0,
    max_score: 27,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 5],   label: 'None',      color: 'var(--green)' },
      { range: [6, 10],  label: 'Mild',      color: 'var(--teal)' },
      { range: [11, 15], label: 'Moderate',  color: 'var(--amber)' },
      { range: [16, 20], label: 'Severe',    color: 'var(--orange, #f97316)' },
      { range: [21, 27], label: 'Very Severe', color: 'var(--red)' },
    ],
    response_cutoff: 4,
    remission_cutoff: 5,
    frequency: 'weekly',
    open_access: true,
    references: ['Rush et al., 2003, Biol Psychiatry'],
    notes: 'Widely used in STAR*D and TMS research. Assesses all 9 DSM symptom domains.',
  },

  {
    id: 'bdi-ii',
    name: 'Beck Depression Inventory — Second Edition',
    abbr: 'BDI-II',
    conditions: ['MDD', 'TRD', 'Anxiety Disorders', 'Chronic Pain'],
    domains: ['Depression severity', 'Cognitive distortions', 'Somatic symptoms'],
    rater: 'self',
    items: 21,
    min_score: 0,
    max_score: 63,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 13],  label: 'Minimal',   color: 'var(--green)' },
      { range: [14, 19], label: 'Mild',      color: 'var(--teal)' },
      { range: [20, 28], label: 'Moderate',  color: 'var(--amber)' },
      { range: [29, 63], label: 'Severe',    color: 'var(--red)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 13,
    frequency: 'bi-weekly',
    open_access: false,
    references: ['Beck et al., 1996, Psychological Assessment'],
    notes: 'Requires license (Pearson). Strong psychometric properties; widely used in cognitive-behavioural research.',
  },

  {
    id: 'ids-sr',
    name: 'Inventory of Depressive Symptomatology — Self-Report',
    abbr: 'IDS-SR',
    conditions: ['MDD', 'TRD', 'Bipolar Depression'],
    domains: ['Depression severity', 'Atypical features', 'Melancholic features'],
    rater: 'self',
    items: 30,
    min_score: 0,
    max_score: 84,
    admin_time_min: 15,
    scoring_bands: [
      { range: [0, 11],  label: 'Normal',    color: 'var(--green)' },
      { range: [12, 23], label: 'Mild',      color: 'var(--teal)' },
      { range: [24, 35], label: 'Moderate',  color: 'var(--amber)' },
      { range: [36, 47], label: 'Severe',    color: 'var(--orange, #f97316)' },
      { range: [48, 84], label: 'Very Severe', color: 'var(--red)' },
    ],
    response_cutoff: 12,
    remission_cutoff: 11,
    frequency: 'weekly',
    open_access: true,
    references: ['Rush et al., 1996, Psychiatry Res'],
    notes: 'Full 30-item version; covers atypical and melancholic specifiers not in QIDS-SR. Freely available at ids-qids.org.',
  },

  {
    id: 'bdi-fs',
    name: 'Beck Depression Inventory — Fast Screen',
    abbr: 'BDI-FS',
    conditions: ['MDD', 'Chronic Pain', 'Medical Populations'],
    domains: ['Depression screening in medical settings'],
    rater: 'self',
    items: 7,
    min_score: 0,
    max_score: 21,
    admin_time_min: 3,
    scoring_bands: [
      { range: [0, 3],  label: 'Minimal',  color: 'var(--green)' },
      { range: [4, 6],  label: 'Mild',     color: 'var(--teal)' },
      { range: [7, 9],  label: 'Moderate', color: 'var(--amber)' },
      { range: [10, 21], label: 'Severe',  color: 'var(--red)' },
    ],
    response_cutoff: 3,
    remission_cutoff: 3,
    frequency: 'monthly',
    open_access: false,
    references: ['Beck et al., 2000, Arch Gen Psychiatry'],
    notes: 'Somatic-item-free; designed for medical/pain populations where somatic overlap confounds standard BDI.',
  },

  {
    id: 'gds',
    name: 'Geriatric Depression Scale',
    abbr: 'GDS-15',
    conditions: ['MDD', 'Geriatric Depression', 'Dementia with Depression'],
    domains: ['Depression in older adults'],
    rater: 'self',
    items: 15,
    min_score: 0,
    max_score: 15,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 4],  label: 'Normal',          color: 'var(--green)' },
      { range: [5, 8],  label: 'Mild Depression', color: 'var(--amber)' },
      { range: [9, 11], label: 'Moderate',        color: 'var(--orange, #f97316)' },
      { range: [12, 15], label: 'Severe',         color: 'var(--red)' },
    ],
    response_cutoff: 3,
    remission_cutoff: 4,
    frequency: 'monthly',
    open_access: true,
    references: ['Yesavage et al., 1983, J Psychiatr Res'],
    notes: 'Yes/no format avoids somatic overlap; validated in ≥65 years. Long form = 30 items.',
  },

  // ── ANXIETY ───────────────────────────────────────────────────────────────

  {
    id: 'gad7',
    name: 'Generalised Anxiety Disorder-7',
    abbr: 'GAD-7',
    conditions: ['GAD', 'Panic Disorder', 'Social Anxiety Disorder', 'MDD', 'PTSD'],
    domains: ['Anxiety severity', 'Worry', 'Functional impairment'],
    rater: 'self',
    items: 7,
    min_score: 0,
    max_score: 21,
    admin_time_min: 3,
    scoring_bands: [
      { range: [0, 4],   label: 'Minimal',  color: 'var(--green)' },
      { range: [5, 9],   label: 'Mild',     color: 'var(--teal)' },
      { range: [10, 14], label: 'Moderate', color: 'var(--amber)' },
      { range: [15, 21], label: 'Severe',   color: 'var(--red)' },
    ],
    response_cutoff: 5,
    remission_cutoff: 5,
    frequency: 'weekly',
    open_access: true,
    references: ['Spitzer et al., 2006, Arch Intern Med'],
    notes: 'Pairs with PHQ-9 in routine neuromodulation monitoring. ≥10 threshold for significant anxiety.',
  },

  {
    id: 'hama',
    name: 'Hamilton Anxiety Rating Scale',
    abbr: 'HAM-A',
    conditions: ['GAD', 'Anxiety Disorders', 'MDD with anxious distress'],
    domains: ['Anxiety severity', 'Somatic anxiety', 'Psychic anxiety'],
    rater: 'clinician',
    items: 14,
    min_score: 0,
    max_score: 56,
    admin_time_min: 20,
    scoring_bands: [
      { range: [0, 17],  label: 'Mild',      color: 'var(--teal)' },
      { range: [18, 24], label: 'Moderate',  color: 'var(--amber)' },
      { range: [25, 56], label: 'Severe',    color: 'var(--red)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 7,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Hamilton, 1959, Br J Med Psychol'],
    notes: 'Standard clinician-rated anxiety measure; psychic and somatic anxiety subscales.',
  },

  {
    id: 'bai',
    name: 'Beck Anxiety Inventory',
    abbr: 'BAI',
    conditions: ['GAD', 'Panic Disorder', 'MDD', 'PTSD'],
    domains: ['Anxiety severity', 'Somatic symptoms of anxiety'],
    rater: 'self',
    items: 21,
    min_score: 0,
    max_score: 63,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 7],   label: 'Minimal',  color: 'var(--green)' },
      { range: [8, 15],  label: 'Mild',     color: 'var(--teal)' },
      { range: [16, 25], label: 'Moderate', color: 'var(--amber)' },
      { range: [26, 63], label: 'Severe',   color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 7,
    frequency: 'bi-weekly',
    open_access: false,
    references: ['Beck & Steer, 1993, Psychological Assessment'],
    notes: 'Focuses on somatic anxiety; less overlap with depression than other scales. Pearson license required.',
  },

  {
    id: 'stai',
    name: 'State–Trait Anxiety Inventory',
    abbr: 'STAI',
    conditions: ['GAD', 'Anxiety Disorders', 'PTSD', 'Perioperative Anxiety'],
    domains: ['State anxiety', 'Trait anxiety'],
    rater: 'self',
    items: 40,
    min_score: 20,
    max_score: 80,
    admin_time_min: 10,
    scoring_bands: [
      { range: [20, 37], label: 'Low',      color: 'var(--green)' },
      { range: [38, 44], label: 'Moderate', color: 'var(--amber)' },
      { range: [45, 80], label: 'High',     color: 'var(--red)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 37,
    frequency: 'bi-weekly',
    open_access: false,
    references: ['Spielberger et al., 1983, Mind Garden'],
    notes: 'Separate state (STAI-S) and trait (STAI-T) subscales. Widely used in neurofeedback and anxiety TMS research.',
  },

  {
    id: 'pdss',
    name: 'Panic Disorder Severity Scale',
    abbr: 'PDSS',
    conditions: ['Panic Disorder'],
    domains: ['Panic attack frequency', 'Anticipatory anxiety', 'Agoraphobic avoidance', 'Functional impairment'],
    rater: 'clinician',
    items: 7,
    min_score: 0,
    max_score: 28,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 5],   label: 'None / Minimal', color: 'var(--green)' },
      { range: [6, 9],   label: 'Mild',           color: 'var(--teal)' },
      { range: [10, 13], label: 'Moderate',       color: 'var(--amber)' },
      { range: [14, 17], label: 'Severe',         color: 'var(--orange, #f97316)' },
      { range: [18, 28], label: 'Very Severe',    color: 'var(--red)' },
    ],
    response_cutoff: 4,
    remission_cutoff: 5,
    frequency: 'weekly',
    open_access: true,
    references: ['Shear et al., 1997, Am J Psychiatry'],
    notes: 'Gold-standard for panic disorder severity in clinical trials.',
  },

  {
    id: 'lsas',
    name: 'Liebowitz Social Anxiety Scale',
    abbr: 'LSAS',
    conditions: ['Social Anxiety Disorder'],
    domains: ['Social performance anxiety', 'Social interaction anxiety', 'Fear', 'Avoidance'],
    rater: 'clinician',
    items: 24,
    min_score: 0,
    max_score: 144,
    admin_time_min: 20,
    scoring_bands: [
      { range: [0, 29],   label: 'None / Minimal',   color: 'var(--green)' },
      { range: [30, 49],  label: 'Mild',             color: 'var(--teal)' },
      { range: [50, 64],  label: 'Moderate',         color: 'var(--amber)' },
      { range: [65, 79],  label: 'Marked',           color: 'var(--orange, #f97316)' },
      { range: [80, 144], label: 'Severe / Very Severe', color: 'var(--red)' },
    ],
    response_cutoff: 20,
    remission_cutoff: 29,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Liebowitz, 1987, Mod Probl Pharmacopsychiatry'],
    notes: 'Performance and interaction subscales. SR version (LSAS-SR) also validated.',
  },

  {
    id: 'spin',
    name: 'Social Phobia Inventory',
    abbr: 'SPIN',
    conditions: ['Social Anxiety Disorder'],
    domains: ['Fear', 'Avoidance', 'Physiological arousal'],
    rater: 'self',
    items: 17,
    min_score: 0,
    max_score: 68,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 18],  label: 'None / Minimal',   color: 'var(--green)' },
      { range: [19, 29], label: 'Mild',             color: 'var(--teal)' },
      { range: [30, 39], label: 'Moderate',         color: 'var(--amber)' },
      { range: [40, 49], label: 'Severe',           color: 'var(--orange, #f97316)' },
      { range: [50, 68], label: 'Very Severe',      color: 'var(--red)' },
    ],
    response_cutoff: 9,
    remission_cutoff: 18,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Connor et al., 2000, Br J Psychiatry'],
    notes: 'Brief self-report alternative to LSAS. Mini-SPIN (3 items) available for screening.',
  },

  {
    id: 'acsa',
    name: 'Agoraphobic Cognitions Scale / Avoidance',
    abbr: 'ACSA',
    conditions: ['Panic Disorder', 'Agoraphobia'],
    domains: ['Agoraphobic cognitions', 'Situational avoidance'],
    rater: 'self',
    items: 14,
    min_score: 0,
    max_score: 56,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 14], label: 'Minimal',  color: 'var(--green)' },
      { range: [15, 28], label: 'Moderate', color: 'var(--amber)' },
      { range: [29, 56], label: 'Severe',  color: 'var(--red)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 14,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Chambless et al., 1984, Behav Res Ther'],
    notes: 'Agoraphobic Cognitions Questionnaire + Mobility Inventory combined; captures avoidance behaviours.',
  },

  // ── PTSD ──────────────────────────────────────────────────────────────────

  {
    id: 'pcl5',
    name: 'PTSD Checklist for DSM-5',
    abbr: 'PCL-5',
    conditions: ['PTSD', 'Complex PTSD', 'Acute Stress Disorder'],
    domains: ['Intrusion', 'Avoidance', 'Negative cognitions', 'Hyperarousal'],
    rater: 'self',
    items: 20,
    min_score: 0,
    max_score: 80,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 10],  label: 'Sub-threshold',  color: 'var(--green)' },
      { range: [11, 32], label: 'Moderate',       color: 'var(--amber)' },
      { range: [33, 80], label: 'Probable PTSD',  color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: 10,
    frequency: 'weekly',
    open_access: true,
    references: ['Weathers et al., 2013, National Center for PTSD'],
    notes: 'Provisional PTSD diagnosis: score ≥33 OR DSM-5 symptom cluster criteria. Replaces PCL-C/M/S.',
  },

  {
    id: 'caps5',
    name: 'Clinician-Administered PTSD Scale for DSM-5',
    abbr: 'CAPS-5',
    conditions: ['PTSD', 'Complex PTSD'],
    domains: ['Intrusion', 'Avoidance', 'Negative cognitions', 'Hyperarousal', 'Dissociation'],
    rater: 'clinician',
    items: 30,
    min_score: 0,
    max_score: 80,
    admin_time_min: 45,
    scoring_bands: [
      { range: [0, 19],  label: 'Asymptomatic',   color: 'var(--green)' },
      { range: [20, 39], label: 'Mild / Sub-threshold', color: 'var(--teal)' },
      { range: [40, 59], label: 'Moderate',       color: 'var(--amber)' },
      { range: [60, 79], label: 'Severe',         color: 'var(--orange, #f97316)' },
      { range: [80, 80], label: 'Extreme',        color: 'var(--red)' },
    ],
    response_cutoff: 15,
    remission_cutoff: 19,
    frequency: 'monthly',
    open_access: true,
    references: ['Weathers et al., 2018, PTSD Research Quarterly'],
    notes: 'Gold-standard structured interview for PTSD diagnosis and severity. Required for TMS PTSD trials.',
  },

  {
    id: 'ies-r',
    name: 'Impact of Event Scale — Revised',
    abbr: 'IES-R',
    conditions: ['PTSD', 'Acute Stress Disorder', 'Adjustment Disorder'],
    domains: ['Intrusion', 'Avoidance', 'Hyperarousal'],
    rater: 'self',
    items: 22,
    min_score: 0,
    max_score: 88,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 8],   label: 'Sub-clinical',  color: 'var(--green)' },
      { range: [9, 25],  label: 'Mild',          color: 'var(--teal)' },
      { range: [26, 43], label: 'Moderate',      color: 'var(--amber)' },
      { range: [44, 88], label: 'Severe',        color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: 8,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Weiss & Marmar, 1997, in Assessing Psychological Trauma'],
    notes: 'Widely used in trauma research; predates DSM-5 but remains useful in clinical monitoring.',
  },

  {
    id: 'pcl-c',
    name: 'PTSD Checklist — Civilian Version (DSM-IV)',
    abbr: 'PCL-C',
    conditions: ['PTSD'],
    domains: ['Intrusion', 'Avoidance/Numbing', 'Hyperarousal'],
    rater: 'self',
    items: 17,
    min_score: 17,
    max_score: 85,
    admin_time_min: 5,
    scoring_bands: [
      { range: [17, 36], label: 'Sub-threshold', color: 'var(--green)' },
      { range: [37, 44], label: 'Borderline',    color: 'var(--amber)' },
      { range: [45, 85], label: 'Probable PTSD', color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: 36,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Weathers et al., 1994, National Center for PTSD'],
    notes: 'Legacy DSM-IV version; PCL-5 preferred for new assessments. Retained here for historical data comparison.',
  },

  // ── OCD ───────────────────────────────────────────────────────────────────

  {
    id: 'ybocs',
    name: 'Yale–Brown Obsessive Compulsive Scale',
    abbr: 'Y-BOCS',
    conditions: ['OCD'],
    domains: ['Obsession severity', 'Compulsion severity', 'Resistance', 'Distress', 'Functional impairment'],
    rater: 'clinician',
    items: 10,
    min_score: 0,
    max_score: 40,
    admin_time_min: 30,
    scoring_bands: [
      { range: [0, 7],   label: 'Sub-clinical',  color: 'var(--green)' },
      { range: [8, 15],  label: 'Mild',          color: 'var(--teal)' },
      { range: [16, 23], label: 'Moderate',      color: 'var(--amber)' },
      { range: [24, 31], label: 'Severe',        color: 'var(--orange, #f97316)' },
      { range: [32, 40], label: 'Extreme',       color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 7,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Goodman et al., 1989, Arch Gen Psychiatry'],
    notes: 'Primary outcome measure for OCD TMS and DBS trials. FDA uses ≥16 as eligibility threshold for dTMS.',
  },

  {
    id: 'ocir',
    name: 'Obsessive-Compulsive Inventory — Revised',
    abbr: 'OCI-R',
    conditions: ['OCD'],
    domains: ['Washing', 'Obsessing', 'Hoarding', 'Ordering', 'Checking', 'Neutralising'],
    rater: 'self',
    items: 18,
    min_score: 0,
    max_score: 72,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 20],  label: 'Sub-clinical', color: 'var(--green)' },
      { range: [21, 40], label: 'Moderate',     color: 'var(--amber)' },
      { range: [41, 72], label: 'Severe',       color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 20,
    frequency: 'weekly',
    open_access: true,
    references: ['Foa et al., 2002, Psychol Assess'],
    notes: 'Self-report companion to Y-BOCS; ≥21 suggests clinically significant OCD.',
  },

  {
    id: 'docs',
    name: 'Dimensional Obsessive-Compulsive Scale',
    abbr: 'DOCS',
    conditions: ['OCD'],
    domains: ['Contamination', 'Responsibility/Harm', 'Unacceptable thoughts', 'Symmetry/Order'],
    rater: 'self',
    items: 20,
    min_score: 0,
    max_score: 80,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 9],   label: 'Sub-clinical', color: 'var(--green)' },
      { range: [10, 29], label: 'Mild-Moderate', color: 'var(--amber)' },
      { range: [30, 80], label: 'Severe',        color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 9,
    frequency: 'bi-weekly',
    open_access: true,
    references: ['Abramowitz et al., 2010, J Obsessive Compuls Relat Disord'],
    notes: 'Captures four core OCD symptom dimensions; sensitive to change in treatment studies.',
  },

  // ── ADHD ──────────────────────────────────────────────────────────────────

  {
    id: 'adhd-rs5',
    name: 'ADHD Rating Scale 5',
    abbr: 'ADHD-RS-5',
    conditions: ['ADHD'],
    domains: ['Inattention', 'Hyperactivity-Impulsivity'],
    rater: 'clinician',
    items: 18,
    min_score: 0,
    max_score: 54,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 14],  label: 'Minimal',   color: 'var(--green)' },
      { range: [15, 28], label: 'Mild',      color: 'var(--teal)' },
      { range: [29, 40], label: 'Moderate',  color: 'var(--amber)' },
      { range: [41, 54], label: 'Severe',    color: 'var(--red)' },
    ],
    response_cutoff: 9,
    remission_cutoff: 14,
    frequency: 'monthly',
    open_access: false,
    references: ['DuPaul et al., 2016, Guilford Press'],
    notes: 'DSM-5 aligned; home and school versions for children, adult version for ≥18. Guilford license required.',
  },

  {
    id: 'conners3',
    name: "Conners' 3rd Edition",
    abbr: 'Conners-3',
    conditions: ['ADHD', 'Conduct Disorder', 'Oppositional Defiant Disorder'],
    domains: ['Inattention', 'Hyperactivity', 'Learning problems', 'Executive function', 'Peer relations'],
    rater: 'parent',
    items: 99,
    min_score: 0,
    max_score: 198,
    admin_time_min: 20,
    scoring_bands: [
      { range: [0, 59],   label: 'Average (T<60)',        color: 'var(--green)' },
      { range: [60, 69],  label: 'Elevated (T 60–69)',    color: 'var(--amber)' },
      { range: [70, 198], label: 'Very Elevated (T≥70)',  color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: false,
    references: ['Conners, 2008, Multi-Health Systems'],
    notes: 'T-score based; parent, teacher and self-report forms. MHS license required. Normative data by age/sex.',
  },

  {
    id: 'brief-a',
    name: 'Behavior Rating Inventory of Executive Function — Adult',
    abbr: 'BRIEF-A',
    conditions: ['ADHD', 'TBI', 'Dementia', 'ASD'],
    domains: ['Inhibition', 'Shifting', 'Emotional control', 'Working memory', 'Planning/Organising'],
    rater: 'self',
    items: 75,
    min_score: 75,
    max_score: 225,
    admin_time_min: 15,
    scoring_bands: [
      { range: [75, 149],  label: 'Within Normal Limits (T<60)',   color: 'var(--green)' },
      { range: [150, 174], label: 'Elevated (T 60–69)',            color: 'var(--amber)' },
      { range: [175, 225], label: 'Clinically Elevated (T≥70)',    color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: false,
    references: ['Roth et al., 2005, PAR Inc.'],
    notes: 'Informant and self-report forms; GEC = Global Executive Composite. PAR license required.',
  },

  {
    id: 'diva2',
    name: 'Diagnostic Interview for ADHD in Adults 2.0',
    abbr: 'DIVA 2.0',
    conditions: ['ADHD'],
    domains: ['DSM-IV inattentive symptoms', 'DSM-IV hyperactive-impulsive symptoms', 'Age of onset', 'Functional impairment'],
    rater: 'clinician',
    items: 64,
    min_score: 0,
    max_score: 64,
    admin_time_min: 60,
    scoring_bands: [],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'once',
    open_access: true,
    references: ['Kooij & Francken, 2010, DIVA Foundation'],
    notes: 'Structured diagnostic interview; freely available at divacenter.eu. Covers childhood and adult examples per symptom.',
  },

  {
    id: 'vanderbilt',
    name: 'Vanderbilt ADHD Diagnostic Rating Scale',
    abbr: 'Vanderbilt (Parent)',
    conditions: ['ADHD', 'Conduct Disorder', 'Anxiety in Children'],
    domains: ['Inattention', 'Hyperactivity-Impulsivity', 'Oppositional', 'Anxiety/Depression', 'Academic performance'],
    rater: 'parent',
    items: 55,
    min_score: 0,
    max_score: 165,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 27],   label: 'Below clinical threshold', color: 'var(--green)' },
      { range: [28, 165], label: 'Above clinical threshold', color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: true,
    references: ['Wolraich et al., 2003, Pediatrics'],
    notes: 'NICHQ Vanderbilt; freely available. Parent and Teacher forms. Widely used in paediatric ADHD neurofeedback protocols.',
  },

  // ── PSYCHOSIS ─────────────────────────────────────────────────────────────

  {
    id: 'panss',
    name: 'Positive and Negative Syndrome Scale',
    abbr: 'PANSS',
    conditions: ['Schizophrenia', 'Schizoaffective Disorder', 'Bipolar Psychosis'],
    domains: ['Positive symptoms', 'Negative symptoms', 'General psychopathology'],
    rater: 'clinician',
    items: 30,
    min_score: 30,
    max_score: 210,
    admin_time_min: 45,
    scoring_bands: [
      { range: [30, 58],  label: 'Mild',      color: 'var(--teal)' },
      { range: [59, 74],  label: 'Moderate',  color: 'var(--amber)' },
      { range: [75, 99],  label: 'Severe',    color: 'var(--orange, #f97316)' },
      { range: [100, 210], label: 'Extreme',  color: 'var(--red)' },
    ],
    response_cutoff: 20,
    remission_cutoff: 58,
    frequency: 'monthly',
    open_access: false,
    references: ['Kay et al., 1987, Schizophr Bull'],
    notes: 'Standard outcome measure for schizophrenia trials including rTMS for auditory hallucinations. Multi-Health Systems license.',
  },

  {
    id: 'bprs',
    name: 'Brief Psychiatric Rating Scale',
    abbr: 'BPRS',
    conditions: ['Schizophrenia', 'Bipolar Disorder', 'Psychotic Depression'],
    domains: ['Positive symptoms', 'Negative symptoms', 'Affective symptoms', 'Resistance'],
    rater: 'clinician',
    items: 24,
    min_score: 24,
    max_score: 168,
    admin_time_min: 20,
    scoring_bands: [
      { range: [24, 40],  label: 'Normal',     color: 'var(--green)' },
      { range: [41, 52],  label: 'Borderline', color: 'var(--teal)' },
      { range: [53, 64],  label: 'Moderate',   color: 'var(--amber)' },
      { range: [65, 168], label: 'Severe',     color: 'var(--red)' },
    ],
    response_cutoff: 20,
    remission_cutoff: 40,
    frequency: 'monthly',
    open_access: true,
    references: ['Overall & Gorham, 1962, Psychol Rep'],
    notes: 'Broadly used across psychotic and affective disorders; quicker than PANSS.',
  },

  {
    id: 'cdss',
    name: 'Calgary Depression Scale for Schizophrenia',
    abbr: 'CDSS',
    conditions: ['Schizophrenia', 'Schizoaffective Disorder'],
    domains: ['Depressive symptoms in schizophrenia'],
    rater: 'clinician',
    items: 9,
    min_score: 0,
    max_score: 27,
    admin_time_min: 15,
    scoring_bands: [
      { range: [0, 5],   label: 'No depression',     color: 'var(--green)' },
      { range: [6, 10],  label: 'Possible depression', color: 'var(--amber)' },
      { range: [11, 27], label: 'Probable depression', color: 'var(--red)' },
    ],
    response_cutoff: 3,
    remission_cutoff: 5,
    frequency: 'monthly',
    open_access: true,
    references: ['Addington et al., 1993, Br J Psychiatry'],
    notes: 'Specifically designed to separate depression from negative symptoms and antipsychotic side effects.',
  },

  {
    id: 'sfs',
    name: 'Social Functioning Scale',
    abbr: 'SFS',
    conditions: ['Schizophrenia', 'Psychotic Disorders'],
    domains: ['Social engagement', 'Interpersonal behaviour', 'Pro-social activities', 'Employment/Occupation'],
    rater: 'self',
    items: 79,
    min_score: 0,
    max_score: 223,
    admin_time_min: 20,
    scoring_bands: [
      { range: [0, 50],   label: 'Poor',     color: 'var(--red)' },
      { range: [51, 100], label: 'Moderate', color: 'var(--amber)' },
      { range: [101, 223], label: 'Good',    color: 'var(--green)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: true,
    references: ['Birchwood et al., 1990, Br J Psychiatry'],
    notes: 'Seven subscale scores; tracks social recovery in psychosis.',
  },

  // ── COGNITIVE ─────────────────────────────────────────────────────────────

  {
    id: 'mmse',
    name: 'Mini-Mental State Examination',
    abbr: 'MMSE',
    conditions: ['Dementia', 'MCI', 'Alzheimer Disease', 'Parkinson Disease'],
    domains: ['Orientation', 'Registration', 'Attention', 'Recall', 'Language', 'Visuoconstructive'],
    rater: 'clinician',
    items: 30,
    min_score: 0,
    max_score: 30,
    admin_time_min: 10,
    scoring_bands: [
      { range: [27, 30], label: 'Normal',                  color: 'var(--green)' },
      { range: [21, 26], label: 'Mild Cognitive Impairment', color: 'var(--teal)' },
      { range: [11, 20], label: 'Moderate Dementia',       color: 'var(--amber)' },
      { range: [0, 10],  label: 'Severe Dementia',         color: 'var(--red)' },
    ],
    response_cutoff: 2,
    remission_cutoff: 26,
    frequency: 'monthly',
    open_access: false,
    references: ['Folstein et al., 1975, J Psychiatr Res'],
    notes: 'Copyright held by PAR Inc since 2001; permission required for commercial use. Education-adjusted norms available.',
  },

  {
    id: 'moca',
    name: 'Montreal Cognitive Assessment',
    abbr: 'MoCA',
    conditions: ['MCI', 'Alzheimer Disease', 'Vascular Dementia', 'Parkinson Disease', 'TBI'],
    domains: ['Visuospatial', 'Executive', 'Naming', 'Attention', 'Language', 'Abstraction', 'Memory', 'Orientation'],
    rater: 'clinician',
    items: 30,
    min_score: 0,
    max_score: 30,
    admin_time_min: 10,
    scoring_bands: [
      { range: [26, 30], label: 'Normal',                    color: 'var(--green)' },
      { range: [18, 25], label: 'Mild Cognitive Impairment', color: 'var(--amber)' },
      { range: [10, 17], label: 'Moderate Dementia',         color: 'var(--orange, #f97316)' },
      { range: [0, 9],   label: 'Severe Dementia',           color: 'var(--red)' },
    ],
    response_cutoff: 2,
    remission_cutoff: 25,
    frequency: 'monthly',
    open_access: true,
    references: ['Nasreddine et al., 2005, J Am Geriatr Soc'],
    notes: 'More sensitive to MCI than MMSE. Free for clinicians at mocatest.org. Add 1 point if ≤12 years education.',
  },

  {
    id: 'ace-iii',
    name: 'Addenbrooke Cognitive Examination III',
    abbr: 'ACE-III',
    conditions: ['Dementia', 'MCI', 'Frontotemporal Dementia', 'Parkinson Disease'],
    domains: ['Attention/Orientation', 'Memory', 'Fluency', 'Language', 'Visuospatial'],
    rater: 'clinician',
    items: 19,
    min_score: 0,
    max_score: 100,
    admin_time_min: 20,
    scoring_bands: [
      { range: [88, 100], label: 'Normal',          color: 'var(--green)' },
      { range: [83, 87],  label: 'Borderline',      color: 'var(--teal)' },
      { range: [0, 82],   label: 'Cognitive Impairment', color: 'var(--red)' },
    ],
    response_cutoff: 4,
    remission_cutoff: 87,
    frequency: 'every 6 months',
    open_access: true,
    references: ['Hsieh et al., 2013, Dement Geriatr Cogn Disord'],
    notes: 'More comprehensive than MoCA; free download from Cambridge Cognition. Sensitive to FTD profile.',
  },

  {
    id: 'ravlt',
    name: 'Rey Auditory Verbal Learning Test',
    abbr: 'RAVLT',
    conditions: ['MCI', 'Alzheimer Disease', 'TBI', 'Depression-related cognitive impairment'],
    domains: ['Verbal learning', 'Immediate recall', 'Delayed recall', 'Recognition'],
    rater: 'clinician',
    items: 15,
    min_score: 0,
    max_score: 75,
    admin_time_min: 20,
    scoring_bands: [
      { range: [45, 75], label: 'Normal',              color: 'var(--green)' },
      { range: [30, 44], label: 'Borderline',          color: 'var(--amber)' },
      { range: [0, 29],  label: 'Impaired',            color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'every 6 months',
    open_access: true,
    references: ['Rey, 1964; Taylor, 1959'],
    notes: 'Five immediate learning trials plus delay and recognition. Sensitive to hippocampal dysfunction.',
  },

  {
    id: 'tmt',
    name: 'Trail Making Test A & B',
    abbr: 'TMT-A/B',
    conditions: ['ADHD', 'TBI', 'Dementia', 'MCI'],
    domains: ['Processing speed (A)', 'Executive function / set-shifting (B)'],
    rater: 'clinician',
    items: null,
    min_score: null,
    max_score: null,
    admin_time_min: 10,
    scoring_bands: [],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'every 6 months',
    open_access: true,
    references: ['Reitan, 1958, Percept Mot Skills'],
    notes: 'Scored by time (seconds); age/education norms required. B-A difference sensitive to executive deficits. Freely available.',
  },

  {
    id: 'dsst',
    name: 'Digit Symbol Substitution Test',
    abbr: 'DSST',
    conditions: ['MDD', 'Schizophrenia', 'ADHD', 'Dementia'],
    domains: ['Processing speed', 'Attention', 'Visuomotor coordination'],
    rater: 'clinician',
    items: 133,
    min_score: 0,
    max_score: 133,
    admin_time_min: 2,
    scoring_bands: [
      { range: [90, 133], label: 'Above Average',   color: 'var(--green)' },
      { range: [70, 89],  label: 'Average',         color: 'var(--teal)' },
      { range: [40, 69],  label: 'Below Average',   color: 'var(--amber)' },
      { range: [0, 39],   label: 'Impaired',        color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: false,
    references: ['Wechsler, 1955, Wechsler Adult Intelligence Scale'],
    notes: 'WAIS subtest; sensitive to processing speed deficits in depression and schizophrenia. Pearson license.',
  },

  // ── PAIN ──────────────────────────────────────────────────────────────────

  {
    id: 'nrs-pain',
    name: 'Numerical Rating Scale — Pain',
    abbr: 'NRS-Pain',
    conditions: ['Chronic Pain', 'Fibromyalgia', 'CRPS', 'Neuropathic Pain'],
    domains: ['Pain intensity'],
    rater: 'self',
    items: 1,
    min_score: 0,
    max_score: 10,
    admin_time_min: 1,
    scoring_bands: [
      { range: [0, 0],  label: 'No Pain',        color: 'var(--green)' },
      { range: [1, 3],  label: 'Mild',           color: 'var(--teal)' },
      { range: [4, 6],  label: 'Moderate',       color: 'var(--amber)' },
      { range: [7, 10], label: 'Severe',         color: 'var(--red)' },
    ],
    response_cutoff: 2,
    remission_cutoff: 3,
    frequency: 'daily',
    open_access: true,
    references: ['Farrar et al., 2001, Pain'],
    notes: '≥30% reduction = clinically meaningful; ≥50% = substantial relief. Use at every session.',
  },

  {
    id: 'vas',
    name: 'Visual Analogue Scale — Pain',
    abbr: 'VAS',
    conditions: ['Chronic Pain', 'Acute Pain', 'Headache'],
    domains: ['Pain intensity'],
    rater: 'self',
    items: 1,
    min_score: 0,
    max_score: 100,
    admin_time_min: 1,
    scoring_bands: [
      { range: [0, 4],   label: 'No / Minimal Pain', color: 'var(--green)' },
      { range: [5, 44],  label: 'Mild',              color: 'var(--teal)' },
      { range: [45, 74], label: 'Moderate',          color: 'var(--amber)' },
      { range: [75, 100], label: 'Severe',           color: 'var(--red)' },
    ],
    response_cutoff: 20,
    remission_cutoff: 4,
    frequency: 'daily',
    open_access: true,
    references: ['Scott & Huskisson, 1976, Rheumatol Rehabil'],
    notes: '100mm horizontal line; mm measured from left. Requires physical form; less practical than NRS for remote monitoring.',
  },

  {
    id: 'bpi',
    name: 'Brief Pain Inventory',
    abbr: 'BPI',
    conditions: ['Chronic Pain', 'Cancer Pain', 'Neuropathic Pain', 'Fibromyalgia'],
    domains: ['Pain severity', 'Pain interference', 'Activity', 'Mood', 'Sleep'],
    rater: 'self',
    items: 9,
    min_score: 0,
    max_score: 10,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 3],  label: 'Mild',     color: 'var(--teal)' },
      { range: [4, 6],  label: 'Moderate', color: 'var(--amber)' },
      { range: [7, 10], label: 'Severe',   color: 'var(--red)' },
    ],
    response_cutoff: 2,
    remission_cutoff: 3,
    frequency: 'weekly',
    open_access: true,
    references: ['Cleeland & Ryan, 1994, Ann Acad Med Singapore'],
    notes: 'Severity and interference composites; validated across languages and cultures. Freely available from MD Anderson.',
  },

  {
    id: 'pdq',
    name: 'Pain Detect Questionnaire',
    abbr: 'PDQ',
    conditions: ['Neuropathic Pain', 'Chronic Pain', 'CRPS'],
    domains: ['Neuropathic pain component', 'Spontaneous pain patterns', 'Radiating pain'],
    rater: 'self',
    items: 9,
    min_score: -1,
    max_score: 38,
    admin_time_min: 5,
    scoring_bands: [
      { range: [-1, 12], label: 'Nociceptive component unlikely', color: 'var(--green)' },
      { range: [13, 18], label: 'Ambiguous', color: 'var(--amber)' },
      { range: [19, 38], label: 'Neuropathic component likely', color: 'var(--red)' },
    ],
    response_cutoff: 4,
    remission_cutoff: 12,
    frequency: 'monthly',
    open_access: true,
    references: ['Freynhagen et al., 2006, Curr Med Res Opin'],
    notes: 'Screens for neuropathic component; useful in TMS pain protocol patient selection.',
  },

  {
    id: 'cpgs',
    name: 'Chronic Pain Grade Scale',
    abbr: 'CPGS',
    conditions: ['Chronic Pain', 'Musculoskeletal Pain'],
    domains: ['Pain intensity', 'Pain disability', 'Pain-related disability days'],
    rater: 'self',
    items: 7,
    min_score: 0,
    max_score: null,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 0],  label: 'Grade 0 — No pain',             color: 'var(--green)' },
      { range: [1, 1],  label: 'Grade I — Low disability/low intensity', color: 'var(--teal)' },
      { range: [2, 2],  label: 'Grade II — Low disability/high intensity', color: 'var(--amber)' },
      { range: [3, 3],  label: 'Grade III — High disability/moderately limiting', color: 'var(--orange, #f97316)' },
      { range: [4, 4],  label: 'Grade IV — High disability/severely limiting', color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: true,
    references: ['Von Korff et al., 1992, Pain'],
    notes: 'Hierarchical classification (0–4); tracks functional disability trajectory.',
  },

  // ── SLEEP ─────────────────────────────────────────────────────────────────

  {
    id: 'isi',
    name: 'Insomnia Severity Index',
    abbr: 'ISI',
    conditions: ['Insomnia Disorder', 'MDD', 'Anxiety Disorders', 'PTSD'],
    domains: ['Sleep onset', 'Sleep maintenance', 'Early waking', 'Sleep satisfaction', 'Daytime impairment'],
    rater: 'self',
    items: 7,
    min_score: 0,
    max_score: 28,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 7],   label: 'No clinically significant insomnia', color: 'var(--green)' },
      { range: [8, 14],  label: 'Sub-threshold insomnia',             color: 'var(--teal)' },
      { range: [15, 21], label: 'Moderate clinical insomnia',         color: 'var(--amber)' },
      { range: [22, 28], label: 'Severe clinical insomnia',           color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 7,
    frequency: 'weekly',
    open_access: true,
    references: ['Morin et al., 2011, Sleep'],
    notes: 'Primary outcome in CES and neurofeedback sleep trials. Validated in multiple languages.',
  },

  {
    id: 'psqi',
    name: 'Pittsburgh Sleep Quality Index',
    abbr: 'PSQI',
    conditions: ['Insomnia Disorder', 'PTSD', 'MDD', 'Fibromyalgia'],
    domains: ['Subjective quality', 'Latency', 'Duration', 'Efficiency', 'Disturbances', 'Medication use', 'Daytime dysfunction'],
    rater: 'self',
    items: 19,
    min_score: 0,
    max_score: 21,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 5],  label: 'Good sleep quality',  color: 'var(--green)' },
      { range: [6, 21], label: 'Poor sleep quality',  color: 'var(--red)' },
    ],
    response_cutoff: 3,
    remission_cutoff: 5,
    frequency: 'monthly',
    open_access: true,
    references: ['Buysse et al., 1989, Psychiatry Res'],
    notes: 'Seven component scores summed. Score >5 = poor sleeper. Retrograde 1-month recall.',
  },

  {
    id: 'ess',
    name: 'Epworth Sleepiness Scale',
    abbr: 'ESS',
    conditions: ['Hypersomnia', 'OSA', 'Narcolepsy', 'Shift Work Disorder'],
    domains: ['Daytime sleepiness'],
    rater: 'self',
    items: 8,
    min_score: 0,
    max_score: 24,
    admin_time_min: 3,
    scoring_bands: [
      { range: [0, 10],  label: 'Normal daytime sleepiness', color: 'var(--green)' },
      { range: [11, 12], label: 'Mild excess sleepiness',    color: 'var(--teal)' },
      { range: [13, 15], label: 'Moderate',                 color: 'var(--amber)' },
      { range: [16, 24], label: 'Severe',                   color: 'var(--red)' },
    ],
    response_cutoff: 4,
    remission_cutoff: 10,
    frequency: 'monthly',
    open_access: true,
    references: ['Johns, 1991, Sleep'],
    notes: 'Likelihood of dozing in 8 situations. Useful safety screen before TMS (>16 may indicate undiagnosed OSA).',
  },

  {
    id: 'rpsq',
    name: 'Restorative Sleep Questionnaire',
    abbr: 'RPSQ',
    conditions: ['Insomnia Disorder', 'Fibromyalgia', 'CFS'],
    domains: ['Sleep restorativeness', 'Morning freshness'],
    rater: 'self',
    items: 9,
    min_score: 0,
    max_score: 36,
    admin_time_min: 3,
    scoring_bands: [
      { range: [27, 36], label: 'Restorative',        color: 'var(--green)' },
      { range: [18, 26], label: 'Somewhat restorative', color: 'var(--teal)' },
      { range: [0, 17],  label: 'Non-restorative',    color: 'var(--red)' },
    ],
    response_cutoff: 6,
    remission_cutoff: 26,
    frequency: 'weekly',
    open_access: true,
    references: ['Restorative Sleep Questionnaire, Zammit et al., 2010, Sleep Med'],
    notes: 'Complementary to PSQI; captures subjective sleep quality dimension distinct from duration.',
  },

  // ── SUBSTANCE ─────────────────────────────────────────────────────────────

  {
    id: 'audit',
    name: 'Alcohol Use Disorders Identification Test',
    abbr: 'AUDIT',
    conditions: ['Alcohol Use Disorder', 'Hazardous Drinking'],
    domains: ['Consumption', 'Dependence symptoms', 'Alcohol-related harm'],
    rater: 'self',
    items: 10,
    min_score: 0,
    max_score: 40,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 7],   label: 'Low risk',          color: 'var(--green)' },
      { range: [8, 15],  label: 'Hazardous use',     color: 'var(--amber)' },
      { range: [16, 19], label: 'Harmful use',       color: 'var(--orange, #f97316)' },
      { range: [20, 40], label: 'Probable dependence', color: 'var(--red)' },
    ],
    response_cutoff: 4,
    remission_cutoff: 7,
    frequency: 'monthly',
    open_access: true,
    references: ['Saunders et al., 1993, Addiction'],
    notes: 'WHO tool; AUDIT-C (3 items) available for brief screening. Required baseline in TMS addiction protocols.',
  },

  {
    id: 'dast10',
    name: 'Drug Abuse Screening Test-10',
    abbr: 'DAST-10',
    conditions: ['Substance Use Disorder', 'Opioid Use Disorder', 'Stimulant Use Disorder'],
    domains: ['Drug use consequences', 'Dependence', 'Control'],
    rater: 'self',
    items: 10,
    min_score: 0,
    max_score: 10,
    admin_time_min: 3,
    scoring_bands: [
      { range: [0, 0],  label: 'No problems',    color: 'var(--green)' },
      { range: [1, 2],  label: 'Low level',      color: 'var(--teal)' },
      { range: [3, 5],  label: 'Moderate',       color: 'var(--amber)' },
      { range: [6, 8],  label: 'Substantial',    color: 'var(--orange, #f97316)' },
      { range: [9, 10], label: 'Severe',         color: 'var(--red)' },
    ],
    response_cutoff: 2,
    remission_cutoff: 2,
    frequency: 'monthly',
    open_access: true,
    references: ['Skinner, 1982, Addictive Behaviors'],
    notes: 'Excludes alcohol; validated for broad drug use. DAST-20 available for research settings.',
  },

  {
    id: 'cage',
    name: 'CAGE Questionnaire',
    abbr: 'CAGE',
    conditions: ['Alcohol Use Disorder'],
    domains: ['Alcohol dependence screening'],
    rater: 'self',
    items: 4,
    min_score: 0,
    max_score: 4,
    admin_time_min: 1,
    scoring_bands: [
      { range: [0, 1], label: 'Unlikely dependence', color: 'var(--green)' },
      { range: [2, 4], label: 'Likely dependence — refer', color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: 1,
    frequency: 'as-needed',
    open_access: true,
    references: ['Ewing, 1984, JAMA'],
    notes: '≥2 positive = 93% sensitivity for alcohol dependence. Ultra-brief; use as gatekeeper before AUDIT.',
  },

  {
    id: 'mast',
    name: 'Michigan Alcoholism Screening Test',
    abbr: 'MAST',
    conditions: ['Alcohol Use Disorder'],
    domains: ['Alcohol problems', 'Dependence', 'Medical consequences'],
    rater: 'self',
    items: 25,
    min_score: 0,
    max_score: 53,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 4],  label: 'Not alcoholic',     color: 'var(--green)' },
      { range: [5, 6],  label: 'Borderline',        color: 'var(--amber)' },
      { range: [7, 53], label: 'Alcoholism present', color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: 4,
    frequency: 'as-needed',
    open_access: true,
    references: ['Selzer, 1971, Am J Psychiatry'],
    notes: 'Short-MAST (13 items) and Geriatric-MAST (24 items) variants available. Weighted scoring.',
  },

  // ── FUNCTIONAL / GLOBAL ───────────────────────────────────────────────────

  {
    id: 'cgi-s',
    name: 'Clinical Global Impressions — Severity',
    abbr: 'CGI-S',
    conditions: ['MDD', 'TRD', 'Anxiety Disorders', 'OCD', 'PTSD', 'Schizophrenia'],
    domains: ['Overall illness severity'],
    rater: 'clinician',
    items: 1,
    min_score: 1,
    max_score: 7,
    admin_time_min: 2,
    scoring_bands: [
      { range: [1, 1], label: 'Normal',                    color: 'var(--green)' },
      { range: [2, 2], label: 'Borderline ill',            color: 'var(--teal)' },
      { range: [3, 3], label: 'Mildly ill',                color: 'var(--teal)' },
      { range: [4, 4], label: 'Moderately ill',            color: 'var(--amber)' },
      { range: [5, 5], label: 'Markedly ill',              color: 'var(--orange, #f97316)' },
      { range: [6, 6], label: 'Severely ill',              color: 'var(--red)' },
      { range: [7, 7], label: 'Extremely ill',             color: 'var(--red)' },
    ],
    response_cutoff: 1,
    remission_cutoff: 2,
    frequency: 'weekly',
    open_access: true,
    references: ['Guy, 1976, ECDEU Assessment Manual'],
    notes: 'Anchored to clinician experience; required in most FDA submissions and TMS RCTs.',
  },

  {
    id: 'cgi-i',
    name: 'Clinical Global Impressions — Improvement',
    abbr: 'CGI-I',
    conditions: ['MDD', 'TRD', 'Anxiety Disorders', 'OCD', 'PTSD', 'Schizophrenia'],
    domains: ['Global treatment response'],
    rater: 'clinician',
    items: 1,
    min_score: 1,
    max_score: 7,
    admin_time_min: 2,
    scoring_bands: [
      { range: [1, 1], label: 'Very much improved',  color: 'var(--green)' },
      { range: [2, 2], label: 'Much improved',       color: 'var(--teal)' },
      { range: [3, 3], label: 'Minimally improved',  color: 'var(--teal)' },
      { range: [4, 4], label: 'No change',           color: 'var(--amber)' },
      { range: [5, 5], label: 'Minimally worse',     color: 'var(--orange, #f97316)' },
      { range: [6, 6], label: 'Much worse',          color: 'var(--red)' },
      { range: [7, 7], label: 'Very much worse',     color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'weekly',
    open_access: true,
    references: ['Guy, 1976, ECDEU Assessment Manual'],
    notes: 'Responder = CGI-I ≤2. Compared to baseline; companion to CGI-S.',
  },

  {
    id: 'gaf',
    name: 'Global Assessment of Functioning',
    abbr: 'GAF',
    conditions: ['MDD', 'Schizophrenia', 'Anxiety Disorders', 'Personality Disorders'],
    domains: ['Psychological functioning', 'Social functioning', 'Occupational functioning'],
    rater: 'clinician',
    items: 1,
    min_score: 1,
    max_score: 100,
    admin_time_min: 5,
    scoring_bands: [
      { range: [91, 100], label: 'Superior',                   color: 'var(--green)' },
      { range: [71, 90],  label: 'Absent/minimal symptoms',    color: 'var(--green)' },
      { range: [51, 70],  label: 'Mild symptoms',             color: 'var(--teal)' },
      { range: [41, 50],  label: 'Moderate symptoms',         color: 'var(--amber)' },
      { range: [31, 40],  label: 'Serious impairment',        color: 'var(--orange, #f97316)' },
      { range: [1, 30],   label: 'Severe impairment',         color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: 70,
    frequency: 'monthly',
    open_access: true,
    references: ['APA, 1994, DSM-IV'],
    notes: 'DSM-IV Axis V; replaced in DSM-5 by WHODAS-2 but still widely used. Lower score = worse function.',
  },

  {
    id: 'whodas2',
    name: 'WHO Disability Assessment Schedule 2.0',
    abbr: 'WHODAS-2',
    conditions: ['MDD', 'Schizophrenia', 'PTSD', 'Chronic Pain', 'Any DSM-5 disorder'],
    domains: ['Cognition', 'Mobility', 'Self-care', 'Getting along', 'Life activities', 'Participation'],
    rater: 'self',
    items: 36,
    min_score: 0,
    max_score: 100,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 4],   label: 'None',     color: 'var(--green)' },
      { range: [5, 24],  label: 'Mild',     color: 'var(--teal)' },
      { range: [25, 49], label: 'Moderate', color: 'var(--amber)' },
      { range: [50, 95], label: 'Severe',   color: 'var(--orange, #f97316)' },
      { range: [96, 100], label: 'Extreme / Complete', color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: 4,
    frequency: 'monthly',
    open_access: true,
    references: ['Ustun et al., 2010, WHO Press'],
    notes: 'DSM-5 endorsed functional outcome measure. 12-item short form available. Freely available from WHO.',
  },

  {
    id: 'sf36',
    name: 'Short Form Health Survey-36',
    abbr: 'SF-36',
    conditions: ['Chronic Pain', 'MDD', 'Fibromyalgia', 'Any chronic condition'],
    domains: ['Physical functioning', 'Role-physical', 'Bodily pain', 'General health', 'Vitality', 'Social functioning', 'Role-emotional', 'Mental health'],
    rater: 'self',
    items: 36,
    min_score: 0,
    max_score: 100,
    admin_time_min: 10,
    scoring_bands: [
      { range: [0, 49],  label: 'Below population norm', color: 'var(--amber)' },
      { range: [50, 100], label: 'At or above norm',     color: 'var(--green)' },
    ],
    response_cutoff: 5,
    remission_cutoff: 50,
    frequency: 'monthly',
    open_access: false,
    references: ['Ware & Sherbourne, 1992, Med Care'],
    notes: 'Two composite summary scores: PCS (physical) and MCS (mental). RAND 36 is a freely available variant.',
  },

  {
    id: 'eq5d',
    name: 'EuroQol 5-Dimension Health Questionnaire',
    abbr: 'EQ-5D',
    conditions: ['Chronic Pain', 'MDD', 'Any chronic condition'],
    domains: ['Mobility', 'Self-care', 'Usual activities', 'Pain/Discomfort', 'Anxiety/Depression'],
    rater: 'self',
    items: 6,
    min_score: 0,
    max_score: 1,
    admin_time_min: 3,
    scoring_bands: [
      { range: [0, 0.5],  label: 'Below average utility', color: 'var(--amber)' },
      { range: [0.51, 1], label: 'Average to full health', color: 'var(--green)' },
    ],
    response_cutoff: 0.074,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: false,
    references: ['EuroQol Group, 1990, Health Policy'],
    notes: 'Utility index used in health economic analyses (QALYs). EQ-5D-5L preferred over 3L. License required from EuroQol.',
  },

  {
    id: 'qols',
    name: 'Quality of Life Scale',
    abbr: 'QOLS',
    conditions: ['Schizophrenia', 'MDD', 'Chronic conditions'],
    domains: ['Material comfort', 'Health', 'Relationships', 'Activities', 'Personal development', 'Independence'],
    rater: 'self',
    items: 16,
    min_score: 16,
    max_score: 112,
    admin_time_min: 10,
    scoring_bands: [
      { range: [16, 64],  label: 'Low QoL',      color: 'var(--red)' },
      { range: [65, 89],  label: 'Moderate QoL', color: 'var(--amber)' },
      { range: [90, 112], label: 'High QoL',     color: 'var(--green)' },
    ],
    response_cutoff: 7,
    remission_cutoff: 89,
    frequency: 'monthly',
    open_access: true,
    references: ['Burckhardt & Anderson, 2003, Qual Life Res'],
    notes: '7-point satisfaction scale per domain. Widely used in fibromyalgia and schizophrenia studies.',
  },

  // ── EATING DISORDERS ──────────────────────────────────────────────────────

  {
    id: 'edeq',
    name: 'Eating Disorder Examination Questionnaire',
    abbr: 'EDE-Q',
    conditions: ['Anorexia Nervosa', 'Bulimia Nervosa', 'Binge Eating Disorder'],
    domains: ['Restraint', 'Eating concern', 'Shape concern', 'Weight concern'],
    rater: 'self',
    items: 28,
    min_score: 0,
    max_score: 6,
    admin_time_min: 15,
    scoring_bands: [
      { range: [0, 2.3],  label: 'Community norms',            color: 'var(--green)' },
      { range: [2.4, 3.4], label: 'Elevated — clinical concern', color: 'var(--amber)' },
      { range: [3.5, 6],  label: 'Clinically significant ED',   color: 'var(--red)' },
    ],
    response_cutoff: 1.0,
    remission_cutoff: 2.3,
    frequency: 'monthly',
    open_access: true,
    references: ['Fairburn & Beglin, 1994, Int J Eat Disord'],
    notes: 'Global score = mean of 4 subscales. Self-report adaptation of the EDE clinician interview.',
  },

  {
    id: 'eat26',
    name: 'Eating Attitudes Test-26',
    abbr: 'EAT-26',
    conditions: ['Anorexia Nervosa', 'Bulimia Nervosa', 'Eating Disorders NOS'],
    domains: ['Dieting', 'Bulimia/Food preoccupation', 'Oral control'],
    rater: 'self',
    items: 26,
    min_score: 0,
    max_score: 78,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 19],  label: 'Below threshold',    color: 'var(--green)' },
      { range: [20, 78], label: 'Abnormal eating attitudes — refer', color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 19,
    frequency: 'monthly',
    open_access: true,
    references: ['Garner et al., 1982, Psychol Med'],
    notes: 'Score ≥20 = clinical follow-up recommended. Widely used as screening tool.',
  },

  {
    id: 'biss',
    name: 'Body Image Satisfaction Scale',
    abbr: 'BISS',
    conditions: ['Anorexia Nervosa', 'Bulimia Nervosa', 'Body Dysmorphic Disorder'],
    domains: ['Body image satisfaction', 'Body dissatisfaction'],
    rater: 'self',
    items: 10,
    min_score: 0,
    max_score: 60,
    admin_time_min: 5,
    scoring_bands: [
      { range: [0, 20],  label: 'High satisfaction',  color: 'var(--green)' },
      { range: [21, 40], label: 'Moderate concern',   color: 'var(--amber)' },
      { range: [41, 60], label: 'Significant dissatisfaction', color: 'var(--red)' },
    ],
    response_cutoff: 8,
    remission_cutoff: 20,
    frequency: 'monthly',
    open_access: true,
    references: ['Berscheid et al., 1973; updated versions'],
    notes: 'Used alongside EDE-Q in eating disorder TMS trials to capture body image dimension.',
  },

  // ── AUTISM / NEURO ────────────────────────────────────────────────────────

  {
    id: 'srs2',
    name: 'Social Responsiveness Scale — Second Edition',
    abbr: 'SRS-2',
    conditions: ['ASD', 'ADHD', 'OCD'],
    domains: ['Social awareness', 'Social cognition', 'Social communication', 'Social motivation', 'Restricted/repetitive behaviours'],
    rater: 'parent',
    items: 65,
    min_score: 65,
    max_score: 195,
    admin_time_min: 15,
    scoring_bands: [
      { range: [65, 75],   label: 'Normal (T<60)',                  color: 'var(--green)' },
      { range: [76, 90],   label: 'Mild-Moderate (T 60–75)',        color: 'var(--amber)' },
      { range: [91, 195],  label: 'Severe (T>75)',                  color: 'var(--red)' },
    ],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'every 6 months',
    open_access: false,
    references: ['Constantino & Gruber, 2012, Western Psychological Services'],
    notes: 'T-score based; parent, teacher and self-report (SRS-2 Adult) forms. WPS license required.',
  },

  {
    id: 'ados-2-screen',
    name: 'ADOS-2 Screening (Module Screener)',
    abbr: 'ADOS-2',
    conditions: ['ASD'],
    domains: ['Social affect', 'Restricted/repetitive behaviours', 'Communication'],
    rater: 'clinician',
    items: null,
    min_score: 0,
    max_score: null,
    admin_time_min: 45,
    scoring_bands: [],
    response_cutoff: null,
    remission_cutoff: null,
    frequency: 'once',
    open_access: false,
    references: ['Lord et al., 2012, Western Psychological Services'],
    notes: 'Gold-standard observational diagnostic tool. 4 modules by language/age. Requires ADOS-2 certification training.',
  },

  {
    id: 'abc',
    name: 'Aberrant Behavior Checklist',
    abbr: 'ABC',
    conditions: ['ASD', 'Intellectual Disability'],
    domains: ['Irritability', 'Social withdrawal', 'Stereotypy', 'Hyperactivity', 'Inappropriate speech'],
    rater: 'informant',
    items: 58,
    min_score: 0,
    max_score: 174,
    admin_time_min: 15,
    scoring_bands: [
      { range: [0, 30],   label: 'Minimal',   color: 'var(--green)' },
      { range: [31, 60],  label: 'Mild',      color: 'var(--teal)' },
      { range: [61, 100], label: 'Moderate',  color: 'var(--amber)' },
      { range: [101, 174], label: 'Severe',   color: 'var(--red)' },
    ],
    response_cutoff: 12,
    remission_cutoff: 30,
    frequency: 'monthly',
    open_access: false,
    references: ['Aman et al., 1985, Am J Ment Defic'],
    notes: 'Primary outcome in many ASD and ID intervention studies. Pro-Ed license required.',
  },

  {
    id: 'updrs-iii',
    name: 'Unified Parkinson Disease Rating Scale — Part III (Motor)',
    abbr: 'UPDRS-III',
    conditions: ['Parkinson Disease'],
    domains: ['Tremor', 'Rigidity', 'Bradykinesia', 'Postural instability', 'Gait'],
    rater: 'clinician',
    items: 33,
    min_score: 0,
    max_score: 132,
    admin_time_min: 25,
    scoring_bands: [
      { range: [0, 32],   label: 'Mild',      color: 'var(--teal)' },
      { range: [33, 58],  label: 'Moderate',  color: 'var(--amber)' },
      { range: [59, 132], label: 'Severe',    color: 'var(--red)' },
    ],
    response_cutoff: 10,
    remission_cutoff: null,
    frequency: 'monthly',
    open_access: true,
    references: ['Fahn & Elton, 1987, UPDRS Development Committee'],
    notes: 'MDS-UPDRS (revised 2008) is current standard. OFF-state assessment; primary motor outcome for TMS/TPS in PD.',
  },

  {
    id: 'pdq39',
    name: "Parkinson's Disease Questionnaire-39",
    abbr: 'PDQ-39',
    conditions: ["Parkinson Disease"],
    domains: ['Mobility', 'ADL', 'Emotional wellbeing', 'Stigma', 'Social support', 'Cognitions', 'Communication', 'Bodily discomfort'],
    rater: 'self',
    items: 39,
    min_score: 0,
    max_score: 100,
    admin_time_min: 20,
    scoring_bands: [
      { range: [0, 24],  label: 'Good QoL',     color: 'var(--green)' },
      { range: [25, 49], label: 'Moderate QoL', color: 'var(--amber)' },
      { range: [50, 100], label: 'Poor QoL',    color: 'var(--red)' },
    ],
    response_cutoff: 4.72,
    remission_cutoff: null,
    frequency: 'every 3 months',
    open_access: false,
    references: ["Jenkinson et al., 1997, Age Ageing"],
    notes: 'PDQ-39 SI (summary index) = mean of 8 dimension scores × 100. Oxford license required.',
  },

  {
    id: 'abc-parkinson',
    name: 'Activities-specific Balance Confidence Scale',
    abbr: 'ABC',
    conditions: ['Parkinson Disease', 'Vestibular Disorders', 'Falls Risk'],
    domains: ['Balance confidence', 'Fall-related self-efficacy'],
    rater: 'self',
    items: 16,
    min_score: 0,
    max_score: 100,
    admin_time_min: 5,
    scoring_bands: [
      { range: [80, 100], label: 'High functioning',     color: 'var(--green)' },
      { range: [50, 79],  label: 'Moderate functioning', color: 'var(--amber)' },
      { range: [0, 49],   label: 'Low functioning',      color: 'var(--red)' },
    ],
    response_cutoff: 11,
    remission_cutoff: 79,
    frequency: 'monthly',
    open_access: true,
    references: ['Powell & Myers, 1995, J Gerontol'],
    notes: 'Percentage confidence (0–100%) in 16 activities. Score <67% = elevated fall risk in PD.',
  },

];

// ── Derived lookups ────────────────────────────────────────────────────────

export const ASSESSMENT_BY_ID = Object.fromEntries(ASSESSMENTS.map(a => [a.id, a]));

export const ASSESSMENTS_BY_CONDITION = {};
ASSESSMENTS.forEach(a => {
  a.conditions.forEach(c => {
    if (!ASSESSMENTS_BY_CONDITION[c]) ASSESSMENTS_BY_CONDITION[c] = [];
    ASSESSMENTS_BY_CONDITION[c].push(a);
  });
});

export default ASSESSMENTS;
