/**
 * brain-targets.js
 * DeepSynaps Protocol Studio — Brain Targets Registry
 * Standard 10-20 / 10-10 EEG sites + key anatomical neuromodulation targets
 * with clinical metadata for protocol building.
 */

export const BRAIN_TARGETS = [
  // ─── Standard 10-20 EEG Sites ──────────────────────────────────────────────
  {
    id: 'fp1',
    label: 'Fp1',
    full_name: 'Left Frontopolar',
    system: '10-20',
    eeg_electrode: 'Fp1',
    coordinates_mni: [-18, 66, 0],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '10/11',
    primary_conditions: ['OCD', 'BDD', 'PMDD', 'Insomnia'],
    typical_protocols: ['tDCS cathodal (inhibitory)', 'LF-TMS 1Hz'],
    notes: 'Approximates OFC/frontopolar cortex; used in OCD and mood regulation protocols.',
  },
  {
    id: 'fp2',
    label: 'Fp2',
    full_name: 'Right Frontopolar',
    system: '10-20',
    eeg_electrode: 'Fp2',
    coordinates_mni: [18, 66, 0],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '10/11',
    primary_conditions: ['OCD', 'Panic Disorder', 'PMDD', 'Insomnia'],
    typical_protocols: ['tDCS cathodal (inhibitory)', 'LF-TMS 1Hz'],
    notes: 'Right frontopolar; pairs with Fp1 for bilateral OFC targeting in OCD spectrum.',
  },
  {
    id: 'f7',
    label: 'F7',
    full_name: 'Left Inferior Frontal',
    system: '10-20',
    eeg_electrode: 'F7',
    coordinates_mni: [-50, 30, 0],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '45/47',
    primary_conditions: ['Stroke Aphasia', 'Social Anxiety', 'MDD'],
    typical_protocols: ['LF-TMS 1Hz (over right homologue)', 'tDCS cathodal right / anodal left'],
    notes: 'Approximates left IFG / Broca area; critical for language and aphasia rehabilitation.',
  },
  {
    id: 'f3',
    label: 'F3',
    full_name: 'Left Dorsolateral Prefrontal Cortex',
    system: '10-20',
    eeg_electrode: 'F3',
    coordinates_mni: [-46, 36, 20],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '9/46',
    primary_conditions: ['MDD', 'TRD', 'PTSD', 'ADHD', 'Schizophrenia Negative'],
    typical_protocols: ['HF-TMS 10Hz excitatory', 'iTBS', 'tDCS anodal'],
    notes: 'Primary MDD target. Excitatory stimulation increases left prefrontal activity, counteracting hypoactivation in depression.',
  },
  {
    id: 'fz',
    label: 'Fz',
    full_name: 'Medial Prefrontal / Supplementary Motor Area',
    system: '10-20',
    eeg_electrode: 'Fz',
    coordinates_mni: [0, 26, 54],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '6/8/9',
    primary_conditions: ['OCD', 'Social Anxiety', 'ADHD', 'Tourette', 'Depression Negative Symptoms'],
    typical_protocols: ['Deep TMS dH-coil DMPFC', 'tDCS anodal', 'Neurofeedback theta/beta'],
    notes: 'Approximates DMPFC and pre-SMA. BrainsWay deep TMS FDA-cleared OCD target; also used for social anxiety and SMA motor suppression.',
  },
  {
    id: 'f4',
    label: 'F4',
    full_name: 'Right Dorsolateral Prefrontal Cortex',
    system: '10-20',
    eeg_electrode: 'F4',
    coordinates_mni: [46, 36, 20],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '9/46',
    primary_conditions: ['MDD', 'GAD', 'Panic Disorder', 'Insomnia', 'Substance Use'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'cTBS', 'tDCS cathodal'],
    notes: 'Right DLPFC inhibition reduces hyperactivation in anxiety. Bilateral protocols pair F3 (excite) + F4 (inhibit) for MDD.',
  },
  {
    id: 'f8',
    label: 'F8',
    full_name: 'Right Inferior Frontal',
    system: '10-20',
    eeg_electrode: 'F8',
    coordinates_mni: [50, 30, 0],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '45/47',
    primary_conditions: ['Stroke Aphasia', 'Social Anxiety'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'cTBS'],
    notes: 'Right IFG homologue of Broca; inhibitory TMS here disinhibits left language network in aphasia rehabilitation.',
  },
  {
    id: 't3',
    label: 'T7 (T3)',
    full_name: 'Left Mid-Temporal',
    system: '10-20',
    eeg_electrode: 'T7',
    coordinates_mni: [-60, -20, 0],
    lobe: 'Temporal',
    hemisphere: 'Left',
    ba: '21/22',
    primary_conditions: ['Schizophrenia AVH', 'Tinnitus', 'Stroke Aphasia'],
    typical_protocols: ['LF-TMS 1Hz inhibitory for AVH', 'tDCS cathodal for tinnitus'],
    notes: 'Formerly T3 in 10-20; approximates left superior/middle temporal gyrus. Primary target for auditory verbal hallucinations in schizophrenia.',
  },
  {
    id: 'c3',
    label: 'C3',
    full_name: 'Left Central / Motor Cortex',
    system: '10-20',
    eeg_electrode: 'C3',
    coordinates_mni: [-40, -16, 60],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '4/6',
    primary_conditions: ['Stroke Motor (Right Hemiparesis)', 'Chronic Pain', 'Neuropathic Pain', 'CRPS', 'Parkinson'],
    typical_protocols: ['HF-TMS 10Hz excitatory', 'tDCS anodal', 'Motor cortex mapping'],
    notes: 'Left M1; excitatory stimulation for right-sided motor rehabilitation. Analgesic via descending inhibition of spinal pain processing.',
  },
  {
    id: 'cz',
    label: 'Cz',
    full_name: 'Vertex / Supplementary Motor Area',
    system: '10-20',
    eeg_electrode: 'Cz',
    coordinates_mni: [0, -10, 74],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '6',
    primary_conditions: ['Tourette', 'Essential Tremor', 'Dystonia', 'Epilepsy', 'SCI Rehab'],
    typical_protocols: ['LF-TMS 1Hz SMA inhibitory', 'cTBS', 'Sham-controlled trials'],
    notes: 'Vertex site overlying SMA and leg motor cortex. Primary Tourette target for tic suppression; also used in spasticity management.',
  },
  {
    id: 'c4',
    label: 'C4',
    full_name: 'Right Central / Motor Cortex',
    system: '10-20',
    eeg_electrode: 'C4',
    coordinates_mni: [40, -16, 60],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '4/6',
    primary_conditions: ['Stroke Motor (Left Hemiparesis)', 'Neuropathic Pain', 'Chronic Pain'],
    typical_protocols: ['HF-TMS 10Hz excitatory', 'tDCS anodal', 'LF-TMS inhibitory (contralesional)'],
    notes: 'Right M1; excitatory for left-sided stroke rehab; inhibitory cTBS used to suppress contralesional over-excitation in stroke protocols.',
  },
  {
    id: 't4',
    label: 'T8 (T4)',
    full_name: 'Right Mid-Temporal',
    system: '10-20',
    eeg_electrode: 'T8',
    coordinates_mni: [60, -20, 0],
    lobe: 'Temporal',
    hemisphere: 'Right',
    ba: '21/22',
    primary_conditions: ['Tinnitus', 'Schizophrenia', 'Music cognition'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'tDCS cathodal'],
    notes: 'Formerly T4; right temporal cortex involved in prosody, music processing, and right-lateralised tinnitus.',
  },
  {
    id: 't5',
    label: 'P7 (T5)',
    full_name: 'Left Temporoparietal',
    system: '10-20',
    eeg_electrode: 'P7',
    coordinates_mni: [-54, -56, 8],
    lobe: 'Temporal',
    hemisphere: 'Left',
    ba: '39/22',
    primary_conditions: ['Schizophrenia AVH', 'Tinnitus', 'Stroke Aphasia', 'Neglect'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'tDCS cathodal'],
    notes: 'Formerly T5; left temporoparietal junction. Critically involved in language, AVH generation, and self-referential processing.',
  },
  {
    id: 'p3',
    label: 'P3',
    full_name: 'Left Parietal',
    system: '10-20',
    eeg_electrode: 'P3',
    coordinates_mni: [-32, -60, 48],
    lobe: 'Parietal',
    hemisphere: 'Left',
    ba: '39/40',
    primary_conditions: ['Alzheimer\'s Disease', 'MCI', 'ADHD', 'Neglect', 'Stroke Aphasia'],
    typical_protocols: ['tDCS anodal (memory)', 'HF-TMS excitatory', 'tACS gamma'],
    notes: 'Left inferior parietal lobule; involved in working memory, semantic processing, and spatial attention.',
  },
  {
    id: 'pz',
    label: 'Pz',
    full_name: 'Midline Parietal / Precuneus',
    system: '10-20',
    eeg_electrode: 'Pz',
    coordinates_mni: [0, -54, 60],
    lobe: 'Parietal',
    hemisphere: 'Midline',
    ba: '7/5',
    primary_conditions: ['Alzheimer\'s Disease', 'MCI', 'Long COVID Neurocognitive'],
    typical_protocols: ['tDCS anodal', 'tACS alpha/gamma', 'Neurofeedback P300'],
    notes: 'Precuneus / posterior parietal cortex; default mode network hub. Targeted in dementia and consciousness research.',
  },
  {
    id: 'p4',
    label: 'P4',
    full_name: 'Right Parietal',
    system: '10-20',
    eeg_electrode: 'P4',
    coordinates_mni: [32, -60, 48],
    lobe: 'Parietal',
    hemisphere: 'Right',
    ba: '39/40',
    primary_conditions: ['Neglect', 'Spatial Processing', 'Stroke Motor'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'tDCS cathodal'],
    notes: 'Right inferior parietal lobule; spatial attention and visuospatial processing. Inhibitory TMS can reduce hemispatial neglect.',
  },
  {
    id: 't6',
    label: 'P8 (T6)',
    full_name: 'Right Temporoparietal',
    system: '10-20',
    eeg_electrode: 'P8',
    coordinates_mni: [54, -56, 8],
    lobe: 'Temporal',
    hemisphere: 'Right',
    ba: '39/22',
    primary_conditions: ['Tinnitus', 'Spatial Processing'],
    typical_protocols: ['LF-TMS 1Hz', 'tDCS cathodal'],
    notes: 'Formerly T6; right temporoparietal junction; involved in social cognition and right-lateralised tinnitus.',
  },
  {
    id: 'o1',
    label: 'O1',
    full_name: 'Left Occipital / Primary Visual Cortex',
    system: '10-20',
    eeg_electrode: 'O1',
    coordinates_mni: [-20, -92, 12],
    lobe: 'Occipital',
    hemisphere: 'Left',
    ba: '17/18',
    primary_conditions: ['Chronic Migraine', 'Visual Processing', 'LBD'],
    typical_protocols: ['LF-TMS 1Hz inhibitory (migraine prevention)', 'tDCS cathodal'],
    notes: 'Left primary visual cortex V1; high-frequency TMS may trigger phosphenes during mapping. Used in migraine prevention protocols.',
  },
  {
    id: 'oz',
    label: 'Oz',
    full_name: 'Midline Occipital / Striate Cortex',
    system: '10-20',
    eeg_electrode: 'Oz',
    coordinates_mni: [0, -98, 8],
    lobe: 'Occipital',
    hemisphere: 'Midline',
    ba: '17',
    primary_conditions: ['Chronic Migraine', 'Visual Evoked Potential Assessment'],
    typical_protocols: ['LF-TMS 1Hz', 'tDCS cathodal', 'tACS visual alpha entrainment'],
    notes: 'Central occipital pole; primary visual cortex. Important reference point for occipital neuromodulation.',
  },
  {
    id: 'o2',
    label: 'O2',
    full_name: 'Right Occipital / Primary Visual Cortex',
    system: '10-20',
    eeg_electrode: 'O2',
    coordinates_mni: [20, -92, 12],
    lobe: 'Occipital',
    hemisphere: 'Right',
    ba: '17/18',
    primary_conditions: ['Chronic Migraine', 'Visual Processing'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'tDCS cathodal'],
    notes: 'Right primary visual cortex; paired with O1/Oz for bilateral migraine prevention protocols.',
  },

  // ─── 10-10 Extended Sites ──────────────────────────────────────────────────
  {
    id: 'afz',
    label: 'AFz',
    full_name: 'Anterior Frontocentral / ACC-DMPFC Junction',
    system: '10-10',
    eeg_electrode: 'AFz',
    coordinates_mni: [0, 40, 30],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '32/24',
    primary_conditions: ['OCD', 'Social Anxiety', 'Chronic Pain'],
    typical_protocols: ['Deep TMS dH-coil (ACC target)', 'tDCS anodal'],
    notes: 'Closest surface approximation to ACC. BrainsWay bilateral DMPFC-OFC protocol for OCD spans Fz-AFz.',
  },
  {
    id: 'af3',
    label: 'AF3',
    full_name: 'Left Anterior Frontal',
    system: '10-10',
    eeg_electrode: 'AF3',
    coordinates_mni: [-30, 56, 18],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '10/46',
    primary_conditions: ['MDD', 'ADHD', 'Anxiety'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory'],
    notes: 'Anterior to DLPFC; some HD-tDCS montages target AF3 for prefrontal augmentation.',
  },
  {
    id: 'af4',
    label: 'AF4',
    full_name: 'Right Anterior Frontal',
    system: '10-10',
    eeg_electrode: 'AF4',
    coordinates_mni: [30, 56, 18],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '10/46',
    primary_conditions: ['Anxiety', 'Insomnia'],
    typical_protocols: ['tDCS cathodal', 'LF-TMS inhibitory'],
    notes: 'Anterior right prefrontal; some anxiety protocols target AF4 cathodal with AF3 anodal.',
  },
  {
    id: 'fc1',
    label: 'FC1',
    full_name: 'Left Frontocentral / Pre-Motor',
    system: '10-10',
    eeg_electrode: 'FC1',
    coordinates_mni: [-22, 0, 62],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '6',
    primary_conditions: ['ADHD', 'Stroke Motor', 'Dystonia'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory'],
    notes: 'Between F3 and C3; targets premotor and prefrontal overlap region for motor-executive tasks.',
  },
  {
    id: 'fc2',
    label: 'FC2',
    full_name: 'Right Frontocentral / Pre-Motor',
    system: '10-10',
    eeg_electrode: 'FC2',
    coordinates_mni: [22, 0, 62],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '6',
    primary_conditions: ['ADHD Hyperactive', 'Tourette', 'Dystonia'],
    typical_protocols: ['tDCS cathodal', 'LF-TMS inhibitory'],
    notes: 'Right premotor; relevant for inhibitory control and hyperactivity protocols in ADHD.',
  },
  {
    id: 'fcz',
    label: 'FCz',
    full_name: 'Midline Frontocentral / SMA',
    system: '10-10',
    eeg_electrode: 'FCz',
    coordinates_mni: [0, -4, 66],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '6',
    primary_conditions: ['Tourette', 'Dystonia', 'Epilepsy'],
    typical_protocols: ['LF-TMS 1Hz SMA inhibitory', 'cTBS'],
    notes: 'Supplementary motor area (SMA) midline target. Used in tic suppression and premotor inhibition protocols.',
  },
  {
    id: 'cp3',
    label: 'CP3',
    full_name: 'Left Centroparietal / Somatosensory',
    system: '10-10',
    eeg_electrode: 'CP3',
    coordinates_mni: [-36, -34, 58],
    lobe: 'Parietal',
    hemisphere: 'Left',
    ba: '1/2/3/40',
    primary_conditions: ['Chronic Pain', 'CRPS', 'Phantom Limb Pain', 'Stroke Rehab'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory'],
    notes: 'Primary somatosensory cortex (S1) left; key for pain neuromodulation and sensory rehabilitation after stroke.',
  },
  {
    id: 'cp4',
    label: 'CP4',
    full_name: 'Right Centroparietal / Somatosensory',
    system: '10-10',
    eeg_electrode: 'CP4',
    coordinates_mni: [36, -34, 58],
    lobe: 'Parietal',
    hemisphere: 'Right',
    ba: '1/2/3/40',
    primary_conditions: ['Chronic Pain', 'CRPS Right', 'Stroke Rehab'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory'],
    notes: 'Primary somatosensory cortex (S1) right; somatotopic mapping guides precise limb-specific pain targeting.',
  },
  {
    id: 'cpz',
    label: 'CPz',
    full_name: 'Midline Centroparietal',
    system: '10-10',
    eeg_electrode: 'CPz',
    coordinates_mni: [0, -30, 66],
    lobe: 'Parietal',
    hemisphere: 'Midline',
    ba: '5/7',
    primary_conditions: ['Chronic Pain', 'SCI Rehab'],
    typical_protocols: ['tDCS anodal', 'Neurofeedback sensorimotor'],
    notes: 'Posterior SMA / superior parietal; used in BCI and sensorimotor rhythm neurofeedback protocols.',
  },
  {
    id: 'po3',
    label: 'PO3',
    full_name: 'Left Parieto-Occipital',
    system: '10-10',
    eeg_electrode: 'PO3',
    coordinates_mni: [-24, -72, 44],
    lobe: 'Parietal',
    hemisphere: 'Left',
    ba: '19/39',
    primary_conditions: ['Migraine', 'Visual Processing', 'Neglect'],
    typical_protocols: ['LF-TMS inhibitory', 'tDCS cathodal'],
    notes: 'Transition zone between parietal and visual association cortex.',
  },
  {
    id: 'po4',
    label: 'PO4',
    full_name: 'Right Parieto-Occipital',
    system: '10-10',
    eeg_electrode: 'PO4',
    coordinates_mni: [24, -72, 44],
    lobe: 'Parietal',
    hemisphere: 'Right',
    ba: '19/39',
    primary_conditions: ['Migraine', 'Spatial Processing'],
    typical_protocols: ['LF-TMS inhibitory', 'tDCS cathodal'],
    notes: 'Right parieto-occipital junction; contributes to visuospatial processing.',
  },
  {
    id: 'poz',
    label: 'POz',
    full_name: 'Midline Parieto-Occipital',
    system: '10-10',
    eeg_electrode: 'POz',
    coordinates_mni: [0, -76, 38],
    lobe: 'Occipital',
    hemisphere: 'Midline',
    ba: '19/7',
    primary_conditions: ['Migraine', 'Visual Alpha Entrainment'],
    typical_protocols: ['tACS alpha 10Hz', 'LF-TMS inhibitory'],
    notes: 'Parieto-occipital sulcus region; key for visual alpha entrainment with tACS.',
  },

  // ─── Key Anatomical Neuromodulation Targets ────────────────────────────────
  {
    id: 'dlpfc-l',
    label: 'DLPFC-L',
    full_name: 'Left Dorsolateral Prefrontal Cortex',
    system: 'anatomical',
    eeg_electrode: 'F3',
    coordinates_mni: [-46, 36, 20],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '9/46',
    primary_conditions: ['MDD', 'TRD', 'PTSD', 'ADHD', 'Negative Symptoms', 'Chronic Pain', 'SUD'],
    typical_protocols: ['HF-TMS 10Hz excitatory', 'iTBS', 'tDCS anodal'],
    notes: 'Primary target for MDD; excitatory stimulation increases prefrontal activity and restores top-down emotion regulation.',
  },
  {
    id: 'dlpfc-r',
    label: 'DLPFC-R',
    full_name: 'Right Dorsolateral Prefrontal Cortex',
    system: 'anatomical',
    eeg_electrode: 'F4',
    coordinates_mni: [46, 36, 20],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '9/46',
    primary_conditions: ['MDD', 'GAD', 'PTSD', 'Panic Disorder', 'Insomnia'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'cTBS', 'tDCS cathodal'],
    notes: 'Inhibitory target to reduce right-hemisphere anxiety hyperactivation; bilateral pairing with left DLPFC excitation is common.',
  },
  {
    id: 'dmpfc',
    label: 'DMPFC',
    full_name: 'Dorsomedial Prefrontal Cortex',
    system: 'anatomical',
    eeg_electrode: 'Fz',
    coordinates_mni: [0, 32, 42],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '9/32',
    primary_conditions: ['OCD', 'Social Anxiety', 'PTSD', 'MDD Negative Symptoms', 'Schizophrenia'],
    typical_protocols: ['Deep TMS BrainsWay dH-coil', 'tDCS anodal', 'iTBS'],
    notes: 'FDA-cleared OCD target (BrainsWay deep TMS 2018). Part of the default mode and salience networks.',
  },
  {
    id: 'm1-l',
    label: 'M1-L',
    full_name: 'Left Primary Motor Cortex',
    system: 'anatomical',
    eeg_electrode: 'C3',
    coordinates_mni: [-40, -16, 60],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '4',
    primary_conditions: ['Stroke Motor', 'Parkinson', 'Chronic Pain', 'Neuropathic Pain', 'Fibromyalgia', 'CRPS', 'Phantom Limb Pain'],
    typical_protocols: ['HF-TMS 10Hz excitatory', 'tDCS anodal', 'MEP mapping'],
    notes: 'Motor threshold determination performed here for all TMS protocols. HF-TMS analgesic effects mediated via descending pain modulation.',
  },
  {
    id: 'm1-r',
    label: 'M1-R',
    full_name: 'Right Primary Motor Cortex',
    system: 'anatomical',
    eeg_electrode: 'C4',
    coordinates_mni: [40, -16, 60],
    lobe: 'Frontal',
    hemisphere: 'Right',
    ba: '4',
    primary_conditions: ['Stroke Motor Left', 'Neuropathic Pain Right', 'Essential Tremor', 'Dystonia'],
    typical_protocols: ['LF-TMS 1Hz inhibitory (contralesional)', 'cTBS', 'tDCS cathodal'],
    notes: 'Inhibitory protocols reduce contralesional competition in stroke rehab. Tremor suppression via cTBS.',
  },
  {
    id: 'pfc-medial',
    label: 'mPFC',
    full_name: 'Medial Prefrontal Cortex',
    system: 'anatomical',
    eeg_electrode: 'Fz',
    coordinates_mni: [0, 50, 10],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '10/11',
    primary_conditions: ['Depression', 'Negative Symptoms', 'Substance Use', 'Fear Extinction'],
    typical_protocols: ['Deep TMS', 'tDCS anodal', 'Neurofeedback theta'],
    notes: 'Ventral mPFC involved in fear extinction and reward valuation; more dorsal mPFC in cognitive control.',
  },
  {
    id: 'acc',
    label: 'ACC',
    full_name: 'Anterior Cingulate Cortex',
    system: 'anatomical',
    eeg_electrode: 'AFz',
    coordinates_mni: [0, 30, 20],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '24/32',
    primary_conditions: ['OCD', 'Chronic Pain', 'Depression', 'ADHD'],
    typical_protocols: ['Deep TMS (dH-coil spanning AFz-Fz)', 'tDCS anodal'],
    notes: 'Error-monitoring, conflict detection, and pain affect hub. Part of OCD CSTC circuit; also modulates pain unpleasantness.',
  },
  {
    id: 'ofc',
    label: 'OFC',
    full_name: 'Orbitofrontal Cortex',
    system: 'anatomical',
    eeg_electrode: 'Fp1',
    coordinates_mni: [0, 36, -12],
    lobe: 'Frontal',
    hemisphere: 'Bilateral',
    ba: '11/13',
    primary_conditions: ['OCD', 'BDD', 'Substance Use', 'Eating Disorders'],
    typical_protocols: ['Deep TMS BrainsWay H7-coil', 'tDCS cathodal'],
    notes: 'Core node in OCD\'s CSTC circuit. BrainsWay H7-coil reaches OFC and DMPFC simultaneously in cleared OCD protocol.',
  },
  {
    id: 'vmpfc',
    label: 'VMPFC',
    full_name: 'Ventromedial Prefrontal Cortex',
    system: 'anatomical',
    eeg_electrode: 'Fp1',
    coordinates_mni: [0, 44, -8],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '10/11/32',
    primary_conditions: ['Depression', 'PTSD', 'Fear Extinction', 'Anxiety'],
    typical_protocols: ['Deep TMS', 'tDCS anodal'],
    notes: 'Critical for emotion regulation, extinction memory consolidation, and mood valuation.',
  },
  {
    id: 'sma',
    label: 'SMA',
    full_name: 'Supplementary Motor Area',
    system: 'anatomical',
    eeg_electrode: 'FCz',
    coordinates_mni: [0, 0, 60],
    lobe: 'Frontal',
    hemisphere: 'Midline',
    ba: '6',
    primary_conditions: ['Tourette', 'Dystonia', 'Epilepsy', 'Parkinson'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'cTBS'],
    notes: 'Pre-movement planning and motor initiation; hyperactivity linked to tic generation. 1Hz rTMS reduces tic frequency.',
  },
  {
    id: 'ifg-l',
    label: 'IFG-L',
    full_name: 'Left Inferior Frontal Gyrus (Broca Area)',
    system: 'anatomical',
    eeg_electrode: 'F7',
    coordinates_mni: [-50, 24, 6],
    lobe: 'Frontal',
    hemisphere: 'Left',
    ba: '44/45',
    primary_conditions: ['Stroke Aphasia', 'Language Disorders', 'Social Anxiety'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory (paired with speech therapy)'],
    notes: 'Broca\'s area; expressive language production. Anodal tDCS enhances recovery when perilesional tissue is spared.',
  },
  {
    id: 'ppc-l',
    label: 'PPC-L',
    full_name: 'Left Posterior Parietal Cortex',
    system: 'anatomical',
    eeg_electrode: 'P3',
    coordinates_mni: [-34, -58, 44],
    lobe: 'Parietal',
    hemisphere: 'Left',
    ba: '7/40',
    primary_conditions: ['ADHD Inattentive', 'Neglect', 'MCI', 'Stroke'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory'],
    notes: 'Attentional control and spatial working memory. Anodal tDCS here enhances attention in ADHD and stroke rehabilitation.',
  },
  {
    id: 'spl',
    label: 'SPL',
    full_name: 'Superior Parietal Lobule',
    system: 'anatomical',
    eeg_electrode: 'Pz',
    coordinates_mni: [0, -52, 62],
    lobe: 'Parietal',
    hemisphere: 'Bilateral',
    ba: '7',
    primary_conditions: ['Neglect', 'Stroke Rehab', 'Spatial Processing'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory'],
    notes: 'Dorsal attentional network node; spatial processing and hand-eye coordination. Active target in stroke neglect protocols.',
  },
  {
    id: 's1',
    label: 'S1',
    full_name: 'Primary Somatosensory Cortex',
    system: 'anatomical',
    eeg_electrode: 'CP3',
    coordinates_mni: [-36, -34, 58],
    lobe: 'Parietal',
    hemisphere: 'Left',
    ba: '1/2/3',
    primary_conditions: ['Chronic Pain', 'Neuropathic Pain', 'CRPS', 'Phantom Limb Pain', 'CIPN'],
    typical_protocols: ['tDCS anodal', 'HF-TMS excitatory', 'Sensory gating neurofeedback'],
    notes: 'Somatotopically organised; stimulation coordinates matched to painful body region. Targets central sensitisation.',
  },
  {
    id: 'temporal-l',
    label: 'TEMPORAL-L',
    full_name: 'Left Temporal Cortex (Superior/Middle Temporal Gyrus)',
    system: 'anatomical',
    eeg_electrode: 'T7',
    coordinates_mni: [-56, -24, 4],
    lobe: 'Temporal',
    hemisphere: 'Left',
    ba: '21/22/42',
    primary_conditions: ['Schizophrenia AVH', 'Tinnitus', 'Stroke Aphasia', 'Language Disorders'],
    typical_protocols: ['LF-TMS 1Hz inhibitory (AVH)', 'tDCS cathodal', 'cTBS'],
    notes: 'Left superior temporal gyrus including Wernicke area. Inhibitory TMS at 1Hz reduces auditory hallucination frequency and intensity.',
  },
  {
    id: 'temporal-r',
    label: 'TEMPORAL-R',
    full_name: 'Right Temporal Cortex (Superior/Middle Temporal Gyrus)',
    system: 'anatomical',
    eeg_electrode: 'T8',
    coordinates_mni: [56, -24, 4],
    lobe: 'Temporal',
    hemisphere: 'Right',
    ba: '21/22/42',
    primary_conditions: ['Tinnitus', 'Prosody', 'Music Cognition', 'Social Cognition'],
    typical_protocols: ['LF-TMS 1Hz inhibitory', 'tDCS cathodal'],
    notes: 'Right STG involved in melodic/prosodic processing and tinnitus perception. Combined left+right temporal targeting for bilateral tinnitus.',
  },
  {
    id: 'v1',
    label: 'V1',
    full_name: 'Primary Visual Cortex',
    system: 'anatomical',
    eeg_electrode: 'Oz',
    coordinates_mni: [0, -90, 4],
    lobe: 'Occipital',
    hemisphere: 'Midline',
    ba: '17',
    primary_conditions: ['Chronic Migraine', 'Visual Rehabilitation', 'Phosphene Mapping'],
    typical_protocols: ['LF-TMS 1Hz inhibitory (migraine)', 'tACS 10Hz visual alpha', 'tDCS cathodal'],
    notes: 'Striate cortex; phosphene threshold here used as marker of occipital excitability. Hyperexcitable in migraine.',
  },
  {
    id: 'cerebellum',
    label: 'Cerebellum',
    full_name: 'Cerebellum (Lateral / Midline)',
    system: 'anatomical',
    eeg_electrode: 'Oz',
    coordinates_mni: [0, -60, -30],
    lobe: 'Cerebellar',
    hemisphere: 'Bilateral',
    ba: 'N/A',
    primary_conditions: ['Essential Tremor', 'Ataxia', 'Cognition', 'Dystonia'],
    typical_protocols: ['cTBS (lateral cerebellum)', 'tDCS anodal', 'TPS'],
    notes: 'Lateral cerebellar stimulation modulates the dentate-thalamo-cortical pathway. cTBS reduces tremor amplitude in ET.',
  },

  // ─── Ear / Peripheral Targets ──────────────────────────────────────────────
  {
    id: 'tragus-l',
    label: 'Tragus-L',
    full_name: 'Left Tragus (Auricular Vagus Nerve Branch)',
    system: 'anatomical',
    eeg_electrode: 'N/A',
    coordinates_mni: null,
    lobe: 'Peripheral',
    hemisphere: 'Left',
    ba: 'N/A',
    primary_conditions: ['Epilepsy', 'PTSD', 'Depression', 'Tinnitus', 'Chronic Pain', 'Migraine'],
    typical_protocols: ['taVNS 25Hz / 200µs pulse width'],
    notes: 'Cymba conchae of left ear contains auricular branch of vagus nerve (Arnold\'s nerve). FDA-cleared for epilepsy (gammaCore). Activates NTS, locus coeruleus, and vagal afferent pathways.',
  },
  {
    id: 'tragus-r',
    label: 'Tragus-R',
    full_name: 'Right Tragus (Auricular Vagus Nerve Branch)',
    system: 'anatomical',
    eeg_electrode: 'N/A',
    coordinates_mni: null,
    lobe: 'Peripheral',
    hemisphere: 'Right',
    ba: 'N/A',
    primary_conditions: ['Epilepsy', 'PTSD', 'Cardiac Autonomic Modulation'],
    typical_protocols: ['taVNS 25Hz / 200µs', 'Cardiac-gated taVNS'],
    notes: 'Right ear taVNS has greater cardiac vagal influence; left ear preferred for CNS effects. Cardiac-gated delivery under research investigation.',
  },
  {
    id: 'mastoid-l',
    label: 'Mastoid-L',
    full_name: 'Left Mastoid Process',
    system: 'anatomical',
    eeg_electrode: 'N/A',
    coordinates_mni: null,
    lobe: 'Peripheral',
    hemisphere: 'Left',
    ba: 'N/A',
    primary_conditions: ['Insomnia', 'Anxiety', 'Depression', 'Post-Concussion'],
    typical_protocols: ['CES 100Hz / 500µs (bilateral mastoid-to-mastoid or ear clip)'],
    notes: 'Standard CES electrode placement. Cranial electrical stimulation FDA-cleared for anxiety, insomnia, and depression. Current path: left mastoid → right mastoid.',
  },
  {
    id: 'mastoid-r',
    label: 'Mastoid-R',
    full_name: 'Right Mastoid Process',
    system: 'anatomical',
    eeg_electrode: 'N/A',
    coordinates_mni: null,
    lobe: 'Peripheral',
    hemisphere: 'Right',
    ba: 'N/A',
    primary_conditions: ['Insomnia', 'Anxiety', 'Depression', 'Post-Concussion'],
    typical_protocols: ['CES 100Hz / 500µs (bilateral)'],
    notes: 'Return electrode for standard CES montage. Ear-clip CES places electrodes over earlobes (overlying mastoid region).',
  },
];

export const BRAIN_TARGET_BY_ID = Object.fromEntries(BRAIN_TARGETS.map(t => [t.id, t]));
export const BRAIN_TARGETS_BY_LOBE = {};
BRAIN_TARGETS.forEach(t => {
  if (!BRAIN_TARGETS_BY_LOBE[t.lobe]) BRAIN_TARGETS_BY_LOBE[t.lobe] = [];
  BRAIN_TARGETS_BY_LOBE[t.lobe].push(t);
});
export default BRAIN_TARGETS;
