/**
 * conditions.js
 * DeepSynaps Protocol Studio — Conditions Registry
 * 53 neuromodulation-relevant clinical conditions with evidence metadata.
 */

export const CONDITIONS = [
  // ─── Mood & Affective ───────────────────────────────────────────────────────
  {
    id: 'mdd',
    name: 'Major Depressive Disorder',
    abbr: 'MDD',
    category: 'Mood & Affective',
    icd10: 'F32.9',
    description:
      'A primary mood disorder characterised by persistent low mood, anhedonia, and neurovegetative symptoms lasting at least two weeks. Associated with hypoactivity of the left DLPFC and overactivity of limbic structures.',
    primary_modalities: ['TMS/rTMS', 'iTBS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'A',
    fda_cleared_modalities: ['TMS/rTMS', 'iTBS'],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'DMPFC'],
    typical_sessions: 30,
    key_assessments: ['PHQ-9', 'MADRS', 'HAM-D', 'QIDS'],
    notes: 'FDA-cleared for TMS/rTMS (2008) and iTBS (2018). First-line neuromodulation candidate.',
  },
  {
    id: 'trd',
    name: 'Treatment-Resistant Depression',
    abbr: 'TRD',
    category: 'Mood & Affective',
    icd10: 'F33.9',
    description:
      'Depression that has failed to respond to at least two adequate antidepressant trials of sufficient dose and duration. Requires aggressive, often multimodal neuromodulation strategies targeting bilateral prefrontal circuits.',
    primary_modalities: ['TMS/rTMS', 'iTBS', 'tDCS', 'Multimodal'],
    evidence_grade: 'A',
    fda_cleared_modalities: ['TMS/rTMS', 'iTBS'],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'DMPFC'],
    typical_sessions: 36,
    key_assessments: ['MADRS', 'HAM-D', 'QIDS', 'CGI'],
    notes: 'NeuroStar and BrainsWay FDA-cleared specifically for MDD/TRD. Consider bilateral protocol.',
  },
  {
    id: 'bipolar-i-depression',
    name: 'Bipolar I Depression',
    abbr: 'BP-I',
    category: 'Mood & Affective',
    icd10: 'F31.0',
    description:
      'Depressive episodes occurring in the context of Bipolar I disorder, where manic episodes are also present. Neuromodulation must be applied cautiously given risk of switching to mania.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'DMPFC'],
    typical_sessions: 25,
    key_assessments: ['MADRS', 'HAM-D', 'CGI', 'QIDS'],
    notes: 'Use lower intensity protocols; monitor closely for manic switch. Mood stabiliser co-medication recommended.',
  },
  {
    id: 'bipolar-ii-depression',
    name: 'Bipolar II Depression',
    abbr: 'BP-II',
    category: 'Mood & Affective',
    icd10: 'F31.81',
    description:
      'Recurrent major depressive episodes with at least one hypomanic episode; the predominant pole is depressive. Neuromodulation is increasingly used as an adjunct to mood stabilisers.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R'],
    typical_sessions: 25,
    key_assessments: ['MADRS', 'PHQ-9', 'CGI', 'QIDS'],
    notes: 'Lower mania-switch risk than BP-I but vigilance still required. Track hypomanic symptoms weekly.',
  },
  {
    id: 'postpartum-depression',
    name: 'Postpartum Depression',
    abbr: 'PPD',
    category: 'Mood & Affective',
    icd10: 'F53.0',
    description:
      'A major depressive episode with onset within four weeks of childbirth, associated with hormonal fluctuations and significant functional impairment. TMS offers a medication-minimising option compatible with breastfeeding.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['TMS/rTMS'],
    target_regions: ['DLPFC-L', 'DLPFC-R'],
    typical_sessions: 20,
    key_assessments: ['EPDS', 'PHQ-9', 'HAM-D', 'CGI'],
    notes: 'Non-pharmacological preference due to breastfeeding. EPDS recommended as primary screen.',
  },
  {
    id: 'pmdd',
    name: 'Premenstrual Dysphoric Disorder',
    abbr: 'PMDD',
    category: 'Mood & Affective',
    icd10: 'F32.81',
    description:
      'A cyclic mood disorder with severe affective, somatic, and behavioural symptoms tightly linked to the luteal phase of the menstrual cycle. Emerging evidence supports tDCS and neurofeedback for symptom modulation.',
    primary_modalities: ['tDCS', 'Neurofeedback', 'CES'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'Fp1', 'Fp2'],
    typical_sessions: 15,
    key_assessments: ['DASS-21', 'PHQ-9', 'CGI'],
    notes: 'Treatment timing relative to menstrual cycle phase is an active research variable.',
  },
  {
    id: 'dysthymia',
    name: 'Persistent Depressive Disorder',
    abbr: 'PDD',
    category: 'Mood & Affective',
    icd10: 'F34.1',
    description:
      'A chronic, low-grade depressive condition persisting for at least two years, often with superimposed major depressive episodes (double depression). Neuromodulation may provide durable benefit when pharmacotherapy is inadequate.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DMPFC'],
    typical_sessions: 30,
    key_assessments: ['PHQ-9', 'MADRS', 'QIDS', 'CGI'],
    notes: 'Maintenance sessions every 4-8 weeks may be needed to sustain response.',
  },
  {
    id: 'sad',
    name: 'Seasonal Affective Disorder',
    abbr: 'SAD',
    category: 'Mood & Affective',
    icd10: 'F33.9',
    description:
      'A recurrent depressive disorder with a seasonal pattern, most commonly winter-onset, linked to circadian dysregulation and reduced photic input. Light therapy is first-line; TMS and tDCS are adjunctive options.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'CES'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R'],
    typical_sessions: 20,
    key_assessments: ['PHQ-9', 'MADRS', 'QIDS', 'PSQI'],
    notes: 'Often combined with bright light therapy. Target treatment to onset of symptomatic season.',
  },

  // ─── Anxiety ─────────────────────────────────────────────────────────────────
  {
    id: 'gad',
    name: 'Generalized Anxiety Disorder',
    abbr: 'GAD',
    category: 'Anxiety',
    icd10: 'F41.1',
    description:
      'Characterised by excessive, uncontrollable worry about multiple life domains, accompanied by somatic symptoms such as muscle tension and sleep disturbance. Right DLPFC inhibition and DMPFC modulation are primary targets.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-R', 'DMPFC', 'ACC'],
    typical_sessions: 20,
    key_assessments: ['GAD-7', 'DASS-21', 'CGI'],
    notes: 'Right DLPFC inhibitory (1Hz/cTBS) protocols most studied. Alpha neurofeedback shows promise.',
  },
  {
    id: 'social-anxiety',
    name: 'Social Anxiety Disorder',
    abbr: 'SAD-S',
    category: 'Anxiety',
    icd10: 'F40.10',
    description:
      'Intense fear of social scrutiny or embarrassing oneself in social or performance situations, causing significant avoidance and functional impairment. DMPFC and right DLPFC are primary neuromodulation targets.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DMPFC', 'DLPFC-R', 'Fz'],
    typical_sessions: 20,
    key_assessments: ['LSAS', 'GAD-7', 'DASS-21', 'CGI'],
    notes: 'DMPFC (Fz/AFz) inhibitory TMS under investigation. Combine with CBT exposure when possible.',
  },
  {
    id: 'panic-disorder',
    name: 'Panic Disorder',
    abbr: 'PD',
    category: 'Anxiety',
    icd10: 'F41.0',
    description:
      'Recurrent, unexpected panic attacks with persistent anticipatory anxiety and behavioural changes. Right DLPFC inhibition and prefrontal modulation aim to reduce threat-salience hyperactivation.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'CES'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-R', 'DLPFC-L', 'Fp2'],
    typical_sessions: 20,
    key_assessments: ['PDSS', 'GAD-7', 'DASS-21', 'CGI'],
    notes: 'Limited RCT data; protocols largely adapted from GAD and MDD studies.',
  },
  {
    id: 'specific-phobia',
    name: 'Specific Phobia',
    abbr: 'SP',
    category: 'Anxiety',
    icd10: 'F40.298',
    description:
      'Marked fear or anxiety about a specific object or situation that is disproportionate to actual danger, causing active avoidance. Neuromodulation is exploratory, typically used as an adjunct to exposure therapy.',
    primary_modalities: ['tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'Fp1', 'Fp2'],
    typical_sessions: 15,
    key_assessments: ['DASS-21', 'CGI'],
    notes: 'Research-stage only. Best evidence for tDCS augmentation of exposure therapy sessions.',
  },
  {
    id: 'agoraphobia',
    name: 'Agoraphobia',
    abbr: 'AG',
    category: 'Anxiety',
    icd10: 'F40.00',
    description:
      'Fear and avoidance of situations where escape may be difficult, such as crowds, open spaces, or public transport, often co-occurring with panic disorder. Neuromodulation evidence remains nascent.',
    primary_modalities: ['tDCS', 'Neurofeedback', 'CES'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-R', 'DMPFC'],
    typical_sessions: 15,
    key_assessments: ['GAD-7', 'DASS-21', 'CGI'],
    notes: 'Evidence limited to case series and small pilots; protocols adapted from panic disorder.',
  },

  // ─── Trauma & Stress ─────────────────────────────────────────────────────────
  {
    id: 'ptsd',
    name: 'Post-Traumatic Stress Disorder',
    abbr: 'PTSD',
    category: 'Trauma & Stress',
    icd10: 'F43.10',
    description:
      'A disorder arising after exposure to actual or threatened death, serious injury, or sexual violence, characterised by intrusion, avoidance, negative cognition/mood, and hyperarousal. TMS targeting DLPFC and DMPFC shows substantial trial evidence.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback', 'taVNS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-R', 'DMPFC', 'DLPFC-L'],
    typical_sessions: 20,
    key_assessments: ['PCL-5', 'CAPS-5', 'DASS-21', 'PHQ-9'],
    notes: 'Right DLPFC inhibitory and bilateral DMPFC protocols most studied. FDA Breakthrough Device (BrainsWay).',
  },
  {
    id: 'complex-ptsd',
    name: 'Complex PTSD',
    abbr: 'C-PTSD',
    category: 'Trauma & Stress',
    icd10: 'F43.10',
    description:
      'A variant of PTSD arising from prolonged, repeated traumatic exposure (e.g., childhood abuse, captivity) with additional features of affect dysregulation, negative self-concept, and relational difficulties.',
    primary_modalities: ['TMS/rTMS', 'Neurofeedback', 'tDCS'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'DMPFC'],
    typical_sessions: 25,
    key_assessments: ['PCL-5', 'CAPS-5', 'DASS-21', 'CGI'],
    notes: 'ICD-11 recognised; trauma-informed framing essential. Stabilisation phase before neuromodulation.',
  },
  {
    id: 'acute-stress-disorder',
    name: 'Acute Stress Disorder',
    abbr: 'ASD',
    category: 'Trauma & Stress',
    icd10: 'F43.0',
    description:
      'An acute stress response within the first month following a traumatic event, featuring dissociation, re-experiencing, and hyperarousal. Early intervention may prevent progression to PTSD.',
    primary_modalities: ['tDCS', 'Neurofeedback', 'CES'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-R', 'DLPFC-L'],
    typical_sessions: 10,
    key_assessments: ['PCL-5', 'DASS-21', 'CGI'],
    notes: 'Time-limited, acute intervention window. Very limited RCT evidence.',
  },

  // ─── OCD Spectrum ─────────────────────────────────────────────────────────────
  {
    id: 'ocd',
    name: 'Obsessive-Compulsive Disorder',
    abbr: 'OCD',
    category: 'OCD Spectrum',
    icd10: 'F42.9',
    description:
      'A disorder characterised by recurrent intrusive obsessions and/or compulsions that are time-consuming and cause marked distress. Cortico-striato-thalamo-cortical (CSTC) circuit hyperactivation is the core pathophysiology.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['TMS/rTMS'],
    target_regions: ['OFC', 'DMPFC', 'ACC'],
    typical_sessions: 29,
    key_assessments: ['Y-BOCS', 'CGI', 'DASS-21'],
    notes: 'FDA-cleared for TMS (BrainsWay deep TMS, 2018). Bilateral DMPFC-OFC is the approved target.',
  },
  {
    id: 'bdd',
    name: 'Body Dysmorphic Disorder',
    abbr: 'BDD',
    category: 'OCD Spectrum',
    icd10: 'F45.22',
    description:
      'Preoccupation with perceived defects in physical appearance that are not observable to others, driving repetitive behaviours and significant distress. Shares OCD-spectrum neurobiology involving fronto-striatal circuits.',
    primary_modalities: ['TMS/rTMS', 'tDCS'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['OFC', 'DMPFC', 'Fp1'],
    typical_sessions: 20,
    key_assessments: ['Y-BOCS', 'BDD-YBOCS', 'CGI'],
    notes: 'Off-label; protocols extrapolated from OCD. Very limited independent trial data.',
  },
  {
    id: 'trichotillomania',
    name: 'Trichotillomania',
    abbr: 'TTM',
    category: 'OCD Spectrum',
    icd10: 'F63.3',
    description:
      'Recurrent, compulsive pulling of one\'s own hair resulting in hair loss, distress, and functional impairment. Involves dysregulation of motor-inhibitory circuits and habit loops.',
    primary_modalities: ['TMS/rTMS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DMPFC', 'OFC', 'Fz'],
    typical_sessions: 18,
    key_assessments: ['MGH-HPS', 'Y-BOCS', 'CGI'],
    notes: 'Pilot studies only. SMA/DMPFC inhibitory TMS most studied.',
  },
  {
    id: 'excoriation',
    name: 'Excoriation Disorder',
    abbr: 'ExD',
    category: 'OCD Spectrum',
    icd10: 'L98.1',
    description:
      'Recurrent skin picking resulting in skin lesions, persistent attempts to stop, and clinically significant distress or functional impairment. Shares habit-loop neurobiology with trichotillomania.',
    primary_modalities: ['TMS/rTMS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DMPFC', 'OFC'],
    typical_sessions: 18,
    key_assessments: ['SPS', 'Y-BOCS', 'CGI'],
    notes: 'Very limited neuromodulation evidence. Off-label extrapolation from OCD/TTM studies.',
  },

  // ─── Neurodevelopmental ───────────────────────────────────────────────────────
  {
    id: 'adhd-inattentive',
    name: 'ADHD (Inattentive)',
    abbr: 'ADHD-I',
    category: 'Neurodevelopmental',
    icd10: 'F90.0',
    description:
      'Attention-deficit/hyperactivity disorder predominately inattentive presentation, characterised by sustained attention failure, organisational difficulties, and executive dysfunction. DLPFC and anterior cingulate are key neuromodulation targets.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['Neurofeedback'],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'Fz'],
    typical_sessions: 25,
    key_assessments: ['ADHD-RS-5', 'BRIEF', 'CGI'],
    notes: 'Theta/beta neurofeedback FDA 510(k) cleared (as EEG biofeedback device). DLPFC tDCS anodal left showing efficacy.',
  },
  {
    id: 'adhd-combined',
    name: 'ADHD (Hyperactive/Combined)',
    abbr: 'ADHD-C',
    category: 'Neurodevelopmental',
    icd10: 'F90.2',
    description:
      'ADHD combined presentation with both significant inattention and hyperactivity-impulsivity, representing the most common and impairing subtype. Fronto-striatal network dysfunction is central.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['Neurofeedback'],
    target_regions: ['DLPFC-R', 'DLPFC-L', 'Cz'],
    typical_sessions: 25,
    key_assessments: ['ADHD-RS-5', 'BRIEF', 'CGI'],
    notes: 'Right DLPFC inhibitory TMS to reduce impulsivity; neurofeedback targeting theta/beta ratio.',
  },
  {
    id: 'asd',
    name: 'Autism Spectrum Disorder',
    abbr: 'ASD',
    category: 'Neurodevelopmental',
    icd10: 'F84.0',
    description:
      'A neurodevelopmental condition characterised by persistent deficits in social communication/interaction and restricted, repetitive patterns of behaviour, with heterogeneous presentation across the spectrum.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'Pz'],
    typical_sessions: 18,
    key_assessments: ['ADOS-2', 'SRS-2', 'CGI', 'BRIEF'],
    notes: 'Primarily targets social cognition and repetitive behaviours. Individualised target selection critical.',
  },
  {
    id: 'tourette',
    name: 'Tourette Syndrome / Tic Disorder',
    abbr: 'TS',
    category: 'Neurodevelopmental',
    icd10: 'F95.2',
    description:
      'A childhood-onset neurodevelopmental disorder with multiple motor tics and at least one vocal tic. Supplementary motor area (SMA) hyperactivity and cortical excitability abnormalities are key pathophysiological features.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['Cz', 'DMPFC', 'Fz'],
    typical_sessions: 20,
    key_assessments: ['YGTSS', 'CGI', 'BRIEF'],
    notes: 'SMA/M1 inhibitory TMS (1Hz/cTBS) most studied. Monitor for tic exacerbation during treatment.',
  },

  // ─── Psychotic ────────────────────────────────────────────────────────────────
  {
    id: 'schizophrenia',
    name: 'Schizophrenia',
    abbr: 'SCZ',
    category: 'Psychotic',
    icd10: 'F20.9',
    description:
      'A severe psychiatric disorder characterised by positive symptoms (hallucinations, delusions), negative symptoms, and cognitive impairment. Auditory verbal hallucinations and negative symptoms are primary TMS targets.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['TEMPORAL-L', 'DLPFC-L', 'Cz'],
    typical_sessions: 20,
    key_assessments: ['PANSS', 'BPRS', 'CGI'],
    notes: 'Low-frequency TMS over left temporoparietal cortex for AVH; high-frequency left DLPFC for negative symptoms.',
  },
  {
    id: 'schizoaffective',
    name: 'Schizoaffective Disorder',
    abbr: 'SZA',
    category: 'Psychotic',
    icd10: 'F25.9',
    description:
      'A disorder featuring concurrent psychotic symptoms and prominent mood disorder episodes (depressive or manic), requiring integrated management of both symptom domains.',
    primary_modalities: ['TMS/rTMS', 'tDCS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'TEMPORAL-L'],
    typical_sessions: 20,
    key_assessments: ['PANSS', 'MADRS', 'CGI'],
    notes: 'Protocol selection driven by dominant symptom cluster. Close liaison with prescriber essential.',
  },
  {
    id: 'negative-symptoms',
    name: 'Negative Symptoms (Schizophrenia)',
    abbr: 'NSZ',
    category: 'Psychotic',
    icd10: 'F20.9',
    description:
      'The "deficit" symptoms of schizophrenia — blunted affect, alogia, avolition, anhedonia, and asociality — which are poorly responsive to antipsychotic medication and heavily impact functional recovery.',
    primary_modalities: ['TMS/rTMS', 'iTBS', 'tDCS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DMPFC', 'Fz'],
    typical_sessions: 25,
    key_assessments: ['PANSS', 'SANS', 'CGI'],
    notes: 'HF-TMS and iTBS over left DLPFC specifically for negative symptom cluster. Separate protocol from AVH treatment.',
  },

  // ─── Neurodegenerative ────────────────────────────────────────────────────────
  {
    id: 'parkinsons',
    name: "Parkinson's Disease",
    abbr: 'PD',
    category: 'Neurodegenerative',
    icd10: 'G20',
    description:
      'A progressive neurodegenerative disorder of dopaminergic nigrostriatal neurons, presenting with resting tremor, bradykinesia, rigidity, and postural instability. TMS can modulate motor cortex excitability and facilitate motor rehabilitation.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'DLPFC-L'],
    typical_sessions: 20,
    key_assessments: ['UPDRS-III', 'MDS-UPDRS', 'CGI'],
    notes: 'HF-TMS over M1 improves motor function. DLPFC stimulation targets PD-related depression/cognition.',
  },
  {
    id: 'alzheimers',
    name: "Alzheimer's Disease",
    abbr: 'AD',
    category: 'Neurodegenerative',
    icd10: 'G30.9',
    description:
      'The most common neurodegenerative dementia, characterised by progressive memory loss, cognitive decline, and eventual loss of functional independence, driven by amyloid-beta and tau pathology.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'tACS', 'PBM'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'Pz', 'P3'],
    typical_sessions: 30,
    key_assessments: ['MMSE', 'MoCA', 'ADAS-Cog', 'CGI'],
    notes: 'NeuroAD (Neuronix) CE-marked in Europe. tACS at gamma (40Hz) targeting hippocampal entrainment is under RCT evaluation.',
  },
  {
    id: 'mci',
    name: 'Mild Cognitive Impairment',
    abbr: 'MCI',
    category: 'Neurodegenerative',
    icd10: 'G31.84',
    description:
      'A syndrome of cognitive decline greater than expected for age without significant impairment in activities of daily living, representing a high-risk transitional state between normal ageing and dementia.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'tACS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'P3', 'Pz'],
    typical_sessions: 20,
    key_assessments: ['MoCA', 'MMSE', 'CGI'],
    notes: 'Intervention at MCI stage may delay conversion to dementia. Gamma-frequency tACS under investigation.',
  },
  {
    id: 'lewy-body-dementia',
    name: 'Lewy Body Dementia',
    abbr: 'LBD',
    category: 'Neurodegenerative',
    icd10: 'G31.83',
    description:
      'A progressive dementia characterised by fluctuating cognition, visual hallucinations, Parkinsonism, and REM sleep behaviour disorder, associated with alpha-synuclein Lewy body pathology.',
    primary_modalities: ['tDCS', 'TPS', 'PBM'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'Pz', 'O1'],
    typical_sessions: 15,
    key_assessments: ['MMSE', 'MoCA', 'NPI', 'CGI'],
    notes: 'Extreme caution with TMS due to DLB sensitivity to medications and fluctuating arousal. Very limited evidence base.',
  },
  {
    id: 'essential-tremor',
    name: 'Essential Tremor',
    abbr: 'ET',
    category: 'Neurodegenerative',
    icd10: 'G25.0',
    description:
      'The most common movement disorder, characterised by action and postural tremor primarily affecting the hands, often with cerebellar network involvement. Cerebellar TMS can modulate tremor via cerebello-thalamo-cortical pathways.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'TPS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'Cz'],
    typical_sessions: 15,
    key_assessments: ['TETRAS', 'UPDRS-III', 'CGI'],
    notes: 'Cerebellar cTBS and M1 inhibitory protocols are primary approaches. Differentiate from Parkinson tremor at rest.',
  },
  {
    id: 'dystonia',
    name: 'Dystonia',
    abbr: 'DYS',
    category: 'Neurodegenerative',
    icd10: 'G24.9',
    description:
      'A movement disorder of sustained or intermittent muscle contractions causing abnormal, often repetitive movements and postures, involving basal ganglia-thalamocortical circuit dysfunction.',
    primary_modalities: ['TMS/rTMS', 'tDCS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'Cz'],
    typical_sessions: 15,
    key_assessments: ['BFMDRS', 'TWSTRS', 'CGI'],
    notes: 'Inhibitory TMS over M1 most studied for focal cervical dystonia. Consider topographic specificity.',
  },

  // ─── Neurological ─────────────────────────────────────────────────────────────
  {
    id: 'stroke-motor',
    name: 'Stroke Rehabilitation (Motor)',
    abbr: 'CVA-M',
    category: 'Neurological',
    icd10: 'I69.391',
    description:
      'Motor deficits following ischaemic or haemorrhagic stroke, including hemiparesis, spasticity, and fine motor impairment. Interhemispheric competition modelling guides dual-site TMS to inhibit contralesional M1 and excite ipsilesional M1.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Multimodal'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'Cz'],
    typical_sessions: 20,
    key_assessments: ['FMA-UE', 'NIHSS', 'mRS', 'CGI'],
    notes: 'Timing relative to stroke onset matters; subacute phase (2 weeks–6 months) most studied. Pair with physiotherapy.',
  },
  {
    id: 'stroke-aphasia',
    name: 'Stroke Rehabilitation (Aphasia)',
    abbr: 'CVA-A',
    category: 'Neurological',
    icd10: 'I69.320',
    description:
      'Language deficits (expressive, receptive, or mixed) following left hemisphere stroke. Inhibitory TMS over right IFG (Broca homologue) aims to disinhibit perilesional language networks.',
    primary_modalities: ['TMS/rTMS', 'tDCS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['IFG-L', 'TEMPORAL-L', 'Fz'],
    typical_sessions: 15,
    key_assessments: ['WAB-R', 'BNT', 'CGI'],
    notes: 'Pair with speech-language therapy. 1Hz rTMS over right IFG most studied protocol.',
  },
  {
    id: 'tbi',
    name: 'Traumatic Brain Injury',
    abbr: 'TBI',
    category: 'Neurological',
    icd10: 'S09.90',
    description:
      'Brain dysfunction caused by external physical force, ranging from concussion to severe injury, with lasting cognitive, emotional, and somatic sequelae depending on lesion location and severity.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback', 'PBM'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'Fz'],
    typical_sessions: 20,
    key_assessments: ['MOCA', 'BRIEF', 'PHQ-9', 'CGI'],
    notes: 'Exclude active seizure disorder before TMS. Avoid stimulation over skull defects or metallic implants.',
  },
  {
    id: 'post-concussion',
    name: 'Post-Concussion Syndrome',
    abbr: 'PCS',
    category: 'Neurological',
    icd10: 'S09.90',
    description:
      'A cluster of persistent symptoms including headache, cognitive difficulties, fatigue, mood disturbance, and sleep disruption following mild traumatic brain injury, lasting beyond the expected recovery window.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback', 'PBM'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'Fz'],
    typical_sessions: 20,
    key_assessments: ['PCSS', 'PHQ-9', 'MoCA', 'PSQI'],
    notes: 'Subsymptom threshold approach; begin at lower intensities. Cognitive exertion monitoring essential.',
  },
  {
    id: 'multiple-sclerosis',
    name: 'Multiple Sclerosis',
    abbr: 'MS',
    category: 'Neurological',
    icd10: 'G35',
    description:
      'A chronic autoimmune demyelinating disease of the central nervous system causing episodic or progressive neurological deficits including fatigue, spasticity, cognitive impairment, and mood disturbance.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'DLPFC-L'],
    typical_sessions: 15,
    key_assessments: ['EDSS', 'MoCA', 'PHQ-9', 'PSQI'],
    notes: 'Avoid stimulation during active relapse. Targets vary by dominant symptom domain (fatigue, spasticity, cognition).',
  },
  {
    id: 'epilepsy',
    name: 'Drug-Resistant Epilepsy',
    abbr: 'DRE',
    category: 'Neurological',
    icd10: 'G40.909',
    description:
      'Epilepsy that has failed two or more appropriate antiseizure medications, representing approximately one-third of all epilepsy patients. Low-frequency TMS aims to reduce cortical excitability at seizure foci.',
    primary_modalities: ['TMS/rTMS', 'taVNS'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['taVNS'],
    target_regions: ['Cz', 'Fz', 'M1-L'],
    typical_sessions: 20,
    key_assessments: ['Seizure diary', 'QOLIE-31', 'CGI'],
    notes: 'taVNS FDA-cleared as adjunctive therapy for partial-onset seizures. TMS requires careful cortical mapping.',
  },
  {
    id: 'chronic-migraine',
    name: 'Chronic Migraine',
    abbr: 'CM',
    category: 'Neurological',
    icd10: 'G43.709',
    description:
      'Headache occurring 15 or more days per month for more than three months, with migrainous features on at least 8 days, associated with cortical hyperexcitability and trigeminovascular sensitisation.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'tACS'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['TMS/rTMS'],
    target_regions: ['O1', 'O2', 'Oz'],
    typical_sessions: 15,
    key_assessments: ['MIDAS', 'NRS-Pain', 'HIT-6', 'CGI'],
    notes: 'eNeura SpringTMS FDA-cleared (2013) for acute migraine with aura. Occipital cortex is primary target.',
  },
  {
    id: 'tinnitus',
    name: 'Tinnitus',
    abbr: 'TIN',
    category: 'Neurological',
    icd10: 'H93.19',
    description:
      'The perception of phantom sound (ringing, buzzing, hissing) in the absence of an external acoustic stimulus, associated with maladaptive neuroplasticity in auditory and non-auditory cortices.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'taVNS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['TEMPORAL-L', 'TEMPORAL-R', 'P3'],
    typical_sessions: 15,
    key_assessments: ['THI', 'TQ', 'NRS-Pain', 'CGI'],
    notes: 'Left temporal cortex (1Hz inhibitory) and/or prefrontal HF protocols. Variability in response is high.',
  },
  {
    id: 'dysphagia',
    name: 'Neurological Dysphagia',
    abbr: 'DYS-N',
    category: 'Neurological',
    icd10: 'R13.10',
    description:
      'Swallowing dysfunction due to neurological damage (stroke, TBI, Parkinson, MS), involving impaired coordination of pharyngeal and laryngeal musculature with risk of aspiration.',
    primary_modalities: ['TMS/rTMS', 'tDCS'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'Cz'],
    typical_sessions: 10,
    key_assessments: ['MASA', 'EAT-10', 'CGI'],
    notes: 'Pharyngeal motor cortex mapping required for precise targeting. Combine with swallowing therapy.',
  },
  {
    id: 'sci-rehab',
    name: 'Spinal Cord Injury (Rehabilitation)',
    abbr: 'SCI',
    category: 'Neurological',
    icd10: 'T14.8',
    description:
      'Motor and sensory deficits following traumatic or non-traumatic spinal cord injury; cortical reorganisation above the lesion level provides targets for TMS-assisted motor rehabilitation and pain management.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'Cz'],
    typical_sessions: 20,
    key_assessments: ['ASIA', 'NRS-Pain', 'CGI'],
    notes: 'Corticospinal tract integrity assessment guides protocol. Combine with robot-assisted therapy.',
  },

  // ─── Pain ─────────────────────────────────────────────────────────────────────
  {
    id: 'chronic-pain',
    name: 'Chronic Pain',
    abbr: 'CP',
    category: 'Pain',
    icd10: 'G89.29',
    description:
      'Pain persisting or recurring for more than three months, representing both a symptom and an independent disease entity with central sensitisation and altered descending pain modulation.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'taVNS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'DLPFC-L'],
    typical_sessions: 20,
    key_assessments: ['NRS-Pain', 'BPI', 'DASS-21', 'CGI'],
    notes: 'M1 HF-TMS and DLPFC tDCS both supported. Multidisciplinary pain clinic integration recommended.',
  },
  {
    id: 'neuropathic-pain',
    name: 'Neuropathic Pain',
    abbr: 'NP',
    category: 'Pain',
    icd10: 'G60.9',
    description:
      'Pain arising directly from a lesion or disease of the somatosensory nervous system, characterised by allodynia, hyperalgesia, and spontaneous burning or shooting pain. Central sensitisation and thalamo-cortical dysrhythmia are targets.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'taVNS'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'S1'],
    typical_sessions: 20,
    key_assessments: ['NRS-Pain', 'DN4', 'NPSI', 'CGI'],
    notes: 'HF-TMS over contralateral M1 is the most replicated protocol. Somatosensory mapping may guide targeting.',
  },
  {
    id: 'fibromyalgia',
    name: 'Fibromyalgia',
    abbr: 'FM',
    category: 'Pain',
    icd10: 'M79.3',
    description:
      'A centralised pain syndrome with widespread musculoskeletal pain, fatigue, sleep disturbance, and cognitive difficulties, underpinned by central sensitisation and altered descending pain inhibition.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'DLPFC-L', 'S1'],
    typical_sessions: 20,
    key_assessments: ['FIQ-R', 'NRS-Pain', 'PHQ-9', 'PSQI'],
    notes: 'Left DLPFC anodal tDCS and M1 HF-TMS both show moderate efficacy in RCTs.',
  },
  {
    id: 'crps',
    name: 'Complex Regional Pain Syndrome',
    abbr: 'CRPS',
    category: 'Pain',
    icd10: 'G90.509',
    description:
      'A chronic pain condition usually affecting a limb following injury, characterised by disproportionate pain, autonomic dysfunction, trophic changes, and motor impairment, involving cortical maladaptive reorganisation.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'S1'],
    typical_sessions: 20,
    key_assessments: ['NRS-Pain', 'CRPS-SX', 'BPI', 'CGI'],
    notes: 'Reversal of motor cortex reorganisation is therapeutic goal. Contralateral M1 HF-TMS primary protocol.',
  },
  {
    id: 'phantom-limb-pain',
    name: 'Phantom Limb Pain',
    abbr: 'PLP',
    category: 'Pain',
    icd10: 'G54.6',
    description:
      'Painful sensations perceived in an amputated or deafferented limb, driven by maladaptive cortical reorganisation of the somatosensory and motor cortices following amputation.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: [],
    target_regions: ['M1-L', 'M1-R', 'S1'],
    typical_sessions: 15,
    key_assessments: ['NRS-Pain', 'PPI', 'BPI', 'CGI'],
    notes: 'Motor cortex HF-TMS targeting the cortical representation zone of the amputated limb. Combine with mirror therapy.',
  },
  {
    id: 'cipn',
    name: 'Chemotherapy-Induced Neuropathy',
    abbr: 'CIPN',
    category: 'Pain',
    icd10: 'G62.0',
    description:
      'Peripheral neuropathy induced by neurotoxic chemotherapy agents, presenting with distal symmetric numbness, tingling, pain, and motor weakness, with limited effective pharmacological treatments.',
    primary_modalities: ['tDCS', 'TMS/rTMS', 'PBM'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['S1', 'M1-L', 'M1-R'],
    typical_sessions: 15,
    key_assessments: ['NRS-Pain', 'FACT-GOG/Ntx', 'CGI'],
    notes: 'Emerging evidence only. PBM over peripheral nerve distribution also under investigation.',
  },

  // ─── Sleep & Circadian ────────────────────────────────────────────────────────
  {
    id: 'insomnia',
    name: 'Insomnia Disorder',
    abbr: 'ID',
    category: 'Sleep & Circadian',
    icd10: 'G47.00',
    description:
      'Difficulty initiating or maintaining sleep, or early morning awakening, with associated daytime impairment, occurring at least three nights per week for at least three months in the absence of other primary sleep disorders.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'CES', 'Neurofeedback'],
    evidence_grade: 'B',
    fda_cleared_modalities: ['CES'],
    target_regions: ['DLPFC-R', 'Fp1', 'Fz'],
    typical_sessions: 15,
    key_assessments: ['ISI', 'PSQI', 'ESS', 'DASS-21'],
    notes: 'CES FDA-cleared for insomnia. Right DLPFC inhibitory TMS and frontal slow-wave tDCS under RCT evaluation.',
  },

  // ─── Substance & Addiction ────────────────────────────────────────────────────
  {
    id: 'substance-use',
    name: 'Substance Use Disorder',
    abbr: 'SUD',
    category: 'Substance & Addiction',
    icd10: 'F19.20',
    description:
      'A pattern of compulsive substance use (alcohol, cocaine, opioids, nicotine, cannabis) resulting in clinically significant impairment, involving dysregulation of prefrontal control over limbic craving circuits.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'OFC'],
    typical_sessions: 15,
    key_assessments: ['AUDIT', 'DAST-10', 'ASSIST', 'CGI'],
    notes: 'Left DLPFC HF-TMS reduces craving in alcohol and cocaine SUD in multiple RCTs. Protocol varies by substance.',
  },

  // ─── Eating & Body Image ──────────────────────────────────────────────────────
  {
    id: 'eating-disorders',
    name: 'Anorexia / Eating Disorders',
    abbr: 'ED',
    category: 'Eating & Body Image',
    icd10: 'F50.9',
    description:
      'A spectrum of psychiatric conditions characterised by persistent disturbances in eating behaviour, body image distortion, and driven pursuit of thinness (anorexia nervosa) or recurrent binge-purge cycles (bulimia nervosa), with significant medical morbidity.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'OFC'],
    typical_sessions: 20,
    key_assessments: ['EDE-Q', 'EAT-26', 'PHQ-9', 'CGI'],
    notes: 'Emerging evidence for right DLPFC inhibitory TMS in AN to address rigid cognitive patterns. Medical stabilisation required first.',
  },

  // ─── Other ────────────────────────────────────────────────────────────────────
  {
    id: 'long-covid-neurocognitive',
    name: 'Long COVID Neurocognitive Syndrome',
    abbr: 'LC-NC',
    category: 'Other',
    icd10: 'U09.9',
    description:
      'Persistent cognitive impairment (brain fog), fatigue, mood disturbance, and autonomic dysfunction following acute SARS-CoV-2 infection, associated with neuroinflammation, microglial activation, and disrupted resting-state network connectivity.',
    primary_modalities: ['TMS/rTMS', 'tDCS', 'Neurofeedback', 'PBM'],
    evidence_grade: 'C',
    fda_cleared_modalities: [],
    target_regions: ['DLPFC-L', 'DLPFC-R', 'Fz'],
    typical_sessions: 20,
    key_assessments: ['MoCA', 'PHQ-9', 'PSQI', 'BRIEF', 'CGI'],
    notes: 'Rapidly evolving evidence base. Multimodal approaches targeting cognitive, mood, and autonomic domains most promising.',
  },
];

export const CONDITION_CATEGORIES = [...new Set(CONDITIONS.map(c => c.category))];
export const CONDITIONS_BY_CATEGORY = CONDITION_CATEGORIES.reduce((acc, cat) => {
  acc[cat] = CONDITIONS.filter(c => c.category === cat);
  return acc;
}, {});
export default CONDITIONS;
