/**
 * consents.js
 * Clinical consent and document templates for neuromodulation practice.
 * DeepSynaps Protocol Studio — Registry
 */

export const CONSENT_TEMPLATES = [
  {
    id: 'consent-tms-general',
    name: 'TMS Treatment Consent Form',
    category: 'Consent',
    modality: 'TMS/rTMS',
    conditions: ['MDD', 'OCD', 'PTSD', 'Anxiety', 'TRD', 'ADHD', 'Chronic Pain'],
    version: '2.1',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Procedure Description',
      'Expected Benefits',
      'Risks and Side Effects',
      'Alternatives to TMS',
      'Confidentiality',
      'Withdrawal Rights',
      'Emergency Contact',
      'Post-Treatment Care',
    ],
    key_risks: [
      'Headache (common, typically mild)',
      'Scalp discomfort at stimulation site',
      'Tingling or twitching of facial muscles',
      'Lightheadedness',
      'Rare: seizure risk (estimated <0.1%)',
      'Rare: hearing change if ear protection not worn',
      'Rare: mania/hypomania in predisposed individuals',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'I understand that Transcranial Magnetic Stimulation (TMS) is a non-invasive brain stimulation technique that uses magnetic fields to stimulate nerve cells in the brain. I have been informed of the procedure, its expected benefits, possible risks, and alternatives. I consent freely and may withdraw at any time without affecting my care.',
    tags: ['mandatory', 'treatment', 'tms'],
  },
  {
    id: 'consent-tdcs-general',
    name: 'tDCS Treatment Consent Form',
    category: 'Consent',
    modality: 'tDCS',
    conditions: ['MDD', 'Chronic Pain', 'Stroke Rehabilitation', 'ADHD', 'Anxiety', 'Fibromyalgia'],
    version: '1.4',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Procedure Description',
      'Expected Benefits',
      'Risks and Side Effects',
      'Electrode Placement',
      'Alternatives',
      'Confidentiality',
      'Withdrawal Rights',
      'Emergency Contact',
    ],
    key_risks: [
      'Tingling or itching under electrodes (common)',
      'Mild scalp redness at electrode sites',
      'Headache (occasional)',
      'Fatigue after sessions',
      'Rare: skin irritation or burn at electrode site',
      'Rare: phosphenes (visual flashes) if electrodes near eyes',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'I understand that transcranial Direct Current Stimulation (tDCS) applies a low-level electrical current to the scalp via electrodes to modulate brain activity. I have been informed of the procedure, its expected benefits, possible risks, and alternatives. I consent freely and understand I may withdraw at any time.',
    tags: ['mandatory', 'treatment', 'tdcs'],
  },
  {
    id: 'consent-neurofeedback',
    name: 'Neurofeedback Treatment Consent Form',
    category: 'Consent',
    modality: 'Neurofeedback/EEG-BF',
    conditions: ['ADHD', 'Anxiety', 'PTSD', 'Insomnia', 'Depression', 'Peak Performance'],
    version: '1.2',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Procedure Description',
      'What Neurofeedback Involves',
      'Expected Benefits',
      'Risks and Side Effects',
      'Number of Sessions',
      'Alternatives',
      'Confidentiality',
      'Withdrawal Rights',
    ],
    key_risks: [
      'Temporary fatigue or drowsiness after sessions',
      'Mild headache (uncommon)',
      'Possible transient mood changes',
      'Rare: exacerbation of symptoms if protocol not individualised',
      'Temporary increased anxiety in early sessions',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'I understand that neurofeedback is a form of biofeedback that uses real-time EEG (brainwave) monitoring to train self-regulation of brain activity. I have been informed of the procedure, expected benefits, possible risks, and alternatives. I consent freely and understand I may withdraw at any time.',
    tags: ['mandatory', 'treatment', 'neurofeedback'],
  },
  {
    id: 'consent-tavns',
    name: 'taVNS Treatment Consent Form',
    category: 'Consent',
    modality: 'taVNS',
    conditions: ['Epilepsy', 'Depression', 'Anxiety', 'Chronic Pain', 'PTSD', 'Tinnitus'],
    version: '1.1',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Procedure Description',
      'Mechanism of Action',
      'Expected Benefits',
      'Risks and Side Effects',
      'Device Use Instructions',
      'Alternatives',
      'Confidentiality',
      'Withdrawal Rights',
    ],
    key_risks: [
      'Skin irritation at auricular electrode site',
      'Ear discomfort or mild pain',
      'Dizziness (uncommon)',
      'Nausea (rare)',
      'Contraindicated with cardiac pacemakers',
      'Caution with vagal hypersensitivity conditions',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'I understand that transcutaneous Auricular Vagus Nerve Stimulation (taVNS) applies mild electrical stimulation to the outer ear to activate the vagus nerve. I have been informed of the procedure, expected benefits, possible risks, and alternatives. I consent freely and understand I may withdraw at any time.',
    tags: ['mandatory', 'treatment', 'tavns'],
  },
  {
    id: 'consent-ces',
    name: 'Cranial Electrotherapy Stimulation (CES) Consent Form',
    category: 'Consent',
    modality: 'CES',
    conditions: ['Insomnia', 'Anxiety', 'Depression', 'Chronic Pain', 'PTSD'],
    version: '1.0',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Procedure Description',
      'Mechanism of Action',
      'Expected Benefits',
      'Risks and Side Effects',
      'Device Use Instructions',
      'Home Use Guidelines',
      'Alternatives',
      'Withdrawal Rights',
    ],
    key_risks: [
      'Skin irritation at electrode sites (ears)',
      'Dizziness or vertigo during stimulation',
      'Headache (mild, uncommon)',
      'Phosphenes (visual flashes) at high intensities',
      'Not for use with implanted electronic devices',
      'Contraindicated during pregnancy (insufficient evidence)',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'I understand that Cranial Electrotherapy Stimulation (CES) delivers small alternating electrical currents to the brain via ear-clip electrodes. I have been informed of the procedure, expected benefits, possible risks, and alternatives. I consent freely and understand I may withdraw at any time.',
    tags: ['mandatory', 'treatment', 'ces'],
  },
  {
    id: 'consent-research',
    name: 'Research Participation Consent Form',
    category: 'Consent',
    modality: 'All',
    conditions: ['All'],
    version: '3.0',
    required_before: 'research',
    requires_witness: true,
    requires_clinician_signature: true,
    validity_days: null,
    sections: [
      'Study Purpose and Background',
      'What Participation Involves',
      'Risks and Discomforts',
      'Potential Benefits',
      'Confidentiality and Data Use',
      'Voluntary Participation and Right to Withdraw',
      'Compensation',
      'Contact Information for Questions',
      'Ethics Approval Statement',
      'Participant Declaration',
    ],
    key_risks: [
      'Risks specific to intervention being studied',
      'Possible discomfort from additional assessments',
      'Time burden',
      'Privacy risks despite de-identification',
      'Possible psychological distress from questionnaires',
    ],
    jurisdiction_notes:
      'Must comply with local Human Research Ethics Committee (HREC) or IRB requirements. Review ethics approval number before use.',
    template_text_outline:
      'I have been given information about this research study and have had the opportunity to ask questions. I understand the purpose of the research, what participation involves, the risks and benefits, and my rights as a participant. I agree to participate voluntarily and understand I may withdraw at any time without penalty.',
    tags: ['research', 'ethics', 'mandatory'],
  },
  {
    id: 'consent-off-label',
    name: 'Off-Label Treatment Consent Form',
    category: 'Consent',
    modality: 'All',
    conditions: ['All'],
    version: '1.3',
    required_before: 'treatment',
    requires_witness: true,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Definition of Off-Label Use',
      'Specific Treatment Being Proposed',
      'Rationale for Off-Label Use',
      'Available Evidence',
      'Risks Including Unknown Risks',
      'Approved Alternatives',
      'Patient Rights',
      'Clinician Responsibility Statement',
      'Regulatory Status',
    ],
    key_risks: [
      'Less evidence available than for approved indications',
      'Unknown long-term risks',
      'Possible reduced insurance coverage',
      'Regulatory status varies by jurisdiction',
      'Condition-specific and modality-specific risks apply',
    ],
    jurisdiction_notes:
      'Off-label use must be documented with clinical justification. Consult relevant professional guidelines and regulatory requirements in your jurisdiction.',
    template_text_outline:
      'I have been informed that the proposed treatment is being used "off-label" — that is, for a condition, dose, or population not specifically approved by the relevant regulatory authority. I understand the available evidence, the risks including unknown risks, and approved alternatives. I consent freely.',
    tags: ['off-label', 'mandatory', 'special-risk'],
  },
  {
    id: 'consent-photography',
    name: 'Clinical Photography and Video Consent Form',
    category: 'Consent',
    modality: 'All',
    conditions: ['All'],
    version: '1.0',
    required_before: 'assessment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: null,
    sections: [
      'Purpose of Recording',
      'What Will Be Recorded',
      'Storage and Security',
      'Who May Access Recordings',
      'Use in Education or Research',
      'Right to Withdraw Consent',
      'De-identification Options',
    ],
    key_risks: [
      'Privacy risks despite secure storage',
      'Possible identification even after de-identification',
      'Digital security vulnerabilities',
    ],
    jurisdiction_notes: 'Must comply with local privacy and health records legislation.',
    template_text_outline:
      'I consent to clinical photography and/or video recording being made during my assessment and/or treatment. I understand the purpose, storage arrangements, and who may access recordings. I understand I can withdraw this consent at any time.',
    tags: ['privacy', 'optional', 'clinical-media'],
  },
  {
    id: 'consent-data-sharing',
    name: 'Clinical Data Sharing Authorization',
    category: 'Authorization',
    modality: 'All',
    conditions: ['All'],
    version: '1.2',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Data to be Shared',
      'Recipients of Data',
      'Purpose of Sharing',
      'Data Security Measures',
      'Your Rights Under Privacy Law',
      'Duration of Authorization',
      'Right to Revoke',
    ],
    key_risks: [
      'Privacy risks inherent in data sharing',
      'Possible re-identification from de-identified data',
    ],
    jurisdiction_notes:
      'Ensure compliance with applicable privacy legislation (e.g., GDPR, HIPAA, Australian Privacy Act) before sharing data.',
    template_text_outline:
      'I authorize the sharing of my clinical data as described in this form. I understand what data will be shared, with whom, and for what purpose. I understand my rights and that I may revoke this authorization at any time.',
    tags: ['data-privacy', 'authorization', 'gdpr'],
  },
  {
    id: 'consent-telehealth',
    name: 'Telehealth and Virtual Care Consent Form',
    category: 'Consent',
    modality: 'All',
    conditions: ['All'],
    version: '1.1',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'What Telehealth Involves',
      'Technology Requirements',
      'Limitations of Telehealth',
      'Privacy and Security',
      'Emergency Procedures',
      'Right to Decline Telehealth',
      'Recording Policy',
      'Billing and Insurance',
    ],
    key_risks: [
      'Technology failure may interrupt care',
      'Reduced ability to perform physical examination',
      'Privacy risks in non-clinical environments',
      'Limited emergency response capability at patient location',
    ],
    jurisdiction_notes:
      'Telehealth regulations and billing rules vary by jurisdiction. Verify compliance with local telehealth legislation.',
    template_text_outline:
      'I understand that telehealth involves the delivery of healthcare services using electronic communications. I have been informed of the benefits and limitations of telehealth, technology requirements, privacy measures, and emergency procedures. I consent to receive care via telehealth.',
    tags: ['telehealth', 'mandatory', 'virtual-care'],
  },
  {
    id: 'consent-minor',
    name: 'Consent Form for Treatment of a Minor (Parent/Guardian)',
    category: 'Consent',
    modality: 'All',
    conditions: ['ADHD', 'Anxiety', 'Depression', 'OCD', 'Autism Spectrum', 'Epilepsy'],
    version: '1.3',
    required_before: 'treatment',
    requires_witness: true,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Identification of Minor Patient',
      'Parent/Guardian Details',
      'Procedure Description (age-appropriate)',
      'Expected Benefits',
      'Risks and Side Effects',
      'Child Assent Statement',
      'Parent/Guardian Rights',
      'Emergency Contact',
      'Authority to Consent',
    ],
    key_risks: [
      'All modality-specific risks apply',
      'Developing brain considerations in paediatric populations',
      'Additional consent requirements for minors',
    ],
    jurisdiction_notes:
      'Age of consent for medical treatment varies by jurisdiction. Confirm legal requirements for parental consent and child assent in your region. Child assent should be obtained for patients aged 7+.',
    template_text_outline:
      'As parent/legal guardian of the above-named minor, I consent to the proposed neuromodulation treatment. I have been informed of the procedure, expected benefits, risks, and alternatives in terms appropriate to my child\'s age. I confirm I have legal authority to consent to this treatment.',
    tags: ['paediatric', 'mandatory', 'guardian-consent'],
  },
  {
    id: 'info-sheet-tms',
    name: 'TMS Patient Information Sheet',
    category: 'Information Sheet',
    modality: 'TMS/rTMS',
    conditions: ['MDD', 'OCD', 'PTSD', 'Anxiety', 'TRD', 'ADHD', 'Chronic Pain'],
    version: '2.0',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: false,
    validity_days: null,
    sections: [
      'What is TMS?',
      'How Does TMS Work?',
      'What Conditions Can TMS Help?',
      'What to Expect During Treatment',
      'How Many Sessions Will I Need?',
      'What Are the Side Effects?',
      'How to Prepare for Your Sessions',
      'What to Do After Sessions',
      'Frequently Asked Questions',
      'Contact Information',
    ],
    key_risks: [
      'Common: headache, scalp discomfort',
      'Uncommon: facial twitching, dizziness',
      'Rare: seizure',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'This information sheet explains what TMS (Transcranial Magnetic Stimulation) is, how it works, what to expect during treatment, and how to prepare. Please read this before your first appointment and bring any questions to your clinician.',
    tags: ['patient-education', 'pre-treatment', 'information'],
  },
  {
    id: 'info-sheet-tdcs',
    name: 'tDCS Patient Information Sheet',
    category: 'Information Sheet',
    modality: 'tDCS',
    conditions: ['MDD', 'Chronic Pain', 'Stroke Rehabilitation', 'ADHD', 'Anxiety'],
    version: '1.3',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: false,
    validity_days: null,
    sections: [
      'What is tDCS?',
      'How Does tDCS Work?',
      'What Conditions Can tDCS Help?',
      'What to Expect During Treatment',
      'Electrode Placement',
      'Sensation During Treatment',
      'Possible Side Effects',
      'How to Prepare',
      'Frequently Asked Questions',
    ],
    key_risks: [
      'Common: tingling, itching under electrodes',
      'Uncommon: mild headache, fatigue',
      'Rare: skin irritation',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'This information sheet explains what tDCS (transcranial Direct Current Stimulation) is, how it works, what to expect, and how to prepare for your sessions.',
    tags: ['patient-education', 'pre-treatment', 'information'],
  },
  {
    id: 'info-sheet-neurofeedback',
    name: 'Neurofeedback Patient Information Sheet',
    category: 'Information Sheet',
    modality: 'Neurofeedback/EEG-BF',
    conditions: ['ADHD', 'Anxiety', 'PTSD', 'Insomnia', 'Depression'],
    version: '1.2',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: false,
    validity_days: null,
    sections: [
      'What is Neurofeedback?',
      'What Does a Session Involve?',
      'What Conditions Can Neurofeedback Help?',
      'How Many Sessions Will I Need?',
      'Possible Side Effects',
      'What to Expect After Sessions',
      'Preparing for Sessions',
      'Frequently Asked Questions',
    ],
    key_risks: [
      'Common: fatigue after sessions',
      'Uncommon: temporary mood changes',
      'Rare: symptom exacerbation with incorrect protocol',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'This information sheet explains neurofeedback — a brain training technique using real-time EEG feedback — including what sessions involve, what conditions it may help, and what to expect.',
    tags: ['patient-education', 'pre-treatment', 'information'],
  },
  {
    id: 'auth-records-release',
    name: 'Medical Records Release Authorization',
    category: 'Authorization',
    modality: 'All',
    conditions: ['All'],
    version: '1.1',
    required_before: 'assessment',
    requires_witness: false,
    requires_clinician_signature: false,
    validity_days: 180,
    sections: [
      'Patient Identification',
      'Records to be Released',
      'Recipient Details',
      'Purpose of Release',
      'Restrictions on Use',
      'Expiry of Authorization',
      'Right to Revoke',
    ],
    key_risks: [],
    jurisdiction_notes:
      'Comply with applicable health records legislation. Some jurisdictions require specific forms.',
    template_text_outline:
      'I authorize the release of my medical records as specified below. I understand the purpose of this release, who will receive the records, and that I may revoke this authorization before the records are released.',
    tags: ['records', 'authorization', 'administrative'],
  },
  {
    id: 'auth-insurance',
    name: 'Insurance Authorization for Neuromodulation Treatment',
    category: 'Authorization',
    modality: 'All',
    conditions: ['MDD', 'OCD', 'TRD', 'Chronic Pain', 'PTSD', 'ADHD'],
    version: '1.0',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 90,
    sections: [
      'Patient & Insurance Details',
      'Proposed Treatment',
      'Clinical Justification',
      'Relevant Diagnosis Codes',
      'Prior Treatment History',
      'Evidence of Medical Necessity',
      'Clinician Declaration',
    ],
    key_risks: [],
    jurisdiction_notes:
      'Insurance coverage for neuromodulation varies widely. Pre-authorization requirements differ by insurer and jurisdiction.',
    template_text_outline:
      'This authorization supports insurance pre-approval for proposed neuromodulation treatment. Clinical justification, diagnosis, and prior treatment history are provided to demonstrate medical necessity.',
    tags: ['insurance', 'authorization', 'billing'],
  },
  {
    id: 'agreement-home-program',
    name: 'Home Program Agreement',
    category: 'Agreement',
    modality: 'All',
    conditions: ['All'],
    version: '1.0',
    required_before: 'treatment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 365,
    sections: [
      'Program Description',
      'Patient Responsibilities',
      'Clinician Responsibilities',
      'Safety Guidelines',
      'When to Contact the Clinic',
      'Recording Progress',
      'Review Schedule',
      'Signature',
    ],
    key_risks: [
      'Unsupervised use of devices carries additional risk',
      'Home environment may not replicate clinical setting',
      'Adherence monitoring limited outside clinic',
    ],
    jurisdiction_notes: '',
    template_text_outline:
      'This agreement outlines the home program prescribed by my clinician, my responsibilities in following the program safely, and when to contact the clinic. I agree to follow the program as prescribed and report any concerns promptly.',
    tags: ['home-program', 'agreement', 'treatment'],
  },
  {
    id: 'referral-template',
    name: 'Neuromodulation Referral Letter Template',
    category: 'Referral',
    modality: 'All',
    conditions: ['All'],
    version: '1.2',
    required_before: 'assessment',
    requires_witness: false,
    requires_clinician_signature: true,
    validity_days: 90,
    sections: [
      'Referring Clinician Details',
      'Patient Details',
      'Reason for Referral',
      'Relevant Diagnoses',
      'Current & Previous Treatments',
      'Current Medications',
      'Relevant History',
      'Specific Questions or Goals',
      'Urgency',
      'Contact for Follow-Up',
    ],
    key_risks: [],
    jurisdiction_notes: '',
    template_text_outline:
      'Dear Colleague, I am referring the above-named patient for neuromodulation assessment and treatment. Please find relevant clinical details below. I would appreciate your assessment and recommendations, and am happy to discuss this case further.',
    tags: ['referral', 'administrative', 'clinical-communication'],
  },
];

export const CONSENT_BY_ID = Object.fromEntries(CONSENT_TEMPLATES.map(c => [c.id, c]));
export const CONSENT_CATEGORIES = [...new Set(CONSENT_TEMPLATES.map(c => c.category))];
export default CONSENT_TEMPLATES;
