// devices.js — Neuromodulation devices registry
// DeepSynaps Protocol Studio

export const DEVICES = [

  // ── TMS / rTMS DEVICES ────────────────────────────────────────────────────

  {
    id: 'magstim-rapid2',
    name: 'Magstim Rapid²',
    manufacturer: 'Magstim',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'TBS'],
    fda_clearance: true,
    fda_indications: ['Major Depressive Disorder'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Figure-8 (70mm)', 'Double Cone (110mm)', 'Butterfly (70mm paediatric)'],
    max_frequency_hz: 100,
    max_intensity_pct_mso: 120,
    pulse_waveforms: ['biphasic'],
    connectivity: ['USB', 'Ethernet'],
    neuronavigation_compatible: true,
    features: [
      'EMG integration for motor threshold determination',
      'Real-time dosimetry',
      'Session logging and export',
      'Active cooling coil option',
      'Remote trigger interface',
    ],
    typical_protocols: ['HF-rTMS 10Hz', 'LF-rTMS 1Hz', 'iTBS', 'cTBS', 'Quad-pulse TMS'],
    notes: 'Industry-standard clinical TMS device; widely used in RCTs for MDD. Supports repetitive and paired-pulse paradigms.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'magstim-200',
    name: 'Magstim 200²',
    manufacturer: 'Magstim',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'Single-pulse TMS'],
    fda_clearance: true,
    fda_indications: ['Motor cortex mapping', 'Major Depressive Disorder'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Figure-8 (70mm)', 'Round (90mm)', 'Double Cone (110mm)'],
    max_frequency_hz: 1,
    max_intensity_pct_mso: 120,
    pulse_waveforms: ['monophasic'],
    connectivity: ['USB'],
    neuronavigation_compatible: true,
    features: [
      'Single and paired-pulse modes',
      'EMG triggering',
      'Monophasic pulse for research paradigms',
    ],
    typical_protocols: ['Single-pulse motor mapping', 'Paired-pulse TMS', 'LF-rTMS 1Hz'],
    notes: 'Workhorse single/paired-pulse device; monophasic waveform preferred for neurophysiology research.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'brainsway-hcoil',
    name: 'BrainsWay Deep TMS System (H-Coil)',
    manufacturer: 'BrainsWay',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'Deep TMS'],
    fda_clearance: true,
    fda_indications: ['Major Depressive Disorder', 'OCD', 'Smoking Cessation', 'Bipolar II Depression'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['H1-Coil (bilateral PFC)', 'H7-Coil (ACC + PFC for OCD)', 'H4-Coil (limbic)'],
    max_frequency_hz: 20,
    max_intensity_pct_mso: 120,
    pulse_waveforms: ['biphasic'],
    connectivity: ['USB', 'Ethernet'],
    neuronavigation_compatible: false,
    features: [
      'Helmet-based coil positioning — no neuronavigation required',
      'Deeper stimulation reach (~3–5 cm)',
      'FDA-cleared OCD protocol with provocation',
      'Integrated patient tracking software',
      'Multi-condition regulatory clearances',
    ],
    typical_protocols: ['Deep TMS MDD H1-coil', 'Deep TMS OCD H7-coil', 'Deep TMS smoking cessation'],
    notes: 'Only FDA-cleared deep TMS device. H7-coil OCD protocol requires symptom provocation immediately pre-stimulation.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'magventure-magpro',
    name: 'MagVenture MagPro R30',
    manufacturer: 'MagVenture',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'TBS', 'Single-pulse TMS'],
    fda_clearance: true,
    fda_indications: ['Major Depressive Disorder'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Cool-B65 A/P', 'Cool-B35', 'MC-B70', 'C-B60'],
    max_frequency_hz: 30,
    max_intensity_pct_mso: 120,
    pulse_waveforms: ['biphasic', 'biphasic burst'],
    connectivity: ['USB', 'Ethernet', 'Trigger I/O'],
    neuronavigation_compatible: true,
    features: [
      'Active liquid-cooled coils for prolonged sessions',
      'Dual-mode waveform (standard + burst)',
      'Integrated EMG module',
      'MagOption research add-on',
      'Quiet coil technology',
    ],
    typical_protocols: ['HF-rTMS 10Hz', 'iTBS', 'cTBS', 'LF-rTMS'],
    notes: 'Popular alternative to Magstim. Active-cooled coils enable full accelerated TMS sessions without cool-down pauses.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'nexstim-nbs',
    name: 'Nexstim NBS System 5',
    manufacturer: 'Nexstim',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'Navigated TMS'],
    fda_clearance: true,
    fda_indications: ['Major Depressive Disorder', 'Pre-surgical cortical mapping'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Figure-8 (70mm) with tracker'],
    max_frequency_hz: 30,
    max_intensity_pct_mso: 110,
    pulse_waveforms: ['biphasic'],
    connectivity: ['USB', 'Ethernet', 'Infrared optical tracking'],
    neuronavigation_compatible: true,
    features: [
      'Integrated real-time MRI neuronavigation',
      'Electric field modelling',
      'Pre-surgical motor/language mapping',
      'eField targeting for personalised dosimetry',
      'Motormap and speech arrest mapping',
    ],
    typical_protocols: ['Navigated HF-rTMS', 'Pre-surgical motor mapping', 'Language mapping'],
    notes: 'Best-in-class neuronavigation integration. E-field guidance optimises DLPFC targeting for treatment-resistant cases.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'eneura-springtms',
    name: 'eNeura SpringTMS',
    manufacturer: 'eNeura',
    modality: 'TMS/rTMS',
    modalities: ['Single-pulse TMS'],
    fda_clearance: true,
    fda_indications: ['Migraine with aura', 'Migraine prevention'],
    ce_mark: true,
    device_type: 'consumer',
    coil_types: ['Flat occipital coil'],
    max_frequency_hz: 0.5,
    max_intensity_pct_mso: 100,
    pulse_waveforms: ['biphasic'],
    connectivity: ['USB (charging only)'],
    neuronavigation_compatible: false,
    features: [
      'Handheld portable design',
      'Patient self-administration',
      'Occipital single-pulse delivery',
      'Usage log via docking station',
    ],
    typical_protocols: ['Single-pulse TMS migraine abort', 'Preventive daily occipital TMS'],
    notes: 'FDA-cleared for patient home use. Delivers single pulse to occipital cortex during migraine aura.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'magstim-horizon',
    name: 'Magstim Horizon Performance TMS',
    manufacturer: 'Magstim',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'TBS', 'Deep TMS'],
    fda_clearance: true,
    fda_indications: ['Major Depressive Disorder'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['D-B80 (deep)', 'Figure-8 (70mm)', 'Paediatric (50mm)'],
    max_frequency_hz: 100,
    max_intensity_pct_mso: 120,
    pulse_waveforms: ['biphasic'],
    connectivity: ['USB', 'Ethernet', 'Wi-Fi'],
    neuronavigation_compatible: true,
    features: [
      'Touchscreen interface',
      'Protocol library with guided setup',
      'Built-in EMG for resting motor threshold',
      'Cloud session archiving',
      'Active cooling',
    ],
    typical_protocols: ['HF-rTMS 10Hz', 'iTBS 2-minute', 'cTBS', 'SAINT accelerated'],
    notes: 'Next-generation Magstim platform with modernised UI and cloud connectivity. Supports SAINT-protocol pulse parameters.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'cloudtms',
    name: 'CloudTMS System',
    manufacturer: 'Cloud TMS',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'TBS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Figure-8 (70mm)', 'Figure-8 (55mm)'],
    max_frequency_hz: 30,
    max_intensity_pct_mso: 120,
    pulse_waveforms: ['biphasic'],
    connectivity: ['USB', 'Bluetooth', 'Wi-Fi'],
    neuronavigation_compatible: true,
    features: [
      'Cloud-based session management and analytics',
      'Remote protocol programming',
      'Integrated outcome tracking dashboard',
      'Multi-site synchronisation',
    ],
    typical_protocols: ['HF-rTMS 10Hz', 'iTBS', 'LF-rTMS'],
    notes: 'CE-marked only; cloud-native platform suited for multi-clinic networks with centralised data management.',
    image_placeholder: 'tms-device',
  },

  {
    id: 'neurosoft-tms',
    name: 'Neurosoft TMS System',
    manufacturer: 'Neurosoft',
    modality: 'TMS/rTMS',
    modalities: ['TMS/rTMS', 'Single-pulse TMS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Figure-8 (70mm)', 'Round (90mm)', 'Double Cone (120mm)'],
    max_frequency_hz: 100,
    max_intensity_pct_mso: 110,
    pulse_waveforms: ['monophasic', 'biphasic'],
    connectivity: ['USB', 'RS-232'],
    neuronavigation_compatible: true,
    features: [
      'Simultaneous EEG-TMS capability',
      'Multi-channel EMG integration',
      'Paired-pulse paradigms',
      'CE-marked for neurophysiology diagnostics',
    ],
    typical_protocols: ['rTMS MDD', 'Neurophysiology TMS-EEG', 'Motor mapping'],
    notes: 'Russian-manufactured CE-marked device; strong neurophysiology research heritage with TMS-EEG integration.',
    image_placeholder: 'tms-device',
  },

  // ── tDCS / tACS DEVICES ───────────────────────────────────────────────────

  {
    id: 'soterix-1x1',
    name: 'Soterix Medical 1×1 tDCS Device',
    manufacturer: 'Soterix Medical',
    modality: 'tDCS',
    modalities: ['tDCS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 0,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['DC'],
    connectivity: ['USB'],
    neuronavigation_compatible: false,
    features: [
      'Constant current delivery (0.1–4 mA)',
      'Electrode impedance monitoring',
      'Session timer and dose tracking',
      'Sham capability (auto-ramp off)',
      'FDA IND-approved for research use',
    ],
    typical_protocols: ['tDCS anodal DLPFC MDD', 'tDCS motor rehabilitation', 'tDCS pain'],
    notes: 'Research gold-standard tDCS device. 2×2 electrode pads. Widely used in published tDCS RCTs.',
    image_placeholder: 'tdcs-device',
  },

  {
    id: 'neuroconn-dc-plus',
    name: 'neuroConn DC-Stimulator Plus',
    manufacturer: 'NeuroConn GmbH',
    modality: 'tDCS',
    modalities: ['tDCS', 'tACS', 'tRNS', 'tOCS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 5000,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['DC', 'sinusoidal AC', 'random noise', 'oscillating DC'],
    connectivity: ['USB', 'Parallel port trigger'],
    neuronavigation_compatible: false,
    features: [
      'Multi-modal: tDCS, tACS, tRNS, tOCS in one device',
      'Up to 5000 Hz AC stimulation',
      'Electrode impedance check',
      'Sham mode with standardised fade',
      'External trigger for EEG synchronisation',
    ],
    typical_protocols: ['tDCS MDD', 'tACS gamma (40 Hz) cognitive enhancement', 'tRNS motor learning'],
    notes: 'Most versatile non-invasive brain stimulation research platform. CE-marked; widely used in European tACS/tRNS research.',
    image_placeholder: 'tdcs-device',
  },

  {
    id: 'starstim-neuroelectrics',
    name: 'Starstim 32 (Neuroelectrics)',
    manufacturer: 'Neuroelectrics',
    modality: 'tDCS',
    modalities: ['tDCS', 'tACS', 'tRNS', 'HD-tDCS', 'EEG'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'hybrid',
    coil_types: [],
    max_frequency_hz: 1000,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['DC', 'sinusoidal AC', 'random noise'],
    connectivity: ['Wi-Fi', 'Bluetooth', 'USB'],
    neuronavigation_compatible: true,
    features: [
      '32-channel simultaneous EEG + tES',
      'Personalised targeting via Neuroelectrics Studio software',
      'Wireless operation',
      'High-definition electrode arrays (HD-tDCS)',
      'Real-time electrode impedance per channel',
    ],
    typical_protocols: ['HD-tDCS DLPFC', 'Closed-loop tACS', 'tRNS motor cortex'],
    notes: 'Premier combined EEG-tES research platform. Closed-loop stimulation based on real-time EEG phase possible.',
    image_placeholder: 'tdcs-device',
  },

  {
    id: 'soterix-4x1',
    name: 'Soterix Medical HD-tDCS 4×1 Ring',
    manufacturer: 'Soterix Medical',
    modality: 'tDCS',
    modalities: ['HD-tDCS', 'tDCS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 0,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['DC'],
    connectivity: ['USB'],
    neuronavigation_compatible: false,
    features: [
      '4×1 ring electrode montage for focal stimulation',
      'Central anode surrounded by 4 cathodes',
      'Reduced shunting vs. conventional tDCS',
      'Per-electrode impedance monitoring',
    ],
    typical_protocols: ['HD-tDCS focal DLPFC', 'HD-tDCS motor cortex rehabilitation', 'HD-tDCS chronic pain'],
    notes: 'Significantly more focal than 1×1 montage. Recommended for studies requiring anatomical precision.',
    image_placeholder: 'tdcs-device',
  },

  {
    id: 'caputron-mindgear',
    name: 'Caputron MindGear tDCS',
    manufacturer: 'Caputron',
    modality: 'tDCS',
    modalities: ['tDCS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'consumer',
    coil_types: [],
    max_frequency_hz: 0,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['DC'],
    connectivity: ['USB (charging)'],
    neuronavigation_compatible: false,
    features: [
      'Consumer-grade portable tDCS',
      'Pre-programmed montages',
      'App-guided session setup',
      'Battery powered',
    ],
    typical_protocols: ['tDCS focus enhancement', 'tDCS relaxation'],
    notes: 'Consumer device; not FDA-cleared or CE-marked for medical use. For investigational/wellness use only.',
    image_placeholder: 'tdcs-device',
  },

  {
    id: 'rogue-tdcs',
    name: 'Rogue Research tDCS Stimulator',
    manufacturer: 'Rogue Research',
    modality: 'tDCS',
    modalities: ['tDCS', 'tACS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'research',
    coil_types: [],
    max_frequency_hz: 1000,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['DC', 'sinusoidal AC'],
    connectivity: ['USB', 'Ethernet', 'Trigger I/O'],
    neuronavigation_compatible: true,
    features: [
      'Integrated with Brainsight neuronavigation',
      'Precise current control ±1 µA',
      'Custom waveform capability',
      'Multi-electrode configurations',
    ],
    typical_protocols: ['Navigated tDCS', 'tACS entrainment research', 'Multi-channel tES'],
    notes: 'Research-grade device designed for tight integration with Brainsight TMS neuronavigation platform.',
    image_placeholder: 'tdcs-device',
  },

  // ── NEUROFEEDBACK / EEG ───────────────────────────────────────────────────

  {
    id: 'emotiv-epoc-x',
    name: 'Emotiv EPOC X',
    manufacturer: 'Emotiv',
    modality: 'EEG/Neurofeedback',
    modalities: ['EEG/Neurofeedback'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'consumer',
    coil_types: [],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: [],
    connectivity: ['Bluetooth', 'USB dongle'],
    neuronavigation_compatible: false,
    features: [
      '14-channel EEG (10-20 system)',
      '256 Hz sample rate',
      'EmotivPRO software platform',
      'Performance Metrics (engagement, stress, focus)',
      'Mental commands API for BCI applications',
    ],
    typical_protocols: ['Alpha/theta neurofeedback', 'SMR ADHD training', 'Stress biofeedback'],
    notes: 'Consumer-grade; limited for clinical neurofeedback but suitable for wellness and research screening applications.',
    image_placeholder: 'eeg-device',
  },

  {
    id: 'brainbit-flex',
    name: 'BrainBit Flex',
    manufacturer: 'BrainBit',
    modality: 'EEG/Neurofeedback',
    modalities: ['EEG/Neurofeedback'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'consumer',
    coil_types: [],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: [],
    connectivity: ['Bluetooth 5.0'],
    neuronavigation_compatible: false,
    features: [
      '4-channel EEG (T3, T4, O1, O2)',
      '250 Hz sample rate',
      'Flexible headband form factor',
      'SDK for custom application development',
    ],
    typical_protocols: ['Alpha relaxation training', 'Sleep onset EEG monitoring'],
    notes: 'Ultra-portable; 4 channels limit clinical utility but sufficient for basic alpha/beta neurofeedback.',
    image_placeholder: 'eeg-device',
  },

  {
    id: 'gnautilus',
    name: 'g.Nautilus PRO',
    manufacturer: 'g.tec Medical Engineering',
    modality: 'EEG/Neurofeedback',
    modalities: ['EEG/Neurofeedback', 'BCI'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: [],
    connectivity: ['Wi-Fi', 'USB'],
    neuronavigation_compatible: false,
    features: [
      '32/64-channel wireless EEG',
      '500/1000 Hz sample rate',
      'Active electrodes with high SNR',
      'g.HIamp and g.USBamp compatible',
      'MATLAB/Simulink real-time processing',
      'BCI2000 and OpenViBE integration',
    ],
    typical_protocols: ['Clinical neurofeedback SMR/theta', 'P300 BCI', 'Motor imagery rehabilitation', 'SSVEP BCI'],
    notes: 'Research and clinical-grade wireless EEG. Premier platform for closed-loop neurofeedback and BCI research.',
    image_placeholder: 'eeg-device',
  },

  {
    id: 'muse-s',
    name: 'Muse S (Gen 2)',
    manufacturer: 'InteraXon',
    modality: 'EEG/Neurofeedback',
    modalities: ['EEG/Neurofeedback'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'consumer',
    coil_types: [],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: [],
    connectivity: ['Bluetooth'],
    neuronavigation_compatible: false,
    features: [
      '4-channel EEG (AF7, AF8, TP9, TP10)',
      'Sleep tracking headband',
      'Meditation/mindfulness feedback app',
      'PPG, accelerometer, gyroscope',
    ],
    typical_protocols: ['Mindfulness neurofeedback', 'Sleep stage monitoring (consumer)'],
    notes: 'Consumer wellness device; limited clinical utility. Useful for patient engagement and adherence in mindfulness programmes.',
    image_placeholder: 'eeg-device',
  },

  {
    id: 'openbci-cyton-daisy',
    name: 'OpenBCI Cyton+Daisy',
    manufacturer: 'OpenBCI',
    modality: 'EEG/Neurofeedback',
    modalities: ['EEG/Neurofeedback', 'BCI'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'research',
    coil_types: [],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: [],
    connectivity: ['Bluetooth (RFduino)', 'SD card logging'],
    neuronavigation_compatible: false,
    features: [
      '16-channel EEG at 125/250 Hz',
      'Open-source hardware and software',
      'Compatible with OpenBCI GUI and BrainFlow',
      'Expandable with EMG, ECG, EXG channels',
      'Ultracortex Mark IV headset compatible',
    ],
    typical_protocols: ['Research neurofeedback', 'Open-source BCI development', 'Tele-neurofeedback'],
    notes: 'Open-source research platform. Low cost enables accessible neurofeedback research; not for clinical diagnostic use.',
    image_placeholder: 'eeg-device',
  },

  {
    id: 'neurosity-crown',
    name: 'Neurosity Crown',
    manufacturer: 'Neurosity',
    modality: 'EEG/Neurofeedback',
    modalities: ['EEG/Neurofeedback'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'consumer',
    coil_types: [],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: [],
    connectivity: ['Wi-Fi', 'USB-C'],
    neuronavigation_compatible: false,
    features: [
      '8-channel EEG at 256 Hz',
      'Developer SDK (Node.js / Python)',
      'Cloud-based data streaming',
      'Focus and calm metric APIs',
    ],
    typical_protocols: ['Neurofeedback focus training', 'Developer BCI prototyping'],
    notes: 'Developer-focused EEG platform with cloud SDK. Not for clinical diagnostic or therapeutic use.',
    image_placeholder: 'eeg-device',
  },

  // ── taVNS DEVICES ─────────────────────────────────────────────────────────

  {
    id: 'nemos-cerbomed',
    name: 'Nemos (tVNS by Cerbomed)',
    manufacturer: 'Cerbomed / tVNS Technologies',
    modality: 'taVNS',
    modalities: ['taVNS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 25,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['biphasic rectangular'],
    connectivity: ['Proprietary cable'],
    neuronavigation_compatible: false,
    features: [
      'Tragus / cymba conchae ear electrode',
      'Adjustable pulse width (100–500 µs)',
      'CE-marked for epilepsy adjunct',
      'Handheld portable unit',
      'Therapy compliance logging',
    ],
    typical_protocols: ['taVNS depression 25 Hz', 'taVNS epilepsy adjunct', 'taVNS PTSD'],
    notes: 'First CE-marked taVNS device; extensively studied in depression and epilepsy. Targets auricular branch of vagus nerve (ABVN).',
    image_placeholder: 'tavns-device',
  },

  {
    id: 'gammacore-electrocore',
    name: 'gammaCore (nVNS)',
    manufacturer: 'electroCore',
    modality: 'taVNS',
    modalities: ['taVNS', 'nVNS'],
    fda_clearance: true,
    fda_indications: ['Cluster Headache', 'Migraine prevention', 'COVID-19 respiratory adjunct'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 25,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['sinusoidal burst'],
    connectivity: ['USB-C (charging)'],
    neuronavigation_compatible: false,
    features: [
      'Non-invasive cervical vagus nerve stimulation (neck)',
      'Two-minute treatment dose',
      'Patient self-administration',
      'Usage data logging',
      'FDA-cleared for cluster and migraine headache',
    ],
    typical_protocols: ['nVNS cluster headache acute', 'nVNS migraine prevention', 'nVNS inflammatory conditions'],
    notes: 'Applied to neck over carotid triangle (not auricular). FDA cleared for headache; separate from auricular taVNS devices.',
    image_placeholder: 'tavns-device',
  },

  {
    id: 'parasym-esense',
    name: 'Parasym eSense',
    manufacturer: 'Parasym',
    modality: 'taVNS',
    modalities: ['taVNS'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 30,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['biphasic'],
    connectivity: ['Bluetooth'],
    neuronavigation_compatible: false,
    features: [
      'Wireless ear clip electrode',
      'Smartphone app control',
      'Programmable stimulation parameters',
      'Heart rate variability monitoring',
      'CE-marked for cardiac autonomic modulation',
    ],
    typical_protocols: ['taVNS depression', 'taVNS heart rate variability enhancement', 'taVNS PTSD'],
    notes: 'CE-marked; wireless design improves patient adherence. Integrated HRV biofeedback provides objective autonomic response monitoring.',
    image_placeholder: 'tavns-device',
  },

  // ── CES DEVICES ───────────────────────────────────────────────────────────

  {
    id: 'alpha-stim-m',
    name: 'Alpha-Stim M',
    manufacturer: 'Electromedical Products International',
    modality: 'CES',
    modalities: ['CES', 'TENS'],
    fda_clearance: true,
    fda_indications: ['Anxiety', 'Depression', 'Insomnia', 'Pain'],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 0.5,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['modified square wave'],
    connectivity: ['USB (charging)'],
    neuronavigation_compatible: false,
    features: [
      'Ear clip electrodes (CES mode)',
      'Smart Probe for TENS pain application',
      'Proprietary 0.5 Hz waveform',
      '510(k) FDA-cleared for anxiety, depression, insomnia, pain',
      'Portable handheld design',
    ],
    typical_protocols: ['CES anxiety 60 min daily', 'CES insomnia', 'CES depression adjunct'],
    notes: 'Most evidence-supported CES device; multiple FDA 510(k) clearances. Ear clip delivery at 0.5 Hz is signature parameter.',
    image_placeholder: 'ces-device',
  },

  {
    id: 'fisher-wallace',
    name: 'Fisher Wallace Stimulator',
    manufacturer: 'Fisher Wallace Laboratories',
    modality: 'CES',
    modalities: ['CES'],
    fda_clearance: true,
    fda_indications: ['Anxiety', 'Depression', 'Insomnia'],
    ce_mark: false,
    device_type: 'clinical',
    coil_types: [],
    max_frequency_hz: 15000,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['carrier wave 15 kHz modulated at 500 Hz and 15 Hz'],
    connectivity: [],
    neuronavigation_compatible: false,
    features: [
      'FDA-cleared CES device',
      'Sponge electrode headband (temporal placement)',
      'Fixed 20-minute treatment time',
      'Three simultaneous frequencies',
      'Prescription required (US)',
    ],
    typical_protocols: ['CES anxiety', 'CES insomnia', 'CES adjunct depression'],
    notes: 'FDA-cleared; temporal electrode placement distinguishes it from ear-clip CES. Prescription required in the US.',
    image_placeholder: 'ces-device',
  },

  {
    id: 'ces-ultra',
    name: 'CES Ultra',
    manufacturer: 'Neuro-Fitness LLC',
    modality: 'CES',
    modalities: ['CES'],
    fda_clearance: true,
    fda_indications: ['Anxiety', 'Insomnia', 'Depression'],
    ce_mark: false,
    device_type: 'consumer',
    coil_types: [],
    max_frequency_hz: 100,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['square wave'],
    connectivity: [],
    neuronavigation_compatible: false,
    features: [
      'Adjustable frequency (0.5–100 Hz)',
      'Adjustable intensity',
      'Ear clip delivery',
      'FDA-cleared OTC device',
    ],
    typical_protocols: ['CES anxiety', 'CES sleep'],
    notes: 'Consumer-grade FDA-cleared CES; variable frequency allows research experimentation with different waveforms.',
    image_placeholder: 'ces-device',
  },

  // ── OTHER / EMERGING ─────────────────────────────────────────────────────

  {
    id: 'sofronics-tps',
    name: 'Softwave TPS System (Transcranial Pulse Stimulation)',
    manufacturer: 'Storz Medical / Sofronics',
    modality: 'TPS',
    modalities: ['TPS'],
    fda_clearance: true,
    fda_indications: ["Alzheimer's Disease (symptom management)"],
    ce_mark: true,
    device_type: 'clinical',
    coil_types: ['Focused ultrasound applicator'],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['single electrohydraulic shock wave pulses'],
    connectivity: ['USB', 'Ethernet'],
    neuronavigation_compatible: true,
    features: [
      'Focused low-energy ultrasound pulses',
      'MRI-based neuronavigation integration',
      'FDA-authorised for Alzheimer disease',
      'Non-thermal, non-ablative mechanism',
      'Depth penetration up to 8 cm',
    ],
    typical_protocols: ['TPS hippocampal stimulation Alzheimer', 'TPS depression investigational'],
    notes: "First FDA-authorised device for Alzheimer's symptom management via transcranial pulse stimulation. Neuronavigation required for targeting.",
    image_placeholder: 'tps-device',
  },

  {
    id: 'vielight-neuro-gamma',
    name: 'Vielight Neuro Gamma',
    manufacturer: 'Vielight',
    modality: 'PBM',
    modalities: ['PBM', 'tPBM'],
    fda_clearance: false,
    fda_indications: [],
    ce_mark: false,
    device_type: 'consumer',
    coil_types: ['Intranasal LED cluster', 'Scalp cluster (810 nm NIR)'],
    max_frequency_hz: 40,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['pulsed NIR 810 nm'],
    connectivity: ['USB-C'],
    neuronavigation_compatible: false,
    features: [
      '40 Hz gamma-pulsed near-infrared light',
      'Intranasal + transcranial delivery',
      'Default 20-minute session',
      'Default brain regions: default mode network nodes',
    ],
    typical_protocols: ['PBM 40Hz gamma cognitive enhancement', 'PBM Alzheimer investigational'],
    notes: 'Transcranial photobiomodulation device; not FDA-cleared. Investigational use for Alzheimer and cognitive enhancement.',
    image_placeholder: 'pbm-device',
  },

  {
    id: 'pons-helius',
    name: 'PONS Device (PoNS)',
    manufacturer: 'Helius Medical',
    modality: 'tTNS',
    modalities: ['tTNS'],
    fda_clearance: true,
    fda_indications: ['Multiple Sclerosis gait rehabilitation (adjunct)'],
    ce_mark: false,
    device_type: 'clinical',
    coil_types: ['Tongue electrode array'],
    max_frequency_hz: null,
    max_intensity_pct_mso: null,
    pulse_waveforms: ['biphasic rectangular'],
    connectivity: ['Proprietary'],
    neuronavigation_compatible: false,
    features: [
      'Translingual neurostimulation via tongue electrode',
      'FDA-authorised De Novo for MS gait',
      'Used concurrently with physical therapy',
      'Non-invasive cranial nerve V and VII stimulation',
    ],
    typical_protocols: ['PoNS MS gait rehabilitation', 'PoNS TBI balance (investigational)'],
    notes: 'FDA De Novo authorised for gait rehabilitation in mild-to-moderate MS. Must be used with supervised physiotherapy programme.',
    image_placeholder: 'tns-device',
  },

];

// ── Derived lookups ────────────────────────────────────────────────────────

export const DEVICE_BY_ID = Object.fromEntries(DEVICES.map(d => [d.id, d]));

export const DEVICES_BY_MODALITY = {};
DEVICES.forEach(d => {
  (d.modalities || [d.modality]).forEach(m => {
    if (!DEVICES_BY_MODALITY[m]) DEVICES_BY_MODALITY[m] = [];
    DEVICES_BY_MODALITY[m].push(d);
  });
});

export default DEVICES;
