/**
 * handbooks.js
 * Condition-specific and modality-specific patient and clinician handbooks.
 * DeepSynaps Protocol Studio — Registry
 */

export const HANDBOOK_TEMPLATES = [
  // ── PATIENT GUIDES: Condition + Modality ────────────────────────────────
  {
    id: 'hb-mdd-patient',
    name: 'Living with Depression: Patient Guide to TMS Treatment',
    type: 'patient',
    category: 'Condition',
    condition_id: 'mdd',
    modality: 'TMS/rTMS',
    target_audience: 'Patient and family',
    chapters: [
      { id: 'what-is-depression', title: 'Understanding Depression', pages: 4 },
      { id: 'what-is-tms', title: 'What is TMS?', pages: 6 },
      { id: 'how-tms-treats-depression', title: 'How TMS Treats Depression', pages: 4 },
      { id: 'what-to-expect', title: 'What to Expect During Treatment', pages: 5 },
      { id: 'managing-side-effects', title: 'Managing Side Effects', pages: 3 },
      { id: 'between-sessions', title: 'Between Sessions: Self-Care', pages: 4 },
      { id: 'measuring-progress', title: 'Tracking Your Progress', pages: 3 },
      { id: 'after-treatment', title: 'Life After TMS', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-03',
    evidence_base: 'FDA-cleared TMS for MDD; NICE guidance; >30 RCTs supporting efficacy',
    tags: ['patient-education', 'treatment-prep', 'depression'],
  },
  {
    id: 'hb-trd-patient',
    name: 'When Antidepressants Haven\'t Helped: TMS for Treatment-Resistant Depression',
    type: 'patient',
    category: 'Condition',
    condition_id: 'trd',
    modality: 'TMS/rTMS',
    target_audience: 'Patient and family',
    chapters: [
      { id: 'what-is-trd', title: 'Understanding Treatment-Resistant Depression', pages: 5 },
      { id: 'why-tms', title: 'Why TMS for TRD?', pages: 4 },
      { id: 'what-evidence', title: 'The Evidence for TMS in TRD', pages: 3 },
      { id: 'advanced-protocols', title: 'Advanced TMS Protocols (TBS, Deep TMS)', pages: 4 },
      { id: 'expectations', title: 'Realistic Expectations', pages: 3 },
      { id: 'combination-treatments', title: 'TMS Combined with Other Treatments', pages: 3 },
      { id: 'what-to-expect', title: 'What to Expect During Treatment', pages: 4 },
      { id: 'after-treatment', title: 'After Treatment & Maintenance', pages: 4 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 9',
    languages: ['en'],
    last_reviewed: '2024-03',
    evidence_base: 'FDA-cleared TMS for TRD; multiple RCTs in medication-resistant populations',
    tags: ['patient-education', 'trd', 'treatment-prep'],
  },
  {
    id: 'hb-ocd-patient',
    name: 'OCD and TMS: A Patient Guide',
    type: 'patient',
    category: 'Condition',
    condition_id: 'ocd',
    modality: 'TMS/rTMS',
    target_audience: 'Patient and family',
    chapters: [
      { id: 'understanding-ocd', title: 'Understanding OCD', pages: 5 },
      { id: 'ocd-and-brain', title: 'OCD and the Brain', pages: 3 },
      { id: 'tms-for-ocd', title: 'How TMS Treats OCD', pages: 4 },
      { id: 'what-to-expect', title: 'What to Expect', pages: 4 },
      { id: 'combined-with-erp', title: 'TMS Combined with ERP Therapy', pages: 4 },
      { id: 'managing-side-effects', title: 'Managing Side Effects', pages: 3 },
      { id: 'measuring-progress', title: 'Tracking Your Progress', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'FDA-cleared Deep TMS (BrainsWay) for OCD; published RCTs for H7 coil',
    tags: ['patient-education', 'ocd', 'treatment-prep'],
  },
  {
    id: 'hb-ptsd-patient',
    name: 'Trauma and Recovery: Patient Guide to TMS for PTSD',
    type: 'patient',
    category: 'Condition',
    condition_id: 'ptsd',
    modality: 'TMS/rTMS',
    target_audience: 'Patient and family',
    chapters: [
      { id: 'understanding-ptsd', title: 'Understanding PTSD', pages: 5 },
      { id: 'ptsd-and-brain', title: 'PTSD and the Brain', pages: 3 },
      { id: 'tms-for-ptsd', title: 'How TMS May Help PTSD', pages: 4 },
      { id: 'what-to-expect', title: 'What to Expect During Treatment', pages: 4 },
      { id: 'trauma-informed-care', title: 'Trauma-Informed Care During TMS', pages: 3 },
      { id: 'combined-treatments', title: 'TMS and Trauma Therapy Together', pages: 3 },
      { id: 'self-care', title: 'Self-Care Between Sessions', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Growing evidence base for TMS in PTSD; multiple RCTs; VA research programs',
    tags: ['patient-education', 'ptsd', 'trauma-informed'],
  },
  {
    id: 'hb-adhd-neurofeedback-patient',
    name: 'ADHD and Neurofeedback: A Patient and Family Guide',
    type: 'patient',
    category: 'Condition',
    condition_id: 'adhd',
    modality: 'Neurofeedback/EEG-BF',
    target_audience: 'Patient and family (adult and paediatric)',
    chapters: [
      { id: 'understanding-adhd', title: 'Understanding ADHD', pages: 5 },
      { id: 'adhd-and-brainwaves', title: 'ADHD and Brainwaves', pages: 4 },
      { id: 'what-is-neurofeedback', title: 'What is Neurofeedback?', pages: 5 },
      { id: 'what-to-expect', title: 'What to Expect in Sessions', pages: 4 },
      { id: 'for-parents', title: 'A Guide for Parents', pages: 4 },
      { id: 'at-home-strategies', title: 'ADHD Strategies at Home and School', pages: 5 },
      { id: 'tracking-progress', title: 'Tracking Progress', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 7',
    languages: ['en'],
    last_reviewed: '2024-02',
    evidence_base: 'Level 5 evidence (AAPB scale) for neurofeedback in ADHD; multiple RCTs',
    tags: ['patient-education', 'adhd', 'paediatric', 'neurofeedback'],
  },
  {
    id: 'hb-anxiety-tdcs-patient',
    name: 'Anxiety and tDCS: A Patient Guide',
    type: 'patient',
    category: 'Condition',
    condition_id: 'anxiety',
    modality: 'tDCS',
    target_audience: 'Patient',
    chapters: [
      { id: 'understanding-anxiety', title: 'Understanding Anxiety Disorders', pages: 4 },
      { id: 'anxiety-and-brain', title: 'Anxiety and the Brain', pages: 3 },
      { id: 'what-is-tdcs', title: 'What is tDCS?', pages: 5 },
      { id: 'what-to-expect', title: 'What to Expect During Sessions', pages: 4 },
      { id: 'combined-treatments', title: 'tDCS Combined with Therapy', pages: 3 },
      { id: 'self-management', title: 'Anxiety Self-Management Skills', pages: 4 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Emerging evidence for tDCS in anxiety; growing number of controlled trials',
    tags: ['patient-education', 'anxiety', 'tdcs'],
  },
  {
    id: 'hb-parkinsons-tms-patient',
    name: 'Parkinson\'s Disease and TMS: A Patient Guide',
    type: 'patient',
    category: 'Condition',
    condition_id: 'parkinsons',
    modality: 'TMS/rTMS',
    target_audience: 'Patient and carer',
    chapters: [
      { id: 'understanding-pd', title: 'Understanding Parkinson\'s Disease', pages: 5 },
      { id: 'tms-for-pd', title: 'How TMS May Help Parkinson\'s', pages: 4 },
      { id: 'motor-symptoms', title: 'TMS and Motor Symptoms', pages: 3 },
      { id: 'depression-in-pd', title: 'Managing Depression in Parkinson\'s', pages: 3 },
      { id: 'what-to-expect', title: 'What to Expect During Treatment', pages: 4 },
      { id: 'complementary-care', title: 'TMS as Complementary Care', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 9',
    languages: ['en'],
    last_reviewed: '2023-12',
    evidence_base: 'Multiple systematic reviews supporting TMS for Parkinson\'s motor symptoms and depression',
    tags: ['patient-education', 'parkinsons', 'neurological'],
  },
  {
    id: 'hb-pain-tdcs-patient',
    name: 'Chronic Pain and tDCS: A Patient Guide',
    type: 'patient',
    category: 'Condition',
    condition_id: 'chronic-pain',
    modality: 'tDCS',
    target_audience: 'Patient',
    chapters: [
      { id: 'understanding-chronic-pain', title: 'Understanding Chronic Pain', pages: 5 },
      { id: 'pain-and-brain', title: 'Pain and the Brain', pages: 4 },
      { id: 'tdcs-for-pain', title: 'How tDCS May Relieve Pain', pages: 4 },
      { id: 'what-to-expect', title: 'What to Expect in Sessions', pages: 3 },
      { id: 'pain-management-toolkit', title: 'Your Pain Management Toolkit', pages: 5 },
      { id: 'pacing-activity', title: 'Pacing & Activity Management', pages: 4 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Multiple RCTs for tDCS in fibromyalgia, CRPS, and neuropathic pain',
    tags: ['patient-education', 'chronic-pain', 'tdcs'],
  },
  {
    id: 'hb-stroke-tms-patient',
    name: 'Stroke Recovery and TMS: A Patient Guide',
    type: 'patient',
    category: 'Condition',
    condition_id: 'stroke',
    modality: 'TMS/rTMS',
    target_audience: 'Patient and carer',
    chapters: [
      { id: 'stroke-recovery', title: 'Understanding Stroke Recovery', pages: 5 },
      { id: 'neuroplasticity', title: 'Neuroplasticity: Your Brain Can Change', pages: 4 },
      { id: 'tms-for-stroke', title: 'How TMS Supports Recovery', pages: 5 },
      { id: 'what-to-expect', title: 'What to Expect During Treatment', pages: 4 },
      { id: 'combined-rehab', title: 'TMS with Other Rehabilitation', pages: 4 },
      { id: 'progress-tracking', title: 'Tracking Your Recovery', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Systematic reviews and RCTs for TMS in post-stroke aphasia and motor rehabilitation',
    tags: ['patient-education', 'stroke', 'rehabilitation'],
  },
  {
    id: 'hb-insomnia-ces-patient',
    name: 'Sleep and CES: A Patient Guide to Cranial Electrotherapy Stimulation for Insomnia',
    type: 'patient',
    category: 'Condition',
    condition_id: 'insomnia',
    modality: 'CES',
    target_audience: 'Patient',
    chapters: [
      { id: 'understanding-insomnia', title: 'Understanding Insomnia', pages: 4 },
      { id: 'sleep-science', title: 'The Science of Sleep', pages: 3 },
      { id: 'what-is-ces', title: 'What is CES?', pages: 4 },
      { id: 'what-to-expect', title: 'What to Expect During Treatment', pages: 3 },
      { id: 'sleep-hygiene', title: 'Sleep Hygiene Essentials', pages: 5 },
      { id: 'home-use', title: 'Home CES Use Guidelines', pages: 4 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2023-12',
    evidence_base: 'FDA-cleared CES devices for insomnia, anxiety, and depression',
    tags: ['patient-education', 'insomnia', 'ces', 'sleep'],
  },

  // ── CLINICIAN HANDBOOKS ─────────────────────────────────────────────────
  {
    id: 'hb-tms-clinician',
    name: 'TMS Clinical Practice Guide',
    type: 'clinician',
    category: 'Modality',
    condition_id: null,
    modality: 'TMS/rTMS',
    target_audience: 'Treating clinicians, psychiatrists, nurses',
    chapters: [
      { id: 'physics-mechanism', title: 'Physics and Mechanism of Action', pages: 8 },
      { id: 'indications', title: 'Indications and Evidence Base', pages: 10 },
      { id: 'contraindications', title: 'Contraindications and Safety Screening', pages: 6 },
      { id: 'motor-threshold', title: 'Motor Threshold Determination', pages: 6 },
      { id: 'coil-positioning', title: 'Coil Positioning Methods', pages: 8 },
      { id: 'protocols', title: 'Standard & Advanced Protocols', pages: 12 },
      { id: 'adverse-events', title: 'Managing Adverse Events', pages: 6 },
      { id: 'outcome-monitoring', title: 'Outcome Monitoring & Assessment', pages: 5 },
      { id: 'equipment-maintenance', title: 'Equipment Maintenance', pages: 4 },
      { id: 'documentation', title: 'Documentation Standards', pages: 4 },
    ],
    reading_level: 'Professional',
    languages: ['en'],
    last_reviewed: '2024-03',
    evidence_base: 'CLINICAL-TMS Consortium guidelines; APA practice guidelines; NICE',
    tags: ['clinician-reference', 'tms', 'clinical-practice'],
  },
  {
    id: 'hb-tdcs-clinician',
    name: 'tDCS Parameter Reference and Clinical Guide',
    type: 'clinician',
    category: 'Modality',
    condition_id: null,
    modality: 'tDCS',
    target_audience: 'Treating clinicians, researchers',
    chapters: [
      { id: 'mechanism', title: 'Mechanism of Action', pages: 6 },
      { id: 'electrode-montages', title: 'Electrode Montages by Indication', pages: 12 },
      { id: 'parameters', title: 'Parameter Selection Reference', pages: 8 },
      { id: 'safety', title: 'Safety and Skin Care', pages: 5 },
      { id: 'protocols-by-condition', title: 'Protocols by Condition', pages: 15 },
      { id: 'concurrent-interventions', title: 'tDCS with Concurrent Interventions', pages: 6 },
      { id: 'outcome-assessment', title: 'Outcome Assessment', pages: 5 },
      { id: 'documentation', title: 'Documentation Standards', pages: 3 },
    ],
    reading_level: 'Professional',
    languages: ['en'],
    last_reviewed: '2024-02',
    evidence_base: 'Bikson et al. safety guidelines; Fregni & Pascual-Leone protocols; current RCT evidence',
    tags: ['clinician-reference', 'tdcs', 'clinical-practice'],
  },
  {
    id: 'hb-neurofeedback-clinician',
    name: 'Neurofeedback Protocol Handbook for Clinicians',
    type: 'clinician',
    category: 'Modality',
    condition_id: null,
    modality: 'Neurofeedback/EEG-BF',
    target_audience: 'Neurofeedback practitioners, psychologists, neurologists',
    chapters: [
      { id: 'eeg-basics', title: 'EEG Fundamentals for Clinicians', pages: 8 },
      { id: 'neurofeedback-theory', title: 'Neurofeedback Theory & Evidence', pages: 8 },
      { id: 'assessment-qeeg', title: 'QEEG Assessment', pages: 7 },
      { id: 'protocol-selection', title: 'Protocol Selection by Indication', pages: 12 },
      { id: 'theta-alpha-beta', title: 'Alpha, Beta, Theta, and SMR Training', pages: 8 },
      { id: 'infra-low', title: 'Infra-Low Frequency Training', pages: 5 },
      { id: 'loreta', title: 'sLORETA / Z-Score Training', pages: 5 },
      { id: 'artifact-management', title: 'Artifact Identification and Management', pages: 6 },
      { id: 'outcome-monitoring', title: 'Outcome Monitoring', pages: 4 },
    ],
    reading_level: 'Professional',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'ISNR guidelines; AAPB standards; peer-reviewed protocol literature',
    tags: ['clinician-reference', 'neurofeedback', 'eeg'],
  },
  {
    id: 'hb-tavns-clinician',
    name: 'taVNS Clinical Practice Guide',
    type: 'clinician',
    category: 'Modality',
    condition_id: null,
    modality: 'taVNS',
    target_audience: 'Treating clinicians, neurologists',
    chapters: [
      { id: 'vagus-nerve-anatomy', title: 'Vagus Nerve Anatomy & Physiology', pages: 6 },
      { id: 'mechanism-tavns', title: 'Mechanism of taVNS', pages: 5 },
      { id: 'indications-evidence', title: 'Indications and Evidence Base', pages: 8 },
      { id: 'device-operation', title: 'Device Operation & Electrode Placement', pages: 5 },
      { id: 'parameter-selection', title: 'Parameter Selection', pages: 5 },
      { id: 'contraindications', title: 'Contraindications & Safety', pages: 4 },
      { id: 'protocols-by-condition', title: 'Protocols by Condition', pages: 10 },
      { id: 'home-use', title: 'Home Use Protocols', pages: 4 },
      { id: 'documentation', title: 'Documentation Standards', pages: 3 },
    ],
    reading_level: 'Professional',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Published RCTs in epilepsy, depression, migraine; CE-marked device literature',
    tags: ['clinician-reference', 'tavns', 'clinical-practice'],
  },
  {
    id: 'hb-safety-emergency',
    name: 'Safety and Emergency Protocols Handbook',
    type: 'clinician',
    category: 'Safety',
    condition_id: null,
    modality: null,
    target_audience: 'All clinical and technical staff',
    chapters: [
      { id: 'safety-overview', title: 'Safety Framework Overview', pages: 4 },
      { id: 'screening-tools', title: 'Pre-Treatment Safety Screening', pages: 6 },
      { id: 'contraindication-reference', title: 'Contraindication Quick Reference', pages: 5 },
      { id: 'seizure-management', title: 'Seizure Management Protocol', pages: 4 },
      { id: 'vasovagal-syncope', title: 'Vasovagal Syncope Protocol', pages: 3 },
      { id: 'acute-distress', title: 'Acute Psychological Distress Protocol', pages: 4 },
      { id: 'equipment-failure', title: 'Equipment Failure Procedures', pages: 3 },
      { id: 'incident-reporting', title: 'Incident Reporting Procedures', pages: 4 },
      { id: 'emergency-contacts', title: 'Emergency Contacts & Escalation', pages: 2 },
    ],
    reading_level: 'Professional',
    languages: ['en'],
    last_reviewed: '2024-03',
    evidence_base: 'International TMS safety consensus; Rossi et al. (2021); facility accreditation standards',
    tags: ['safety', 'emergency', 'all-staff', 'mandatory'],
  },

  // ── MODALITY GUIDES ─────────────────────────────────────────────────────
  {
    id: 'hb-guide-tms-patient',
    name: 'Your Guide to TMS Treatment',
    type: 'patient',
    category: 'Modality',
    condition_id: null,
    modality: 'TMS/rTMS',
    target_audience: 'All TMS patients',
    chapters: [
      { id: 'what-is-tms', title: 'What is TMS?', pages: 5 },
      { id: 'your-first-session', title: 'Your First TMS Session', pages: 4 },
      { id: 'a-typical-session', title: 'A Typical TMS Session', pages: 3 },
      { id: 'side-effects', title: 'Understanding Side Effects', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 4 },
      { id: 'contact', title: 'Contact Us', pages: 1 },
    ],
    reading_level: 'Grade 7',
    languages: ['en'],
    last_reviewed: '2024-03',
    evidence_base: 'FDA-cleared TMS; manufacturer patient education materials',
    tags: ['patient-education', 'tms', 'general'],
  },
  {
    id: 'hb-guide-tdcs-patient',
    name: 'Your Guide to tDCS Treatment',
    type: 'patient',
    category: 'Modality',
    condition_id: null,
    modality: 'tDCS',
    target_audience: 'All tDCS patients',
    chapters: [
      { id: 'what-is-tdcs', title: 'What is tDCS?', pages: 5 },
      { id: 'your-first-session', title: 'Your First Session', pages: 4 },
      { id: 'the-electrodes', title: 'About the Electrodes', pages: 3 },
      { id: 'sensations', title: 'What You Might Feel', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 7',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Published patient information from leading tDCS research centres',
    tags: ['patient-education', 'tdcs', 'general'],
  },
  {
    id: 'hb-guide-neurofeedback-patient',
    name: 'Your Guide to Neurofeedback',
    type: 'patient',
    category: 'Modality',
    condition_id: null,
    modality: 'Neurofeedback/EEG-BF',
    target_audience: 'All neurofeedback patients',
    chapters: [
      { id: 'what-is-neurofeedback', title: 'What is Neurofeedback?', pages: 5 },
      { id: 'your-first-session', title: 'Your First Session', pages: 4 },
      { id: 'cap-and-sensors', title: 'The EEG Cap and Sensors', pages: 3 },
      { id: 'what-happens', title: 'What Happens in a Session', pages: 3 },
      { id: 'how-many-sessions', title: 'How Many Sessions Will I Need?', pages: 2 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 7',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'ISNR and AAPB patient education guidelines',
    tags: ['patient-education', 'neurofeedback', 'general'],
  },
  {
    id: 'hb-guide-tavns-patient',
    name: 'Your Guide to taVNS',
    type: 'patient',
    category: 'Modality',
    condition_id: null,
    modality: 'taVNS',
    target_audience: 'All taVNS patients',
    chapters: [
      { id: 'what-is-tavns', title: 'What is taVNS?', pages: 5 },
      { id: 'the-vagus-nerve', title: 'Your Vagus Nerve', pages: 3 },
      { id: 'your-first-session', title: 'Your First Session', pages: 3 },
      { id: 'the-device', title: 'The taVNS Device', pages: 3 },
      { id: 'sensations', title: 'What You Might Feel', pages: 2 },
      { id: 'home-use', title: 'Using taVNS at Home', pages: 4 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 7',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'CE-marked device patient information; published clinical trial summaries',
    tags: ['patient-education', 'tavns', 'general'],
  },

  // ── CAREGIVER GUIDES ────────────────────────────────────────────────────
  {
    id: 'hb-caregiver-tms',
    name: 'Supporting a Loved One Through TMS Treatment',
    type: 'caregiver',
    category: 'General',
    condition_id: null,
    modality: 'TMS/rTMS',
    target_audience: 'Family members and carers of TMS patients',
    chapters: [
      { id: 'what-is-tms', title: 'Understanding TMS', pages: 4 },
      { id: 'what-to-expect', title: 'What to Expect Week by Week', pages: 5 },
      { id: 'how-to-support', title: 'How You Can Help', pages: 5 },
      { id: 'side-effects', title: 'Understanding Side Effects', pages: 3 },
      { id: 'if-concerned', title: 'When to Be Concerned', pages: 3 },
      { id: 'carer-self-care', title: 'Looking After Yourself as a Carer', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 3 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-01',
    evidence_base: 'Carer experience research; depression family psychoeducation literature',
    tags: ['carer-education', 'family-support', 'tms'],
  },
  {
    id: 'hb-caregiver-paediatric-tms',
    name: 'Paediatric TMS: A Guide for Parents and Carers',
    type: 'caregiver',
    category: 'General',
    condition_id: null,
    modality: 'TMS/rTMS',
    target_audience: 'Parents and carers of children receiving TMS',
    chapters: [
      { id: 'tms-for-children', title: 'TMS for Children and Adolescents', pages: 5 },
      { id: 'safety-paediatric', title: 'Is TMS Safe for My Child?', pages: 4 },
      { id: 'what-to-expect', title: 'What Your Child Will Experience', pages: 4 },
      { id: 'how-to-prepare', title: 'Preparing Your Child for TMS', pages: 4 },
      { id: 'how-to-support', title: 'Supporting Your Child Through Treatment', pages: 4 },
      { id: 'school-and-activities', title: 'School and Activities During Treatment', pages: 3 },
      { id: 'faqs', title: 'Frequently Asked Questions', pages: 4 },
    ],
    reading_level: 'Grade 8',
    languages: ['en'],
    last_reviewed: '2024-02',
    evidence_base: 'Paediatric TMS safety literature; AACAP guidelines; published paediatric TMS RCTs',
    tags: ['carer-education', 'paediatric', 'tms', 'family'],
  },
  {
    id: 'hb-staff-orientation',
    name: 'Neuromodulation Clinic Staff Orientation Handbook',
    type: 'staff',
    category: 'General',
    condition_id: null,
    modality: null,
    target_audience: 'New clinical and administrative staff',
    chapters: [
      { id: 'clinic-overview', title: 'Clinic Overview & Values', pages: 4 },
      { id: 'modality-overview', title: 'Overview of Modalities Offered', pages: 8 },
      { id: 'safety-essentials', title: 'Safety Essentials', pages: 6 },
      { id: 'consent-documentation', title: 'Consent & Documentation Procedures', pages: 5 },
      { id: 'patient-flow', title: 'Patient Pathway & Scheduling', pages: 4 },
      { id: 'equipment-basics', title: 'Equipment Overview', pages: 4 },
      { id: 'emergency-procedures', title: 'Emergency Procedures', pages: 4 },
      { id: 'professional-conduct', title: 'Professional Conduct & Boundaries', pages: 3 },
    ],
    reading_level: 'Professional',
    languages: ['en'],
    last_reviewed: '2024-03',
    evidence_base: 'Clinical governance standards; facility accreditation requirements',
    tags: ['staff-training', 'orientation', 'administrative'],
  },
];

export const HANDBOOK_BY_ID = Object.fromEntries(HANDBOOK_TEMPLATES.map(h => [h.id, h]));
export default HANDBOOK_TEMPLATES;
