// protocols.js — Reference protocol templates for neuromodulation practice
// DeepSynaps Protocol Studio
// These are population-level templates, NOT patient-specific courses.

export const PROTOCOL_TEMPLATES = [

  // ── TMS — MAJOR DEPRESSIVE DISORDER ───────────────────────────────────────

  {
    id: 'tms-mdd-hf-standard',
    name: 'HF-rTMS Standard MDD Protocol',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'TMS/rTMS',
    classification: 'on-label',
    evidence_grade: 'A',
    fda_cleared: true,
    sessions: 36,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      frequency_hz: 10,
      intensity_pct_mso: 120,
      pulses_per_session: 3000,
      train_duration_s: 4,
      inter_train_interval_s: 26,
      trains_per_session: 75,
      target: 'DLPFC-L',
      coil: 'Figure-8 (70mm)',
      positioning: 'Beam F3 rule or MRI neuronavigation',
    },
    outcome_measures: ['PHQ-9', 'MADRS', 'CGI-S', 'CGI-I'],
    contraindications: [
      'Ferromagnetic implants in head or neck',
      'Cochlear implant',
      'Active seizure disorder or epilepsy',
      'Raised intracranial pressure',
      'Pregnancy (relative)',
      'Active psychosis',
    ],
    governance_flags: [],
    notes: 'FDA-cleared reference protocol (NeuroStar approval basis: O\'Reardon et al., 2007). 10 Hz, 4s trains, 26s ITI, 3000 pulses. Neuronavigation improves DLPFC accuracy. Screen for seizure risk before initiating.',
    references: ["O'Reardon et al., 2007, Biol Psychiatry", 'Carpenter et al., 2012, Brain Stimul'],
  },

  {
    id: 'tms-mdd-itbs',
    name: 'iTBS Standard MDD Protocol (2-Minute)',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'TMS/rTMS',
    classification: 'on-label',
    evidence_grade: 'A',
    fda_cleared: true,
    sessions: 36,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      frequency_hz: 50,
      burst_frequency_hz: 5,
      pulses_per_burst: 3,
      intensity_pct_mso: 80,
      pulses_per_session: 600,
      train_duration_s: 2,
      inter_train_interval_s: 8,
      trains_per_session: 20,
      session_duration_min: 3,
      target: 'DLPFC-L',
      coil: 'Figure-8 (70mm)',
      positioning: 'Beam F3 rule or MRI neuronavigation',
    },
    outcome_measures: ['PHQ-9', 'MADRS', 'CGI-S', 'CGI-I'],
    contraindications: [
      'Ferromagnetic implants in head or neck',
      'Cochlear implant',
      'Active seizure disorder',
      'Active psychosis',
    ],
    governance_flags: [],
    notes: 'Non-inferior to 10 Hz HF-rTMS (THREE-D trial, Blumberger et al. 2018). Session duration = 3 min vs. 37 min for HF. 80% AMT intensity. Enables higher session throughput in busy clinics.',
    references: ['Blumberger et al., 2018, Lancet', 'Health Canada approval 2018', 'FDA 510(k) clearance 2018'],
  },

  {
    id: 'tms-mdd-deep-h1',
    name: 'Deep TMS H1-Coil MDD Protocol',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'TMS/rTMS',
    classification: 'on-label',
    evidence_grade: 'A',
    fda_cleared: true,
    sessions: 30,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      frequency_hz: 18,
      intensity_pct_mso: 120,
      pulses_per_session: 1980,
      train_duration_s: 2,
      inter_train_interval_s: 20,
      trains_per_session: 55,
      target: 'DLPFC-L bilateral',
      coil: 'H1-Coil (BrainsWay)',
      positioning: 'Helmet-based standardised placement',
    },
    outcome_measures: ['HAM-D17', 'MADRS', 'CGI-S', 'CGI-I'],
    contraindications: [
      'Ferromagnetic implants in head or neck',
      'Cochlear implant',
      'Active seizure disorder',
      'Cardiac pacemaker',
    ],
    governance_flags: [],
    notes: 'FDA-cleared BrainsWay dTMS protocol. H1-coil reaches deeper DLPFC layers bilaterally without neuronavigation. 18 Hz, 2s trains, 20s ITI.',
    references: ['Levkovitz et al., 2015, World Psychiatry', 'BrainsWay FDA 510(k) 2013'],
  },

  {
    id: 'tms-mdd-bilateral',
    name: 'Bilateral TMS MDD (HF-L + LF-R Sequential)',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 36,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      left_frequency_hz: 10,
      left_intensity_pct_mso: 110,
      left_pulses: 2000,
      right_frequency_hz: 1,
      right_intensity_pct_mso: 110,
      right_pulses: 1200,
      total_pulses_per_session: 3200,
      target: 'DLPFC bilateral (L active, R inhibitory)',
      coil: 'Figure-8 (70mm)',
      positioning: 'Beam F3/F4 or neuronavigation',
    },
    outcome_measures: ['HAM-D17', 'PHQ-9', 'MADRS', 'CGI-S'],
    contraindications: [
      'Ferromagnetic implants in head or neck',
      'Active seizure disorder',
      'Bipolar I (increased switch risk)',
    ],
    governance_flags: ['off-label-use', 'clinical-governance-review-recommended'],
    notes: 'Sequential LH HF then RH LF. Evidence from multiple open-label trials and one RCT (Fitzgerald et al., 2006). Right LF may augment left HF via interhemispheric disinhibition. Governance sign-off recommended.',
    references: ['Fitzgerald et al., 2006, Am J Psychiatry', 'Isserles et al., 2011, Brain Stimul'],
  },

  {
    id: 'tms-mdd-saint',
    name: 'SAINT Accelerated TMS Protocol (MDD)',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 50,
    sessions_per_week: 50,
    duration_weeks: 1,
    parameters: {
      sessions_per_day: 10,
      inter_session_interval_min: 50,
      protocol_per_session: 'iTBS',
      frequency_hz: 50,
      burst_frequency_hz: 5,
      pulses_per_session: 1800,
      intensity_pct_mso: 90,
      target: 'DLPFC-L (individualised via resting-state fMRI sgACC anticorrelation)',
      coil: 'Figure-8 (70mm)',
      positioning: 'MRI neuronavigation — sgACC anticorrelation targeting',
    },
    outcome_measures: ['HDRS', 'PHQ-9', 'MADRS', 'CGI-S'],
    contraindications: [
      'Active seizure disorder',
      'Ferromagnetic cranial implants',
      'Inability to tolerate 10 consecutive sessions per day',
      'MRI contraindication (fMRI targeting required)',
    ],
    governance_flags: ['off-label-use', 'requires-institutional-review', 'fmri-targeting-required', 'accelerated-protocol'],
    notes: 'Stanford Accelerated Intelligent Neuromodulation Therapy. 5-day intensive: 10 iTBS sessions/day, 50-minute gaps. 90% remission rate in open-label (Cole et al., 2022 AJP). fMRI-guided personalised DLPFC target is integral to efficacy. Not widely available; requires dedicated infrastructure.',
    references: ['Cole et al., 2022, Am J Psychiatry', 'Williams et al., 2018, Am J Psychiatry'],
  },

  // ── TMS — ANXIETY DISORDERS ───────────────────────────────────────────────

  {
    id: 'tms-anxiety-lf-rdlpfc',
    name: 'LF-rTMS Right DLPFC for Anxiety',
    condition_id: 'anxiety',
    condition: 'Anxiety Disorders',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 1,
      intensity_pct_mso: 110,
      pulses_per_session: 1200,
      train_duration_s: 60,
      inter_train_interval_s: 30,
      trains_per_session: 20,
      target: 'DLPFC-R',
      coil: 'Figure-8 (70mm)',
      positioning: 'Beam F4 or neuronavigation',
    },
    outcome_measures: ['HAM-A', 'GAD-7', 'BAI', 'CGI-S'],
    contraindications: [
      'Active seizure disorder',
      'Ferromagnetic cranial implants',
    ],
    governance_flags: ['off-label-use'],
    notes: 'Inhibitory LF-rTMS to right DLPFC leverages right-hemisphere hyperactivity in anxiety disorders. Strongest evidence in GAD and social anxiety. Often combined with HF-L for bilateral approach.',
    references: ['Diefenbach et al., 2016, Brain Stimul', 'Mantovani et al., 2013, Depress Anxiety'],
  },

  {
    id: 'tms-gad',
    name: 'HF-rTMS Left DLPFC for GAD',
    condition_id: 'gad',
    condition: 'Generalised Anxiety Disorder',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 10,
      intensity_pct_mso: 110,
      pulses_per_session: 2000,
      train_duration_s: 4,
      inter_train_interval_s: 26,
      trains_per_session: 50,
      target: 'DLPFC-L',
      coil: 'Figure-8 (70mm)',
      positioning: 'Beam F3',
    },
    outcome_measures: ['GAD-7', 'HAM-A', 'CGI-S', 'PHQ-9'],
    contraindications: [
      'Active seizure disorder',
      'Ferromagnetic cranial implants',
    ],
    governance_flags: ['off-label-use'],
    notes: 'Extrapolation from MDD evidence; comorbid MDD/GAD presentations are common. Consider bilateral protocol if anxiety-dominant. Limited RCT evidence specific to GAD.',
    references: ['Bystritsky et al., 2008, J Clin Psychiatry', 'Dilkov et al., 2017, Psychiatry Res'],
  },

  {
    id: 'tms-ptsd-dlpfc',
    name: 'HF-rTMS DLPFC for PTSD',
    condition_id: 'ptsd',
    condition: 'Post-Traumatic Stress Disorder',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 10,
      intensity_pct_mso: 110,
      pulses_per_session: 2000,
      train_duration_s: 4,
      inter_train_interval_s: 26,
      trains_per_session: 50,
      target: 'DLPFC-R',
      coil: 'Figure-8 (70mm)',
      positioning: 'Beam F4 or neuronavigation',
    },
    outcome_measures: ['PCL-5', 'CAPS-5', 'PHQ-9', 'CGI-S'],
    contraindications: [
      'Active suicidality',
      'Active psychosis',
      'Ferromagnetic cranial implants',
    ],
    governance_flags: ['off-label-use', 'trauma-informed-care-required'],
    notes: 'Right DLPFC target based on hyperactive threat/fear circuitry hypothesis. RCT by Watts et al. (2012) demonstrated PTSD symptom reduction. Trauma-informed care protocols essential; risk of dissociation during sessions.',
    references: ['Watts et al., 2012, J Clin Psychiatry', 'Isserles et al., 2013, Neuropsychopharmacology'],
  },

  // ── TMS — OCD ─────────────────────────────────────────────────────────────

  {
    id: 'tms-ocd-deep-h7',
    name: 'Deep TMS H7-Coil OCD Protocol (BrainsWay)',
    condition_id: 'ocd',
    condition: 'Obsessive-Compulsive Disorder',
    modality: 'TMS/rTMS',
    classification: 'on-label',
    evidence_grade: 'A',
    fda_cleared: true,
    sessions: 29,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      frequency_hz: 20,
      intensity_pct_mso: 100,
      pulses_per_session: 1800,
      train_duration_s: 2,
      inter_train_interval_s: 20,
      trains_per_session: 45,
      target: 'mPFC + ACC (H7-coil)',
      coil: 'H7-Coil (BrainsWay)',
      positioning: 'Helmet placement; symptom provocation immediately pre-stimulation',
      provocation_protocol: 'Patient-specific OCD symptom exposure (standardised 15-min script) immediately before each session',
    },
    outcome_measures: ['Y-BOCS', 'OCI-R', 'CGI-S', 'CGI-I'],
    contraindications: [
      'Ferromagnetic cranial implants',
      'Active seizure disorder',
      'Insufficient response to ≥2 adequate SRI trials (eligibility, not contraindication)',
      'Active suicidality requiring inpatient care',
    ],
    governance_flags: [],
    notes: 'FDA-cleared 2018. Y-BOCS ≥20 eligibility threshold. Symptom provocation before each session is integral — activates OCD circuitry before stimulation. Response defined as ≥30% Y-BOCS reduction.',
    references: ['Carmi et al., 2019, Am J Psychiatry', 'BrainsWay FDA De Novo 2018'],
  },

  {
    id: 'tms-ocd-standard',
    name: 'LF-rTMS OFC/pre-SMA for OCD',
    condition_id: 'ocd',
    condition: 'Obsessive-Compulsive Disorder',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 1,
      intensity_pct_mso: 100,
      pulses_per_session: 1200,
      train_duration_s: 60,
      inter_train_interval_s: 30,
      trains_per_session: 20,
      target: 'pre-SMA / OFC',
      coil: 'Figure-8 (70mm)',
      positioning: 'Neuronavigation preferred; or 2 cm anterior to vertex midline for pre-SMA',
    },
    outcome_measures: ['Y-BOCS', 'OCI-R', 'CGI-S'],
    contraindications: [
      'Active seizure disorder',
      'Ferromagnetic cranial implants',
    ],
    governance_flags: ['off-label-use'],
    notes: 'Pre-SMA target has RCT support (Mantovani et al., 2010); OFC target investigational. Alternative to H7-coil in clinics without BrainsWay system.',
    references: ['Mantovani et al., 2010, J Clin Psychiatry', 'Gomes et al., 2012, Biol Psychiatry'],
  },

  // ── TMS — OTHER CONDITIONS ────────────────────────────────────────────────

  {
    id: 'tms-schizophrenia-avh',
    name: 'LF-rTMS Left Temporoparietal for Auditory Verbal Hallucinations',
    condition_id: 'schizophrenia',
    condition: 'Schizophrenia',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 1,
      intensity_pct_mso: 90,
      pulses_per_session: 1200,
      train_duration_s: 60,
      inter_train_interval_s: 30,
      trains_per_session: 20,
      target: 'Left temporoparietal junction (TPJ / T3-P3)',
      coil: 'Figure-8 (70mm)',
      positioning: '50% between T3 and P3 (10-20 system) or neuronavigation',
    },
    outcome_measures: ['PANSS', 'BPRS', 'AHRS (Auditory Hallucination Rating Scale)', 'CGI-S'],
    contraindications: [
      'Active seizure disorder',
      'Ferromagnetic cranial implants',
      'Clozapine (increases seizure risk — consult psychiatry)',
    ],
    governance_flags: ['off-label-use', 'concurrent-antipsychotic-review-required'],
    notes: 'Inhibitory LF-rTMS to TPJ targets hyperactive speech-perception cortex generating AVH. Meta-analytic effect sizes modest (Slotema et al., 2010 meta-analysis). Coordinate psychiatric medication review. Treatment-resistant AVH only.',
    references: ['Hoffman et al., 2003, Arch Gen Psychiatry', 'Slotema et al., 2010, J Clin Psychiatry'],
  },

  {
    id: 'tms-addiction-mfc',
    name: 'Deep TMS H4/H7-Coil for Substance Use Disorder',
    condition_id: 'addiction',
    condition: 'Substance Use Disorder',
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 10,
      intensity_pct_mso: 100,
      pulses_per_session: 1800,
      trains_per_session: 45,
      target: 'mPFC + ACC (craving circuitry)',
      coil: 'H4-Coil or H7-Coil (BrainsWay)',
      positioning: 'Helmet placement; cue-exposure provocation immediately pre-stimulation',
      provocation_protocol: 'Substance-specific cue exposure (images/odours) 15 min before stimulation',
    },
    outcome_measures: ['Craving VAS', 'AUDIT / DAST-10', 'CGI-S', 'Self-reported use days'],
    contraindications: [
      'Active withdrawal requiring medical management',
      'Seizure history (especially alcohol-related)',
      'Ferromagnetic cranial implants',
    ],
    governance_flags: ['off-label-use', 'requires-addiction-medicine-consultation', 'cue-exposure-protocol-required'],
    notes: 'FDA approved BrainsWay dTMS for smoking cessation (2020). Alcohol, cocaine, and opioid craving protocols are investigational. Cue-elicited craving activates mPFC target prior to stimulation.',
    references: ['Dinur-Klein et al., 2014, Biol Psychiatry', 'BrainsWay FDA clearance smoking 2020'],
  },

  {
    id: 'tms-parkinsons-motor',
    name: 'HF-rTMS M1 for Parkinson Motor Symptoms',
    condition_id: 'parkinsons',
    condition: "Parkinson's Disease",
    modality: 'TMS/rTMS',
    classification: 'off-label',
    evidence_grade: 'C',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      frequency_hz: 10,
      intensity_pct_mso: 110,
      pulses_per_session: 2000,
      train_duration_s: 4,
      inter_train_interval_s: 26,
      trains_per_session: 50,
      target: 'M1 bilateral / supplementary motor area',
      coil: 'Double Cone (110mm)',
      positioning: 'Neuronavigation or anatomical M1 (C3/C4)',
    },
    outcome_measures: ['UPDRS-III', 'PDQ-39', 'Timed Up and Go', 'CGI-S'],
    contraindications: [
      'Deep brain stimulator in situ',
      'Cochlear implant',
      'Active seizure disorder',
    ],
    governance_flags: ['off-label-use', 'neurologist-co-management-required'],
    notes: 'Investigational; evidence limited to small open-label studies. DBS is contraindicated with TMS. Motor benefit modest and transient (Shirota et al., 2013). Co-managed with neurology.',
    references: ['Shirota et al., 2013, Mov Disord', 'Brys et al., 2016, Brain Stimul'],
  },

  // ── tDCS PROTOCOLS ────────────────────────────────────────────────────────

  {
    id: 'tdcs-mdd-anodal-f3',
    name: 'tDCS Anodal F3 / Cathodal F4 for MDD',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'tDCS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 30,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      current_ma: 2,
      anode: 'F3 (left DLPFC)',
      cathode: 'F4 (right DLPFC)',
      electrode_size_cm2: 35,
      current_density_ma_cm2: 0.057,
      session_duration_min: 30,
      ramp_up_s: 30,
      ramp_down_s: 30,
      total_charge_C: 3.6,
    },
    outcome_measures: ['PHQ-9', 'MADRS', 'HAM-D17', 'CGI-S'],
    contraindications: [
      'Metallic cranial implants or electrodes at/near stimulation site',
      'Active skin lesions at electrode placement site',
      'Pregnancy (relative)',
    ],
    governance_flags: ['off-label-use'],
    notes: 'ELECT-TDCS and SELECT-TDCS trials established 2 mA 30-min as reference parameters. Effect size smaller than TMS; may be useful as adjunct. Can be combined with cognitive training (tDCS-timed tasks).',
    references: ['Brunoni et al., 2017, JAMA Psychiatry', 'Loo et al., 2018, Lancet Psychiatry'],
  },

  {
    id: 'tdcs-adhd',
    name: 'tDCS Anodal DLPFC for ADHD',
    condition_id: 'adhd',
    condition: 'ADHD',
    modality: 'tDCS',
    classification: 'off-label',
    evidence_grade: 'C',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      current_ma: 1.5,
      anode: 'F3 (left DLPFC)',
      cathode: 'right orbitofrontal cortex (Fp2)',
      electrode_size_cm2: 25,
      current_density_ma_cm2: 0.06,
      session_duration_min: 20,
      ramp_up_s: 30,
      ramp_down_s: 30,
    },
    outcome_measures: ['ADHD-RS-5', 'CGI-S', 'BRIEF-A', 'CPT-II (continuous performance)'],
    contraindications: [
      'Metallic cranial implants',
      'Skin lesions at electrode site',
    ],
    governance_flags: ['off-label-use', 'paediatric-ethics-review-if-under-18'],
    notes: 'Evidence base developing (Soff et al., 2017). 1.5–2 mA DLPFC anodal shows attention improvements in small RCTs. Paediatric use requires ethics review. Combination with working memory training investigated.',
    references: ['Soff et al., 2017, J Neural Transm', 'Allenby et al., 2018, Brain Stimul'],
  },

  {
    id: 'tdcs-pain-motor-cortex',
    name: 'tDCS Anodal Motor Cortex for Chronic Pain',
    condition_id: 'chronic-pain',
    condition: 'Chronic Pain',
    modality: 'tDCS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      current_ma: 2,
      anode: 'C3 or C4 (contralateral motor cortex)',
      cathode: 'contralateral supraorbital (SO)',
      electrode_size_cm2: 35,
      current_density_ma_cm2: 0.057,
      session_duration_min: 20,
      ramp_up_s: 30,
      ramp_down_s: 30,
    },
    outcome_measures: ['NRS-Pain', 'BPI', 'SF-36', 'CGI-S'],
    contraindications: [
      'Metallic cranial implants',
      'Active skin lesions at electrode site',
    ],
    governance_flags: ['off-label-use'],
    notes: 'M1 anodal tDCS mimics spinal cord stimulation mechanism via corticospinal modulation. Strongest evidence in fibromyalgia (Fregni et al.) and CRPS. Cathodal SO is reference electrode placement.',
    references: ['Fregni et al., 2006, Arthritis Rheum', 'Lefaucheur et al., 2017, Clin Neurophysiol'],
  },

  {
    id: 'tdcs-stroke-rehabilitation',
    name: 'tDCS Motor Cortex Stroke Rehabilitation Protocol',
    condition_id: 'stroke',
    condition: 'Stroke Motor Rehabilitation',
    modality: 'tDCS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 5,
    duration_weeks: 4,
    parameters: {
      current_ma: 2,
      anode: 'ipsilesional M1 (C3 or C4)',
      cathode: 'contralesional M1 (opposite)',
      electrode_size_cm2: 25,
      current_density_ma_cm2: 0.08,
      session_duration_min: 20,
      ramp_up_s: 30,
      ramp_down_s: 30,
      concurrent_therapy: 'Physical/occupational therapy during stimulation (dual-tDCS + motor training)',
    },
    outcome_measures: ['UPDRS motor', 'Fugl-Meyer UE', 'NHSS', 'Wolf Motor Function Test'],
    contraindications: [
      'Acute stroke < 4 weeks',
      'Metallic intracranial implants',
      'Unstable cardiac status',
    ],
    governance_flags: ['off-label-use', 'physiotherapy-concurrent-required', 'neurologist-clearance-required'],
    notes: 'Dual-site montage: facilitates ipsilesional and inhibits contralesional M1 simultaneously. Concurrent motor therapy during stimulation maximises plasticity window. Timing post-stroke optimal at subacute phase (1–6 months).',
    references: ['Nitsche et al., 2008, Brain Stimul', 'Kang et al., 2016, Cochrane'],
  },

  {
    id: 'tdcs-aphasia',
    name: 'tDCS Broca Area for Post-Stroke Aphasia',
    condition_id: 'aphasia',
    condition: 'Post-Stroke Aphasia',
    modality: 'tDCS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 15,
    sessions_per_week: 5,
    duration_weeks: 3,
    parameters: {
      current_ma: 1,
      anode: 'F5 (left Broca area / IFG)',
      cathode: 'right supraorbital (Fp2)',
      electrode_size_cm2: 25,
      current_density_ma_cm2: 0.04,
      session_duration_min: 20,
      ramp_up_s: 30,
      ramp_down_s: 30,
      concurrent_therapy: 'Language/speech therapy during stimulation',
    },
    outcome_measures: ['Western Aphasia Battery', 'Boston Naming Test', 'Naming accuracy', 'CGI-S'],
    contraindications: [
      'Metallic cranial implants',
      'Large cortical lesion overlapping stimulation site (reassess target)',
    ],
    governance_flags: ['off-label-use', 'speech-language-pathology-required'],
    notes: 'Concurrent SLP during tDCS is essential. Left Broca anodal facilitates language production. Some evidence for right IFG cathodal to reduce maladaptive contralesional compensation.',
    references: ['Monti et al., 2013, Restor Neurol Neurosci', 'Elsner et al., 2019, Cochrane'],
  },

  // ── NEUROFEEDBACK PROTOCOLS ───────────────────────────────────────────────

  {
    id: 'nfb-alpha-theta-anxiety',
    name: 'Alpha/Theta Neurofeedback for Anxiety',
    condition_id: 'anxiety',
    condition: 'Anxiety Disorders',
    modality: 'EEG/Neurofeedback',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 30,
    sessions_per_week: 2,
    duration_weeks: 15,
    parameters: {
      target_bands: ['alpha (8–12 Hz)', 'theta (4–8 Hz)'],
      training_direction: 'Upward reinforce alpha and theta amplitude',
      electrode_placement: 'Oz, Pz (posterior midline)',
      reference: 'linked mastoids (A1+A2)',
      session_duration_min: 30,
      protocol: 'Alpha/theta ratio training — threshold-based audio/visual feedback',
      threshold: 'Individual adaptive threshold, 70th percentile rolling',
    },
    outcome_measures: ['GAD-7', 'STAI', 'HAM-A', 'HRV'],
    contraindications: [
      'Active psychosis',
      'Severe dissociative disorder',
    ],
    governance_flags: ['off-label-use'],
    notes: 'Peniston-Kulkosky protocol origin (alcohol relapse prevention); extended to anxiety and PTSD. Deep relaxation state induced. Suitable for phobia, PTSD, and GAD. Requires trained EEG technician.',
    references: ['Peniston & Kulkosky, 1989, Alc Treat Q', 'Hammond, 2005, J Neurother'],
  },

  {
    id: 'nfb-smr-adhd',
    name: 'SMR / Theta Suppression Neurofeedback for ADHD',
    condition_id: 'adhd',
    condition: 'ADHD',
    modality: 'EEG/Neurofeedback',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 40,
    sessions_per_week: 2,
    duration_weeks: 20,
    parameters: {
      target_bands: ['SMR (12–15 Hz)', 'theta (4–8 Hz)'],
      training_direction: 'Upward reinforce SMR; downward suppress theta',
      electrode_placement: 'Cz, C3, C4',
      reference: 'linked mastoids or Fz',
      session_duration_min: 30,
      protocol: 'Standard ADHD protocol: enhance SMR/beta, suppress theta',
      theta_beta_ratio: 'Target theta/beta ratio reduction ≥1 SD',
    },
    outcome_measures: ['ADHD-RS-5', 'Conners-3', 'BRIEF-A', 'CPT-II'],
    contraindications: [],
    governance_flags: ['off-label-use'],
    notes: '40-session minimum for durable benefit. Arns et al. (2009) meta-analysis: large ES for inattention and impulsivity. Slower results than medication; useful when medication declined/contraindicated. Parent home-based NFB systems emerging.',
    references: ['Arns et al., 2009, Clin EEG Neurosci', 'Strehl et al., 2006, Prog Brain Res'],
  },

  {
    id: 'nfb-gamma-cognitive',
    name: 'Gamma Band (40 Hz) Neurofeedback for Cognitive Enhancement',
    condition_id: 'mci',
    condition: 'Mild Cognitive Impairment',
    modality: 'EEG/Neurofeedback',
    classification: 'investigational',
    evidence_grade: 'C',
    fda_cleared: false,
    sessions: 20,
    sessions_per_week: 2,
    duration_weeks: 10,
    parameters: {
      target_bands: ['gamma (40 Hz)'],
      training_direction: 'Upward reinforce 40 Hz gamma at frontal and occipital sites',
      electrode_placement: 'Fz, Fp1, Fp2, Oz',
      reference: 'linked mastoids',
      session_duration_min: 20,
      protocol: 'SSVEP + EEG neurofeedback hybrid; 40 Hz visual flicker entrainment during training',
    },
    outcome_measures: ['MoCA', 'RAVLT', 'DSST', 'CGI-S'],
    contraindications: [
      'Photosensitive epilepsy (SSVEP component)',
      'Active psychosis',
    ],
    governance_flags: ['off-label-use', 'investigational', 'photosensitivity-screen-required'],
    notes: 'Emerging area following Tsai lab GENUS research (40 Hz flickering light reduces amyloid in mice). Human neurofeedback for gamma remains investigational. Photosensitivity screening mandatory before SSVEP component.',
    references: ['Iaccarino et al., 2016, Nature', 'Adaikkan & Tsai, 2020, Trends Neurosci'],
  },

  {
    id: 'nfb-theta-alpha-depression',
    name: 'Theta/Alpha Neurofeedback for Depression',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'EEG/Neurofeedback',
    classification: 'off-label',
    evidence_grade: 'C',
    fda_cleared: false,
    sessions: 30,
    sessions_per_week: 2,
    duration_weeks: 15,
    parameters: {
      target_bands: ['alpha (8–12 Hz)', 'theta (5–7 Hz)'],
      training_direction: 'Normalise frontal alpha asymmetry; enhance posterior alpha; suppress frontal theta',
      electrode_placement: 'F3, F4, Fz, Pz',
      reference: 'Cz or linked mastoids',
      session_duration_min: 30,
      protocol: 'Frontal alpha asymmetry protocol; right > left alpha targeted',
    },
    outcome_measures: ['PHQ-9', 'MADRS', 'QIDS-SR16', 'CGI-S'],
    contraindications: [
      'Active psychosis',
      'Bipolar I (mania risk)',
    ],
    governance_flags: ['off-label-use'],
    notes: 'Left hypoactivation in depression reflected as increased left frontal alpha. Frontal alpha asymmetry is a biomarker and training target. Adjunct to pharmacotherapy. Evidence moderate; RCTs ongoing.',
    references: ['Allen et al., 2004, Psychophysiology', 'Choi et al., 2011, Clin Neurophysiol'],
  },

  // ── taVNS PROTOCOLS ───────────────────────────────────────────────────────

  {
    id: 'tavns-depression-standard',
    name: 'taVNS Standard Depression Protocol',
    condition_id: 'mdd',
    condition: 'Major Depressive Disorder',
    modality: 'taVNS',
    classification: 'off-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: 84,
    sessions_per_week: 7,
    duration_weeks: 12,
    parameters: {
      frequency_hz: 25,
      pulse_width_us: 250,
      current_ma: 0.5,
      on_time_s: 30,
      off_time_s: 30,
      sessions_per_day: 2,
      session_duration_min: 30,
      target: 'Left cymba conchae (auricular branch of vagus nerve)',
      device: 'Nemos (Cerbomed) or equivalent taVNS device',
    },
    outcome_measures: ['PHQ-9', 'MADRS', 'HAM-D17', 'CGI-S'],
    contraindications: [
      'Implanted cardiac devices (relative)',
      'Unilateral vagus nerve injury',
      'Active skin lesion in ear',
    ],
    governance_flags: ['off-label-use'],
    notes: 'Cymba conchae target (auricular branch of vagus). 25 Hz, 250 µs PW is reference parameter set (Kraus et al. 2013). Twice-daily self-administered sessions. CE-marked devices available. Non-inferior to implanted VNS in small comparative trials.',
    references: ['Kraus et al., 2013, J Affect Disord', 'Rong et al., 2016, J Affect Disord'],
  },

  {
    id: 'tavns-epilepsy',
    name: 'taVNS Adjunct for Drug-Resistant Epilepsy',
    condition_id: 'epilepsy',
    condition: 'Drug-Resistant Epilepsy',
    modality: 'taVNS',
    classification: 'on-label',
    evidence_grade: 'B',
    fda_cleared: false,
    sessions: null,
    sessions_per_week: 7,
    duration_weeks: 52,
    parameters: {
      frequency_hz: 25,
      pulse_width_us: 250,
      current_ma: 1.0,
      duty_cycle: '30s ON / 30s OFF (continuous cycling)',
      sessions_per_day: 3,
      session_duration_min: 60,
      target: 'Left cymba conchae',
    },
    outcome_measures: ['Seizure frequency diary', 'Seizure severity scale', 'QOLS', 'CGI-S'],
    contraindications: [
      'Implanted vagus nerve stimulator (avoid duplication)',
      'Bilateral vagal neuropathy',
    ],
    governance_flags: ['concurrent-neurology-required', 'medication-review-required'],
    notes: 'CE-marked indication (Nemos). Adjunct to antiepileptic drugs; add-on after ≥2 AED failures. Continuous cycling protocol mirrors implanted VNS parameters. Neurology co-management mandatory.',
    references: ['Stefan et al., 2012, Seizure', 'Bauer et al., 2016, Lancet Neurol'],
  },

  {
    id: 'tavns-ptsd',
    name: 'taVNS for PTSD with Autonomic Dysregulation',
    condition_id: 'ptsd',
    condition: 'Post-Traumatic Stress Disorder',
    modality: 'taVNS',
    classification: 'off-label',
    evidence_grade: 'C',
    fda_cleared: false,
    sessions: 60,
    sessions_per_week: 5,
    duration_weeks: 12,
    parameters: {
      frequency_hz: 25,
      pulse_width_us: 200,
      current_ma: 0.5,
      on_time_s: 30,
      off_time_s: 30,
      sessions_per_day: 2,
      session_duration_min: 30,
      target: 'Left cymba conchae',
    },
    outcome_measures: ['PCL-5', 'IES-R', 'HRV (RMSSD)', 'CGI-S'],
    contraindications: [
      'Active cardiac arrhythmia',
      'Implanted cardiac device',
    ],
    governance_flags: ['off-label-use', 'trauma-informed-care-required'],
    notes: 'PTSD is characterised by HRV reduction; vagal stimulation may restore autonomic balance. HRV monitoring is recommended outcome. Trauma-informed care framework essential. Limited RCT evidence.',
    references: ['Kong et al., 2021, Eur Arch Psychiatry Clin Neurosci', 'Huffman et al., 2020, Brain Stimul'],
  },

  // ── CES PROTOCOLS ────────────────────────────────────────────────────────

  {
    id: 'ces-insomnia',
    name: 'CES Standard Protocol for Insomnia',
    condition_id: 'insomnia',
    condition: 'Insomnia Disorder',
    modality: 'CES',
    classification: 'on-label',
    evidence_grade: 'B',
    fda_cleared: true,
    sessions: 42,
    sessions_per_week: 7,
    duration_weeks: 6,
    parameters: {
      frequency_hz: 0.5,
      current_ma: 0.1,
      waveform: 'modified square wave',
      electrode_placement: 'Bilateral ear clips (earlobe or tragus)',
      session_duration_min: 60,
      timing: 'Evening, 60 minutes before intended sleep onset',
      device_reference: 'Alpha-Stim M or equivalent FDA-cleared CES device',
    },
    outcome_measures: ['ISI', 'PSQI', 'ESS', 'Sleep diary'],
    contraindications: [
      'Implanted electronic devices in head/neck region (relative)',
      'Active open wound at electrode site',
    ],
    governance_flags: [],
    notes: 'FDA-cleared indication. 0.5 Hz Alpha-Stim waveform is best-evidenced. Meta-analysis (Shekelle et al., 2018) showed significant ISI reduction vs. sham. Evening session timing critical.',
    references: ['Shekelle et al., 2018, Ann Intern Med', 'Lande & Gragnani, 2013, J Am Osteopath Assoc'],
  },

  {
    id: 'ces-anxiety',
    name: 'CES Protocol for Anxiety',
    condition_id: 'anxiety',
    condition: 'Anxiety Disorders',
    modality: 'CES',
    classification: 'on-label',
    evidence_grade: 'B',
    fda_cleared: true,
    sessions: 21,
    sessions_per_week: 7,
    duration_weeks: 3,
    parameters: {
      frequency_hz: 0.5,
      current_ma: 0.1,
      waveform: 'modified square wave',
      electrode_placement: 'Bilateral ear clips',
      session_duration_min: 60,
      timing: 'Morning or mid-day session preferred',
      device_reference: 'Alpha-Stim M or equivalent',
    },
    outcome_measures: ['GAD-7', 'HAM-A', 'STAI', 'CGI-S'],
    contraindications: [
      'Active psychosis',
      'Implanted cranial electronic device',
    ],
    governance_flags: [],
    notes: 'FDA-cleared for anxiety. Kirsch meta-analysis (2002) showing large ES in anxiety. Well-tolerated; suitable as adjunct or monotherapy for mild-moderate GAD. Response typically begins within 1–2 weeks.',
    references: ['Kirsch, 2002, Am J Pain Manag', 'Bystritsky et al., 2008, J Clin Psychiatry'],
  },

  {
    id: 'ces-pain',
    name: 'CES Protocol for Chronic Pain',
    condition_id: 'chronic-pain',
    condition: 'Chronic Pain',
    modality: 'CES',
    classification: 'on-label',
    evidence_grade: 'B',
    fda_cleared: true,
    sessions: 30,
    sessions_per_week: 5,
    duration_weeks: 6,
    parameters: {
      frequency_hz: 0.5,
      current_ma: 0.1,
      waveform: 'modified square wave',
      electrode_placement: 'Bilateral ear clips',
      session_duration_min: 60,
      timing: 'As needed up to twice daily; maintain ≥4 hours between sessions',
      smart_probe: 'Alpha-Stim Smart Probe for local pain application (optional adjunct)',
    },
    outcome_measures: ['NRS-Pain', 'BPI', 'CPGS', 'SF-36'],
    contraindications: [
      'Implanted electronic device',
      'Active skin wound at electrode site',
    ],
    governance_flags: [],
    notes: 'FDA-cleared for pain. TENS-mode (Smart Probe) can be used concurrently for local pain. CES works centrally; TENS works peripherally. Combination approach endorsed by Electromedical Products International clinical guidelines.',
    references: ['Smith, 2006, Anesth Prog', 'Capel et al., 2003, Am J Electromedicine'],
  },

];

// ── Derived lookups ────────────────────────────────────────────────────────

export const PROTOCOL_BY_ID = Object.fromEntries(PROTOCOL_TEMPLATES.map(p => [p.id, p]));

export const PROTOCOLS_BY_CONDITION = {};
PROTOCOL_TEMPLATES.forEach(p => {
  if (!PROTOCOLS_BY_CONDITION[p.condition_id]) PROTOCOLS_BY_CONDITION[p.condition_id] = [];
  PROTOCOLS_BY_CONDITION[p.condition_id].push(p);
});

export default PROTOCOL_TEMPLATES;
