/**
 * reports.js
 * Clinical report templates for neuromodulation practice.
 * DeepSynaps Protocol Studio — Registry
 */

export const REPORT_TEMPLATES = [
  {
    id: 'report-initial-assessment',
    name: 'Initial Clinical Assessment Report',
    category: 'Assessment',
    audience: 'referring-physician',
    trigger: 'initial-assessment',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'presenting-complaint', title: 'Presenting Complaint', required: true },
      { id: 'psychiatric-history', title: 'Psychiatric & Medical History', required: true },
      { id: 'current-medications', title: 'Current Medications', required: true },
      { id: 'contraindications-screening', title: 'Contraindications Screening', required: true },
      { id: 'assessment-scores', title: 'Baseline Assessment Scores', required: true },
      { id: 'mental-state-exam', title: 'Mental State Examination', required: true },
      { id: 'risk-assessment', title: 'Risk Assessment (Suicide/Self-Harm)', required: true },
      { id: 'treatment-recommendation', title: 'Treatment Recommendation', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'current-medications', 'assessment-scores'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 20,
    tags: ['standard', 'required', 'baseline'],
  },
  {
    id: 'report-treatment-plan',
    name: 'Neuromodulation Treatment Plan',
    category: 'Assessment',
    audience: 'internal',
    trigger: 'post-assessment',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'diagnosis', title: 'Primary & Secondary Diagnoses', required: true },
      { id: 'treatment-rationale', title: 'Treatment Rationale', required: true },
      { id: 'modality-selection', title: 'Selected Modality & Protocol', required: true },
      { id: 'parameters', title: 'Stimulation Parameters', required: true },
      { id: 'session-schedule', title: 'Session Schedule', required: true },
      { id: 'goals', title: 'Treatment Goals & Expected Outcomes', required: true },
      { id: 'outcome-measures', title: 'Outcome Measures to Track', required: true },
      { id: 'adjunct-interventions', title: 'Adjunct Interventions', required: false },
      { id: 'review-milestones', title: 'Review Milestones', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'diagnosis', 'parameters', 'session-schedule'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 20,
    tags: ['standard', 'required', 'treatment-planning'],
  },
  {
    id: 'report-session-progress',
    name: 'Session Progress Note',
    category: 'Progress',
    audience: 'internal',
    trigger: 'per-session',
    sections: [
      { id: 'session-info', title: 'Session Date & Number', required: true },
      { id: 'patient-reported-mood', title: 'Patient-Reported Mood & Symptoms', required: true },
      { id: 'session-parameters', title: 'Stimulation Parameters Delivered', required: true },
      { id: 'tolerance', title: 'Tolerance & Comfort', required: true },
      { id: 'adverse-events', title: 'Adverse Events (if any)', required: false },
      { id: 'brief-assessment', title: 'Brief Symptom Assessment', required: false },
      { id: 'clinician-observations', title: 'Clinician Observations', required: true },
      { id: 'plan-next-session', title: 'Plan for Next Session', required: true },
      { id: 'clinician-initials', title: 'Clinician Initials', required: true },
    ],
    auto_populate: ['session-info', 'session-parameters', 'patient-reported-mood'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 5,
    tags: ['standard', 'per-session', 'progress'],
  },
  {
    id: 'report-midpoint-review',
    name: 'Mid-Treatment Review Report',
    category: 'Progress',
    audience: 'referring-physician',
    trigger: 'session-10-to-15',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'treatment-summary-to-date', title: 'Treatment Summary to Date', required: true },
      { id: 'symptom-trajectory', title: 'Symptom Trajectory', required: true },
      { id: 'assessment-scores-current', title: 'Current Assessment Scores vs Baseline', required: true },
      { id: 'response-classification', title: 'Response Classification (Response/Partial/Non-response)', required: true },
      { id: 'adverse-events-summary', title: 'Adverse Events Summary', required: false },
      { id: 'protocol-modifications', title: 'Protocol Modifications Made', required: false },
      { id: 'plan-remainder', title: 'Plan for Remaining Sessions', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'treatment-summary-to-date', 'assessment-scores-current', 'adverse-events-summary'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 15,
    tags: ['standard', 'mid-treatment', 'review'],
  },
  {
    id: 'report-end-of-treatment',
    name: 'End of Treatment Summary',
    category: 'Discharge',
    audience: 'referring-physician',
    trigger: 'final-session',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'treatment-overview', title: 'Treatment Overview', required: true },
      { id: 'sessions-delivered', title: 'Sessions Delivered & Attendance', required: true },
      { id: 'final-parameters', title: 'Final Stimulation Parameters', required: true },
      { id: 'outcome-scores', title: 'Outcome Assessment Scores (Baseline vs Final)', required: true },
      { id: 'clinical-response', title: 'Clinical Response Classification', required: true },
      { id: 'adverse-events', title: 'Adverse Events Throughout Treatment', required: false },
      { id: 'recommendations', title: 'Recommendations & Follow-Up Plan', required: true },
      { id: 'relapse-prevention', title: 'Relapse Prevention Plan', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'sessions-delivered', 'outcome-scores', 'adverse-events'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 25,
    tags: ['standard', 'required', 'discharge'],
  },
  {
    id: 'report-outcome-summary',
    name: 'Outcomes and Response Summary Report',
    category: 'Assessment',
    audience: 'internal',
    trigger: 'end-of-treatment',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'diagnosis', title: 'Diagnosis', required: true },
      { id: 'treatment-protocol', title: 'Treatment Protocol', required: true },
      { id: 'baseline-scores', title: 'Baseline Assessment Scores', required: true },
      { id: 'post-scores', title: 'Post-Treatment Assessment Scores', required: true },
      { id: 'percent-change', title: 'Percent Change & Clinical Significance', required: true },
      { id: 'response-definition', title: 'Response Definition Applied', required: true },
      { id: 'charts', title: 'Score Trajectory Charts', required: false },
      { id: 'conclusions', title: 'Clinical Conclusions', required: true },
    ],
    auto_populate: ['patient-info', 'baseline-scores', 'post-scores', 'percent-change', 'charts'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 10,
    tags: ['outcomes', 'data', 'review'],
  },
  {
    id: 'report-adverse-event',
    name: 'Adverse Event Report',
    category: 'Adverse Event',
    audience: 'internal',
    trigger: 'adverse-event-occurrence',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'event-description', title: 'Adverse Event Description', required: true },
      { id: 'onset-time', title: 'Onset Time & Duration', required: true },
      { id: 'severity', title: 'Severity Classification (Mild/Moderate/Severe)', required: true },
      { id: 'treatment-at-time', title: 'Treatment Parameters at Time of Event', required: true },
      { id: 'immediate-management', title: 'Immediate Management Actions', required: true },
      { id: 'outcome', title: 'Outcome of Event', required: true },
      { id: 'protocol-modification', title: 'Protocol Modification Following Event', required: false },
      { id: 'notification', title: 'Notification to Referring Clinician / Regulatory Body', required: false },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'treatment-at-time'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 20,
    tags: ['safety', 'mandatory', 'adverse-event'],
  },
  {
    id: 'report-discharge-summary',
    name: 'Discharge Summary',
    category: 'Discharge',
    audience: 'referring-physician',
    trigger: 'discharge',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'admission-summary', title: 'Reason for Referral / Admission', required: true },
      { id: 'treatment-received', title: 'Treatment Received', required: true },
      { id: 'clinical-progress', title: 'Clinical Progress', required: true },
      { id: 'current-mental-state', title: 'Current Mental State at Discharge', required: true },
      { id: 'discharge-scores', title: 'Discharge Assessment Scores', required: true },
      { id: 'medications-on-discharge', title: 'Medications on Discharge', required: true },
      { id: 'follow-up-plan', title: 'Follow-Up Plan', required: true },
      { id: 'safety-plan', title: 'Safety Plan (if applicable)', required: false },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'treatment-received', 'discharge-scores', 'medications-on-discharge'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 20,
    tags: ['standard', 'required', 'discharge'],
  },
  {
    id: 'report-gp-letter',
    name: 'Letter to GP / Referring Physician',
    category: 'Referral',
    audience: 'referring-physician',
    trigger: 'as-needed',
    sections: [
      { id: 'header', title: 'Letterhead & Date', required: true },
      { id: 'patient-info', title: 'Patient Details', required: true },
      { id: 'reason-for-contact', title: 'Reason for Contact', required: true },
      { id: 'clinical-update', title: 'Clinical Update', required: true },
      { id: 'assessment-findings', title: 'Assessment Findings', required: false },
      { id: 'treatment-details', title: 'Treatment Details & Response', required: false },
      { id: 'current-medications', title: 'Current Medications', required: true },
      { id: 'recommendations', title: 'Recommendations', required: true },
      { id: 'follow-up', title: 'Follow-Up Arrangements', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'current-medications', 'treatment-details'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 15,
    tags: ['communication', 'clinical-letter', 'standard'],
  },
  {
    id: 'report-insurer-justification',
    name: 'Insurance Pre-Authorization Justification Letter',
    category: 'Administrative',
    audience: 'insurer',
    trigger: 'pre-treatment',
    sections: [
      { id: 'patient-info', title: 'Patient & Insurer Details', required: true },
      { id: 'diagnosis', title: 'Diagnosis & ICD Codes', required: true },
      { id: 'proposed-treatment', title: 'Proposed Treatment', required: true },
      { id: 'prior-treatments', title: 'Prior Treatments Tried & Failed', required: true },
      { id: 'clinical-necessity', title: 'Medical Necessity Justification', required: true },
      { id: 'evidence-summary', title: 'Evidence Base Summary', required: true },
      { id: 'expected-outcomes', title: 'Expected Outcomes', required: true },
      { id: 'estimated-sessions', title: 'Estimated Number of Sessions & Cost', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature & Credentials', required: true },
    ],
    auto_populate: ['patient-info', 'diagnosis', 'prior-treatments'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 25,
    tags: ['insurance', 'administrative', 'pre-auth'],
  },
  {
    id: 'report-research-data',
    name: 'Research Data Export Summary',
    category: 'Research',
    audience: 'research',
    trigger: 'research-milestone',
    sections: [
      { id: 'study-info', title: 'Study Information', required: true },
      { id: 'participant-summary', title: 'Participant Summary (de-identified)', required: true },
      { id: 'data-collected', title: 'Data Collected', required: true },
      { id: 'assessment-results', title: 'Assessment Results Summary', required: true },
      { id: 'adverse-events-summary', title: 'Adverse Events Summary', required: false },
      { id: 'protocol-deviations', title: 'Protocol Deviations', required: false },
      { id: 'data-quality', title: 'Data Quality Notes', required: true },
      { id: 'investigator-signature', title: 'Principal Investigator Signature', required: true },
    ],
    auto_populate: ['participant-summary', 'assessment-results', 'adverse-events-summary'],
    output_formats: ['PDF', 'DOCX', 'CSV'],
    estimated_completion_min: 30,
    tags: ['research', 'data-export', 'ethics'],
  },
  {
    id: 'report-consent-audit',
    name: 'Consent Status Audit Report',
    category: 'Administrative',
    audience: 'internal',
    trigger: 'scheduled',
    sections: [
      { id: 'audit-period', title: 'Audit Period', required: true },
      { id: 'patient-list', title: 'Patient List (de-identified or internal)', required: true },
      { id: 'consent-status', title: 'Consent Status per Patient', required: true },
      { id: 'expiring-consents', title: 'Expiring Consents', required: true },
      { id: 'missing-consents', title: 'Missing or Incomplete Consents', required: true },
      { id: 'actions-required', title: 'Actions Required', required: true },
      { id: 'auditor-signature', title: 'Auditor Signature', required: true },
    ],
    auto_populate: ['patient-list', 'consent-status', 'expiring-consents', 'missing-consents'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 10,
    tags: ['compliance', 'audit', 'administrative'],
  },
  {
    id: 'report-wearable-summary',
    name: 'Wearable Data Summary Report',
    category: 'Progress',
    audience: 'internal',
    trigger: 'scheduled',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'device-info', title: 'Wearable Device & Metrics', required: true },
      { id: 'date-range', title: 'Data Collection Period', required: true },
      { id: 'sleep-data', title: 'Sleep Metrics Summary', required: false },
      { id: 'hrv-data', title: 'HRV Summary', required: false },
      { id: 'activity-data', title: 'Activity & Step Count Summary', required: false },
      { id: 'mood-logs', title: 'Mood Diary / EMA Summary', required: false },
      { id: 'treatment-correlation', title: 'Correlation with Treatment Timeline', required: true },
      { id: 'clinical-observations', title: 'Clinical Observations', required: true },
    ],
    auto_populate: ['patient-info', 'sleep-data', 'hrv-data', 'activity-data', 'mood-logs'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 10,
    tags: ['wearable', 'digital-health', 'progress'],
  },
  {
    id: 'report-assessment-history',
    name: 'Assessment History Report',
    category: 'Assessment',
    audience: 'internal',
    trigger: 'as-needed',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'assessment-list', title: 'All Assessments Completed (Chronological)', required: true },
      { id: 'score-trends', title: 'Score Trends & Graphs', required: true },
      { id: 'clinician-notes', title: 'Clinician Notes on Trends', required: false },
    ],
    auto_populate: ['patient-info', 'assessment-list', 'score-trends'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 5,
    tags: ['assessment', 'history', 'data'],
  },
  {
    id: 'report-medication-interaction',
    name: 'Medication–Protocol Interaction Report',
    category: 'Assessment',
    audience: 'internal',
    trigger: 'pre-treatment',
    sections: [
      { id: 'patient-info', title: 'Patient Information', required: true },
      { id: 'current-medications', title: 'Current Medications List', required: true },
      { id: 'proposed-protocol', title: 'Proposed Neuromodulation Protocol', required: true },
      { id: 'interaction-analysis', title: 'Known Medication Interactions with Stimulation', required: true },
      { id: 'seizure-threshold-meds', title: 'Medications Affecting Seizure Threshold', required: true },
      { id: 'recommendations', title: 'Recommendations & Precautions', required: true },
      { id: 'clinician-signature', title: 'Clinician Signature', required: true },
    ],
    auto_populate: ['patient-info', 'current-medications', 'proposed-protocol'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 15,
    tags: ['safety', 'medication', 'pre-treatment'],
  },
  {
    id: 'report-governance-review',
    name: 'Governance and Compliance Review Report',
    category: 'Administrative',
    audience: 'internal',
    trigger: 'scheduled',
    sections: [
      { id: 'review-period', title: 'Review Period', required: true },
      { id: 'incidents-summary', title: 'Incidents & Adverse Events Summary', required: true },
      { id: 'consent-compliance', title: 'Consent Compliance Status', required: true },
      { id: 'protocol-adherence', title: 'Protocol Adherence Audit', required: true },
      { id: 'training-records', title: 'Staff Training & Credentialing Status', required: true },
      { id: 'equipment-maintenance', title: 'Equipment Maintenance Records', required: true },
      { id: 'complaints', title: 'Complaints & Feedback', required: false },
      { id: 'recommendations', title: 'Governance Recommendations', required: true },
      { id: 'approver-signature', title: 'Clinical Director Signature', required: true },
    ],
    auto_populate: ['incidents-summary', 'consent-compliance'],
    output_formats: ['PDF', 'DOCX'],
    estimated_completion_min: 45,
    tags: ['governance', 'compliance', 'administrative'],
  },
];

export const REPORT_BY_ID = Object.fromEntries(REPORT_TEMPLATES.map(r => [r.id, r]));
export default REPORT_TEMPLATES;
