/**
 * virtual-care.js
 * Structured virtual care session templates and video consultation guides.
 * DeepSynaps Protocol Studio — Registry
 */

export const VIRTUAL_CARE_TEMPLATES = [
  {
    id: 'vc-initial-consult',
    name: 'Initial Consultation',
    category: 'Assessment',
    session_type: 'video',
    duration_min: 60,
    trigger: 'pre-treatment',
    frequency: 'once',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Welcome & tech check', duration_min: 5 },
      { item: 'Identity verification', duration_min: 3 },
      { item: 'Chief complaint & presenting history', duration_min: 20 },
      { item: 'Psychiatric & medical history', duration_min: 10 },
      { item: 'Risk assessment (suicide, self-harm, harm to others)', duration_min: 8 },
      { item: 'Assessment scores review (pre-completed)', duration_min: 7 },
      { item: 'Treatment recommendation & explanation', duration_min: 10 },
      { item: 'Consent overview & questions', duration_min: 5 },
      { item: 'Next steps & scheduling', duration_min: 2 },
    ],
    pre_session_tasks: [
      'Complete PHQ-9, GAD-7, CGI (sent via secure link)',
      'Review and sign consent forms',
      'Complete medical history questionnaire',
      'Tech check email sent (camera, microphone, private space)',
      'Confirm identity documents available',
    ],
    post_session_tasks: [
      'Send session summary letter to patient',
      'Send referral letter to GP/referring physician',
      'Update care plan in system',
      'Schedule treatment planning consultation if proceeding',
      'Document risk assessment outcome',
    ],
    assessments_to_complete: ['PHQ-9', 'GAD-7', 'CGI', 'QIDS-SR', 'Columbia Suicide Severity Rating Scale'],
    screening_questions: [
      'What brings you to the clinic today, and how long have these difficulties been present?',
      'Have you had any previous treatment for this condition, including medications and therapy?',
      'Do you have any thoughts of harming yourself or others?',
      'Are you currently taking any medications, including supplements?',
      'Do you have any implanted metal or electronic devices, or a history of seizures?',
    ],
    documentation_template: 'report-initial-assessment',
    platform_notes:
      'Ensure patient is in a private location before beginning clinical discussion. Verify identity using photo ID at session start. Record session only with explicit consent. Have emergency contact number on hand.',
    tags: ['standard', 'required', 'assessment'],
  },
  {
    id: 'vc-pre-treatment-briefing',
    name: 'Pre-Treatment Briefing',
    category: 'Psychoeducation',
    session_type: 'video',
    duration_min: 30,
    trigger: 'pre-treatment',
    frequency: 'once',
    clinician_role: 'nurse',
    agenda: [
      { item: 'Welcome & introductions', duration_min: 3 },
      { item: 'Review treatment plan & protocol', duration_min: 8 },
      { item: 'What to expect in the first session (sensations, logistics)', duration_min: 7 },
      { item: 'Practical preparation (hair, metal screening, clothing)', duration_min: 4 },
      { item: 'Review patient information handbook', duration_min: 4 },
      { item: 'Answer questions', duration_min: 4 },
    ],
    pre_session_tasks: [
      'Send patient information handbook (PDF)',
      'Send treatment plan summary',
      'Confirm all consents signed',
    ],
    post_session_tasks: [
      'Confirm first in-clinic appointment',
      'Send "What to bring on Day 1" checklist',
      'Note any patient concerns in care record',
    ],
    assessments_to_complete: [],
    screening_questions: [
      'Have you had a chance to read the patient information handbook?',
      'Do you have any questions about the procedure itself?',
      'Are there any practical concerns about getting to the clinic?',
      'Do you have any new medical changes since your initial consultation?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Can be conducted by clinical nurse or technician. Ensure treatment plan has been reviewed and approved by prescribing clinician before this session.',
    tags: ['standard', 'education', 'pre-treatment'],
  },
  {
    id: 'vc-weekly-checkin',
    name: 'Weekly Check-In',
    category: 'Follow-Up',
    session_type: 'video',
    duration_min: 15,
    trigger: 'mid-treatment',
    frequency: 'weekly',
    clinician_role: 'nurse',
    agenda: [
      { item: 'Mood & symptom check', duration_min: 5 },
      { item: 'Side effects & tolerance review', duration_min: 4 },
      { item: 'Home program adherence', duration_min: 3 },
      { item: 'Brief risk screen', duration_min: 2 },
      { item: 'Plan for upcoming week', duration_min: 1 },
    ],
    pre_session_tasks: [
      'Complete PHQ-9 or PHQ-2 (brief) prior to call',
      'Review session notes from past week',
    ],
    post_session_tasks: [
      'Update session progress note',
      'Flag concerns to treating clinician if indicated',
      'Adjust home program if needed',
    ],
    assessments_to_complete: ['PHQ-2', 'Side effects checklist'],
    screening_questions: [
      'How have you been feeling since our last contact?',
      'Have you noticed any changes — positive or negative — in your mood or functioning?',
      'Any side effects or discomfort from sessions this week?',
      'Any safety concerns or thoughts of self-harm?',
      'How has the home program been going?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Can be phone or video. Flag any safety concerns to treating clinician immediately. If PHQ-2 score ≥3, complete full PHQ-9.',
    tags: ['routine', 'monitoring', 'brief'],
  },
  {
    id: 'vc-progress-review',
    name: 'Mid-Treatment Progress Review',
    category: 'Progress Review',
    session_type: 'video',
    duration_min: 30,
    trigger: 'mid-treatment',
    frequency: 'biweekly',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Symptom review since baseline', duration_min: 8 },
      { item: 'Assessment scores comparison (current vs baseline)', duration_min: 7 },
      { item: 'Treatment tolerance & side effects', duration_min: 5 },
      { item: 'Protocol adjustment discussion if needed', duration_min: 5 },
      { item: 'Goals review & patient feedback', duration_min: 5 },
    ],
    pre_session_tasks: [
      'Complete PHQ-9, CGI prior to session',
      'Prepare sessions-to-date summary',
      'Pull baseline vs current scores for comparison',
    ],
    post_session_tasks: [
      'Complete mid-treatment review report',
      'Update treatment plan if protocol modified',
      'Letter to GP if significant clinical change',
    ],
    assessments_to_complete: ['PHQ-9', 'GAD-7', 'CGI-I', 'CGI-S'],
    screening_questions: [
      'Looking back over the past 2 weeks, how would you describe your mood compared to when we started?',
      'Are you noticing any functional improvements (work, sleep, relationships)?',
      'Any concerns about continuing treatment?',
      'Any changes to medications or other health issues?',
    ],
    documentation_template: 'report-midpoint-review',
    platform_notes:
      'Should be conducted by prescribing clinician. Compare assessment scores formally. Document response classification (Response/Partial/Non-response).',
    tags: ['standard', 'review', 'mid-treatment'],
  },
  {
    id: 'vc-adverse-event-review',
    name: 'Adverse Event Review',
    category: 'Follow-Up',
    session_type: 'video',
    duration_min: 20,
    trigger: 'as-needed',
    frequency: 'as-needed',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Review of adverse event details', duration_min: 7 },
      { item: 'Current clinical status', duration_min: 5 },
      { item: 'Decision re treatment continuation/modification', duration_min: 5 },
      { item: 'Safety plan review if indicated', duration_min: 3 },
    ],
    pre_session_tasks: [
      'Review adverse event report from clinic',
      'Confirm patient is medically stable before proceeding',
    ],
    post_session_tasks: [
      'Complete adverse event report',
      'Update treatment plan',
      'Notify GP/referring physician',
      'Report to manufacturer or registry if required',
    ],
    assessments_to_complete: ['PHQ-9', 'Adverse event severity rating'],
    screening_questions: [
      'Can you describe exactly what happened and when?',
      'How are you feeling now?',
      'Are you comfortable continuing treatment, or would you like a break?',
      'Any ongoing symptoms from the event?',
    ],
    documentation_template: 'report-adverse-event',
    platform_notes:
      'Urgent review — conduct within 24 hours of reported adverse event. Escalate to senior clinician if severe. Document manufacturer notification if device-related.',
    tags: ['urgent', 'safety', 'adverse-event'],
  },
  {
    id: 'vc-crisis-call',
    name: 'Crisis and Safety Assessment',
    category: 'Crisis',
    session_type: 'video',
    duration_min: 30,
    trigger: 'as-needed',
    frequency: 'as-needed',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Safety check & de-escalation', duration_min: 10 },
      { item: 'Comprehensive risk assessment', duration_min: 10 },
      { item: 'Safety planning (collaborative)', duration_min: 7 },
      { item: 'Disposition decision & next steps', duration_min: 3 },
    ],
    pre_session_tasks: [
      'Confirm patient is currently safe before scheduling',
      'Have emergency services number ready',
      'Identify local emergency contact from file',
    ],
    post_session_tasks: [
      'Document full risk assessment',
      'Update safety plan in record',
      'Notify GP/emergency contact if risk threshold met',
      'Follow up within 24 hours',
    ],
    assessments_to_complete: ['Columbia Suicide Severity Rating Scale', 'Clinical risk formulation'],
    screening_questions: [
      'Are you safe right now? Is anyone with you?',
      'Can you tell me what\'s been happening and what led to you reaching out?',
      'Are you having thoughts of ending your life? Do you have a plan?',
      'What has helped you stay safe in the past?',
      'Who can be with you tonight?',
    ],
    documentation_template: 'report-adverse-event',
    platform_notes:
      'URGENT. Conducted by senior clinician only. If imminent risk, call emergency services immediately. Do not end call until safety is confirmed or services dispatched. Document disposition clearly.',
    tags: ['urgent', 'crisis', 'safety', 'mandatory'],
  },
  {
    id: 'vc-medication-review',
    name: 'Medication Review',
    category: 'Follow-Up',
    session_type: 'video',
    duration_min: 15,
    trigger: 'scheduled',
    frequency: 'monthly',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Current medication list review', duration_min: 4 },
      { item: 'Side effects & tolerability', duration_min: 4 },
      { item: 'Symptom response', duration_min: 4 },
      { item: 'Prescribing decisions & next steps', duration_min: 3 },
    ],
    pre_session_tasks: [
      'Pull current medication list',
      'Review any recent pathology or monitoring results',
      'Patient completes brief symptom screen prior',
    ],
    post_session_tasks: [
      'Update medication record',
      'Send updated prescription if required',
      'Notify pharmacy or GP if changes made',
    ],
    assessments_to_complete: ['PHQ-2', 'Side effects checklist', 'UKU Side Effect Rating Scale (if indicated)'],
    screening_questions: [
      'Are you taking your medications as prescribed?',
      'Any side effects you\'ve noticed?',
      'Do you feel the medication is helping?',
      'Any recent blood tests or health checks relevant to medications?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Prescribing clinician must attend. Confirm jurisdiction requirements for prescribing via telehealth. Document any changes to medication clearly.',
    tags: ['medication', 'review', 'routine'],
  },
  {
    id: 'vc-end-of-treatment',
    name: 'End of Treatment Review',
    category: 'Discharge',
    session_type: 'video',
    duration_min: 45,
    trigger: 'post-treatment',
    frequency: 'once',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Treatment recap & achievements', duration_min: 8 },
      { item: 'Final assessment scores review', duration_min: 8 },
      { item: 'Response classification & discussion', duration_min: 7 },
      { item: 'Relapse prevention planning', duration_min: 10 },
      { item: 'Follow-up & maintenance plan', duration_min: 7 },
      { item: 'Patient questions & closure', duration_min: 5 },
    ],
    pre_session_tasks: [
      'Complete full outcome assessment battery (PHQ-9, GAD-7, CGI, condition-specific)',
      'Prepare outcome comparison chart (baseline vs final)',
      'Draft end-of-treatment summary',
    ],
    post_session_tasks: [
      'Finalise end-of-treatment summary report',
      'Send letter to GP/referring physician',
      'Issue relapse prevention plan to patient',
      'Schedule maintenance follow-up (if indicated)',
      'Close active treatment episode in system',
    ],
    assessments_to_complete: ['PHQ-9', 'GAD-7', 'CGI-I', 'CGI-S', 'Condition-specific scales', 'PGI-I'],
    screening_questions: [
      'Looking back on your treatment, how do you feel about the results?',
      'What changes have you noticed in your daily life and functioning?',
      'What do you feel were the most helpful aspects of treatment?',
      'What are your main concerns about the period ahead?',
      'What early warning signs should prompt you to seek help?',
    ],
    documentation_template: 'report-end-of-treatment',
    platform_notes:
      'Final formal clinical review. Ensure all documentation is completed. Provide patient with written relapse prevention plan and clear instructions for seeking further care.',
    tags: ['standard', 'required', 'discharge', 'outcomes'],
  },
  {
    id: 'vc-family-session',
    name: 'Family and Caregiver Session',
    category: 'Family',
    session_type: 'video',
    duration_min: 45,
    trigger: 'as-needed',
    frequency: 'as-needed',
    clinician_role: 'psychologist',
    agenda: [
      { item: 'Introductions & consent for family participation', duration_min: 5 },
      { item: 'Psychoeducation: condition & treatment', duration_min: 10 },
      { item: 'Family members\' questions & concerns', duration_min: 10 },
      { item: 'How to support the patient', duration_min: 10 },
      { item: 'Family impact & carer wellbeing', duration_min: 7 },
      { item: 'Plan & resources', duration_min: 3 },
    ],
    pre_session_tasks: [
      'Obtain patient consent for family participation',
      'Send family information sheet in advance',
      'Confirm who will attend',
    ],
    post_session_tasks: [
      'Send family resource list',
      'Document in patient record (with consent)',
      'Note any family-related concerns for clinical team',
    ],
    assessments_to_complete: ['Carer Wellbeing Scale (optional)'],
    screening_questions: [
      'How has your family member\'s condition been affecting you?',
      'What do you understand about the treatment they are receiving?',
      'What has been the most challenging aspect for you as a carer?',
      'How can we best support you as well as the patient?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Obtain explicit written patient consent before conducting with family. Clarify confidentiality boundaries at the outset. Patient may or may not be present depending on clinical decision.',
    tags: ['family', 'carer', 'psychoeducation'],
  },
  {
    id: 'vc-psychoeducation-tms',
    name: 'TMS Psychoeducation Session',
    category: 'Psychoeducation',
    session_type: 'video',
    duration_min: 20,
    trigger: 'pre-treatment',
    frequency: 'once',
    clinician_role: 'nurse',
    agenda: [
      { item: 'What is TMS? (overview)', duration_min: 5 },
      { item: 'How TMS works for the patient\'s condition', duration_min: 5 },
      { item: 'What a session looks and feels like', duration_min: 5 },
      { item: 'Expected timeline and outcomes', duration_min: 3 },
      { item: 'Questions', duration_min: 2 },
    ],
    pre_session_tasks: [
      'Send TMS Patient Information Sheet',
      'Send TMS patient handbook link',
    ],
    post_session_tasks: [
      'Confirm patient\'s questions were addressed',
      'Note any misconceptions addressed for record',
    ],
    assessments_to_complete: [],
    screening_questions: [
      'What do you already know about TMS?',
      'Do you have any specific worries about the procedure?',
      'Did you get a chance to read the information sheet?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Can be conducted by clinical nurse or technician. Supplement with video demonstration if available. Ensure patient has received and reviewed written materials.',
    tags: ['education', 'pre-treatment', 'tms'],
  },
  {
    id: 'vc-outcome-feedback',
    name: 'Outcome Results and Feedback Session',
    category: 'Progress Review',
    session_type: 'video',
    duration_min: 20,
    trigger: 'post-treatment',
    frequency: 'once',
    clinician_role: 'any',
    agenda: [
      { item: 'Outcome data review (visual chart)', duration_min: 8 },
      { item: 'Patient explanation of results', duration_min: 5 },
      { item: 'Patient\'s perspective on changes', duration_min: 5 },
      { item: 'Next steps (maintenance, further treatment, discharge)', duration_min: 2 },
    ],
    pre_session_tasks: [
      'Prepare outcome summary chart (baseline to post-treatment)',
      'Calculate response and remission rates',
    ],
    post_session_tasks: [
      'Send patient copy of outcome summary (with consent)',
      'Update outcomes database',
    ],
    assessments_to_complete: ['PGI-I (Patient Global Impression of Improvement)'],
    screening_questions: [
      'Looking at these results — do they match how you feel?',
      'Are there areas of your life that have improved that the scales don\'t fully capture?',
      'What surprised you about the results?',
    ],
    documentation_template: 'report-outcome-summary',
    platform_notes:
      'Share screen to show outcome charts. Use plain language to explain scores. Empower patient with their own data.',
    tags: ['outcomes', 'feedback', 'data'],
  },
  {
    id: 'vc-relapse-prevention',
    name: 'Relapse Prevention Planning Session',
    category: 'Discharge',
    session_type: 'video',
    duration_min: 30,
    trigger: 'post-treatment',
    frequency: 'once',
    clinician_role: 'psychologist',
    agenda: [
      { item: 'Review of treatment gains', duration_min: 5 },
      { item: 'Identifying personal early warning signs', duration_min: 8 },
      { item: 'Building the relapse prevention plan', duration_min: 10 },
      { item: 'Action steps if relapse occurs', duration_min: 5 },
      { item: 'Review available supports', duration_min: 2 },
    ],
    pre_session_tasks: [
      'Patient completes "What has helped me" reflection worksheet',
      'Clinician reviews full treatment history',
    ],
    post_session_tasks: [
      'Send written relapse prevention plan to patient',
      'Copy to GP if consent given',
      'Schedule 3-month maintenance follow-up',
    ],
    assessments_to_complete: ['PHQ-9'],
    screening_questions: [
      'What do you notice first when your mood is starting to decline?',
      'What situations or stressors put you most at risk?',
      'What strategies have worked best for you during treatment?',
      'Who in your life can you reach out to when struggling?',
      'At what point would you want to seek professional help again?',
    ],
    documentation_template: 'report-discharge-summary',
    platform_notes:
      'Provide written plan. Ensure patient has contact details for re-referral. Discuss maintenance TMS if clinically indicated.',
    tags: ['discharge', 'relapse-prevention', 'planning'],
  },
  {
    id: 'vc-home-program-review',
    name: 'Home Program Review',
    category: 'Follow-Up',
    session_type: 'video',
    duration_min: 15,
    trigger: 'mid-treatment',
    frequency: 'biweekly',
    clinician_role: 'any',
    agenda: [
      { item: 'Review home program adherence', duration_min: 5 },
      { item: 'Barriers & challenges discussed', duration_min: 4 },
      { item: 'Symptom change relevant to program', duration_min: 3 },
      { item: 'Modify program if needed', duration_min: 3 },
    ],
    pre_session_tasks: [
      'Patient completes home program diary review',
      'Clinician reviews adherence data if digital tracking used',
    ],
    post_session_tasks: [
      'Update home program prescription if modified',
      'Document adherence rate',
    ],
    assessments_to_complete: ['PHQ-2', 'Home program adherence checklist'],
    screening_questions: [
      'How often have you been completing the home program exercises?',
      'What has been most helpful from the program?',
      'What has been the hardest part to do consistently?',
      'Have you noticed any changes since starting the program?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Brief practical session. Can be conducted by allied health or nursing staff. Focus on problem-solving adherence barriers.',
    tags: ['home-program', 'review', 'adherence'],
  },
  {
    id: 'vc-async-update',
    name: 'Asynchronous Patient Update',
    category: 'Follow-Up',
    session_type: 'async-message',
    duration_min: 5,
    trigger: 'as-needed',
    frequency: 'as-needed',
    clinician_role: 'any',
    agenda: [
      { item: 'Patient submits brief symptom update and any questions (5 min)', duration_min: 5 },
      { item: 'Clinician reviews and responds asynchronously within 24h', duration_min: 10 },
    ],
    pre_session_tasks: [
      'Patient completes PHQ-2 and brief text field',
      'Auto-routing to appropriate clinician',
    ],
    post_session_tasks: [
      'Clinician sends written response within agreed timeframe',
      'Flag urgent responses for same-day review',
      'Document in patient record',
    ],
    assessments_to_complete: ['PHQ-2'],
    screening_questions: [
      'In a few sentences, how have you been since your last session?',
      'Any side effects or concerns to report?',
      'Any questions for your clinician?',
    ],
    documentation_template: 'report-session-progress',
    platform_notes:
      'Not suitable for crisis or urgent clinical concerns. Clearly communicate expected response times. Flag if PHQ-2 ≥3 for urgent follow-up.',
    tags: ['async', 'digital-health', 'brief', 'monitoring'],
  },
  {
    id: 'vc-discharge',
    name: 'Discharge and Aftercare Planning',
    category: 'Discharge',
    session_type: 'video',
    duration_min: 45,
    trigger: 'post-treatment',
    frequency: 'once',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Treatment journey review', duration_min: 8 },
      { item: 'Final outcome scores discussion', duration_min: 7 },
      { item: 'Aftercare plan (GP, therapist, medication)', duration_min: 8 },
      { item: 'Relapse prevention essentials', duration_min: 7 },
      { item: 'Patient questions & final concerns', duration_min: 7 },
      { item: 'Formal discharge & contact for re-referral', duration_min: 5 },
      { item: 'Feedback on service', duration_min: 3 },
    ],
    pre_session_tasks: [
      'Complete discharge summary report (draft)',
      'Prepare outcome summary chart',
      'Confirm all consents updated for discharge communications',
      'Prepare aftercare referral letters',
    ],
    post_session_tasks: [
      'Finalise and sign discharge summary',
      'Send discharge letter to GP and referring clinician',
      'Provide patient with written aftercare plan',
      'Archive record and close episode',
      'Schedule 3-month outcome follow-up (if service offers)',
    ],
    assessments_to_complete: ['PHQ-9', 'GAD-7', 'CGI-S', 'PGI-I', 'Patient satisfaction survey'],
    screening_questions: [
      'How do you feel as you come to the end of your treatment here?',
      'What would you tell someone else who is about to start this treatment?',
      'What remaining concerns do you have about the period ahead?',
      'Do you know who to contact if you need support in the future?',
    ],
    documentation_template: 'report-discharge-summary',
    platform_notes:
      'Full clinical closure. Ensure patient leaves with written plan, emergency contacts, and GP is notified. Offer feedback opportunity. Close episode in system only after all documentation complete.',
    tags: ['standard', 'required', 'discharge', 'aftercare'],
  },
  {
    id: 'vc-clinical-supervision',
    name: 'Clinical Supervision Session',
    category: 'Supervision',
    session_type: 'video',
    duration_min: 45,
    trigger: 'scheduled',
    frequency: 'biweekly',
    clinician_role: 'psychiatrist',
    agenda: [
      { item: 'Caseload review & case of concern', duration_min: 15 },
      { item: 'Clinical skills development discussion', duration_min: 10 },
      { item: 'Difficult or complex case formulation', duration_min: 10 },
      { item: 'Wellbeing check-in (supervisee)', duration_min: 5 },
      { item: 'Governance & compliance updates', duration_min: 5 },
    ],
    pre_session_tasks: [
      'Supervisee prepares case for discussion',
      'Review any adverse events or incidents since last supervision',
      'Supervisee notes professional development goals',
    ],
    post_session_tasks: [
      'Supervision notes recorded (de-identified)',
      'Action items logged',
      'Update CPD/supervision log',
    ],
    assessments_to_complete: [],
    screening_questions: [
      'Is there any case you\'ve been finding particularly challenging or complex?',
      'How are you feeling about your clinical work overall?',
      'Any adverse events or near-misses to discuss?',
      'Are there any clinical skills areas you want to focus on?',
    ],
    documentation_template: 'report-governance-review',
    platform_notes:
      'Supervision records are separate from patient records. Maintain confidentiality — use de-identified case discussions. Supervisors must be credentialed in relevant neuromodulation modalities.',
    tags: ['supervision', 'governance', 'professional-development', 'internal'],
  },
];

export const VC_TEMPLATE_BY_ID = Object.fromEntries(VIRTUAL_CARE_TEMPLATES.map(t => [t.id, t]));
export default VIRTUAL_CARE_TEMPLATES;
