"""DeepSynaps clinical text pipeline package."""

from deepsynaps_text.coding import auto_code_note, link_entities_to_terminology
from deepsynaps_text.core_nlp import (
    ClinicalEntityBackend,
    RuleBasedClinicalBackend,
    SpaCyClinicalBackend,
    detect_negation_and_assertion,
    detect_sections,
    detect_temporal_context,
    extract_clinical_entities,
)
from deepsynaps_text.neuromodulation_phenotyper import (
    extract_neuromodulation_history,
    extract_neuromodulation_risks_and_contraindications,
    extract_stimulation_parameters,
)
from deepsynaps_text.ingestion import (
    DeidBackend,
    RegexDeidBackend,
    build_note_sections_from_text,
    deidentify_text,
    import_clinical_text,
    normalize_note_format,
)
from deepsynaps_text.schemas import (
    AssertionStatus,
    AutoCodingResult,
    ClinicalChannel,
    ClinicalEntity,
    ClinicalEntityExtractionResult,
    ClinicalTextDocument,
    ClinicalTextMetadata,
    CodeSystem,
    CodedEntity,
    CodedEntityExtractionResult,
    EntityType,
    ModalityName,
    NeuromodulationHistory,
    NeuromodulationParameters,
    NeuromodulationRiskProfile,
    NeuromodulationTherapyLine,
    PhiKind,
    PhiSpan,
    ResponseCategory,
    SectionedText,
    SuggestedCode,
    TemporalContext,
    TerminologyReference,
    TextSection,
    TextSpan,
)

__all__ = [
    "AssertionStatus",
    "AutoCodingResult",
    "ClinicalChannel",
    "ClinicalEntity",
    "ClinicalEntityBackend",
    "ClinicalEntityExtractionResult",
    "ClinicalTextDocument",
    "ClinicalTextMetadata",
    "CodeSystem",
    "CodedEntity",
    "CodedEntityExtractionResult",
    "DeidBackend",
    "EntityType",
    "ModalityName",
    "NeuromodulationHistory",
    "NeuromodulationParameters",
    "NeuromodulationRiskProfile",
    "NeuromodulationTherapyLine",
    "PhiKind",
    "PhiSpan",
    "ResponseCategory",
    "RegexDeidBackend",
    "RuleBasedClinicalBackend",
    "SectionedText",
    "SpaCyClinicalBackend",
    "SuggestedCode",
    "TemporalContext",
    "TerminologyReference",
    "TextSection",
    "TextSpan",
    "auto_code_note",
    "build_note_sections_from_text",
    "deidentify_text",
    "detect_negation_and_assertion",
    "detect_sections",
    "detect_temporal_context",
    "extract_clinical_entities",
    "extract_neuromodulation_history",
    "extract_neuromodulation_risks_and_contraindications",
    "extract_stimulation_parameters",
    "import_clinical_text",
    "link_entities_to_terminology",
    "normalize_note_format",
]
